# -*- coding: utf-8 -*-
"""Almanca ceviriler — parti 1: lenfodem, lipodem."""

T = {
"lenfodem": {
 "crumb":"Lymphödem- und Lipödemchirurgie",
 "title":"Lymphödem: Ursachen, Stadien und operative Behandlung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lymphödem: Ursachen, Stadien und operative Behandlung",
 "desc":"Was ist ein Lymphödem, wie entsteht es, welche Stadien gibt es und wie wird es behandelt? LVA, vaskularisierter Lymphknotentransfer und Reduktionschirurgie — ein umfassender Leitfaden von Doz. Dr. T. Oğuz Acartürk, University of Pittsburgh.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Was ist ein Lymphödem und wie wird es behandelt?",
 "lead":"Das Lymphödem ist keine Erkrankung, die lebenslang allein mit Bandagen und Lymphdrainage verwaltet werden muss. Es ist eine Erkrankung, die bereits im Frühstadium mikrochirurgisch behandelt werden kann. Diese Seite beantwortet Ihre Fragen zu Stadien, Diagnostik, operativen Möglichkeiten und Heilungsverlauf.",
 "watopic":"Lymphödembehandlung",
 "about":"Lymphödem",
 "card":"Lymphödemchirurgie","cardsub":"LVA, Lymphknotentransfer und Reduktionschirurgie",
 "procedure":{"name":"Lymphovenöse Anastomose (LVA)",
   "how":"Blockierte Lymphbahnen werden unter dem Mikroskop mit benachbarten Venen von 0,3–0,8 mm Durchmesser verbunden, sodass die Lymphflüssigkeit in den venösen Kreislauf abgeleitet wird.",
   "prep":"Untersuchung, Stadieneinteilung und Lymphmapping mittels ICG-Lymphographie oder Lymphszintigraphie.",
   "follow":"Kompressionsversorgung, geplante Kontrollen und bei Bedarf Lymphödem-Physiotherapie.",
   "body":"Lymphsystem der Arme und Beine"},
 "keyfacts":[("Frühstadium","LVA — die schonendste Option"),("Fortgeschritten","Lymphknotentransfer + Reduktion"),
             ("Diagnostik","ICG-Lymphographie, Lymphszintigraphie"),("Entscheidend","Stadium und verstrichene Zeit")],
 "authority":"Die Lymphödem-Mikrochirurgie ist das technisch anspruchsvollste Gebiet der plastischen Chirurgie: das Verbinden von Lymphbahnen mit 0,3–0,8 mm Durchmesser mit Venen unter dem Mikroskop. Doz. Dr. Acartürk führte als Direktor für Kopf-Hals-Rekonstruktion an der University of Pittsburgh über 300 mikrochirurgische Eingriffe durch; er nimmt an den Arbeiten der europäischen lymphatischen Mikrochirurgie-Gruppe teil und hat auf dem Weltkongress für Lymphologie vorgetragen.",
 "creds":["Ehem. Direktor für Kopf-Hals-Rekonstruktion, University of Pittsburgh — 300+ mikrochirurgische Fälle",
          "Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie",
          "Senkung der mikrochirurgischen Lappenverlustrate auf 3% — gegenüber 5% im weltweiten Mittel"],
 "sections":[
  {"id":"nedir","tag":"Grundlagen","h2":"Was ist ein Lymphödem und warum entsteht es?","body":[
   "Das Lymphsystem ist ein feines Kanalnetz, das eiweißreiche Flüssigkeit aus dem Gewebe sammelt und in den Kreislauf zurückführt. Ist dieses Netz blockiert oder geschädigt, sammelt sich Flüssigkeit im Gewebe; die daraus entstehende dauerhafte Schwellung nennt man <strong>Lymphödem</strong>.",
   ("h3","Hauptursachen"),
   ("ul",["<strong>Sekundäres Lymphödem:</strong> entsteht nach Entfernung von Lymphknoten im Rahmen einer Krebsoperation, nach Bestrahlung, wiederkehrenden Infektionen oder Verletzungen. Dies ist die häufigste Form; das Armlymphödem nach Brustkrebs ist das typische Beispiel.",
          "<strong>Primäres Lymphödem:</strong> beruht auf einer angeborenen Unterentwicklung des Lymphsystems. Es kann bei Geburt, in der Pubertät oder im Erwachsenenalter auftreten."]),
   "Mit der Zeit ist die Schwellung nicht mehr nur eine Frage des Aussehens: Es kommt zu Fetteinlagerung und Fibrose, die Haut verdickt sich, wiederkehrende Erysipel-Schübe beginnen und die Beweglichkeit wird eingeschränkt. <strong>Der Zeitpunkt bestimmt daher unmittelbar, welche Behandlungsmöglichkeiten bestehen.</strong>",
   ("note","Das Ansprechen auf mikrochirurgische Eingriffe im Frühstadium, solange die Lymphbahnen noch funktionieren, ist deutlich besser als nach eingetretener Gewebeverhärtung. Abwarten verringert die Optionen.")]},
  {"id":"fark","tag":"Differentialdiagnose","h2":"Lymphödem oder Lipödem?","body":[
   "Beide Krankheitsbilder werden häufig verwechselt, ihre Behandlung unterscheidet sich jedoch. Die folgende Tabelle bietet einen Orientierungsrahmen; eine sichere Abgrenzung ist nur durch ärztliche Untersuchung möglich.",
   ("table",["Befund","Lymphödem","Lipödem"],[
     ["Symmetrie","Meist asymmetrisch; eine Seite deutlich stärker geschwollen","Typischerweise symmetrisch; beide Seiten ähnlich"],
     ["Fußbeteiligung","Schwellung reicht bis Fußrücken und Zehen","Schwellung endet am Knöchel — Manschettenzeichen; Füße bleiben frei"],
     ["Haut und Gewebe","Haut gespannt; Dellen bei Druck möglich","Gewebe weich und knotig; oft druckschmerzhaft"],
     ["Schmerz","Schwere- und Spannungsgefühl im Vordergrund","Druckschmerz und leichte Hämatombildung ausgeprägt"],
     ["Bezug zum Gewicht","Diät und Gewichtsabnahme beheben die Schwellung nicht","Fettdepots widerstehen der Gewichtsabnahme"],
     ["Stemmer-Zeichen","Meist positiv","Meist negativ"],
     ["Beginn","Nach Operation, Bestrahlung oder Infektion","Oft in Pubertät, Schwangerschaft oder Menopause"]]),
   "Beide können auch gemeinsam vorliegen. Ein unbehandeltes Lipödem erhöht mit der Zeit die lymphatische Last und kann zu einem kombinierten Bild führen, dem <strong>Lipo-Lymphödem</strong>. Einzelheiten finden Sie auf unserer <a href=\"../lipodem-cerrahisi.html\">Seite zur Lipödemchirurgie</a>."]},
  {"id":"evre","tag":"Stadien","h2":"Stadien des Lymphödems","body":[
   "Die Stadieneinteilung der International Society of Lymphology (ISL) ist der Rahmen, der bestimmt, welche operative Option infrage kommt.",
   ("table",["Stadium","Befunde","Operatives Vorgehen"],[
     ["Stadium 0","Die lymphatische Transportkapazität ist vermindert, es besteht jedoch keine sichtbare Schwellung. Nachweis durch Bildgebung.","LVA — vorbeugend und am wirksamsten"],
     ["Stadium 1","Die Schwellung nimmt im Tagesverlauf zu und geht bei Hochlagerung teilweise zurück. Dellen bei Druck.","LVA"],
     ["Stadium 2","Die Schwellung geht bei Hochlagerung nicht zurück. Das Gewebe verhärtet, das Infektionsrisiko steigt.","LVA und/oder Lymphknotentransfer"],
     ["Stadium 3","Deutliche Volumenzunahme, verdickte Haut, wiederkehrende Erysipele. Elephantiasis möglich.","Lymphknotentransfer + Reduktionschirurgie"]]),
   ("note","<strong>Grundlinie:</strong> In den Stadien 0–2 steht die LVA im Vordergrund, soweit die Lymphbahnen erhalten sind. In den Stadien 2–3 werden vaskularisierter Lymphknotentransfer und Reduktionschirurgie einzeln oder kombiniert geplant. Die endgültige Entscheidung fällt zusammen mit den Bildgebungsbefunden.")]},
  {"id":"tani","tag":"Diagnostik","h2":"Diagnostik und Lymphmapping","body":[
   "Eine operative Planung ist nicht möglich, ohne den tatsächlichen Zustand des Lymphsystems zu kennen. Die wichtigsten Verfahren:",
   ("ul",["<strong>ICG-Lymphographie:</strong> Der unter die Haut gespritzte Farbstoff Indocyaningrün wird mit einer Infrarotkamera verfolgt. Sie liefert eine Echtzeitkarte funktionierender Lymphbahnen und dient der Festlegung der LVA-Schnitte.",
          "<strong>Lymphszintigraphie:</strong> Beurteilung des Lymphflusses und der Lymphknotenbeteiligung mit einem radioaktiv markierten Tracer. Eines der Referenzverfahren zur Stadieneinteilung.",
          "<strong>MR-Lymphangiographie:</strong> Detaillierte anatomische Darstellung der Lymphbahnen und der Flüssigkeitsverteilung. Bevorzugt bei fortgeschrittenen und komplexen Fällen.",
          "<strong>Klinische Beurteilung:</strong> Umfangmessungen, Stemmer-Zeichen, Hautqualität, Infektionsanamnese und bisheriges Therapieansprechen."])]},
  {"id":"yontem","tag":"Operative Optionen","h2":"Operative Verfahren","body":[
   "Die Lymphödemchirurgie teilt sich in zwei Ansätze: <strong>physiologische</strong> Verfahren, die den Lymphabfluss wiederherstellen, und <strong>reduzierende</strong> Verfahren, die angesammeltes Gewebe entfernen. Bei vielen Patientinnen und Patienten werden beide schrittweise kombiniert.",
   ("h3","Lymphovenöse Anastomose (LVA)"),
   "Blockierte Lymphbahnen werden unter dem Mikroskop mit benachbarten Venen von etwa 0,3–0,8 mm Durchmesser verbunden. Die Lymphflüssigkeit wird so in den venösen Kreislauf abgeleitet. Der Eingriff erfolgt meist über wenige Zentimeter kleine Schnitte, ist im Frühstadium die schonendste physiologische Option und erfordert bei den meisten Patienten nur einen kurzen Aufenthalt.",
   ("h3","Vaskularisierter Lymphknotentransfer (VLNT)"),
   "Ein Lymphknotenpaket wird mit seiner Gefäßversorgung aus einer gesunden Spenderregion entnommen, in das betroffene Gebiet übertragen und mikrochirurgisch angeschlossen. Bevorzugt bei fortgeschrittenen Stadien und ausgedehnter Schädigung der Lymphbahnen; die Planung kann zeitgleich mit einer <a href=\"../meme-rekonstruksiyonu.html\">Brustrekonstruktion</a> erfolgen.",
   ("h3","Reduktionschirurgie"),
   "Entfernung von eingelagertem Fett und fibrotischem Gewebe mit lymphgefäßschonenden Liposuktionstechniken. Sie verringert Volumen und Gewicht im fortgeschrittenen Stadium deutlich; danach ist die Kompressionsversorgung dauerhaft erforderlich.",
   ("h3","Vorbeugender Ansatz (LYMPHA)"),
   "Lymphovenöse Verbindungen, die während der Krebsoperation zeitgleich mit der Lymphknotenentfernung angelegt werden. Ziel ist die Risikominderung, bevor ein Lymphödem entsteht. Die Planung erfolgt gemeinsam mit dem onkologischen Operationsteam.",
   ("note","Kein Verfahren ist für jede Patientin und jeden Patienten das richtige. Selbst bei zwei Betroffenen im gleichen Stadium kann das Lymphmapping einen anderen Plan erfordern. Die Wahl folgt einer gemeinsamen Beurteilung von Stadium, Bildgebung, Vorbehandlungen, Hautqualität und Erwartungen.")]},
  {"id":"surec","tag":"Ablauf","h2":"Operation und Heilungsverlauf","body":[
   ("steps",[
    ("SCHRITT 1 — ERSTKONTAKT","Erster Kontakt per WhatsApp oder Formular. Erste Einschätzung anhand der Dauer, früherer Operationen, der Bestrahlungsanamnese und eventueller Bilder."),
    ("SCHRITT 2 — UNTERSUCHUNG UND BILDGEBUNG","Umfangmessungen, klinische Beurteilung und bei Bedarf Lymphmapping mittels ICG-Lymphographie oder Lymphszintigraphie."),
    ("SCHRITT 3 — PLANUNGSGESPRÄCH","Mögliche Verfahren, erwarteter Nutzen, Risiken und Anzahl der Sitzungen werden offen besprochen. Die Entscheidung wird nicht übereilt."),
    ("SCHRITT 4 — OPERATION","Unter vollständigen Klinikbedingungen. Die LVA erfordert meist nur einen kurzen Aufenthalt; bei Lymphknotentransfer und Reduktionschirurgie ist er länger."),
    ("SCHRITT 5 — ERSTE 6 WOCHEN","Kompressionsversorgung, Wundpflege und schrittweise Mobilisation. Erste Veränderungen der Schwellung werden in diesem Zeitraum spürbar."),
    ("SCHRITT 6 — 3–12 MONATE","Das Ansprechen wird durch geplante Kontrollen und Umfangmessungen verfolgt. Die Intensität der Lymphödem-Physiotherapie wird schrittweise angepasst.")]),
   ("note","<strong>Für Patientinnen und Patienten aus dem Ausland:</strong> Die Vorabbeurteilung erfolgt über eine Online-Beratung und die von Ihnen gesendeten Bilder. Operation und Kontrolltermine werden zu einem einzigen Reiseplan zusammengefasst; die weitere Nachsorge erfolgt online.")]}],
 "faqs":[
  ("Für wen kommt eine Lymphödemoperation infrage?","Die Eignung richtet sich nach dem Stadium, dem Zustand des Lymphsystems in der Bildgebung, der Dauer der Schwellung, der Hautqualität und dem Allgemeinzustand. Im Frühstadium (ISL 0–2) steht die LVA im Vordergrund, im fortgeschrittenen Stadium kommen Lymphknotentransfer und reduzierende Verfahren infrage. Eine laufende Krebstherapie, eine unkontrollierte Infektion oder eine fortgeschrittene Gefäßerkrankung können den Zeitpunkt verändern."),
  ("Muss ich nach der Operation weiterhin Kompressionsstrümpfe tragen?","Die meisten Patientinnen und Patienten tragen in der ersten Zeit weiterhin Kompression. Tragedauer und Kompressionsklasse können mit der Zeit reduziert werden; ob ganz darauf verzichtet werden kann, hängt von Stadium, Verfahren und Ansprechen ab. Nach einer LVA im Frühstadium wird über eine geringere Abhängigkeit berichtet."),
  ("Wie lange dauert die Heilung?","Nach einer LVA kehren die meisten Patienten innerhalb weniger Tage in den Alltag zurück. Nach Lymphknotentransfer und Reduktionschirurgie dauert die Heilung länger. Die Abnahme der Schwellung erfolgt nicht plötzlich, sondern über Wochen und Monate; deshalb sind Verlaufsmessungen wichtig."),
  ("Wann sollte ich mich bei Armschwellung nach Brustkrebs vorstellen?","Sobald Sie eine Zunahme des Armumfangs, ein Schweregefühl oder ein Spannen von Ringen und Uhren bemerken, sollten Sie ohne Verzögerung untersucht werden. Früh durchgeführte mikrochirurgische Eingriffe sind deutlich wirksamer als eine Behandlung nach eingetretener Gewebeverhärtung."),
  ("Geht ein Lymphödem ohne Operation zurück?","Komplexe physikalische Entstauungstherapie, Bandagen und Kompressionsversorgung helfen, die Schwellung zu kontrollieren, und sind unverzichtbarer Teil der Behandlung. Sie beseitigen jedoch nicht die Blockade im Lymphabfluss. Die Chirurgie ist ein ergänzender Schritt, der das zugrunde liegende Abflussproblem angeht."),
  ("Werden meine Erysipel-Schübe seltener?","Angesammelte Lymphflüssigkeit erhöht das Infektionsrisiko. Mit verbessertem Abfluss wird über eine geringere Häufigkeit wiederkehrender Erysipele berichtet. Dies ist jedoch individuell und stadienabhängig und kann nicht garantiert werden."),
  ("Beide Beine sind betroffen — wird das in einer Sitzung gemacht?","Das hängt von der Ausdehnung des betroffenen Gebiets und dem geplanten Verfahren ab. Große Areale werden aus Sicherheits- und Heilungsgründen meist auf mehrere Sitzungen verteilt."),
  ("Sind Lymphödem und Lymphom dasselbe?","Nein. Das Lymphödem ist eine Abflussstörung durch Ansammlung von Lymphflüssigkeit im Gewebe. Das Lymphom ist eine Krebserkrankung des Lymphsystems und wird von Hämatologie und Onkologie behandelt. Die Ähnlichkeit der Begriffe führt häufig zu Verwechslungen.")],
 "ctah":"Der erste Schritt zur Lymphödem-Beurteilung",
 "ctap":"Teilen Sie uns mit, seit wann die Beschwerden bestehen, welche Behandlungen erfolgt sind und ob eine Bestrahlung stattgefunden hat, und senden Sie nach Möglichkeit Fotos des betroffenen Beins oder Arms."},

"lipodem": {
 "crumb":"Lipödemchirurgie",
 "title":"Lipödem: Symptome, Stadien und operative Behandlung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lipödem: Symptome, Stadien und operative Behandlung",
 "desc":"Was ist ein Lipödem, wie unterscheidet es sich von Adipositas und Cellulite, welche Stadien gibt es? Lymphgefäßschonende WAL- und PAL-Liposuktion, Heilungsverlauf und häufige Fragen.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Was ist ein Lipödem und wie wird es behandelt?",
 "lead":"Das Lipödem ist eine fast ausschließlich bei Frauen auftretende chronische Erkrankung mit symmetrischer Fettvermehrung an den Beinen und häufig auch an den Armen. Es widersteht Diät und Sport, verursacht Druckschmerz und verändert mit der Zeit das Gangbild. Es ist kein Gewichtsproblem, sondern eine Erkrankung, die erkannt werden muss.",
 "watopic":"Lipödembehandlung",
 "about":"Lipödem",
 "card":"Lipödemchirurgie","cardsub":"Lymphgefäßschonende Liposuktion zur Verringerung von Schmerz und Volumen",
 "procedure":{"name":"Lipödemchirurgie — lymphgefäßschonende Liposuktion",
   "how":"Das erkrankte Fettgewebe wird mit WAL- (wasserstrahlassistiert) oder PAL-Technik (kraftassistiert) unter Schonung der lymphatischen Strukturen entfernt.",
   "prep":"Untersuchung, Stadieneinteilung, bei Bedarf lymphatische Bildgebung und Anpassung der Kompressionsversorgung.",
   "follow":"Kompressionsversorgung, frühe Mobilisation und bei Bedarf manuelle Lymphdrainage.",
   "body":"Beine, Hüfte, Arme"},
 "keyfacts":[("Häufigkeit","Bis zu 10% der Frauen"),("Hauptbeschwerde","Schmerz, Berührungsempfindlichkeit, Hämatome"),
             ("Technik","WAL- / PAL-Liposuktion"),("Sitzungen","1–3 je nach Ausdehnung")],
 "authority":"Die Lipödemchirurgie erfordert die Beherrschung von Liposuktionstechniken, die das Lymphsystem schonen. Doz. Dr. Acartürk gehört zu den ersten türkischen plastischen Chirurgen, die an der University of Pittsburgh zu Fettgewebe und Stammzelltechnologien gearbeitet haben; als Chirurg, der zugleich Lymphödem-Mikrochirurgie durchführt, arbeitet er täglich mit der lymphatischen Anatomie. Die Verbindung beider Gebiete ermöglicht ein gewebeschonendes Vorgehen.",
 "creds":["Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie","Forschung zu Fettgewebe und Stammzellen an der University of Pittsburgh","Vortrag auf dem Weltkongress für Lymphologie"],
 "sections":[
  {"id":"nedir","tag":"Grundlagen","h2":"Was ist ein Lipödem?","body":[
   "Das Lipödem ist eine chronische Erkrankung, bei der sich das Fettgewebe krankhaft und symmetrisch vermehrt, begleitet von Schmerz und Berührungsempfindlichkeit. Der Oberkörper bleibt meist ausgespart; die Vermehrung konzentriert sich auf Hüfte, Oberschenkel und Waden. Die Füße sind typischerweise nicht betroffen — daraus ergibt sich der scharfe Übergang am Knöchel, das sogenannte <strong>Manschettenzeichen</strong>.",
   "Die Erkrankung beginnt häufig in hormonellen Umbruchphasen: Pubertät, Schwangerschaft oder Menopause. Eine familiäre Veranlagung ist verbreitet. Dennoch wird die Diagnose oft jahrelang verzögert, und viele Betroffene werden auf Übergewicht oder mangelnde Disziplin zurückgeworfen. Tatsächlich widersteht das Fettgewebe beim Lipödem einer Kalorienreduktion und sportlicher Betätigung.",
   ("h3","Unterschied zu Adipositas und Cellulite"),
   ("ul",["Bei <strong>Adipositas</strong> verteilt sich das Fett über den ganzen Körper und nimmt proportional zur Gewichtsabnahme ab. Beim Lipödem bleibt die regionale Vermehrung trotz Gewichtsabnahme bestehen.",
          "<strong>Cellulite</strong> ist eine Veränderung des Erscheinungsbilds des Unterhautfettgewebes und verursacht keine Schmerzen. Beim Lipödem prägen Schmerz und Empfindlichkeit das Bild.",
          "Beim <strong>Ödem</strong> hinterlässt Druck Dellen und die Schwellung nimmt bei Hochlagerung ab. Beides ist beim Lipödem untypisch."]),
   ("note","Die Diagnose des Lipödems erfolgt klinisch. Schmerz, Symmetrie, Aussparung der Füße und Resistenz gegenüber Gewichtsabnahme werden gemeinsam beurteilt. Eine verzögerte Diagnose lässt die Erkrankung fortschreiten und belastet mit der Zeit das Lymphsystem.")]},
  {"id":"evre","tag":"Stadien","h2":"Stadien des Lipödems","body":[
   "Die Stadieneinteilung richtet sich nach dem Erscheinungsbild der Hautoberfläche und des Fettgewebes. Das Stadium bestimmt, welche Behandlung angezeigt ist und wie viele Sitzungen erforderlich sein können.",
   ("table",["Stadium","Haut und Gewebe","Klinisches Bild"],[
     ["Stadium 1","Glatte Hautoberfläche, feine Knötchen darunter","Schmerz und leichte Hämatombildung haben begonnen; die Formveränderung ist gering"],
     ["Stadium 2","Unebene, wellige Hautoberfläche","Knötchen treten hervor; regionale Schwellung und Empfindlichkeit nehmen zu"],
     ["Stadium 3","Verdickte Haut, große Fettlappen","Die Beweglichkeit ist eingeschränkt; Knie- und Hüftgelenke werden belastet"],
     ["Stadium 4","Lipo-Lymphödem","Zum Lipödem tritt eine lymphatische Insuffizienz hinzu; auch die Füße können betroffen sein"]]),
   "Mit fortschreitendem Stadium verschlechtert sich nicht nur das Erscheinungsbild, sondern auch die Funktion. Das Aneinanderreiben der Oberschenkelinnenseiten verändert das Gangbild, was mit der Zeit zu Knie- und Rückenschmerzen führt. Die Lipödemchirurgie ist daher keine ästhetische Entscheidung, sondern ein Eingriff zum Erhalt der Funktion.",
   ("h3","Lipo-Lymphödem: wo zwei Erkrankungen zusammentreffen"),
   "Beim unbehandelten Lipödem übersteigt das zunehmende Gewebevolumen irgendwann die Transportkapazität des Lymphsystems. Ab diesem Punkt tritt ein Lymphödem hinzu und der Behandlungsplan muss beide Komponenten umfassen. Diese Abgrenzung finden Sie ausführlich auf unserer <a href=\"../lenfodem-lipodem-cerrahisi.html\">Lymphödem-Seite</a>."]},
  {"id":"tedavi","tag":"Behandlung","h2":"Operative Behandlung: lymphgefäßschonende Liposuktion","body":[
   "Die Lipödemchirurgie ist eine medizinische Behandlung. Ziel ist nicht die Volumenreduktion, sondern die Entfernung des erkrankten Fettgewebes <strong>unter Schonung der lymphatischen Strukturen</strong>, die Verringerung der Schmerzen und die Wiederherstellung der Beweglichkeit. Die Technik unterscheidet sich daher deutlich von der ästhetischen Liposuktion.",
   ("h3","WAL — wasserstrahlassistierte Liposuktion"),
   "Ein feiner Wasserstrahl löst die Fettzellen schonend aus dem umgebenden Gewebe. Lymphgefäße und Nerven bleiben weitgehend erhalten, Blutung und Hämatombildung sind geringer. So können große Areale in einer Sitzung sicher behandelt werden.",
   ("h3","PAL — kraftassistierte Liposuktion"),
   "Eine vibrierende Kanüle zerlegt fibrotisches und derbes Fettgewebe mit weniger Trauma. Bevorzugt in fortgeschrittenen Stadien mit verhärtetem Gewebe.",
   ("ul",["Die Kanülen werden parallel zur Richtung des Lymphabflusses geführt",
          "Der Tumeszenzplan wird so gewählt, dass das Gewebeödem minimal bleibt",
          "Große Areale werden aus Sicherheitsgründen auf mehrere Sitzungen verteilt",
          "Die Kompressionsversorgung nach dem Eingriff ist fester Bestandteil der Behandlung"]),
   ("note","Die Lipödemchirurgie beseitigt die Erkrankung nicht; sie verringert das erkrankte Fettgewebe. Entferntes Gewebe kehrt nicht zurück, die Erkrankung besteht jedoch im verbleibenden Gewebe fort. Kompression, Bewegung und ein stabiles Gewicht nach der Operation bestimmen daher das langfristige Ergebnis.")]},
  {"id":"surec","tag":"Ablauf","h2":"Operation und Heilungsverlauf","body":[
   ("steps",[
    ("SCHRITT 1 — ERSTKONTAKT","Erster Kontakt per WhatsApp oder Formular. Erste Einschätzung anhand der Beschwerdedauer, der Schmerzstärke, früherer Behandlungen und eventueller Fotos."),
    ("SCHRITT 2 — UNTERSUCHUNG UND STADIENEINTEILUNG","Umfangmessungen, Beurteilung von Haut und Gewebe, Bildgebung bei Verdacht auf lymphatische Beteiligung."),
    ("SCHRITT 3 — PLANUNG","Welche Areale in welcher Reihenfolge behandelt werden, die Zahl der Sitzungen, Risiken und der erwartete Nutzen werden offen besprochen."),
    ("SCHRITT 4 — OPERATION","Unter vollständigen Klinikbedingungen, in Vollnarkose oder Sedierung. Die Dauer richtet sich nach dem behandelten Areal."),
    ("SCHRITT 5 — ERSTE 6 WOCHEN","Kompressionsversorgung, frühes Gehen, bei Bedarf manuelle Lymphdrainage. Die Schwellung geht in diesem Zeitraum schrittweise zurück."),
    ("SCHRITT 6 — 3–6 MONATE","Die endgültige Form stellt sich in diesem Zeitraum ein. Die Schmerzlinderung bemerken die meisten Betroffenen deutlich früher.")]),
   ("note","<strong>Für Patientinnen aus dem Ausland:</strong> Die Vorabbeurteilung erfolgt über eine Online-Beratung und die von Ihnen gesendeten Bilder. Operation und Kontrolltermine werden zu einem einzigen Reiseplan zusammengefasst; die weitere Nachsorge erfolgt online.")]}],
 "faqs":[
  ("Ist die Lipödemoperation dasselbe wie eine ästhetische Liposuktion?","Nein. Die Lipödemchirurgie ist eine medizinische Behandlung; Ziel ist die Entfernung des erkrankten Fettgewebes unter Schonung der lymphatischen Strukturen und die Verringerung der Schmerzen. Kanülenwahl, Zugangsrichtungen, Tumeszenzplan und Sitzungszahl unterscheiden sich von der ästhetischen Liposuktion."),
  ("Verschwinden die Schmerzen nach der Operation?","Bei der Mehrzahl der Betroffenen wird über eine deutliche Abnahme von Berührungsempfindlichkeit und Schmerz berichtet, oft schon vor einer sichtbaren Volumenänderung. Das Ergebnis hängt vom Stadium und vom verbleibenden Gewebe ab und kann nicht garantiert werden."),
  ("Wie viele Sitzungen sind nötig?","Das hängt von der Ausdehnung des betroffenen Gebiets und vom Stadium ab. Aus Gründen der Sicherheit und der Heilungsqualität werden große Areale meist auf 2–3 Sitzungen mit mehreren Wochen Abstand verteilt."),
  ("Kommt das Fett zurück, wenn ich nach der Operation zunehme?","Die entfernten Fettzellen kehren nicht zurück. Das Lipödem ist jedoch eine chronische Erkrankung, die im verbleibenden Gewebe fortbesteht; eine deutliche Gewichtszunahme kann das Ergebnis beeinträchtigen."),
  ("Wie lange muss ich Kompression tragen?","In der Regel die ersten 6 Wochen ganztägig, danach reduziert. Die Dauer wird individuell nach Stadium, behandeltem Areal und Heilungsverlauf festgelegt."),
  ("Woran erkenne ich, ob ich ein Lipödem habe?","Symmetrische Schwellung der Beine, Druckschmerz, leichte Hämatombildung, ein scharfer Übergang am Knöchel und eine regionale Fettvermehrung trotz Gewichtsabnahme sind typische Befunde. Für eine sichere Diagnose ist eine ärztliche Untersuchung erforderlich.")],
 "ctah":"Der erste Schritt zur Lipödem-Beurteilung",
 "ctap":"Teilen Sie uns mit, seit wann die Beschwerden bestehen und wie stark die Schmerzen Ihren Alltag beeinflussen, und senden Sie nach Möglichkeit Fotos Ihrer Beine."},
}
