# -*- coding: utf-8 -*-
"""Almanca ceviriler — parti 4: kalan rekonstruktif ve estetik sayfalar."""

STEPS = lambda op, days, back: ("steps",[
 ("SCHRITT 1 — ERSTKONTAKT","Erster Kontakt per WhatsApp oder Formular, anhand Ihrer Vorstellungen, Ihrer Vorgeschichte und eventueller Fotos."),
 ("SCHRITT 2 — UNTERSUCHUNG UND PLANUNG","Beurteilung Ihrer Anatomie sowie offene Besprechung möglicher Techniken, Risiken und realistischer Erwartungen."),
 ("SCHRITT 3 — VORBEREITUNG","Blutuntersuchungen, Narkosevorbereitung, Anpassung von Rauchen und blutverdünnenden Medikamenten."),
 ("SCHRITT 4 — OPERATION", op),
 ("SCHRITT 5 — ERSTE TAGE", days),
 ("SCHRITT 6 — RÜCKKEHR UND NACHSORGE", back)])

T = {
"goz-kapagi": {
 "crumb":"Lidchirurgie",
 "title":"Lidchirurgie (Blepharoplastik) — Ober- und Unterlid | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lidchirurgie (Blepharoplastik)",
 "desc":"Ober- und Unterlidstraffung: hängende Lider, Tränensäcke, örtliche Betäubung, Heilungsverlauf und häufige Fragen.",
 "eyebrow":"Ästhetische Chirurgie",
 "h1":"Lidchirurgie (Blepharoplastik)",
 "lead":"Die Augenregion altert im Gesicht zuerst. Hängende Oberlider lassen den Blick müde wirken und schränken im fortgeschrittenen Stadium das Gesichtsfeld ein; Tränensäcke am Unterlid lassen selbst ausgeruhte Menschen erschöpft aussehen. Die Blepharoplastik verändert den Ausdruck mit einem kleinen Eingriff deutlich.",
 "watopic":"Lidstraffung",
 "about":"Blepharoplastik",
 "card":"Lidchirurgie","cardsub":"Ober- und Unterlid, Tränensäcke",
 "procedure":{"name":"Blepharoplastik",
   "how":"Am Oberlid werden überschüssige Haut und bei Bedarf Fettgewebe über die natürliche Lidfalte entfernt; am Unterlid werden die Fettpolster umverteilt oder reduziert.",
   "prep":"Augenärztliche Untersuchung, bei Bedarf Gesichtsfeldprüfung und Abklärung trockener Augen.",
   "follow":"Kühlung, Augentropfen und Schonung in der ersten Woche.","body":"Augenlider"},
 "keyfacts":[("Narkose","Meist örtlich + Sedierung"),("Dauer","45–90 Minuten"),
             ("Fadenentfernung","Tag 5–7"),("Gesellschaftsfähig","7–10 Tage")],
 "authority":"Die Augenregion verlangt in der Gesichtsanatomie die feinste Detailarbeit. Aus seiner Erfahrung in der Gesichtsskelettchirurgie und der Kopf-Hals-Rekonstruktion heraus beurteilt Doz. Dr. Acartürk das Lid gemeinsam mit den umgebenden Strukturen und bietet auch chirurgische Lösungen für Lidprobleme bei Fazialisparese.",
 "creds":["Zusatzqualifikation Mund-, Kiefer- und Gesichtschirurgie","Erfahrung in der Lidrekonstruktion bei Fazialisparese","Praxis in Gesichtsskelett- und Orbitachirurgie"],
 "sections":[
  {"id":"ust","tag":"Oberlid","h2":"Oberlidstraffung","body":[
   "Am Oberlid erschlafft die Haut mit der Zeit und hängt über die Wimpernkante. Das verleiht dem Blick einen müden und strengen Ausdruck; im fortgeschrittenen Stadium liegt die Haut auf den Wimpern, schränkt das Gesichtsfeld ein und führt zu ständigem Anspannen der Stirnmuskulatur.",
   "Die überschüssige Haut wird über die <strong>natürliche Lidfalte</strong> entfernt. Da die Narbe in dieser Falte liegt, ist sie nach abgeschlossener Heilung weitgehend verborgen. Bei Bedarf wird das Fettpolster im inneren Augenwinkel reduziert.",
   ("note","Ein Absinken der Braue kann mit einer Lidererschlaffung verwechselt werden. Liegt das eigentliche Problem in der abgesunkenen Braue, bleibt eine reine Lidoperation unzureichend und kann die Braue sogar weiter nach unten ziehen. Die Unterscheidung erfolgt bei der Untersuchung.")]},
  {"id":"alt","tag":"Unterlid","h2":"Unterlid und Tränensäcke","body":[
   "Die Wölbung am Unterlid entsteht meist nicht durch überschüssige Haut, sondern dadurch, dass die <strong>Fettpolster nach vorn drängen</strong>. Haut allein zu entfernen behebt das daher nicht und kann das Lid nach unten ziehen.",
   ("ul",["<strong>Transkonjunktivaler Zugang:</strong> Der Schnitt erfolgt von der Lidinnenseite, außen bleibt keine Narbe. Bevorzugt bei jüngeren Patienten ohne Hautüberschuss.",
          "<strong>Fettumverteilung:</strong> Statt das Fett vollständig zu entfernen, wird es in die Tränenrinne verlagert. Das verhindert ein eingefallenes, schattiges Aussehen.",
          "<strong>Zugang über einen Hautschnitt:</strong> Bei deutlichem Hautüberschuss über einen feinen Schnitt unterhalb der Wimpern."]),
   ("note","Dunkle Ringe unter den Augen stammen nicht immer von Tränensäcken. Wenn durchscheinende Gefäße bei dünner Haut oder eine Pigmentierung die Ursache sind, behebt die Operation sie nicht; diese Unterscheidung muss vorab getroffen werden.")]},
  {"id":"surec","tag":"Ablauf","h2":"Der Heilungsverlauf","body":[
   STEPS("Bei den meisten Patienten genügen örtliche Betäubung und Sedierung; der Eingriff dauert 45–90 Minuten und Sie gehen am selben Tag nach Hause.",
         "Regelmäßiges Kühlen in den ersten 48 Stunden. Schwellung und Blutergüsse sind an Tag 2–3 am stärksten; erhöhte Kopflage beschleunigt die Heilung.",
         "Die Fäden werden an Tag 5–7 entfernt. Die meisten Patienten kehren nach 7–10 Tagen mit Make-up ins gesellschaftliche Leben zurück; eine feine Schwellung kann einige Wochen länger bestehen."),
   ("ul",["In der ersten Woche kein schweres Heben und kein Bücken",
          "Kontaktlinsen werden meist 2 Wochen aufgeschoben",
          "Am Bildschirm kann Trockenheit auftreten; künstliche Tränen werden empfohlen",
          "In den ersten Monaten Sonnenbrille und Sonnenschutz verwenden"])]}],
 "faqs":[
  ("Übernimmt die Krankenkasse die Lidoperation?","Wenn das Hängen des Oberlids das Gesichtsfeld einschränkt und dies durch eine Gesichtsfeldprüfung belegt ist, übernehmen manche Kassen die Kosten. Die Bedingungen unterscheiden sich."),
  ("Nach wie vielen Jahren ist eine Wiederholung nötig?","Das Ergebnis der Oberlidstraffung hält in der Regel 10 Jahre und länger. Wurde am Unterlid Fett umverteilt, ist das Ergebnis langlebig; im weiteren Alterungsverlauf kann Jahre später ein zusätzlicher Eingriff sinnvoll sein."),
  ("Wirken meine Augen danach schräg?","Bei richtig geplanter Blepharoplastik verändert sich die Augenform nicht. Zu viel entfernte Haut oder ein nicht abgestütztes Unterlid können dieses Aussehen erzeugen; deshalb zählt das Maß mehr als die Menge des entfernten Gewebes."),
  ("Was ist der Unterschied zu Botox?","Botox mindert Linien, die durch Muskelbewegung entstehen; hängende Haut oder Fettpolster behebt es nicht. Beides sind keine Alternativen, sondern Lösungen für unterschiedliche Probleme und können kombiniert werden."),
  ("Ich habe trockene Augen — kann ich operiert werden?","Das muss vorab mitgeteilt werden. Trockene Augen können sich nach der Operation vorübergehend verstärken; die Planung erfolgt dann zurückhaltender und gemeinsam mit Ihrer Augenärztin oder Ihrem Augenarzt.")],
 "ctah":"Beurteilung zur Lidchirurgie",
 "ctap":"Teilen Sie uns mit, was Sie am Aussehen stört und ob Sie Beschwerden beim Sehen haben, und senden Sie nach Möglichkeit Nahaufnahmen."},

"jinekomasti": {
 "crumb":"Gynäkomastie",
 "title":"Gynäkomastie-Operation (Brustvergrößerung beim Mann) | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Gynäkomastie: Brustvergrößerung beim Mann und ihre operative Behandlung",
 "desc":"Was ist eine Gynäkomastie, welche Ursachen hat sie, worin unterscheidet sie sich von reinem Fettgewebe, operative Optionen, Narbenlage und Heilungsverlauf.",
 "eyebrow":"Ästhetische Chirurgie",
 "h1":"Gynäkomastie (Brustvergrößerung beim Mann)",
 "lead":"Die Gynäkomastie ist eine Vergrößerung des Brustdrüsengewebes beim Mann. Etwa jeder dritte Mann ist im Lauf seines Lebens davon betroffen. Sie verschwindet nicht durch Sport oder Diät, denn das Problem ist Drüsen- und kein Fettgewebe. Die Operation ist die einzige dauerhafte und wirksame Lösung.",
 "watopic":"Gynäkomastie-Operation",
 "about":"Gynäkomastie",
 "card":"Gynäkomastie","cardsub":"Operative Behandlung der Brustvergrößerung beim Mann",
 "procedure":{"name":"Gynäkomastie-Chirurgie",
   "how":"Das Drüsengewebe wird über einen Schnitt am unteren Rand des Warzenhofs entfernt; das umgebende Fett wird mit Liposuktion abgesaugt, um der Brustwand eine natürliche männliche Kontur zu geben.",
   "prep":"Hormonelle Abklärung, Überprüfung von Medikamenten und Substanzgebrauch, bei Bedarf Brustultraschall.",
   "follow":"Kompressionsweste, Einschränkung schweren Trainings.","body":"Brustkorb"},
 "keyfacts":[("Häufigkeit","Etwa 30% der Männer"),("Narkose","Vollnarkose oder Sedierung"),
             ("Dauer","1–2 Stunden"),("Rückkehr zur Arbeit","3–7 Tage")],
 "authority":"Über das Ergebnis der Gynäkomastie-Chirurgie entscheidet das Gleichgewicht zwischen vollständiger Entfernung des Drüsengewebes und einer natürlichen Kontur der Brustwand. Die Erfahrung von Doz. Dr. Acartürk in Brustchirurgie und Body Contouring erlaubt es, beide Ziele gemeinsam zu verfolgen.",
 "creds":["Langjährige Praxis in der Brustchirurgie","Erfahrung in Liposuktion und Konturchirurgie","Aktive chirurgische Tätigkeit in den USA und der Türkei"],
 "sections":[
  {"id":"nedir","tag":"Grundlagen","h2":"Was ist eine Gynäkomastie und warum entsteht sie?","body":[
   "Die Gynäkomastie ist eine Vergrößerung der männlichen Brustdrüse durch ein hormonelles Ungleichgewicht. Sie muss von reiner Fettansammlung (Pseudogynäkomastie) unterschieden werden: Drüsengewebe ist unter dem Warzenhof als derbe Scheibe tastbar, Fett dagegen weich und diffus.",
   ("h3","Hauptursachen"),
   ("ul",["<strong>Pubertät:</strong> die häufigste Ursache. Die Mehrzahl bildet sich innerhalb von 1–2 Jahren spontan zurück.",
          "<strong>Medikamente:</strong> einige Blutdruck- und Magenmittel, Antidepressiva und Prostatamedikamente",
          "<strong>Anabole Steroide und leistungssteigernde Mittel</strong>",
          "<strong>Hormonelle Erkrankungen:</strong> Schilddrüse, Leber und Hoden",
          "<strong>Gewichtszunahme und Alterung</strong>"]),
   ("note","Vor der Operation sollte eine zugrunde liegende Ursache abgeklärt werden. Einseitige, rasch wachsende oder derbe und unregelmäßige Knoten erfordern weitere Untersuchungen. Bei Beginn in der Pubertät wird meist 1–2 Jahre abgewartet.")]},
  {"id":"derece","tag":"Einteilung","h2":"Einteilung und Verfahrenswahl","body":[
   ("table",["Grad","Erscheinungsbild","Vorgehen"],[
    ["Grad 1","Begrenzte Vergrößerung um den Warzenhof, kein Hautüberschuss","Drüsenentfernung ± Liposuktion"],
    ["Grad 2","Mäßige Vergrößerung, begrenzter Hautüberschuss","Drüsenentfernung + Liposuktion"],
    ["Grad 3","Deutliche Vergrößerung mit Hautüberschuss","Entfernung + Liposuktion + Hautstraffung"],
    ["Grad 4","Weibliches Brustbild, tiefstehende Brustwarze","Entfernung + Hautresektion + Neupositionierung der Brustwarze"]]),
   "Bei Grad 1 und 2 bleibt der Schnitt am unteren Rand des Warzenhofs und die Narbe verbirgt sich im Farbübergang. Grad 3 und 4 können zusätzliche Schnitte erfordern; dies wird in der Planung offen besprochen.",
   ("note","Eine alleinige Liposuktion ist der häufigste Grund für ein Wiederauftreten der Gynäkomastie. Drüsengewebe lässt sich nicht absaugen; es bleibt als derbe Scheibe unter dem Warzenhof zurück und die Beschwerden bestehen fort.")]},
  {"id":"surec","tag":"Ablauf","h2":"Der Heilungsverlauf","body":[
   STEPS("1–2 Stunden in Vollnarkose oder Sedierung, bei den meisten Patienten mit Entlassung am selben Tag.",
         "Eine Kompressionsweste wird ab dem ersten Tag getragen. Blutergüsse und Schwellung sind an Tag 3–5 am stärksten.",
         "Rückkehr zur Bürotätigkeit in 3–7 Tagen. Die Kompression wird 4–6 Wochen getragen, Brusttraining 6 Wochen aufgeschoben. Die endgültige Form stellt sich nach 3–6 Monaten ein."),
   ("ul",["Eine vorübergehende Verhärtung unter dem Warzenhof ist normal",
          "Eine vorübergehende Gefühlsveränderung der Brustwarze ist möglich und bildet sich über Monate zurück",
          "Der Erhalt des Ergebnisses hängt von stabilem Gewicht und dem Verzicht auf Steroide ab"])]}],
 "faqs":[
  ("Geht sie mit Sport weg?","Nein. Sport kann Fettgewebe verringern, entfernt aber kein Drüsengewebe. Die derbe Scheibe unter dem Warzenhof spricht auf Training nicht an; eine Operation ist erforderlich."),
  ("Tritt sie nach der Operation erneut auf?","Wird das Drüsengewebe vollständig entfernt, ist ein Wiederauftreten nicht zu erwarten. Anabole Steroide, deutliche Gewichtszunahme oder ein neues hormonelles Problem können den Prozess jedoch neu auslösen."),
  ("Ist die Narbe sichtbar?","Der Schnitt liegt am unteren Rand des Warzenhofs, im Übergang zwischen dunkler und heller Haut. Narben, die entlang dieser Linie heilen, werden mit der Zeit unauffällig. Höhere Grade können zusätzliche Narben erfordern."),
  ("Kann in der Pubertät operiert werden?","Meist wird 1–2 Jahre abgewartet, da sich die Mehrzahl spontan zurückbildet. Bei ausgeprägter sozialer und psychischer Belastung und stabilem Befund kann eine frühere Operation erwogen werden."),
  ("Übernimmt die Krankenkasse die Kosten?","In manchen Fällen, besonders bei Schmerzen und dokumentierter hormoneller Ursache, ist eine Kostenübernahme möglich. Die Bedingungen unterscheiden sich."),
  ("Wann kann ich wieder Brust trainieren?","In der Regel nach 6 Wochen, schrittweise und nach ärztlicher Freigabe. Zu früh begonnenes schweres Brusttraining verstärkt die Schwellung und verzögert die Heilung.")],
 "ctah":"Beurteilung zur Gynäkomastie",
 "ctap":"Teilen Sie uns mit, seit wann der Befund besteht und welche Medikamente oder Nahrungsergänzungsmittel Sie einnehmen, und senden Sie Fotos von vorn und von der Seite."},

"yag-enjeksiyonu": {
 "crumb":"Eigenfetttransfer",
 "title":"Eigenfetttransfer (Lipofilling) und stammzellgestützte Volumengabe | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Eigenfetttransfer und stammzellgestützte Volumengabe",
 "desc":"Volumenaufbau an Gesicht und Körper mit eigenem Fett: Was ist Lipofilling, wie lange hält es, Stammzellanreicherung und Anwendung in bestrahltem Gewebe.",
 "eyebrow":"Ästhetische Chirurgie",
 "h1":"Eigenfetttransfer und stammzellgestützte Volumengabe",
 "lead":"Ihr eigenes Fettgewebe ist der körperverträglichste Filler: kein Fremdmaterial, keine Allergie, ein natürliches Gefühl und dauerhaft, soweit es anwächst. Und es gibt nicht nur Volumen — die enthaltenen Zellen verbessern auch die Hautqualität.",
 "watopic":"Eigenfetttransfer",
 "about":"Autologer Fetttransfer",
 "card":"Eigenfetttransfer","cardsub":"Volumenaufbau und Gewebeverbesserung mit eigenem Fett",
 "procedure":{"name":"Autologer Fetttransfer (Lipofilling)",
   "how":"Mit feinen Kanülen aus Bauch oder Oberschenkel gewonnenes Fett wird aufbereitet und gereinigt und anschließend in kleinen Mengen mehrschichtig in die Zielregion eingebracht.",
   "prep":"Auswahl der Spenderregion und Planung des Zielvolumens.",
   "follow":"Kein Druck auf die behandelte Region, Ödemmanagement.","body":"Gesicht, Brust, Gesäß, Narbenregionen"},
 "keyfacts":[("Narkose","Sedierung oder Vollnarkose"),("Haltbarkeit","Angewachsenes Fett bleibt dauerhaft"),
             ("Anwachsrate","Etwa 50–70%"),("Sitzungen","Bei Bedarf wiederholt")],
 "authority":"Fettgewebe und Stammzelltechnologien stehen im Mittelpunkt der wissenschaftlichen Arbeit von Doz. Dr. Acartürk. Die University of Pittsburgh ist auf diesem Gebiet ein internationales Zentrum; er gehört zu den ersten türkischen plastischen Chirurgen, die mit diesen Technologien gearbeitet haben, und war zudem beratend für Stammzellunternehmen in den USA tätig.",
 "creds":["Forschung zu fettgewebsstämmigen Stammzellen an der University of Pittsburgh","Postdoktorandenzeit zu Tissue Engineering und Biomaterialien an der Carnegie Mellon","Beratung im Bereich Stammzelltechnologien in den USA"],
 "sections":[
  {"id":"nedir","tag":"Grundlagen","h2":"Was ist ein Eigenfetttransfer?","body":[
   "Lipofilling bezeichnet die Übertragung von Fettgewebe aus einem Körperbereich in einen anderen nach Aufbereitung. Damit das übertragene Fett überlebt, muss es am neuen Ort eine Blutversorgung ausbilden; deshalb wird es in feinen Schichten statt als große Masse eingebracht.",
   "Ein Teil des eingebrachten Fetts wird in den ersten Monaten resorbiert. Der angewachsene Anteil bleibt dauerhaft und nimmt mit dem Körpergewicht zu und ab. Die durchschnittliche Anwachsrate liegt bei 50–70%, weshalb bewusst etwas mehr Volumen eingebracht und bei Bedarf eine zweite Sitzung durchgeführt wird.",
   ("h3","Anwendungsbereiche"),
   ("ul",["<strong>Gesicht:</strong> Schläfen, Wangenknochen, Tränenrinne, Kieferlinie und Lippenvolumen",
          "<strong>Brust:</strong> begrenzte Vergrößerung, Weichzeichnen von Implantatkanten, Konturkorrektur nach Rekonstruktion",
          "<strong>Gesäß und Körper:</strong> Volumen- und Konturangleichung",
          "<strong>Narben und Strahlenschäden:</strong> Auflockerung verhärteten Gewebes"])]},
  {"id":"kokhucre","tag":"Stammzellen","h2":"Der stammzellgestützte Ansatz","body":[
   "Fettgewebe enthält nicht nur Volumen, sondern auch <strong>regenerative Zellen</strong>. Sie fördern die Neubildung von Gefäßen, verbessern die Hautqualität und unterstützen die Geweberegeneration. Die Anreicherung des Fetts mit diesen Zellen zielt darauf, sowohl die Anwachsrate als auch die Wirkung auf das Gewebe zu erhöhen.",
   "Die University of Pittsburgh ist auf diesem Gebiet ein internationales Zentrum. Doz. Dr. Acartürk gehört zu den ersten türkischen plastischen Chirurgen, die mit fettgewebsstämmigen Stammzelltechnologien gearbeitet haben, und setzt diese Technik besonders in der <a href=\"../yanik-travma-onarimi.html\">Rekonstruktion nach Krebs, Verbrennungen und Bestrahlung</a> ein.",
   ("note","Der Begriff Stammzellen wird in der Ästhetik häufig überzogen vermarktet. Aus Fettgewebe gewonnene Zellen tragen zur Gewebequalität bei, doch handelt es sich nicht um eine Behandlung, die Alterung aufhält oder umkehrt. Erwartungen in diesem Rahmen zu setzen ist wichtig.")]},
  {"id":"surec","tag":"Ablauf","h2":"Eingriff und Heilung","body":[
   ("steps",[
    ("SCHRITT 1 — PLANUNG","Zielregion, benötigtes Volumen und Spenderregion werden festgelegt."),
    ("SCHRITT 2 — FETTGEWINNUNG","Entnahme aus Bauch oder Oberschenkel mit feinen Kanülen bei niedrigem Druck, um die Zellen nicht zu schädigen."),
    ("SCHRITT 3 — AUFBEREITUNG","Das Fett wird von Blut und Flüssigkeit getrennt und gereinigt."),
    ("SCHRITT 4 — EINBRINGUNG","Es wird in zahlreichen feinen Kanälen schichtweise in die Zielregion eingebracht."),
    ("SCHRITT 5 — ERSTE 3 MONATE","Die Schwellung klingt ab und die Resorption ist abgeschlossen. Das dauerhafte Ergebnis wird am Ende dieses Zeitraums beurteilt.")]),
   ("ul",["In der ersten Woche sollte kein Druck auf die behandelte Region ausgeübt werden",
          "Rauchen senkt die Überlebensrate der Fettzellen deutlich",
          "Deutliche Gewichtsschwankungen beeinflussen das Ergebnis",
          "Bei Bedarf wird nach 3–6 Monaten eine zweite Sitzung geplant"])]}],
 "faqs":[
  ("Wie viel des eingebrachten Fetts bleibt dauerhaft?","Im Durchschnitt 50–70%. Der Rest wird innerhalb der ersten 3 Monate resorbiert. Deshalb wird zusätzliches Volumen eingeplant und bei Bedarf eine zweite Sitzung durchgeführt."),
  ("Welchen Vorteil hat es gegenüber Fillern?","Da es sich um Ihr eigenes Gewebe handelt, besteht kein Risiko einer Fremdkörperreaktion, es fühlt sich natürlich an und der angewachsene Anteil bleibt dauerhaft. Zudem verbessert es die Hautqualität. Nachteile sind der operative Charakter und die geringere Vorhersagbarkeit."),
  ("Wirkt mein Gesicht nach dem Eigenfetttransfer aufgedunsen?","In den ersten 2–3 Wochen wirkt es durch die Schwellung voller; das ist vorübergehend. Solange kein übermäßiges Volumen eingebracht und schichtweise gearbeitet wird, ist das Ergebnis natürlich."),
  ("Kann statt eines Implantats Fett zur Brustvergrößerung verwendet werden?","Für eine begrenzte Vergrößerung ja. Das in einer Sitzung erreichbare Volumen ist jedoch geringer als mit einem Implantat und mehrere Sitzungen können nötig sein. Die Entscheidung richtet sich nach Ihren Erwartungen."),
  ("Beeinflusst der Eigenfetttransfer die Brustkrebsvorsorge?","Ein Teil des eingebrachten Fetts kann zu Verkalkungen führen, die in der Bildgebung sichtbar sind, von einer erfahrenen Radiologin jedoch von Krebs unterschieden werden können. Es genügt, das radiologische Team zu informieren."),
  ("Ich bin schlank — habe ich genug Fett?","In der Regel lässt sich aus Bauch, Oberschenkelinnenseite oder Knieinnenseite genügend Fett gewinnen. Bei sehr schlanken Patienten kann das Zielvolumen begrenzt sein; das wird bei der Untersuchung beurteilt.")],
 "ctah":"Beurteilung zum Eigenfetttransfer",
 "ctap":"Teilen Sie uns mit, wo Sie Volumen wünschen und ob Sie bereits Filler hatten, und senden Sie nach Möglichkeit Fotos."},

"kol-uyluk-germe": {
 "crumb":"Arm-, Oberschenkel- und Körperstraffung",
 "title":"Armstraffung (Brachioplastik), Oberschenkel- und Körperstraffung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Arm-, Oberschenkel- und Körperstraffung",
 "desc":"Armstraffung (Brachioplastik), Oberschenkelstraffung und Körperstraffung nach starkem Gewichtsverlust: Narbenlage, Reihenfolge der Planung und Heilungsverlauf.",
 "eyebrow":"Ästhetische Chirurgie",
 "h1":"Arm-, Oberschenkel- und Körperstraffung",
 "lead":"Ein großer Gewichtsverlust ist ein Erfolg, hinterlässt aber erschlaffte Haut. Innenseiten der Arme, Oberschenkel und Rumpf zeigen diese Veränderung am deutlichsten. Straffungsoperationen entfernen die überschüssige Haut, damit der Körper zum verlorenen Gewicht passt.",
 "watopic":"Arm- und Oberschenkelstraffung",
 "about":"Körperkonturchirurgie",
 "card":"Arm- und Oberschenkelstraffung","cardsub":"Entfernung überschüssiger Haut nach Gewichtsverlust",
 "procedure":{"name":"Brachioplastik und Oberschenkelstraffung",
   "how":"Überschüssige Haut und Fett werden entlang der Linie entfernt, in der sich die Narbe am besten verbergen lässt; das darunterliegende Gewebe wird aufgehängt, um Kontur zu schaffen.",
   "prep":"Stabiles Gewicht sowie Beurteilung des Ernährungs- und Vitaminstatus.",
   "follow":"Kompressionsversorgung, Ödemkontrolle, schrittweise Rückkehr zu Aktivitäten.",
   "body":"Arm, Oberschenkel, Rumpf"},
 "keyfacts":[("Voraussetzung","Gewicht seit 6 Monaten stabil"),("Narkose","Vollnarkose"),
             ("Narbe","Bleibend, entlang verdeckbarer Linien"),("Rückkehr zur Arbeit","2–3 Wochen")],
 "authority":"Körperkonturchirurgie nach starkem Gewichtsverlust erfordert wegen der großen Wundflächen und des hohen Komplikationsrisikos rekonstruktive Disziplin. Die Erfahrung von Doz. Dr. Acartürk in der Rumpf- und Extremitätenrekonstruktion erlaubt es, diese Eingriffe sicher zu staffeln.",
 "creds":["Erfahrung in Rumpf- und Extremitätenrekonstruktion","Drei Jahre allgemeinchirurgische Ausbildung","Praxis in der Versorgung komplexer Wunden und Gewebeverluste"],
 "sections":[
  {"id":"kol","tag":"Armstraffung","h2":"Armstraffung (Brachioplastik)","body":[
   "Die Erschlaffung an der Innenseite des Oberarms gehört nach Gewichtsverlust zu den häufigsten Beschwerden. Sie führt dazu, dass kurze Ärmel gemieden werden und das Mitschwingen des Arms als unangenehm empfunden wird. Muskelaufbau durch Training behebt diese Erschlaffung nicht; die überschüssige Haut muss operativ entfernt werden.",
   ("ul",["<strong>Begrenzte Erschlaffung:</strong> ein kurzer, in der Achselhöhle verborgener Schnitt kann genügen",
          "<strong>Deutliche Erschlaffung:</strong> ein Schnitt von der Achselhöhle bis zum Ellenbogen an der Arminnenseite ist erforderlich",
          "Eine Liposuktion begleitet den Eingriff meist und glättet die Kontur"]),
   ("note","Die Narbe der Armstraffung ist bleibend und nur begrenzt zu verbergen. Die Entscheidung fällt zwischen der Belastung durch die Erschlaffung und der Akzeptanz der Narbe. Die meisten Patientinnen geben an, die Narbe der Erschlaffung vorzuziehen — diese Abwägung muss jedoch vorab klar sein.")]},
  {"id":"uyluk","tag":"Oberschenkelstraffung","h2":"Oberschenkelstraffung","body":[
   "Die Erschlaffung an der Oberschenkelinnenseite führt zu Reibung beim Gehen, Hautreizungen und Einschränkungen bei der Kleidung. Der Schnitt wird je nach Ausmaß auf zwei Arten geplant:",
   ("ul",["<strong>Schnitt in der Leistenfalte:</strong> Die Narbe verbirgt sich in der Unterwäschelinie. Bevorzugt bei begrenzter Erschlaffung.",
          "<strong>Vertikaler Schnitt:</strong> verläuft von der Leiste bis zur Knieinnenseite. Bei deutlicher Erschlaffung erforderlich; die Narbe ist lang, das Ergebnis jedoch wirksamer."]),
   "Der Oberschenkel ist für die Wundheilung eine empfindliche Region: beweglich, feucht und Druck ausgesetzt. Wunddehiszenz und verzögerte Heilung treten hier daher häufiger auf als anderswo."]},
  {"id":"govde","tag":"Körperstraffung","h2":"Körperstraffung und Reihenfolge","body":[
   "Die Körperstraffung (Body Lift) entfernt die überschüssige Haut vollständig über einen Schnitt, der Bauch, Taille, Gesäß und Außenseiten der Oberschenkel umläuft. Sie wird bei Patienten nach deutlichem Gewichtsverlust durchgeführt, typischerweise nach bariatrischer Chirurgie.",
   ("h3","Reihenfolge der Planung"),
   ("ul",["Meist werden zuerst Rumpf und Bauch behandelt — hier ist die Volumenveränderung am größten",
          "Arm- und Oberschenkelstraffung werden 3–6 Monate später geplant",
          "Brust und Gesicht bleiben in der Regel zuletzt",
          "Zwischen den Etappen muss die Heilung abgeschlossen sein"]),
   ("note","Vitamin- und Eiweißmangel nach starkem Gewichtsverlust beeinflussen die Wundheilung unmittelbar. Den Ernährungsstatus vor der Operation zu prüfen und bei Bedarf auszugleichen senkt das Komplikationsrisiko deutlich.")]},
  {"id":"surec","tag":"Ablauf","h2":"Der Heilungsverlauf","body":[
   STEPS("In Vollnarkose; je nach Region und Umfang 2–5 Stunden, meist mit 1–2 Nächten in der Klinik.",
         "Kompressionswäsche ab dem ersten Tag, gegebenenfalls Drainagen. In der ersten Woche bleibt die Bewegung eingeschränkt.",
         "Rückkehr zur Bürotätigkeit in 2–3 Wochen. Die Kompression wird 6 Wochen fortgeführt. Die Narben reifen im ersten Jahr; die Pflege ist in dieser Zeit entscheidend.")]}],
 "faqs":[
  ("Wie lange nach dem Gewichtsverlust kann ich operiert werden?","Ihr Gewicht sollte mindestens 6 Monate stabil sein. Eine zu frühe Operation birgt das Risiko, dass spätere Gewichtsveränderungen das Ergebnis verderben."),
  ("Wie auffällig werden die Narben?","Bei diesen Eingriffen sind die Narben lang und bleibend. Sie verblassen mit der Zeit, verschwinden aber nicht vollständig. Silikonpflege, Sonnenschutz und Rauchverzicht beeinflussen die Narbenqualität unmittelbar."),
  ("Kann alles in einer Sitzung gemacht werden?","Davon wird in der Regel abgeraten. Lange Operationszeiten und große Wundflächen erhöhen das Risiko. Eine gestaffelte Planung ist sowohl aus Sicherheits- als auch aus Qualitätsgründen vorzuziehen."),
  ("Würde eine Liposuktion allein nicht genügen?","Nicht, wenn die Hautelastizität verloren ist. Die Fettentfernung macht die Erschlaffung dann noch deutlicher. Bei Patienten nach Gewichtsverlust muss die überschüssige Haut entfernt werden."),
  ("Wann kann ich nach der Operation Sport treiben?","Gehen beginnt in den ersten Tagen. Leichter Sport ab der 4. Woche, Krafttraining ab der 8. Woche, jeweils schrittweise und nach ärztlicher Freigabe.")],
 "ctah":"Beurteilung zu Straffungsoperationen",
 "ctap":"Teilen Sie uns mit, wie viel Gewicht Sie verloren haben, wie lange Ihr Gewicht stabil ist und ob eine bariatrische Operation stattgefunden hat; senden Sie nach Möglichkeit Fotos."},

"lip-lift": {
 "crumb":"Lip Lift, Bichektomie und Otoplastik",
 "title":"Lip Lift, Bichektomie und Ohrkorrektur (Otoplastik) | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lip Lift, Bichektomie und Otoplastik",
 "desc":"Lippenlifting, Wangenfettentfernung (Bichektomie) und Korrektur abstehender Ohren (Otoplastik): für wen geeignet, Technik, Narben und Heilungsverlauf.",
 "eyebrow":"Ästhetische Chirurgie",
 "h1":"Lip Lift, Bichektomie und Ohrkorrektur",
 "lead":"Drei kleine Eingriffe mit großer Wirkung auf das Gesicht. Alle sind in örtlicher Betäubung möglich, die Heilung ist kurz und die Ergebnisse bleiben. Ihre Gemeinsamkeit: Bei der richtigen Patientin bewirken sie viel, bei der falschen sind sie überflüssig.",
 "watopic":"Lip Lift, Bichektomie oder Otoplastik",
 "about":"Ästhetische Gesichtschirurgie",
 "card":"Lip Lift · Bichektomie · Otoplastik","cardsub":"Lippenlifting, Wangenverschmälerung, abstehende Ohren",
 "procedure":{"name":"Lip Lift",
   "how":"Unmittelbar unterhalb der Nasenbasis wird ein feiner Hautstreifen entfernt, um die Oberlippe anzuheben; das Lippenrot wird sichtbarer und mehr Zahn zeigt sich.",
   "prep":"Messung des Abstands zwischen Nasenbasis und Lippe sowie Beurteilung der Zahnsichtbarkeit.",
   "follow":"Nahtpflege und Vermeidung übertriebener Mimik in den ersten Wochen.","body":"Oberlippe"},
 "keyfacts":[("Narkose","Örtliche Betäubung"),("Dauer","30–60 Minuten"),
             ("Fadenentfernung","Tag 5–7"),("Gesellschaftsfähig","1 Woche")],
 "authority":"Auch wenn diese Eingriffe klein sind, verlangen sie Sicherheit im Umgang mit Gesichtsproportionen. Die Zusatzqualifikation von Doz. Dr. Acartürk in Mund-, Kiefer- und Gesichtschirurgie und seine Erfahrung in der Gesichtsskelettchirurgie erlauben es, Lippen-, Wangen- und Ohreingriffe im Zusammenhang des gesamten Gesichts zu planen.",
 "creds":["Zusatzqualifikation Mund-, Kiefer- und Gesichtschirurgie","Fellowship für Ohrrekonstruktion an der University of Helsinki","Erfahrung in Gesichtsskelett- und Weichteilchirurgie"],
 "sections":[
  {"id":"liplift","tag":"Lip Lift","h2":"Lip Lift (Lippenlifting)","body":[
   "Mit dem Alter vergrößert sich der Abstand zwischen Nasenbasis und Oberlippe, das Lippenrot wird schmaler und beim Lächeln zeigt sich weniger Zahn. Das verleiht dem Gesicht einen älteren, strengeren Ausdruck. Der Lip Lift hebt die Lippe an, indem unmittelbar unter der Nasenbasis ein feiner Hautstreifen entfernt wird.",
   ("ul",["Das Lippenrot wird sichtbarer — es wird kein Volumen wie bei Fillern hinzugefügt, sondern vorhandenes Gewebe freigelegt",
          "Beim Lächeln zeigt sich mehr Zahn",
          "Das Ergebnis ist dauerhaft; anders als Filler muss es nicht wiederholt werden",
          "Die Narbe verbirgt sich in der Falte an der Nasenbasis"]),
   ("note","Der Lip Lift ist keine Alternative zu Fillern. Filler fügen Volumen hinzu, der Lip Lift verändert die Proportion. Bei einem langen Abstand zwischen Nase und Lippe lösen Filler das Problem nicht und können die Oberlippe sogar schwerer wirken lassen.")]},
  {"id":"bisektomi","tag":"Bichektomie","h2":"Bichektomie (Wangenfettentfernung)","body":[
   "Die Bichektomie ist die Entfernung eines Teils des tief in der Wange liegenden Bichat-Fettpolsters über die Mundhöhle. Sie verringert die Fülle in der mittleren Wange und lässt Wangenknochen und Kieferlinie deutlicher hervortreten. Da der Schnitt im Mund liegt, entsteht außen keine Narbe.",
   ("h3","Für wen ist sie nicht geeignet?"),
   ("ul",["Schlanke Personen mit ohnehin eingefallenen Wangen",
          "Ältere Patienten, bei denen der Volumenverlust im Gesicht begonnen hat",
          "Patienten, deren eigentliches Problem eine Gesichtserschlaffung ist"]),
   ("note","Dieses Fettpolster verkleinert sich mit dem Alter ohnehin. Wird in jungen Jahren zu viel entfernt, kann später ein eingefallenes, gealtertes Gesicht entstehen. Die Menge sollte daher zurückhaltend bemessen werden; entferntes Gewebe lässt sich nicht zurückgeben.")]},
  {"id":"otoplasti","tag":"Otoplastik","h2":"Korrektur abstehender Ohren (Otoplastik)","body":[
   "Ein abstehendes Ohr steht in einem zu großen Winkel vom Kopf ab oder seine Faltungen sind unzureichend ausgebildet. Da die soziale Wirkung im Kindesalter ausgeprägt sein kann, wird eine frühe Korrektur häufig bevorzugt.",
   ("ul",["Der Ohrknorpel wird über einen Schnitt hinter dem Ohr geformt und mit Nähten fixiert",
          "Die Narbe liegt hinter dem Ohr und ist von vorn nicht sichtbar",
          "Da das Ohrwachstum mit 5–6 Jahren weitgehend abgeschlossen ist, ist der Eingriff vor der Einschulung möglich",
          "Bei Erwachsenen erfolgt er in örtlicher Betäubung"]),
   "Das angeborene Fehlen der Ohrmuschel (Mikrotie) ist ein anderes Krankheitsbild und erfordert eine mehrstufige Rekonstruktion; Einzelheiten auf unserer <a href=\"../mikrotia-kulak-onarimi.html\">Mikrotie-Seite</a>."]},
  {"id":"surec","tag":"Ablauf","h2":"Der Heilungsverlauf","body":[
   ("steps",[
    ("LIP LIFT","Die Fäden werden an Tag 5–7 entfernt. In der ersten Woche ist die Schwellung deutlich; die Rückkehr ins gesellschaftliche Leben erfolgt meist nach 1 Woche. Die Narbe verblasst über 3–6 Monate."),
    ("BICHEKTOMIE","In den ersten 3–5 Tagen weiche Kost und Mundpflege. Die Schwellung klingt in 1–2 Wochen ab. Das Ergebnis stellt sich nach 3–6 Monaten ein."),
    ("OTOPLASTIK","Ein Stirnband wird in der ersten Woche ganztägig und weitere 3–4 Wochen nachts getragen. Gesellschaftsfähig nach 5–7 Tagen; Sport wird 4 Wochen aufgeschoben.")])]}],
 "faqs":[
  ("Ist die Narbe des Lip Lifts sichtbar?","Der Schnitt liegt in der Falte an der Nasenbasis. In den ersten Monaten bleibt er rosa und verblasst innerhalb von 3–6 Monaten, sodass er mit der natürlichen Falte verschmilzt. Narbenpflege und Sonnenschutz beeinflussen das Ergebnis unmittelbar."),
  ("Fallen meine Wangen nach der Bichektomie ein?","Bei maßvoller Entnahme nicht. Da sich dieses Fettpolster mit dem Alter ohnehin verkleinert, kann eine zu große Entnahme in jungen Jahren später zu einem eingefallenen Aussehen führen. Deshalb wird zurückhaltend vorgegangen."),
  ("Welches Alter ist für die Ohrkorrektur richtig?","Das Ohrwachstum ist mit 5–6 Jahren weitgehend abgeschlossen; die Zeit vor der Einschulung wird häufig bevorzugt. Bei Erwachsenen ist der Eingriff in jedem Alter möglich."),
  ("Stellen sich die Ohren wieder ab?","Wegen der Knorpelrückstellkraft ist ein teilweises Wiederabstehen möglich. Um dieses Risiko zu senken, wird die Knorpelform mit dauerhaften Nähten gestützt; die Einhaltung der Stirnbandtragezeit ist wichtig."),
  ("Können diese Eingriffe kombiniert werden?","Ja. Lip Lift und Bichektomie werden häufig in derselben Sitzung durchgeführt. Auch eine Kombination mit anderen Gesichtseingriffen ist möglich; die Planung erfolgt bei der Untersuchung.")],
 "ctah":"Der erste Schritt zur Beurteilung",
 "ctap":"Teilen Sie uns mit, welcher Eingriff Sie interessiert und was Sie verändern möchten, und senden Sie Fotos von vorn und von der Seite."},
}
