# -*- coding: utf-8 -*-
"""Almanca ceviriler — parti 2: meme rekonstruksiyonu, rinoplasti, mikrotia."""

T = {
"meme-rek": {
 "crumb":"Brustrekonstruktion",
 "title":"Brustrekonstruktion nach Brustkrebs — DIEP-Lappen und Implantat | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Brustrekonstruktion nach Brustkrebs",
 "desc":"Brustrekonstruktion nach Mastektomie: DIEP-Lappen mit Eigengewebe, implantatbasierte Rekonstruktion, sofortige und verzögerte Planung sowie die gleichzeitige Behandlung eines Armlymphödems.",
 "eyebrow":"Rekonstruktive Chirurgie",
 "h1":"Brustrekonstruktion nach Brustkrebs",
 "lead":"Die Brustrekonstruktion ist nicht das Ende der Krebsbehandlung, sondern Teil der Genesung. Sie kann mit Eigengewebe oder mit einem Implantat erfolgen, zeitgleich mit der Mastektomie oder nach Abschluss der Therapie. Der richtige Zeitpunkt bestimmt Ihre Möglichkeiten.",
 "watopic":"Brustrekonstruktion",
 "about":"Brustrekonstruktion",
 "card":"Brustrekonstruktion","cardsub":"Wiederaufbau nach Krebs mit Eigengewebe oder Implantat",
 "procedure":{"name":"Brustrekonstruktion mit DIEP-Lappen",
   "how":"Haut, Fett und die versorgenden Gefäße werden aus dem Unterbauch entnommen, ohne Muskel zu durchtrennen, mikrochirurgisch an die Brustwandgefäße angeschlossen und zur Brust geformt.",
   "prep":"Gemeinsame Planung mit dem onkologischen Team, Gefäßdarstellung (CT-Angiographie) und Prüfung des Bestrahlungsplans.",
   "follow":"Überwachung der Gewebedurchblutung, Bauchpflege und Brustwarzenrekonstruktion in einer zweiten Sitzung.",
   "body":"Brust"},
 "keyfacts":[("Zeitpunkt","Sofort oder verzögert"),("Eigengewebe","DIEP, TRAM, Latissimus dorsi"),
             ("Implantat","Expander + Implantat"),("Zusatzoption","Gleichzeitige Lymphödembehandlung")],
 "authority":"Die Brustrekonstruktion erfordert, Mikrochirurgie und ästhetische Chirurgie gemeinsam zu denken. Doz. Dr. Acartürk verfügt über langjährige Praxis sowohl im freien Gewebetransfer als auch in der Brustästhetik; da er zugleich Lymphödem-Mikrochirurgie durchführt, kann er Brustrekonstruktion und Behandlung des Armlymphödems <strong>in einer Operation</strong> planen.",
 "creds":["300+ freie Gewebetransfers","Gleichzeitige Planung mit Lymphödem-Mikrochirurgie","Brustchirurgische Praxis in den USA und Zuweisungen durch Kollegen"],
 "sections":[
  {"id":"zamanlama","tag":"Zeitpunkt","h2":"Sofort oder später?","body":[
   ("h3","Sofortrekonstruktion"),
   "Sie erfolgt in derselben Operation wie die Mastektomie. Da die Brusthaut erhalten bleibt, ist das Ergebnis meist natürlicher, die Patientin erlebt keine Zeit ohne Brust und die Gesamtzahl der Eingriffe sinkt. Bevorzugt, wenn keine Bestrahlung zu erwarten ist.",
   ("h3","Verzögerte Rekonstruktion"),
   "Sie erfolgt nach Abschluss der onkologischen Therapie, insbesondere der Bestrahlung. In bestrahltem Gewebe sind die Ergebnisse mit Implantat schlechter; bei Patientinnen mit Bestrahlung steht daher die Rekonstruktion mit Eigengewebe im Vordergrund.",
   ("note","Die Entscheidung sollte gemeinsam mit Ihrer Brustchirurgin und Ihrem Strahlentherapeuten getroffen werden. Ein Gespräch mit dem plastischen Chirurgen <strong>vor</strong> der Mastektomie erweitert Ihre Möglichkeiten deutlich. Die Rekonstruktion erschwert die Krebsnachsorge nicht und erhöht das Rezidivrisiko nicht.")]},
  {"id":"yontem","tag":"Verfahren","h2":"Rekonstruktionsverfahren","body":[
   ("h3","DIEP-Lappen — mit Eigengewebe"),
   "Haut und Fettgewebe aus dem Unterbauch werden mit ihren versorgenden Gefäßen zur Brust verlagert. <strong>Der Bauchmuskel wird nicht durchtrennt</strong>, worin sich das Verfahren vom älteren TRAM unterscheidet; die Bauchkraft bleibt erhalten und das Bruchrisiko sinkt. Das Ergebnis ist weich, fällt natürlich und verändert sich mit dem Körpergewicht.",
   ("h3","Implantatbasierte Rekonstruktion"),
   "Zunächst wird ein Gewebeexpander eingesetzt und über Wochen schrittweise gefüllt, um die Haut zu dehnen; anschließend erfolgt der Wechsel auf ein endgültiges Implantat. Kürzere Operation und schnellere Heilung, jedoch hohes Risiko einer Kapselfibrose in bestrahltem Gewebe.",
   ("h3","Latissimus-dorsi-Lappen"),
   "Muskel und Haut vom Rücken, meist in Kombination mit einem Implantat. Eine Option bei unzureichendem Bauchgewebe oder nach früheren Bauchoperationen.",
   ("h3","Volumenfeinabstimmung mit Eigenfett"),
   "Ihr eigenes Fettgewebe dient der Korrektur von Konturunregelmäßigkeiten und der Verbesserung der Qualität bestrahlter Haut. Dies ist meist ein ergänzender Schritt."]},
  {"id":"lenfodem","tag":"Zusatzoption","h2":"Gleichzeitige Behandlung des Armlymphödems","body":[
   "Die Entfernung der Achsellymphknoten und die Bestrahlung können zu einem Lymphödem des Arms führen. Bei geplanter Brustrekonstruktion lassen sich beide Probleme <strong>in einer Operation</strong> angehen: Zeitgleich mit dem Gewebetransfer kann ein vaskularisierter Lymphknotentransfer erfolgen.",
   "Das erspart der Patientin einen zweiten großen Eingriff und ermöglicht eine frühe Behandlung des Lymphödems. Einzelheiten auf unserer <a href=\"../lenfodem-lipodem-cerrahisi.html\">Seite zur Lymphödemchirurgie</a>.",
   ("note","Wenn Sie frühe Anzeichen bemerken — ein Schweregefühl im Arm oder das Spannen von Ringen und Uhren —, warten Sie nicht. Beim Lymphödem ist ein früher Eingriff deutlich wirksamer als eine Behandlung nach eingetretener Gewebeverhärtung.")]},
  {"id":"surec","tag":"Ablauf","h2":"Ablauf und Heilung","body":[
   ("steps",[
    ("SCHRITT 1 — GEMEINSAME PLANUNG","Entscheidung über Zeitpunkt und Verfahren zusammen mit Brustchirurgie und Strahlentherapie."),
    ("SCHRITT 2 — VORBEREITUNG","Gefäßdarstellung, Beurteilung des Bauchgewebes, Rauchstopp und allgemeine Vorbereitung."),
    ("SCHRITT 3 — OPERATION","6–8 Stunden beim DIEP-Lappen; kürzer bei implantatbasierter Rekonstruktion. Klinikaufenthalt 3–5 Tage."),
    ("SCHRITT 4 — ERSTE 6 WOCHEN","Hebebeschränkungen, Bauchpflege und schrittweise Rückkehr zu Aktivitäten."),
    ("SCHRITT 5 — 3–6 MONATE","Symmetrieangleichung, bei Bedarf Eingriff an der Gegenseite sowie Rekonstruktion von Brustwarze und Warzenhof.")])]}],
 "faqs":[
  ("Verdeckt die Rekonstruktion ein Rezidiv?","Nein. Studien zeigen, dass die Brustrekonstruktion das Rezidivrisiko nicht erhöht und die Nachsorge nicht erschwert. Ihre onkologische Nachsorge läuft unverändert weiter."),
  ("Was ist der Unterschied zwischen DIEP und TRAM?","Beim DIEP-Lappen wird der Bauchmuskel nicht durchtrennt; nur die Gefäße werden aus dem Muskel herauspräpariert, sodass die Bauchkraft erhalten bleibt und das Bruchrisiko sinkt. Beim TRAM wird ein Teil des Muskels mit entnommen."),
  ("Was gilt, wenn ich bestrahlt werde?","In bestrahltem Gewebe sind die Ergebnisse mit Implantat schlechter und das Risiko einer Kapselfibrose steigt. Bei geplanter Bestrahlung werden daher meist Eigengewebe und eine verzögerte Rekonstruktion bevorzugt."),
  ("Werde ich wieder Gefühl haben?","Das Gefühl im übertragenen Gewebe ist anfangs gering. Mit der Zeit kann teilweise Sensibilität zurückkehren; in manchen Fällen wird zusätzlich eine Nervennaht durchgeführt, um das Gefühl wiederherzustellen."),
  ("Welche Narbe bleibt am Bauch?","Der Schnitt wird ähnlich einer Bauchdeckenstraffung in die Bikinilinie gelegt, der Nabel wird neu geformt. Der Bauch wird dabei zugleich flacher."),
  ("Nur eine Brust wurde entfernt — ist Symmetrie möglich?","Ja. Durch Verkleinerung, Straffung oder Vergrößerung der Gegenseite lässt sich Symmetrie herstellen. Dies wird meist in einer zweiten Sitzung geplant.")],
 "ctah":"Beurteilung zur Brustrekonstruktion",
 "ctap":"Senden Sie uns Ihre Diagnose, die geplante oder bereits erfolgte Operation, Ihren Bestrahlungsstatus und vorhandene Befunde. Wir melden uns zur Abstimmung mit Ihrem onkologischen Team."},

"rinoplasti": {
 "crumb":"Nasenkorrektur (Rhinoplastik)",
 "title":"Nasenkorrektur (Rhinoplastik) — natürliches Ergebnis und freie Atmung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Nasenkorrektur (Rhinoplastik): funktionelle und ästhetische Nasenchirurgie",
 "desc":"Was ist eine Rhinoplastik, worin unterscheiden sich offene und geschlossene Technik, gleichzeitige Korrektur der Nasenscheidewand, Heilungsverlauf und Wissenswertes zur Revisionsrhinoplastik.",
 "eyebrow":"Ästhetische Chirurgie",
 "h1":"Nasenkorrektur (Rhinoplastik)",
 "lead":"Eine gute Rhinoplastik ist eine Nase, der man die Operation nicht ansieht. Angestrebt wird ein Ergebnis, das zum übrigen Gesicht passt, natürlich altert und die Atmung mindestens ebenso ernst nimmt wie das Aussehen.",
 "watopic":"Nasenkorrektur",
 "about":"Rhinoplastik",
 "card":"Rhinoplastik","cardsub":"Funktionelle und ästhetische Nasenchirurgie",
 "procedure":{"name":"Rhinoplastik",
   "how":"Das knöcherne und knorpelige Gerüst der Nase wird in offener oder geschlossener Technik neu geformt; bei Bedarf werden Knorpeltransplantate zur Stabilisierung eingesetzt und die Nasenscheidewand begradigt.",
   "prep":"Untersuchung, Beurteilung der Atmung, Fotoanalyse und Blutuntersuchungen.",
   "follow":"Pflege von Schiene und Tamponade, Ödemmanagement, Sonnenschutz im ersten Jahr.",
   "body":"Nase"},
 "keyfacts":[("Narkose","Vollnarkose"),("Dauer","2–4 Stunden"),
             ("Gesellschaftsfähig","7–10 Tage"),("Endgültige Form","12–18 Monate")],
 "authority":"Türkische Chirurgen verfügen in der Rhinoplastik über international anerkannte Erfahrung. Doz. Dr. Acartürk setzte diese Erfahrung an der University of Pittsburgh fort; seine dortigen Kollegen überwiesen ihm mit der Zeit nahezu alle Rhinoplastik-Patienten, die sich an sie wandten. Seine Zusatzqualifikation in Mund-, Kiefer- und Gesichtschirurgie erlaubt ihm, Nase und Gesichtsskelett gemeinsam zu beurteilen.",
 "creds":["Hohe Rhinoplastik-Fallzahl an der University of Pittsburgh durch Kollegenzuweisungen","Zusatzqualifikation Mund-, Kiefer- und Gesichtschirurgie","Erfahrung in Gesichtsfrakturen und Gesichtsskelettchirurgie"],
 "sections":[
  {"id":"kimler","tag":"Für wen","h2":"Für wen kommt eine Rhinoplastik infrage?","body":[
   "Die Rhinoplastik verbessert das Aussehen der Nase, ihre Atemfunktion oder beides. Die häufigsten Beratungsanlässe sind:",
   ("ul",["Ein knöcherner oder knorpeliger Höcker am Nasenrücken",
          "Eine hängende, breite oder unscharf definierte Nasenspitze",
          "Eine im Verhältnis zum Gesicht zu große oder zu kleine Nase",
          "Schiefstand und Asymmetrie",
          "Atembehinderung durch eine verbogene Nasenscheidewand oder vergrößerte Nasenmuscheln",
          "Eine Formveränderung oder Atemstörung nach einer früheren Operation"]),
   "Das Nasenwachstum ist bei Mädchen etwa mit 16, bei Jungen mit 17–18 Jahren abgeschlossen; die Operation wird nach Abschluss dieses Wachstums geplant.",
   ("note","Eine Rhinoplastik ist Gesichtschirurgie, nicht bloß Nasenchirurgie. Entscheidungen, die Kinn, Stirnneigung und Gesichtsproportionen außer Acht lassen, führen zu technisch gelungenen, aber zum Gesicht nicht passenden Ergebnissen.")]},
  {"id":"teknik","tag":"Technik","h2":"Offene und geschlossene Technik","body":[
   ("h3","Offene Rhinoplastik"),
   "Über einen kleinen Schnitt am Nasensteg (Columella) wird die Nasenhaut angehoben. Der Operateur sieht das gesamte Gerüst direkt; Asymmetrien, Transplantatlage und Spitzenformung lassen sich kontrollierter gestalten. Die Narbe an der Columella wird innerhalb weniger Monate unauffällig.",
   ("h3","Geschlossene Rhinoplastik"),
   "Alle Schnitte bleiben im Naseninneren, außen entsteht keine Narbe. Schwellung und Heilungsdauer sind geringer. Bevorzugt bei Nasen mit symmetrischem Gerüst und begrenztem Korrekturbedarf.",
   ("h3","Erhaltender Ansatz (Preservation)"),
   "Techniken, die den natürlichen Aufbau des Nasenrückens möglichst wenig stören und ihn stattdessen neu positionieren. Bei geeigneter Anatomie ergeben sie eine natürlichere Rückenlinie und weniger Schwellung.",
   ("note","Die Technikwahl sollte Ihrer Anatomie folgen, nicht der Gewohnheit des Operateurs. Bei Revisionen, ausgeprägten Asymmetrien und Nasen, die Knorpelstützung benötigen, ist die offene Technik in der Regel sicherer.")]},
  {"id":"nefes","tag":"Funktion","h2":"Atmung und Nasenscheidewand","body":[
   "Die Atmung ist untrennbarer Teil der Nasenchirurgie. Ein Eingriff, der das Aussehen verbessert und eine Atemstörung ignoriert, mindert die Lebensqualität.",
   ("ul",["<strong>Septumdeviation:</strong> Verbiegung der Trennwand; wird in derselben Sitzung korrigiert (Septorhinoplastik)",
          "<strong>Nasenmuschelvergrößerung:</strong> Verkleinerung der Strukturen im Naseninneren",
          "<strong>Enge der Nasenklappe:</strong> Einsinken des Nasenflügels; wird mit Knorpeltransplantaten gestützt"]),
   "Der aus dem Septum entnommene Knorpel dient zugleich als Transplantat zur Stützung der Nasenspitze. So lassen sich Funktion und Form in einer Sitzung angehen.",
   ("note","Ob die Krankenkasse die Kosten übernimmt, hängt davon ab, ob ein funktioneller Anteil vorliegt. Klären Sie dies im Planungsgespräch.")]},
  {"id":"surec","tag":"Ablauf","h2":"Der Heilungsverlauf","body":[
   ("steps",[
    ("SCHRITT 1 — ERSTKONTAKT","Erster Kontakt per WhatsApp oder Formular, anhand Ihrer Vorstellungen, Ihrer Vorgeschichte und eventueller Fotos."),
    ("SCHRITT 2 — UNTERSUCHUNG UND PLANUNG","Beurteilung Ihrer Anatomie sowie offene Besprechung möglicher Techniken, Risiken und realistischer Erwartungen."),
    ("SCHRITT 3 — VORBEREITUNG","Blutuntersuchungen, Narkosevorbereitung, Anpassung von Rauchen und blutverdünnenden Medikamenten."),
    ("SCHRITT 4 — OPERATION","2–4 Stunden in Vollnarkose, meist mit einer Nacht in der Klinik."),
    ("SCHRITT 5 — ERSTE TAGE","Schiene auf dem Nasenrücken, bei Bedarf Silikontamponade. Kühlung und erhöhte Kopflage in den ersten 48 Stunden; Blutergüsse und Schwellung sind an Tag 3–5 am stärksten."),
    ("SCHRITT 6 — RÜCKKEHR UND NACHSORGE","Die Schiene wird am 7. Tag entfernt; die meisten Patienten kehren nach 7–10 Tagen ins gesellschaftliche Leben zurück. Die Schwellung der Nasenspitze klingt über 12–18 Monate ab.")]),
   ("ul",["In den ersten 6 Wochen sollte keine Brille auf dem Nasenrücken aufliegen",
          "In den ersten 3 Wochen sind schwerer Sport und Bücken zu vermeiden",
          "Der Sonnenschutz sollte im ersten Jahr nicht vernachlässigt werden"])]}],
 "faqs":[
  ("Verbessert sich meine Atmung nach der Rhinoplastik?","Liegen eine Septumdeviation, vergrößerte Nasenmuscheln oder eine Klappenenge vor, können diese in derselben Sitzung korrigiert werden, und die Atmung verbessert sich meist deutlich. Das wird bei der Untersuchung beurteilt."),
  ("Wann sehe ich das Ergebnis?","Die Grundform ist nach Entfernung der Schiene erkennbar, die Schwellung der Spitze klingt jedoch langsam ab. Für das endgültige Ergebnis sind 12–18 Monate nötig, bei dicker Haut länger."),
  ("Bleibt bei der offenen Technik eine Narbe?","Die Narbe an der Columella verblasst innerhalb weniger Monate und ist im normalen Gesprächsabstand nicht erkennbar. Narbenpflege ist in dieser Zeit wichtig."),
  ("Wann ist eine Revisionsrhinoplastik möglich?","Da das Gewebe weich werden und die Schwellung vollständig abklingen muss, wird eine Revision in der Regel frühestens 12 Monate nach dem Ersteingriff geplant. Sie ist technisch anspruchsvoller als die Erstoperation."),
  ("Ist die Operation sehr schmerzhaft?","Die Rhinoplastik ist weniger schmerzhaft als erwartet. Als unangenehm empfunden wird vor allem das Gefühl der verstopften Nase; moderne Silikonschienen mit Luftkanal mindern dies deutlich."),
  ("Verändert sich meine Nase mit dem Alter?","Jede Nase altert. Bei einer gut geplanten Rhinoplastik bleiben die Stützstrukturen erhalten, sodass die Spitze mit der Zeit nicht übermäßig absinkt; bei Nasen, denen zu viel Gewebe entnommen wurde, kann es zu einem Einsinken kommen.")],
 "ctah":"Beurteilung zur Nasenkorrektur",
 "ctap":"Teilen Sie uns mit, was Sie verändern möchten und ob Sie Atembeschwerden haben, und senden Sie nach Möglichkeit Fotos von vorn und von der Seite."},

"mikrotia": {
 "crumb":"Mikrotie — Ohrrekonstruktion",
 "title":"Mikrotie (angeborenes Fehlen der Ohrmuschel) und Ohrrekonstruktion | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Mikrotie: angeborenes Fehlen der Ohrmuschel und ihre Rekonstruktion",
 "desc":"Was ist Mikrotie und in welchem Alter wird operiert? Ohrrekonstruktion mit Rippenknorpel, die Operationsschritte, Hörvermögen und Heilungsverlauf.",
 "eyebrow":"Rekonstruktive Chirurgie",
 "h1":"Mikrotie: angeborenes Fehlen der Ohrmuschel und ihre Rekonstruktion",
 "lead":"Mikrotie bezeichnet die angeborene Unterentwicklung oder das Fehlen der Ohrmuschel. Sie tritt bei etwa einer von 6.000–10.000 Geburten auf. Aus dem eigenen Rippenknorpel des Kindes lässt sich ein neues Ohrgerüst formen und damit ein natürlich wirkendes, lebenslang haltbares Ohr aufbauen.",
 "watopic":"Mikrotie (Ohrrekonstruktion)",
 "about":"Mikrotie",
 "card":"Mikrotie-Rekonstruktion","cardsub":"Rekonstruktion mit Rippenknorpel bei angeborenem Fehlen der Ohrmuschel",
 "procedure":{"name":"Mikrotie-Rekonstruktion",
   "how":"Aus dem eigenen Rippenknorpel wird ein dreidimensionales Ohrgerüst geschnitzt, unter die Haut eingebracht und in einem späteren Schritt vom Kopf abgehoben, um die natürliche Abstehung zu erzeugen.",
   "prep":"Beurteilung von Knorpelreife und Brustkorbentwicklung; Hörtests und bei Bedarf Computertomographie.",
   "follow":"Wundpflege, Vermeidung von Druck auf das Ohr und geplante Kontrollen zwischen den Schritten.",
   "body":"Ohr"},
 "keyfacts":[("Häufigkeit","1 von 6.000–10.000 Geburten"),("Operationsalter","Meist 8–10 Jahre"),
             ("Verfahren","Autologer Rippenknorpel"),("Schritte","2–3 geplante Etappen")],
 "authority":"Die Mikrotie-Rekonstruktion verlangt handwerkliches Können beim Knorpelschnitzen und Erfahrung aus vielen Fällen. Doz. Dr. Acartürk arbeitete während seines Fellowships an der University of Helsinki an Ohrrekonstruktionen und führt Mikrotie-Operationen regelmäßig auf den freiwilligen chirurgischen Missionen durch, an denen er jährlich in Vietnam teilnimmt.",
 "creds":["University of Helsinki — Fellowship für Mikrochirurgie und Ohrrekonstruktion","Regelmäßige Mikrotie-Chirurgie auf freiwilligen Missionen in Vietnam","Zusatzqualifikation Mund-, Kiefer- und Gesichtschirurgie"],
 "sections":[
  {"id":"nedir","tag":"Grundlagen","h2":"Was ist Mikrotie?","body":[
   "Mikrotie entsteht, wenn die Entwicklung der Ohrmuschel in den frühen Schwangerschaftswochen nicht abgeschlossen wird. Sie ist häufiger einseitig und betrifft meist das rechte Ohr. Dem Fehlen der Ohrmuschel geht oft ein enger oder gar nicht angelegter Gehörgang einher (Atresie).",
   ("h3","Einteilung"),
   ("ul",["<strong>Grad 1:</strong> Das Ohr ist klein, die meisten Strukturen sind jedoch erkennbar.",
          "<strong>Grad 2:</strong> Der untere Ohranteil ist vorhanden, die oberen Strukturen sind nicht entwickelt.",
          "<strong>Grad 3:</strong> Die häufigste Form. Es finden sich nur ein erdnussförmiger Knorpelrest und ein Ohrläppchen; der Gehörgang fehlt meist.",
          "<strong>Grad 4 (Anotie):</strong> Ohrgewebe fehlt vollständig."]),
   ("note","Mikrotie tritt meist isoliert auf, kann jedoch Teil eines Syndroms sein. Die Erstbeurteilung beschränkt sich daher nicht auf das Ohr; Gesichtssymmetrie, Kieferentwicklung und Hörvermögen werden mitbeurteilt.")]},
  {"id":"isitme","tag":"Hörvermögen","h2":"Hören und Sprachentwicklung","body":[
   "Die Ohrmuschel sammelt den Schall, die eigentliche Arbeit des Hörens leistet jedoch das Innenohr. Bei einseitiger Mikrotie mit gesundem Gegenohr verläuft die Sprachentwicklung in der Regel normal. Dennoch können Schwierigkeiten bestehen, die Schallrichtung zu bestimmen und Sprache in lauter Umgebung zu verstehen.",
   "Bei beidseitiger Mikrotie ist die Lage anders: Die Hörversorgung muss <strong>früh</strong> erfolgen. Sie kann mit Knochenleitungshörgeräten sichergestellt werden und ist für die Sprachentwicklung entscheidend.",
   ("note","Die Hördiagnostik ist von der Ohrmuschelrekonstruktion unabhängig und hat Vorrang. Sie wird gemeinsam mit Audiologie und HNO geplant; der Aufbau der Ohrmuschel verbessert das Hören für sich genommen nicht.")]},
  {"id":"yontem","tag":"Operation","h2":"Operationsverfahren und Etappen","body":[
   "Der Goldstandard ist ein dreidimensionales Ohrgerüst aus dem <strong>eigenen Rippenknorpel des Kindes</strong>. Da es sich um körpereigenes Gewebe handelt, besteht kein Abstoßungsrisiko, es wächst mit dem Kind mit und hält ein Leben lang.",
   ("h3","Warum mit 8–10 Jahren?"),
   ("ul",["Der Rippenknorpel erreicht erst in diesem Alter die zum Schnitzen nötige Dicke",
          "Das Ohr erreicht etwa 85% seiner Erwachsenengröße, sodass Symmetrie zum Gegenohr möglich ist",
          "Das Kind ist reif genug, an der Nachsorge mitzuwirken",
          "Der Zeitpunkt liegt vor den Schuljahren, in denen das Aussehen an Bedeutung gewinnt"]),
   ("h3","Die Etappen"),
   ("steps",[
    ("ETAPPE 1 — GERÜST","Rippenknorpel wird entnommen, zu einem Ohrgerüst geschnitzt und in eine an der Ohrregion vorbereitete Hauttasche eingebracht."),
    ("ETAPPE 2 — OHRLÄPPCHEN","Das vorhandene Ohrläppchen wird in die richtige Position gebracht und mit dem Gerüst verbunden. In manchen Plänen wird dies mit der ersten Etappe zusammengelegt."),
    ("ETAPPE 3 — ABHEBEN DES OHRS","Das Ohr wird vom Kopf abgehoben; dahinter werden Gewebe und ein Hauttransplantat eingebracht, um dem Ohr seinen natürlichen Winkel und seine Tiefe zu geben.")]),
   "Zwischen den Etappen liegen in der Regel 4–6 Monate. Diese Zeit ist nötig, damit sich das Gewebe setzt und die Durchblutung ausreift."]},
  {"id":"deneyim","tag":"Erfahrung","h2":"Erfahrung auf diesem Gebiet","body":[
   "Die Mikrotie-Rekonstruktion gehört zu den Bereichen der plastischen Chirurgie, die am stärksten von Wiederholung und handwerklichem Können abhängen. Das Schnitzen des Knorpels entscheidet unmittelbar darüber, ob das Ergebnis natürlich wirkt.",
   "Doz. Dr. Acartürk nimmt jedes Jahr an freiwilligen chirurgischen Missionen in Vietnam teil und führt dort Mikrotie-Rekonstruktionen, Lippen-Kiefer-Gaumenspalten-Operationen und Plexus-brachialis-Chirurgie durch. Auch während seines Fellowships an der University of Helsinki gehörte die Ohrrekonstruktion zu seinen Arbeitsgebieten.",
   ("note","Eine verfrühte Mikrotie-Rekonstruktion kann das Ergebnis dauerhaft einschränken — sowohl wegen unzureichenden Knorpels als auch wegen der Symmetrie. Der richtige Zeitpunkt ist nicht weniger wichtig als die richtige Technik.")]}],
 "faqs":[
  ("Welches Alter ist für die Mikrotie-Operation richtig?","Da der Rippenknorpel ausreichend dick und das Ohr nahezu erwachsen groß sein muss, werden meist 8–10 Jahre empfohlen. Bei beidseitiger Mikrotie und je nach Brustkorbentwicklung kann dieser Zeitraum abweichen."),
  ("Wie viele Operationen sind nötig?","In der Regel werden 2–3 Etappen mit 4–6 Monaten Abstand geplant. Die Zahl richtet sich nach dem Schweregrad und dem vorhandenen Gewebe."),
  ("Schadet die Entnahme von Rippenknorpel dem Kind?","Der Entnahmebereich regeneriert sich mit der Zeit und die Brustkorbentwicklung verläuft normal. Schmerzen im Brustbereich sind in den ersten Tagen zu erwarten und werden behandelt."),
  ("Verbessert die Operation das Hören?","Nein. Der Aufbau der Ohrmuschel stellt das Aussehen wieder her; das Hören ist eine eigene Frage und wird mit Audiologie und HNO beurteilt. Bei Bedarf werden Knochenleitungsgeräte oder eine gesonderte Ohroperation geplant."),
  ("Ist eine Ohrprothese eine Option?","Klebe- oder implantatgetragene Prothesen sind in manchen Situationen eine Option, besonders bei unzureichendem Knorpel oder wenn keine Operation gewünscht wird. Die Rekonstruktion mit Eigengewebe ist jedoch dauerhaft und erfordert keine tägliche Pflege."),
  ("Bleiben sichtbare Narben?","Narben entstehen hinter dem Ohr und am Brustkorb. Der Brustschnitt wird in die Unterbrustfalte gelegt, die Narben hinter dem Ohr liegen im Schatten von Ohr und Haaren; sie werden mit der Zeit unauffälliger.")],
 "ctah":"Beurteilung zur Mikrotie",
 "ctap":"Senden Sie uns das Alter Ihres Kindes, welches Ohr betroffen ist, vorhandene Hörtestergebnisse und Fotos. Wir melden uns für ein Planungsgespräch."},
}
