# -*- coding: utf-8 -*-
"""Almanca ceviriler — parti 3: estetik cerrahi."""

STEPS = lambda op, days, back: ("steps",[
 ("SCHRITT 1 — ERSTKONTAKT","Erster Kontakt per WhatsApp oder Formular, anhand Ihrer Vorstellungen, Ihrer Vorgeschichte und eventueller Fotos."),
 ("SCHRITT 2 — UNTERSUCHUNG UND PLANUNG","Beurteilung Ihrer Anatomie sowie offene Besprechung möglicher Techniken, Risiken und realistischer Erwartungen."),
 ("SCHRITT 3 — VORBEREITUNG","Blutuntersuchungen, Narkosevorbereitung, Anpassung von Rauchen und blutverdünnenden Medikamenten."),
 ("SCHRITT 4 — OPERATION", op),
 ("SCHRITT 5 — ERSTE TAGE", days),
 ("SCHRITT 6 — RÜCKKEHR UND NACHSORGE", back)])

T = {
"meme-estetigi": {
 "crumb":"Brustästhetik",
 "title":"Brustästhetik: Vergrößerung, Verkleinerung und Straffung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Brustästhetik: Vergrößerung, Verkleinerung und Straffung",
 "desc":"Brustvergrößerung, Brustverkleinerung und Bruststraffung (Mastopexie): Implantatwahl, Narbenverläufe, Stillen, Heilungsverlauf und häufige Fragen.",
 "eyebrow":"Ästhetische Chirurgie",
 "h1":"Brustästhetik: Vergrößerung, Verkleinerung, Straffung",
 "lead":"In der Brustchirurgie gibt es keine einzige richtige Antwort. Richtig ist der Plan, der zu Ihren Proportionen, Ihrer Gewebequalität und Ihrer Lebensweise passt. Manche Patientinnen wünschen Volumen, andere möchten Last abgeben; für die meisten geht es darum, Form und Straffheit zurückzugewinnen.",
 "watopic":"Brustästhetik",
 "about":"Ästhetische Brustchirurgie",
 "card":"Brustästhetik","cardsub":"Vergrößerung, Verkleinerung und Straffung",
 "procedure":{"name":"Ästhetische Brustchirurgie",
   "how":"Je nach Ziel wird ein Implantat eingesetzt, Brustgewebe verkleinert und neu geformt oder das Brustgewebe höher an der Brustwand positioniert.",
   "prep":"Untersuchung, Vermessung, Brustbildgebung und Implantatplanung.",
   "follow":"Sport-BH, Hebebeschränkungen und geplante Kontrollen.","body":"Brust"},
 "keyfacts":[("Narkose","Vollnarkose"),("Dauer","1,5–3 Stunden"),
             ("Rückkehr zur Arbeit","5–10 Tage"),("Sport","Nach 4–6 Wochen")],
 "authority":"In der Brustästhetik verwendet Doz. Dr. Acartürk eine Verkleinerungstechnik, die <strong>weniger Narben hinterlässt und die Brust stärker anhebt</strong> als das unter seinen amerikanischen Kollegen übliche Vorgehen. Deshalb wurden ihm in Pittsburgh besonders jüngere Patientinnen überwiesen, für die das ästhetische Ergebnis im Vordergrund stand.",
 "creds":["Brustverkleinerungstechnik mit geringerer Narbenbildung","Hohe brustchirurgische Fallzahl in den USA durch Kollegenzuweisungen","Integrierter Ansatz aus der Erfahrung in der Brustrekonstruktion"],
 "sections":[
  {"id":"buyutme","tag":"Vergrößerung","h2":"Brustvergrößerung","body":[
   "Sie wird bei Volumenverlust, anlagebedingt kleiner Brust oder Erschlaffung nach einer Schwangerschaft durchgeführt. Ziel ist keine große Brust, sondern ein Volumen, das zu Ihrem Körper passt und natürlich wirkt.",
   ("h3","Wahl des Implantats"),
   ("ul",["<strong>Lage:</strong> unter dem Muskel, über dem Muskel oder Dual Plane. Entscheidend ist Ihre Gewebedicke; bei dünnem Gewebe wirkt die submuskuläre Lage natürlicher.",
          "<strong>Form:</strong> Runde Implantate geben dem oberen Pol Fülle; tropfenförmige erzeugen einen natürlicheren Verlauf.",
          "<strong>Oberfläche und Größe:</strong> richten sich nach Ihrer Brustkorbbreite. Ein Implantat, das größer ist als Ihre Anatomie tragen kann, führt langfristig zu Absinken und Gewebeverdünnung."]),
   ("h3","Vergrößerung mit Eigenfett"),
   "Mit Ihrem eigenen Fettgewebe lässt sich eine begrenzte Volumenzunahme erreichen. Es enthält kein Fremdmaterial und fühlt sich natürlich an, die Zunahme ist jedoch geringer als mit einem Implantat und ein Teil des Fetts wird resorbiert.",
   ("note","Implantate sind keine Produkte für ein ganzes Leben. Sie können im Lauf der Jahre gewechselt werden müssen; regelmäßige Kontrollen und bei Bedarf Bildgebung gehören zum Plan.")]},
  {"id":"kucultme","tag":"Verkleinerung","h2":"Brustverkleinerung","body":[
   "Die Brustverkleinerung ist nicht nur eine ästhetische Entscheidung. Eine große Brust verursacht Rücken-, Nacken- und Schulterschmerzen, Einschnürungen durch BH-Träger, Pilzinfektionen in der Unterbrustfalte und Haltungsschäden. Der Satz, den Patientinnen danach am häufigsten sagen, lautet: „Hätte ich das nur früher gemacht.“",
   "Doz. Dr. Acartürk verwendet eine Technik, die <strong>weniger Narben hinterlässt und die Brust stärker anhebt</strong> als das unter seinen amerikanischen Kollegen übliche Vorgehen; jüngere Patientinnen, denen das Aussehen besonders wichtig war, wurden ihm deshalb überwiesen.",
   ("h3","Narbenverläufe"),
   ("ul",["<strong>Vertikale Narbe (Lollipop):</strong> um den Warzenhof und senkrecht nach unten. Bevorzugt bei mittleren Verkleinerungen.",
          "<strong>Umgekehrtes T (Anker):</strong> zusätzlich zur vertikalen eine waagerechte Linie in der Unterbrustfalte. Bei sehr großen Volumina erforderlich."]),
   ("note","Die Verkleinerung strafft die Brust zugleich; eine gesonderte Mastopexie ist nicht nötig. Stillen bleibt bei den meisten Patientinnen möglich, kann aber wegen der Beteiligung der Milchgänge nicht garantiert werden.")]},
  {"id":"dikleştirme","tag":"Straffung","h2":"Bruststraffung (Mastopexie)","body":[
   "Schwangerschaft, Stillzeit, Gewichtsschwankungen und die Schwerkraft lassen das Brustgewebe mit der Zeit absinken. Die Mastopexie hebt die Brust an die Stelle, an der sie sein sollte, und positioniert die Brustwarze neu — ohne Gewebe zu entfernen oder hinzuzufügen.",
   ("ul",["Nur Absinken: Mastopexie allein genügt",
          "Absinken plus Volumenverlust: Mastopexie in Kombination mit einem Implantat",
          "Absinken plus zu viel Volumen: eine Verkleinerung löst beides zugleich"]),
   "Zu welcher Gruppe Sie gehören, ergibt sich aus der Lage der Brustwarze zur Unterbrustfalte. Diese Unterscheidung verändert den Operationsplan unmittelbar."]},
  {"id":"surec","tag":"Ablauf","h2":"Der Heilungsverlauf","body":[
   STEPS("1,5–3 Stunden in Vollnarkose, meist mit einer Nacht in der Klinik.",
         "Unterstützung durch einen Sport-BH. Ein Spannungsgefühl in den ersten Tagen ist normal; Schmerzen werden gut kontrolliert.",
         "Rückkehr zur Bürotätigkeit in 5–10 Tagen. Schweres Heben und Sport werden 4–6 Wochen aufgeschoben. Die endgültige Form stellt sich nach 3–6 Monaten ein, die Narben verblassen im Lauf eines Jahres.")]}],
 "faqs":[
  ("Kann ich nach der Operation stillen?","Bei der Vergrößerung werden die Milchgänge meist nicht berührt und Stillen ist möglich. Bei Verkleinerung und Straffung können einzelne Gänge betroffen sein; die meisten Patientinnen können dennoch stillen, garantiert werden kann es jedoch nicht. Teilen Sie Ihre Pläne vor der Operation mit."),
  ("Wie auffällig bleiben die Narben?","Narben sind in den ersten Monaten rot und deutlich, verblassen aber bis zum Ende des ersten Jahres in Richtung Hautton. Silikonpflaster, Sonnenschutz und Rauchverzicht beeinflussen die Narbenqualität unmittelbar."),
  ("Halten Implantate ein Leben lang?","Nein. Implantate sind Medizinprodukte, die mit der Zeit gewechselt werden müssen können. Eine feste Haltbarkeit lässt sich nicht garantieren; regelmäßige Kontrollen und bei Bedarf Bildgebung werden empfohlen."),
  ("Übernimmt die Krankenkasse die Brustverkleinerung?","Wenn Rücken- und Nackenbeschwerden sowie Hautprobleme infolge großer Brüste dokumentiert sind, übernehmen manche Kassen die Kosten. Die Bedingungen unterscheiden sich und sollten vorab geklärt werden."),
  ("Beeinträchtigt die Operation meine Mammographie?","Nein. Bei Patientinnen mit Implantat werden spezielle Aufnahmetechniken (Eklund-Technik) eingesetzt. Ihre Brustkrebsvorsorge läuft im gewohnten Rhythmus weiter; informieren Sie lediglich das radiologische Team."),
  ("Verliere ich das Gefühl in der Brustwarze?","Vorübergehende Gefühlsveränderungen sind häufig und bilden sich über Monate weitgehend zurück. Eine dauerhafte Gefühlsminderung ist selten, aber möglich; bei Verkleinerungen ist das Risiko etwas höher als bei Vergrößerungen.")],
 "ctah":"Beurteilung zur Brustästhetik",
 "ctap":"Teilen Sie uns mit, was Sie verändern möchten, ob Sie eine Schwangerschaft planen, ob frühere Brustoperationen stattgefunden haben, sowie Größe und Gewicht."},

"yuz-germe": {
 "crumb":"Facelift",
 "title":"Facelift und Halsstraffung — SMAS-Techniken | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Facelift und Halsstraffung",
 "desc":"Was ein Facelift umfasst: SMAS- und Deep-Plane-Techniken, Planung zusammen mit einer Halsstraffung, Narbenverläufe und Heilungsverlauf.",
 "eyebrow":"Ästhetische Chirurgie",
 "h1":"Facelift und Halsstraffung",
 "lead":"Alterung bedeutet nicht nur erschlaffte Haut: Die Fettpolster sinken ab, Volumen geht verloren, die Muskelschicht erschlafft. Straffen der Haut allein erzeugt ein gespanntes, aber weiterhin gealtertes Gesicht. Das richtige Ergebnis entsteht, wenn die Gewebe an ihren ursprünglichen Ort zurückgeführt werden.",
 "watopic":"Facelift",
 "about":"Rhytidektomie",
 "card":"Facelift","cardsub":"Gesichts- und Halsverjüngung mit SMAS- und Deep-Plane-Techniken",
 "procedure":{"name":"Facelift (Rhytidektomie)",
   "how":"Die unter der Haut liegende SMAS-Schicht wird gelöst und nach oben und hinten neu positioniert; überschüssige Haut wird anschließend ohne Spannung entfernt.",
   "prep":"Untersuchung, Fotoanalyse, Blutuntersuchungen und Rauchstopp.",
   "follow":"Gesichtsverband, Ödemmanagement, erhöhte Kopflage in der ersten Woche.","body":"Gesicht und Hals"},
 "keyfacts":[("Narkose","Vollnarkose"),("Dauer","4–6 Stunden"),
             ("Gesellschaftsfähig","2–3 Wochen"),("Haltbarkeit","8–12 Jahre")],
 "authority":"Beim Facelift entscheidet der richtige Umgang mit den tiefen Geweben über das Ergebnis, nicht die Haut. Die Erfahrung von Doz. Dr. Acartürk in der Kopf-Hals-Rekonstruktion und der Gesichtsskelettchirurgie verschafft ihm Sicherheit in allen Schichten der Gesichtsanatomie. Seine Zusatzqualifikation in Mund-, Kiefer- und Gesichtschirurgie besitzen nur wenige plastische Chirurgen.",
 "creds":["Zusatzqualifikation Mund-, Kiefer- und Gesichtschirurgie","Ehem. Direktor für Kopf-Hals-Rekonstruktion, University of Pittsburgh","Erfahrung in Eigenfetttransfer und stammzellgestützter Volumengabe"],
 "sections":[
  {"id":"teknik","tag":"Technik","h2":"Der SMAS- und Deep-Plane-Ansatz","body":[
   "Unter der Gesichtshaut liegt eine Schicht aus Muskel- und Bindegewebe, das SMAS. Sie ist es, die beim Altern tatsächlich absinkt. Beim modernen Facelift ist die Haut nur die Hülle; die tragende Arbeit übernimmt die SMAS-Schicht.",
   ("ul",["<strong>SMAS-Plikatur:</strong> Die Schicht wird gefaltet und aufgehängt. Weniger invasiv, geeignet bei mittlerer Erschlaffung.",
          "<strong>SMAS-Ektomie:</strong> Ein Streifen wird aus der Schicht entnommen, um Spannung zu erzeugen.",
          "<strong>Deep Plane:</strong> SMAS und Haut werden als Einheit gehoben und neu positioniert. Das ergibt im Mittelgesicht und in der Nasolabialregion ein kräftigeres und länger anhaltendes Ergebnis."]),
   ("note","Ein „gezogenes“ Aussehen entsteht durch übermäßigen Zug an der Haut. Trägt die SMAS-Schicht die Last, bleibt die Hautspannung gering, der Ausdruck natürlich und die Narbenqualität deutlich besser.")]},
  {"id":"boyun","tag":"Hals","h2":"Planung zusammen mit einer Halsstraffung","body":[
   "Gesicht und Hals lassen sich nicht getrennt betrachten. Ein erschlaffter Hals unter einem gestrafften Gesicht verdirbt das gesamte Ergebnis. Am Hals können drei Probleme gleichzeitig vorliegen:",
   ("ul",["Fettansammlung unter dem Kinn — wird mit Liposuktion entfernt",
          "Auseinanderweichen des Platysma in der Mittellinie mit Strangbildung — wird mit Nähten vereinigt (Platysmaplastik)",
          "Überschüssige, erschlaffte Haut — wird über den Schnitt hinter dem Ohr aufgehängt"]),
   "Welche dieser Komponenten bei Ihnen vorliegen, wird bei der Untersuchung bestimmt und der Plan entsprechend aufgebaut."]},
  {"id":"tamamlayici","tag":"Ergänzend","h2":"Ergänzende Eingriffe","body":[
   "Ein Facelift korrigiert das Absinken, <strong>bringt aber verlorenes Volumen nicht zurück</strong>. Deshalb gehört zu den meisten Plänen ein Eigenfetttransfer: Schläfen, Wangenknochen und die Tränenrinne werden mit Ihrem eigenen Fett aufgefüllt.",
   ("ul",["<a href=\"../goz-kapagi-estetigi.html\">Lidchirurgie</a> — häufig kombiniert, um den müden Ausdruck der Augen zu nehmen",
          "<a href=\"../yag-enjeksiyonu.html\">Eigenfetttransfer</a> — Ausgleich des Volumenverlusts",
          "Brauenlift — bei ausgeprägtem Absinken von Stirn und Brauen",
          "Hautoberflächenbehandlungen — gegen Pigmentflecken und feine Linien, nach abgeschlossener Heilung"]),
   ("note","Ein Facelift verändert die Hautqualität nicht. Pigmentflecken, feine Linien und Porenprobleme werden durch die Operation nicht behoben; dafür sind gesonderte Oberflächenbehandlungen nötig, meist nach abgeschlossener Heilung.")]},
  {"id":"surec","tag":"Ablauf","h2":"Der Heilungsverlauf","body":[
   STEPS("4–6 Stunden in Vollnarkose, mit einer Nacht in der Klinik.",
         "Gesichtsverband und Drainagen. Schwellung und Blutergüsse sind an Tag 4–7 am stärksten; in der ersten Woche ist erhöhte Kopflage nötig.",
         "Die Fäden werden an Tag 7–10 entfernt. Die meisten Patienten kehren nach 2–3 Wochen ins gesellschaftliche Leben zurück. Bis Schwellung und Narben vollständig abklingen, vergehen 6–12 Monate."),
   ("ul",["Rauchen stört die Wundheilung und erhöht das Risiko eines Hautverlusts erheblich — es sollte mindestens 4 Wochen vorher eingestellt werden",
          "In den ersten 3 Wochen sind schwerer Sport und Bücken eingeschränkt",
          "Haarfärbung wird meist 4–6 Wochen aufgeschoben"])]}],
 "faqs":[
  ("Wie lange hält das Ergebnis eines Facelifts?","Die Operation dreht die Uhr zurück, hält sie aber nicht an. Bei einer gut geplanten, von der SMAS-Schicht getragenen Straffung bleibt das Ergebnis in der Regel 8–12 Jahre erhalten; die Alterung geht von diesem Punkt aus weiter."),
  ("Wo verlaufen die Narben?","Die Schnitte werden im Haaransatz, in der natürlichen Falte vor dem Ohr und hinter dem Ohr verborgen. Richtig geplant liegen sie im Schatten von Haar und Ohr und sind aus normaler Entfernung nicht erkennbar."),
  ("Ersetzt ein Fadenlifting das Facelift?","Nein. Fäden bewirken einen begrenzten, vorübergehenden Effekt, der meist nach 1–2 Jahren verschwindet. Bei ausgeprägter Erschlaffung sind sie keine Alternative zur operativen Straffung."),
  ("In welchem Alter sollte man ein Facelift machen lassen?","Entscheidend ist der Gewebezustand, nicht das Alter. Die meisten Patienten sind zwischen 45 und 65, bei früher Alterung oder deutlichem Gewichtsverlust kann es auch früher sinnvoll sein."),
  ("Verändert sich mein Gesichtsausdruck?","Ziel ist der Erhalt des Ausdrucks. Wird die Last auf die SMAS-Schicht statt auf die Haut gelegt, bleibt der Ausdruck natürlich. Eine vorübergehende Schwäche durch Nervenreizung ist selten und bildet sich meist innerhalb von Wochen zurück."),
  ("Wann kann ich wieder an einem geschäftlichen Termin teilnehmen?","Blutergüsse lassen sich meist nach etwa 2 Wochen abdecken, wirklich wohl fühlt man sich nach etwa 3 Wochen. Bei einem wichtigen Termin sollten Sie mindestens 4 Wochen einplanen.")],
 "ctah":"Beurteilung zum Facelift",
 "ctap":"Teilen Sie uns mit, was Sie am meisten stört, ob frühere ästhetische Eingriffe stattgefunden haben, und senden Sie Fotos von vorn und von der Seite."},

"karin-germe": {
 "crumb":"Bauchdeckenstraffung",
 "title":"Bauchdeckenstraffung (Abdominoplastik) — Muskelrekonstruktion und Heilung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Bauchdeckenstraffung (Abdominoplastik)",
 "desc":"Abdominoplastik: Wer ist geeignet, Rekonstruktion der Rektusdiastase, Unterschied zur Mini-Abdominoplastik, Narbenverlauf und Heilungsprozess.",
 "eyebrow":"Ästhetische Chirurgie",
 "h1":"Bauchdeckenstraffung (Abdominoplastik)",
 "lead":"Schwangerschaft und starker Gewichtsverlust hinterlassen am Bauch zwei bleibende Spuren: überschüssige, erschlaffte Haut und in der Mittellinie auseinandergewichene Bauchmuskeln. Beides kommt mit Diät und Sport nicht zurück. Die Bauchdeckenstraffung behandelt Haut und Muskelwand gemeinsam.",
 "watopic":"Bauchdeckenstraffung",
 "about":"Abdominoplastik",
 "card":"Bauchdeckenstraffung","cardsub":"Entfernung überschüssiger Haut und Rekonstruktion der Bauchmuskeln",
 "procedure":{"name":"Abdominoplastik",
   "how":"Überschüssige Haut und Fett werden über einen Schnitt in der Bikinilinie entfernt, die auseinandergewichenen Bauchmuskeln mit Nähten in der Mittellinie vereinigt und der Nabel neu geformt.",
   "prep":"Stabiles Zielgewicht, Rauchstopp, Blutuntersuchungen und bei Bedarf Bruchabklärung.",
   "follow":"Kompressionsmieder, frühes Gehen, Hebebeschränkungen.","body":"Bauch"},
 "keyfacts":[("Narkose","Vollnarkose"),("Dauer","2–4 Stunden"),
             ("Klinik","1–2 Nächte"),("Rückkehr zur Arbeit","2–3 Wochen")],
 "authority":"Die Bauchdeckenstraffung ist ebenso sehr funktionelle Rekonstruktion der Bauchwand wie ästhetischer Eingriff. Die dreijährige allgemeinchirurgische Ausbildung von Doz. Dr. Acartürk und seine Erfahrung in der Bauchwandrekonstruktion erlauben es, Muskelrekonstruktion und begleitende Brüche sicher in derselben Operation zu versorgen.",
 "creds":["Drei Jahre allgemeinchirurgische Ausbildung — Bauchwand- und Hernienchirurgie","Erfahrung in Rumpf- und Bauchrekonstruktion","Vertrautheit mit der Bauchanatomie durch DIEP-Lappenchirurgie"],
 "sections":[
  {"id":"kimler","tag":"Für wen","h2":"Für wen ist der Eingriff geeignet?","body":[
   ("ul",["Frauen, deren Bauchhaut nach einer Schwangerschaft erschlafft und deren Muskeln auseinandergewichen sind",
          "Personen mit erschlaffter Bauchhaut nach deutlichem Gewichtsverlust",
          "Personen mit einem Absinken des Unterbauchs, das auf Diät und Sport nicht anspricht",
          "Personen, deren Gewicht stabil ist und die es halten können"]),
   ("h3","Für wen ist er nicht geeignet?"),
   ("ul",["Personen mit geplanter deutlicher Gewichtsabnahme — die Operation sollte nach Erreichen des Zielgewichts erfolgen",
          "Frauen mit Kinderwunsch in naher Zukunft — eine Schwangerschaft trennt die rekonstruierte Muskelwand erneut",
          "Personen, die das Rauchen nicht einstellen können — das Risiko für Wundheilungsstörungen und Gewebeverlust steigt deutlich"]),
   ("note","Die Bauchdeckenstraffung ist keine Methode zur Gewichtsabnahme. Sie entfernt regionales Fett und überschüssige Haut, senkt aber nicht das Gesamtgewicht. Erwartungen in diesem Rahmen zu setzen ist der stärkste Faktor für Zufriedenheit.")]},
  {"id":"diastazis","tag":"Muskelrekonstruktion","h2":"Rektusdiastase: auseinandergewichene Bauchmuskeln","body":[
   "In der Schwangerschaft drückt die wachsende Gebärmutter die beiden geraden Bauchmuskeln aus der Mittellinie zur Seite. Nach der Geburt kehren sie oft nicht in ihre Ausgangslage zurück; das Bindegewebe dazwischen bleibt gedehnt. Das nennt man <strong>Rektusdiastase</strong>.",
   "Eine Diastase führt nicht nur zu einem vorgewölbten Bauch, sondern auch zu Rückenschmerzen, Problemen mit dem Bauchinnendruck und Haltungsschäden. Übungen wie Sit-ups oder Planks schließen die Lücke nicht und können sie vergrößern.",
   "Bei der Bauchdeckenstraffung werden diese Muskeln mit Nähten wieder in der Mittellinie vereinigt. Die Taille wird schmaler und die Bauchwand gewinnt funktionell an Kraft. Das ist die funktionelle, nicht die ästhetische Seite des Eingriffs.",
   ("note","Liegt ein Nabelbruch vor, kann er in derselben Operation versorgt werden. Eine Untersuchung auf Brüche und bei Bedarf eine Bildgebung gehören zum Standardvorgehen.")]},
  {"id":"tipler","tag":"Verfahren","h2":"Vollständige und Mini-Abdominoplastik","body":[
   ("table",["","Vollständige Abdominoplastik","Mini-Abdominoplastik"],[
    ["Umfang","Ober- und Unterbauch","Nur Unterbauch"],
    ["Nabel","Wird neu geformt","Bleibt an Ort und Stelle"],
    ["Muskelrekonstruktion","Über die gesamte Mittellinie","Nur im unteren Bereich"],
    ["Narbe","Länger, entlang der Bikinilinie","Kürzer"],
    ["Geeignet bei","Deutlichem Absinken und Diastase","Begrenzter Erschlaffung des Unterbauchs"]]),
   "Eine Liposuktion begleitet die meisten Pläne; die Formung von Taille und Flanken bestimmt die Stimmigkeit des Ergebnisses. Bei Erschlaffung des gesamten Rumpfes kommt eine <a href=\"../kol-uyluk-germe.html\">Körperstraffung</a> infrage."]},
  {"id":"surec","tag":"Ablauf","h2":"Der Heilungsverlauf","body":[
   STEPS("2–4 Stunden in Vollnarkose, mit 1–2 Nächten in der Klinik und eingelegten Drainagen.",
         "In den ersten Tagen geht man leicht vorgebeugt; das ist normal und bessert sich innerhalb weniger Tage. Frühes Gehen ist wichtig, da es das Thromboserisiko senkt.",
         "Das Mieder wird 6 Wochen getragen. Rückkehr zur Bürotätigkeit in 2–3 Wochen; schwerer Sport wird 6–8 Wochen aufgeschoben. Die endgültige Form stellt sich nach 6 Monaten ein."),
   ("ul",["Thromboseprophylaxe: frühe Mobilisation, bei Bedarf Kompressionsstrümpfe und Blutverdünner",
          "In den ersten 6 Wochen kein schweres Heben",
          "Narbenpflege mit Silikonpflaster und Sonnenschutz sollte im ersten Jahr fortgeführt werden"])]}],
 "faqs":[
  ("Wo verläuft die Narbe und wie lang ist sie?","Der Schnitt wird in die Bikinilinie gelegt, auf Höhe der Unterwäsche. Die Länge hängt von der entfernten Hautmenge ab; bei ausgeprägter Erschlaffung reicht sie zwischen den Hüftknochen. Die Narbe ist bleibend, verblasst aber mit der Zeit."),
  ("Kann ich nach der Operation schwanger werden?","Medizinisch ja, doch eine Schwangerschaft trennt die rekonstruierte Muskelwand erneut und dehnt die Haut wieder. Bei Kinderwunsch empfiehlt es sich, die Operation zu verschieben."),
  ("Was ist der Unterschied zur Liposuktion?","Die Liposuktion entfernt nur Fett und eignet sich für Patienten mit guter Hautqualität. Ist die Haut erschlafft oder sind die Muskeln auseinandergewichen, reicht sie nicht aus und kann das Absinken sogar verstärken."),
  ("Wie wird mein Nabel aussehen?","Bei der vollständigen Abdominoplastik bleibt der Nabel an Ort und Stelle, die umgebende Haut wird nach unten gezogen und der Nabel durch die neue Haut ausgeleitet. Um ihn herum entsteht eine feine Narbe, die mit der Zeit unauffällig wird."),
  ("Wann kann ich wieder Sport treiben?","Gehen beginnt in den ersten Tagen. Leichtes Cardiotraining ab der 4. Woche, Bauchübungen ab der 8. Woche, jeweils schrittweise und nach ärztlicher Freigabe."),
  ("Kommt es zu Gefühlsverlust?","Eine vorübergehende Taubheit unterhalb des Nabels ist zu erwarten und bildet sich über Monate weitgehend zurück. In einem kleinen Bereich kann eine dauerhafte Gefühlsminderung bleiben.")],
 "ctah":"Beurteilung zur Bauchdeckenstraffung",
 "ctap":"Teilen Sie uns Ihre Schwangerschaftsgeschichte, Ihre Gewichtsentwicklung und die Dauer Ihres stabilen Gewichts mit und senden Sie nach Möglichkeit Fotos."},

"liposuction": {
 "crumb":"Liposuktion und Body Contouring",
 "title":"Liposuktion (Fettabsaugung) und Body Contouring | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Liposuktion und Body Contouring",
 "desc":"Was Liposuktion leistet, für wen sie geeignet ist, VASER- und kraftassistierte Techniken, Konturierung mit Eigenfetttransfer, Heilung und realistische Erwartungen.",
 "eyebrow":"Ästhetische Chirurgie",
 "h1":"Liposuktion und Body Contouring",
 "lead":"Die Liposuktion ist keine Methode zur Gewichtsabnahme; sie entfernt regionale Fettdepots, die Diät und Sport widerstehen, und stellt die Proportionen wieder her. Beim richtigen Patienten verändert sie die Kontur deutlich, beim falschen enttäuscht sie. Der Unterschied beginnt bei der richtigen Indikation.",
 "watopic":"Liposuktion",
 "about":"Liposuktion",
 "card":"Liposuktion","cardsub":"Regionale Fettentfernung und Körperkontur",
 "procedure":{"name":"Liposuktion",
   "how":"Nach Infiltration der Tumeszenzlösung wird das Unterhautfett über kleine Schnitte mit Kanülen kontrolliert abgesaugt.",
   "prep":"Stabiles Zielgewicht, Beurteilung der Hautelastizität und Anpassung des Kompressionsmieders.",
   "follow":"Kompressionsversorgung, Lymphdrainage und schrittweise Rückkehr zu Aktivitäten.",
   "body":"Bauch, Taille, Oberschenkel, Arme, Rücken, Kinn"},
 "keyfacts":[("Narkose","Vollnarkose oder Sedierung"),("Dauer","1–3 Stunden"),
             ("Kompression","4–6 Wochen"),("Endgültige Form","3–6 Monate")],
 "authority":"Doz. Dr. Acartürk gehört zu den ersten türkischen plastischen Chirurgen, die an der University of Pittsburgh zu Fettgewebe und fettgewebsstämmigen Stammzelltechnologien gearbeitet haben. Diese Erfahrung erlaubt es ihm, die Liposuktion nicht bloß als Fettentfernung, sondern als Formungsinstrument zu begreifen, bei dem das gewonnene Gewebe weiterverwendet werden kann.",
 "creds":["Forschung zu Fettgewebe und Stammzellen an der University of Pittsburgh","Erfahrung in lymphgefäßschonenden Liposuktionstechniken","Body Contouring integriert mit Eigenfetttransfer"],
 "sections":[
  {"id":"kimler","tag":"Für wen","h2":"Wer ist die richtige Patientin, der richtige Patient?","body":[
   "Entscheidend ist bei der Liposuktion nicht die entnommene Fettmenge, sondern <strong>die Fähigkeit der Haut, sich zurückzubilden</strong>. Nach der Fettentnahme muss sich die Haut an das neue Volumen anpassen; bei Haut, die ihre Elastizität verloren hat, macht die Fettentfernung die Erschlaffung sichtbar.",
   ("ul",["Personen nahe ihrem Idealgewicht, aber mit regionalen Fettdepots",
          "Personen mit erhaltener Hautelastizität",
          "Personen mit einer Lebensweise, die das Gewicht hält",
          "Personen mit realistischen Erwartungen"]),
   ("note","Ist die Haut erschlafft, reicht die Liposuktion allein nicht aus. Dann muss sie zusammen mit einer <a href=\"../karin-germe.html\">Bauchdeckenstraffung</a> oder einer <a href=\"../kol-uyluk-germe.html\">Arm- bzw. Oberschenkelstraffung</a> geplant werden. Diese Unterscheidung vorab zu treffen beseitigt die häufigste Ursache für Unzufriedenheit.")]},
  {"id":"teknik","tag":"Technik","h2":"Verwendete Techniken","body":[
   ("ul",["<strong>Tumeszenz-Liposuktion:</strong> Zunächst wird eine spezielle Lösung infiltriert; Blutung und Schmerz nehmen ab, das Fett löst sich leichter. Sie ist die Grundlage aller Verfahren.",
          "<strong>VASER (ultraschallassistiert):</strong> Ultraschallenergie zerlegt Fettzellen selektiv. Vorteilhaft in fibrösen Arealen und bei der Betonung von Muskelkonturen.",
          "<strong>PAL (kraftassistiert):</strong> Eine vibrierende Kanüle ermöglicht das Arbeiten in derbem Gewebe mit weniger Trauma.",
          "<strong>WAL (wasserstrahlassistiert):</strong> Ein Wasserstrahl löst das Fett schonend und wird, da er die lymphatischen Strukturen schont, bei der <a href=\"../lipodem-cerrahisi.html\">Lipödemchirurgie</a> bevorzugt."]),
   ("h3","Konturierung mit Eigenfetttransfer"),
   "Das gewonnene Fett muss nicht verworfen werden. Es kann aufbereitet und in Bereiche übertragen werden, in denen Volumen erwünscht ist — Gesäß, Brust oder Gesicht. So lassen sich Verschlankung und Volumengabe in derselben Sitzung verbinden. Einzelheiten auf unserer <a href=\"../yag-enjeksiyonu.html\">Seite zum Eigenfetttransfer</a>.",
   ("note","Es gibt eine Grenze für die Fettmenge, die in einer Sitzung sicher entnommen werden kann. Ihre Überschreitung stört den Flüssigkeits- und Elektrolythaushalt und schafft ernsthafte Risiken. Bei großen Arealen wird die Behandlung auf mehrere Sitzungen verteilt.")]},
  {"id":"surec","tag":"Ablauf","h2":"Der Heilungsverlauf","body":[
   STEPS("1–3 Stunden je nach Zahl der Areale. Bei begrenzten Arealen Entlassung am selben Tag, bei größeren eine Nacht in der Klinik.",
         "Das Mieder wird ab dem ersten Tag getragen. Blutergüsse und Schwellung sind an Tag 3–5 am stärksten; ein Nässen in den ersten Tagen ist normal.",
         "Rückkehr zur Bürotätigkeit in 3–7 Tagen. Das Mieder wird 4–6 Wochen getragen, Sport ab der 4. Woche schrittweise. Die endgültige Form stellt sich nach 3–6 Monaten ein."),
   ("ul",["Manuelle Lymphdrainage beschleunigt den Rückgang der Schwellung",
          "Verhärtungen und ein welliges Gefühl in der frühen Phase sind normal und werden mit der Zeit weicher",
          "Der Erhalt des Ergebnisses hängt von einem stabilen Gewicht ab"])]}],
 "faqs":[
  ("Kommt das Fett zurück?","Die entfernten Fettzellen kehren nicht zurück. Bei Gewichtszunahme vergrößern sich jedoch die verbliebenen Fettzellen und die Fettverteilung kann sich ändern, was das Ergebnis beeinträchtigt."),
  ("Beseitigt die Liposuktion Cellulite?","Nein. Cellulite entsteht durch die Bindegewebsstränge, die die Haut nach unten ziehen, und wird durch Fettentfernung nicht behoben. In manchen Fällen kann sie danach sogar deutlicher erscheinen."),
  ("Wie viel Gewicht verliere ich?","Die Liposuktion ist keine Methode zur Gewichtsabnahme. Die Veränderung auf der Waage beträgt meist wenige Kilogramm; der eigentliche Unterschied zeigt sich in Maßen und Kleidergröße."),
  ("Wird meine Haut uneben?","Verhärtungen und ein welliges Gefühl in der frühen Phase sind normal und werden über Monate weicher. Das Risiko bleibender Unregelmäßigkeiten hängt von Kanülenstärke und Technik ab; bei Bedarf lässt es sich mit Eigenfett korrigieren."),
  ("Ist eine Vollnarkose zwingend?","Bei begrenzten Arealen kann eine Sedierung mit örtlicher Betäubung ausreichen. Bei größeren Arealen wird aus Sicherheitsgründen die Vollnarkose bevorzugt."),
  ("Wie lange muss ich das Mieder tragen?","In der Regel 4–6 Wochen, die ersten 2–3 Wochen ganztägig. Die Kompression trägt unmittelbar dazu bei, dass die Schwellung zurückgeht und sich die Haut an die neue Kontur anlegt.")],
 "ctah":"Beurteilung zur Liposuktion",
 "ctap":"Teilen Sie uns mit, welche Bereiche Sie stören, Ihre Größe und Ihr Gewicht sowie die Dauer Ihres stabilen Gewichts; senden Sie nach Möglichkeit Fotos."},
}
