# -*- coding: utf-8 -*-
"""Almanca ceviriler — parti 7: lipodem kumesi (6 uydu sayfa)."""

T = {
"lipodem-nedir": {
 "crumb":"Was ist Lipödem",
 "title":"Was ist Lipödem? Ursachen, Symptome und Behandlung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Was ist Lipödem? Ursachen und Behandlung",
 "desc":"Was ist ein Lipödem, wie entsteht es, worin unterscheidet es sich von Adipositas und Cellulite? Symptome, Stadien, Diagnostik und lymphgefäßschonende operative Behandlung.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Was ist ein Lipödem?",
 "lead":"Wenn Ihre Beine im Verhältnis zum übrigen Körper unproportioniert wirken, bei Berührung schmerzen und beim Abnehmen Ihr Oberkörper schlanker wird, während die Beine gleich bleiben — dann ist das keine Frage der Willenskraft. Das Lipödem ist eine Erkrankung, die erkannt werden muss, und sie betrifft etwa 10% der Frauen.",
 "watopic":"Lipödem",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Was ist Lipödem","cardsub":"Definition, Ursachen und Behandlungsansatz",
 "procedure":{"name":"Lipödemchirurgie — lymphgefäßschonende Liposuktion",
   "how":"Krankhaftes Fettgewebe wird mit WAL- (wasserstrahlassistierter) oder PAL- (kraftunterstützter) Technik entfernt, während die lymphatischen Strukturen erhalten bleiben.",
   "prep":"Untersuchung, Stadieneinteilung, bei Bedarf lymphatische Bildgebung und Anpassung der Kompressionsversorgung.",
   "follow":"Kompressionsversorgung, frühe Mobilisation und bei Bedarf manuelle Lymphdrainage.",
   "body":"Beine, Hüften, Arme"},
 "keyfacts":[("Häufigkeit","Etwa 10% der Frauen"),
             ("Unterscheidendes Merkmal","Die Füße bleiben frei — Manschettenzeichen"),
             ("Hauptbeschwerde","Schmerz, Berührungsempfindlichkeit, leichte Blutergüsse"),
             ("Bezug zum Gewicht","Verschwindet nicht durch Diät")],
 "authority":"Die Lipödemchirurgie erfordert die Beherrschung von Liposuktionstechniken, die das Lymphsystem schonen. Doz. Dr. Acartürk gehört zu den ersten türkischen plastischen Chirurgen, die an der University of Pittsburgh mit Fettgewebs- und Stammzelltechnologien gearbeitet haben; als Chirurg, der auch Lymphödem-Mikrochirurgie durchführt, arbeitet er täglich mit der lymphatischen Anatomie.",
 "creds":["Forschung zu Fettgewebe und Stammzellen an der University of Pittsburgh",
          "Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie",
          "Vortrag auf dem Weltkongress für Lymphologie"],
 "sections":[
  {"id":"tanim","tag":"Definition","h2":"Was ist ein Lipödem?","body":[
   "Das Lipödem ist eine chronische Erkrankung, bei der das Fettgewebe krankhaft und <strong>symmetrisch</strong> zunimmt, begleitet von Schmerz und Berührungsempfindlichkeit. Es tritt fast ausschließlich bei Frauen auf.",
   "Die Ansammlung konzentriert sich auf Hüften, Oberschenkel und Waden; in etwa einem Viertel der Fälle sind auch die Arme betroffen. Der Oberkörper bleibt meist verschont. <strong>Die Füße sind nicht betroffen</strong> — daraus ergibt sich der scharfe Übergang am Knöchel, das <strong>Manschettenzeichen</strong>, der typischste Befund beim Lipödem.",
   ("h3","Drei Merkmale, die das Lipödem definieren"),
   ("ul",["<strong>Symmetrie:</strong> beide Seiten sind ähnlich betroffen",
          "<strong>Schmerz:</strong> Berührungsempfindlichkeit und leichte Blutergüsse — das wichtigste Unterscheidungsmerkmal gegenüber einfacher Fettansammlung",
          "<strong>Diätresistenz:</strong> beim Abnehmen wird der Oberkörper schlanker, die regionale Ansammlung bleibt"]),
   ("note","Das Lipödem ist kein Gewichtsproblem. Kalorienrestriktion und Bewegung verringern die allgemeine Fettmasse, wirken auf das krankhafte Fettgewebe jedoch nicht. Betroffene werden deshalb häufig beschuldigt, sich \"nicht genug angestrengt\" zu haben — dabei liegt das Problem nicht im Willen, sondern im Gewebe selbst.")]},
  {"id":"neden","tag":"Ursachen","h2":"Warum entsteht ein Lipödem?","body":[
   "Die Ursache des Lipödems ist nicht vollständig geklärt, doch zwei Faktoren stechen hervor: <strong>hormonelle Übergänge</strong> und <strong>genetische Veranlagung</strong>.",
   ("ul",["<strong>Hormonelle Phasen:</strong> die Erkrankung beginnt am häufigsten in Pubertät, Schwangerschaft oder Menopause. Das weist auf die Rolle des Östrogens bei der Fettverteilung hin.",
          "<strong>Familienanamnese:</strong> bei einem erheblichen Teil der Betroffenen findet sich eine ähnliche Körperform bei Mutter, Tante oder Schwester",
          "<strong>Auftreten bei Frauen:</strong> bei Männern äußerst selten und meist von einer hormonellen Störung begleitet",
          "<strong>Mikrozirkulation und Entzündung:</strong> im betroffenen Gewebe wurden eine erhöhte Durchlässigkeit kleiner Gefäße und eine niedriggradige Entzündung nachgewiesen — das erklärt Schmerz und leichte Blutergüsse"]),
   ("note","Das Lipödem ist keine Folge von Adipositas. Beide können jedoch gemeinsam vorliegen, und Adipositas verschlimmert das Lipödem. Gewichtskontrolle beseitigt die Erkrankung nicht, verringert aber Beschwerden und lymphatische Last.")]},
  {"id":"fark","tag":"Differentialdiagnose","h2":"Unterschied zu Adipositas, Cellulite und Lymphödem","body":[
   "Das Lipödem wird am häufigsten mit diesen drei Zuständen verwechselt. Die Abgrenzung ist wichtig, weil sie die Behandlung völlig verändert.",
   ("table",["Merkmal","Lipödem","Adipositas","Lymphödem"],[
     ["Verteilung","Regional — Hüften, Oberschenkel, Waden","Über den ganzen Körper","Meist ein einzelnes Glied"],
     ["Symmetrie","Symmetrisch","Symmetrisch","Häufig asymmetrisch"],
     ["Fußbeteiligung","Fehlt — Manschettenzeichen","Wechselnd","Vorhanden — Fußrücken und Zehen"],
     ["Schmerz","Deutlich, bei Berührung","Fehlt","Schweregefühl überwiegt"],
     ["Blutergüsse","Entstehen leicht","Normal","Normal"],
     ["Beim Abnehmen","Regionale Ansammlung bleibt","Nimmt proportional ab","Unverändert"],
     ["Stemmer-Zeichen","Negativ","Negativ","Positiv"]]),
   ("h3","Unterschied zur Cellulite"),
   "Cellulite ist eine Veränderung des Erscheinungsbilds des Unterhautfetts und <strong>schmerzlos</strong>. Beim Lipödem beherrschen Schmerz und Empfindlichkeit das Bild. Cellulite ist ein kosmetischer Zustand, das Lipödem eine fortschreitende Erkrankung.",
   ("note","Lipödem und Lymphödem können auch gemeinsam vorliegen. Bei unbehandeltem Lipödem übersteigt das wachsende Gewebevolumen irgendwann die Transportkapazität des Lymphsystems, und ein Lymphödem kommt hinzu; das nennt man <strong>Lipo-Lymphödem</strong>. Einzelheiten auf unserer <a href=\"../lenfodem-lipodem-cerrahisi.html\">Lymphödem-Seite</a>.")]},
  {"id":"tani","tag":"Diagnostik","h2":"Wie wird ein Lipödem festgestellt?","body":[
   "Für das Lipödem gibt es keinen Bluttest und kein eindeutiges bildgebendes Verfahren. Die Diagnose ist <strong>klinisch</strong> — sie wird aus Anamnese und Untersuchung gestellt.",
   ("h3","Was bei der Diagnose beurteilt wird"),
   ("ul",["Wann und in welcher Lebensphase die Beschwerden begannen",
          "Vorgeschichte von Berührungsschmerz und leichten Blutergüssen",
          "Symmetrie und Verschonung der Füße",
          "Die Reaktion auf Abnehmversuche",
          "Familienanamnese",
          "Haut- und Gewebekonsistenz, Knotigkeit",
          "Stemmer-Zeichen — beim Lipödem negativ"]),
   "Bildgebung wird bei Verdacht auf lymphatische Beteiligung oder zur Differentialdiagnose eingesetzt; für die Diagnose des Lipödems ist sie nicht erforderlich.",
   ("note","Eine jahrelange Diagnoseverzögerung ist beim Lipödem sehr häufig. Die meisten Betroffenen erhalten beim ersten Arztbesuch die Diagnose Adipositas und werden mit einem Diätrat weggeschickt. Die richtige Diagnose ist für sich genommen wertvoll, weil sie das Fortschreiten der Erkrankung verhindern hilft.")]},
  {"id":"tedavi","tag":"Behandlung","h2":"Behandlung des Lipödems","body":[
   ("h3","Konservative Behandlung"),
   "Kompressionsversorgung, manuelle Lymphdrainage, regelmäßige Bewegung und Gewichtskontrolle bilden die Grundlage der Behandlung. Diese Ansätze lindern die Beschwerden und verlangsamen das Fortschreiten, entfernen das krankhafte Fettgewebe jedoch nicht. Einzelheiten auf unserer <a href=\"../ameliyatsiz-lipodem-tedavisi.html\">Seite zur nicht-operativen Behandlung</a>.",
   ("h3","Operative Behandlung — lymphgefäßschonende Liposuktion"),
   "Die Lipödemchirurgie ist eine medizinische Behandlung, kein kosmetischer Eingriff. Das Ziel ist nicht Volumenreduktion, sondern die Entfernung des krankhaften Fettgewebes <strong>unter Erhalt der lymphatischen Strukturen</strong>, die Linderung des Schmerzes und die Wiederherstellung der Beweglichkeit.",
   ("ul",["<strong>WAL (wasserstrahlassistiert):</strong> ein feiner Wasserstrahl löst die Fettzellen schonend aus dem umgebenden Gewebe; Lymphgefäße und Nerven bleiben weitgehend erhalten",
          "<strong>PAL (kraftunterstützt):</strong> eine vibrierende Kanüle löst fibrotisches und dichtes Gewebe mit geringerem Trauma; im fortgeschrittenen Stadium bevorzugt"]),
   ("note","Die Operation beseitigt die Erkrankung nicht; sie verringert das krankhafte Fettgewebe. Entferntes Gewebe kehrt nicht zurück, doch der Zustand besteht im verbleibenden Gewebe fort. Kompressionsversorgung, Bewegung und ein stabiles Gewicht bleiben deshalb auch nach der Operation Teil der Behandlung.")]}],
 "faqs":[
  ("Was ist ein Lipödem, kurz gesagt?","Eine chronische Erkrankung, bei der das Fettgewebe symmetrisch und krankhaft zunimmt, begleitet von Berührungsschmerz. Sie tritt fast ausschließlich bei Frauen auf, konzentriert sich auf Hüften und Beine, und die Füße bleiben frei."),
  ("Ist das Lipödem ein Gewichtsproblem?","Nein. Das krankhafte Fettgewebe widersteht Kalorienrestriktion und Bewegung. Beim Abnehmen wird der Oberkörper schlanker, während die regionale Ansammlung bleibt — das Missverhältnis kann dadurch sogar deutlicher werden."),
  ("Tritt das Lipödem nur bei Frauen auf?","Nahezu ausschließlich. Bei Männern ist es äußerst selten und dann meist von einer hormonellen Störung begleitet."),
  ("Ist ein Lipödem gefährlich?","Es ist nicht unmittelbar lebensbedrohlich, aber fortschreitend. Mit der Zeit wird die Beweglichkeit eingeschränkt, Knie- und Hüftgelenke werden belastet, und wegen der Last auf dem Lymphsystem kann ein Lymphödem hinzukommen."),
  ("Geht ein Lipödem weg?","Die Erkrankung verschwindet nicht vollständig. Die konservative Behandlung kann die Beschwerden lindern, die Operation das krankhafte Fettgewebe verringern und Schmerz sowie Bewegungseinschränkung deutlich bessern."),
  ("Sind Lipödem und Lymphödem dasselbe?","Nein. Das Lipödem ist eine Erkrankung des Fettgewebes, symmetrisch und schmerzhaft. Das Lymphödem ist eine Ansammlung von Lymphflüssigkeit, meist einseitig und mit Fußbeteiligung. Beide können auch gemeinsam vorliegen (Lipo-Lymphödem).")],
 "related":["lipodem","lipodem-belirtileri","lipodem-evreleri","ameliyatsiz-lipodem-tedavisi"],
 "ctah":"Der erste Schritt zur Lipödem-Beurteilung",
 "ctap":"Teilen Sie uns mit, wann Ihre Beschwerden begannen, wie stark der Schmerz ist und welche Behandlungen Sie versucht haben; senden Sie nach Möglichkeit Fotos Ihrer Beine von vorn und von der Seite."},

"lipodem-belirtileri": {
 "crumb":"Lipödem-Symptome",
 "title":"Lipödem-Symptome: Woran erkennt man es? | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lipödem-Symptome und wie man sie erkennt",
 "desc":"Welche Symptome hat ein Lipödem und woran erkennt man es? Manschettenzeichen, Schmerz und Blutergüsse, frühe Befunde und Methoden zur Selbstkontrolle.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Lipödem-Symptome: woran erkennt man es?",
 "lead":"Das Lipödem wird im Durchschnitt Jahre zu spät diagnostiziert. Der Grund für diese Verzögerung ist nicht die Seltenheit der Erkrankung — es ist, dass ihre Symptome für ein Gewichtsproblem gehalten werden. Diese Seite stellt die Befunde dar, die das Lipödem von anderen Zuständen unterscheiden.",
 "watopic":"Lipödem-Symptome",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Lipödem-Symptome","cardsub":"Unterscheidende Befunde und Selbstkontrolle",
 "procedure":{"name":"Diagnostische Beurteilung des Lipödems",
   "how":"Schmerz, Symmetrie, Verschonung der Füße, Reaktion auf Gewichtsabnahme und Gewebekonsistenz werden gemeinsam beurteilt und führen zur klinischen Diagnose.",
   "prep":"Die Lebensphase des Beschwerdebeginns und die Familienanamnese.",
   "follow":"Behandlungsplan nach Stadium.",
   "body":"Beine, Hüften, Arme"},
 "keyfacts":[("Manschettenzeichen","Schwellung endet am Knöchel, Füße bleiben frei"),
             ("Schmerz","Berührungsempfindlichkeit ist typisch"),
             ("Blutergüsse","Entstehen schon bei leichten Stößen"),
             ("Symmetrie","Beide Seiten ähnlich betroffen")],
 "authority":"Das Lipödem richtig zu erkennen beendet unnötige Diätzyklen und ermöglicht zugleich die richtige Behandlung. Als Chirurg, der sowohl Lipödemchirurgie als auch Lymphödem-Mikrochirurgie durchführt, beurteilt Doz. Dr. Acartürk beide Bilder gemeinsam.",
 "creds":["Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie",
          "Forschung zu Fettgewebe und Stammzellen an der University of Pittsburgh",
          "Integrierter Ansatz für Lipödem und Lymphödem"],
 "sections":[
  {"id":"temel","tag":"Kernsymptome","h2":"Die Kernsymptome des Lipödems","body":[
   ("ul",["<strong>Unproportionierte Körperform:</strong> schlanker Oberkörper bei deutlich vollen Hüften und Beinen",
          "<strong>Manschettenzeichen:</strong> die Schwellung endet scharf am Knöchel, die Füße bleiben normal",
          "<strong>Berührungsschmerz:</strong> Empfindlichkeit schon bei leichtem Druck — der unterscheidendste Befund",
          "<strong>Leichte Blutergüsse:</strong> Blutergüsse nach Stößen, an die man sich nicht erinnert",
          "<strong>Symmetrie:</strong> beide Beine sind ähnlich betroffen",
          "<strong>Diätresistenz:</strong> beim Abnehmen wird der Oberkörper schlanker, die Beine bleiben gleich",
          "<strong>Knotiges Gewebe:</strong> kleine körnige Strukturen unter der Haut tastbar",
          "<strong>Schwere- und Spannungsgefühl:</strong> besonders am Tagesende zunehmend"]),
   ("note","Es müssen nicht alle diese Befunde zusammen vorliegen. Liegt jedoch die Trias aus <strong>Schmerz, Symmetrie und Verschonung der Füße</strong> vor, sollte ein Lipödem ernsthaft erwogen werden.")]},
  {"id":"baslangic","tag":"Beginn","h2":"Beginn des Lipödems: erste Befunde","body":[
   "Das Lipödem beginnt meist in einer hormonellen Übergangsphase: Pubertät, Schwangerschaft oder Menopause. Der Beginn ist schleichend und wird im Allgemeinen einer Gewichtszunahme zugeschrieben.",
   ("ul",["Die Hose sitzt im Verhältnis zum Oberkörper eng",
          "Die Oberschenkelinnenseiten berühren und reiben sich",
          "Schweregefühl in den Beinen am Tagesende",
          "Unerwartete Empfindlichkeit nach Massage oder Druck",
          "Blutergüsse ohne erinnerbare Ursache"]),
   ("note","Eine in der Pubertät beginnende Beinform, die mit \"Übergewicht\" erklärt wird, verdient eine sorgfältige Beurteilung — besonders bei entsprechender Familienanamnese. Die Frühdiagnose ist der einzige wirksame Weg, das Fortschreiten in ein fortgeschrittenes Stadium zu verlangsamen.")]},
  {"id":"kontrol","tag":"Selbstkontrolle","h2":"Selbstkontrolle: vier einfache Fragen","body":[
   ("steps",[
    ("1 — SCHAUEN SIE AUF IHRE FÜSSE","Endet die Schwellung an Ihrem Knöchel, während die Füße normal bleiben? Gibt es am Knöchel eine deutliche Übergangslinie? Das ist das Manschettenzeichen und spricht für ein Lipödem."),
    ("2 — DRÜCKEN SIE","Verspüren Sie Schmerz, wenn Sie mit mittlerer Kraft auf Oberschenkel oder Wade drücken? Diese Empfindlichkeit ist typisch für das Lipödem; bei einfacher Fettansammlung fehlt sie."),
    ("3 — PRÜFEN SIE DIE SYMMETRIE","Sind beide Beine ähnlich betroffen? Das Lipödem ist symmetrisch; ausgeprägte Einseitigkeit spricht für ein Lymphödem."),
    ("4 — DENKEN SIE AN IHRE GEWICHTSGESCHICHTE","Werden beim Abnehmen Gesicht, Arme und Taille schlanker, während die Beine gleich bleiben? Diese Resistenz ist das unterscheidende Merkmal des Lipödems.")]),
   ("note","Diese Fragen ersetzen keine ärztliche Untersuchung. Sie sollen Ihnen helfen zu erkennen, dass ein jahrelang als \"Gewichtsproblem\" erklärtes Bild in Wirklichkeit ein abklärungsbedürftiger Zustand sein kann.")]},
  {"id":"karisan","tag":"Verwechselte Zustände","h2":"Mit dem Lipödem verwechselte Zustände","body":[
   ("table",["Zustand","Unterscheidendes Merkmal"],[
     ["Adipositas","Fett über den ganzen Körper verteilt; kein Schmerz; nimmt beim Abnehmen proportional ab"],
     ["Cellulite","Nur eine Veränderung des Hautbilds; schmerzlos"],
     ["Lymphödem","Meist einseitig; Fußrücken und Zehen betroffen; Stemmer positiv"],
     ["Venöse Insuffizienz","Geht bei Hochlagerung rasch zurück; Krampfadern begleiten"],
     ["Kardiales/renales Ödem","Dellen bei Druck; systemische Grunderkrankung"]]),
   "Eine Vergleichstabelle mit dem Lymphödem finden Sie auf unserer <a href=\"../lenfodem-belirtileri.html\">Seite zu Lymphödem-Symptomen</a>."]},
  {"id":"nezaman","tag":"Wann zum Arzt","h2":"Wann sollten Sie ärztlichen Rat einholen?","body":[
   ("ul",["Wenn Ihre Beine bei Berührung schmerzen",
          "Wenn sich die regionale Ansammlung trotz Abnehmversuchen nicht ändert",
          "Wenn Sie leicht blaue Flecken bekommen",
          "Wenn Ihre Beine im Verhältnis zum Oberkörper unproportioniert sind",
          "Wenn das Reiben der Oberschenkel beim Gehen Ihren Alltag beeinträchtigt",
          "Wenn es in Ihrer Familie eine ähnliche Körperform gibt"]),
   ("note","Für die Diagnose des Lipödems gibt es keinen Bluttest und keine eindeutige Bildgebung; die Diagnose ist klinisch. Ihre Beschwerden ausführlich schildern zu können — besonders das Vorhandensein von Schmerz — ist deshalb der wichtigste Teil der Diagnosefindung.")]}],
 "faqs":[
  ("Woran erkennt man ein Lipödem?","Vier Befunde werden gemeinsam beurteilt: Berührungsschmerz, Symmetrie, Verschonung der Füße (Manschettenzeichen) und Resistenz gegenüber Gewichtsabnahme. Liegen diese vier zusammen vor, wird ein Lipödem ernsthaft erwogen."),
  ("Was ist das Manschettenzeichen?","Die Schwellung endet scharf am Knöchel, während die Füße normal bleiben. Es ist der typischste Befund beim Lipödem und das praktischste Unterscheidungsmerkmal gegenüber dem Lymphödem — bei dem die Schwellung bis Fußrücken und Zehen reicht."),
  ("Warum bekomme ich beim Lipödem so leicht blaue Flecken?","Im betroffenen Gewebe ist die Durchlässigkeit kleiner Gefäße erhöht und die Kapillaren sind fragiler. Blutergüsse können deshalb schon nach Stößen entstehen, an die man sich nicht erinnert."),
  ("Meine Beine schmerzen — ist das ein Lipödem?","Berührungsschmerz ist der unterscheidendste Befund beim Lipödem, sichert die Diagnose aber nicht allein. Symmetrie, Verschonung der Füße und die Reaktion auf Gewichtsabnahme müssen gemeinsam beurteilt werden."),
  ("Welcher Test dient der Lipödem-Diagnose?","Es gibt keinen Bluttest und kein bildgebendes Verfahren, das die Diagnose sichert; sie wird durch klinische Untersuchung und Anamnese gestellt. Bildgebung dient bei Verdacht auf lymphatische Beteiligung oder der Differentialdiagnose."),
  ("Gibt es Symptome im Frühstadium?","Ja, aber sie sind subtil: Schweregefühl am Tagesende, unerwartete Empfindlichkeit, Blutergüsse ohne erinnerbare Ursache und eine im Verhältnis zum Oberkörper eng sitzende Hose. Diese Phase wird meist der Gewichtszunahme zugeschrieben und übersehen.")],
 "related":["lipodem-nedir","lipodem","lipodem-evreleri","lenfodem-belirtileri"],
 "ctah":"Lassen Sie uns Ihre Symptome beurteilen",
 "ctap":"Teilen Sie uns mit, wann Ihre Beschwerden begannen, wie stark der Schmerz ist und welche Erfahrungen Sie mit Gewichtsabnahme gemacht haben; senden Sie nach Möglichkeit Fotos Ihrer Beine von vorn und von der Seite."},

"lipodem-hangi-doktor": {
 "crumb":"Welcher Arzt behandelt ein Lipödem",
 "title":"Welcher Arzt behandelt ein Lipödem? | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Welcher Arzt behandelt ein Lipödem?",
 "desc":"An welche Abteilung sollten Sie sich beim Lipödem wenden? Die Rollen von plastischer Chirurgie, physikalischer Medizin und weiteren Fächern, worauf bei der Wahl des Chirurgen zu achten ist, und die Terminvorbereitung.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Welcher Arzt behandelt ein Lipödem?",
 "lead":"Die meisten Lipödem-Betroffenen erreichen die richtige Abteilung Jahre zu spät. Unterwegs liegen Ernährungsberatungen, Endokrinologie und ästhetische Zentren; der gemeinsame Nenner ist, dass das Bild für ein Gewichtsproblem gehalten wird. Diese Seite weist den Weg.",
 "watopic":"die richtige Fachrichtung beim Lipödem",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Welcher Arzt?","cardsub":"Die richtige Zuordnung beim Lipödem",
 "procedure":{"name":"Chirurgische Beurteilung beim Lipödem",
   "how":"Die plastische und rekonstruktive Chirurgie entfernt krankhaftes Fettgewebe mit Liposuktionstechniken, die die lymphatischen Strukturen erhalten.",
   "prep":"Stadieneinteilung, Differentialdiagnose und bei Bedarf lymphatische Bildgebung.",
   "follow":"Langfristige, gemeinsam mit der Physiotherapie geführte Nachsorge.",
   "body":"Beine, Hüften, Arme"},
 "keyfacts":[("Operative Behandlung","Plastische und Rekonstruktive Chirurgie"),
             ("Konservative Behandlung","Physikalische Medizin und Rehabilitation"),
             ("Wichtig","Nicht jede Liposuktion ist Lipödemchirurgie"),
             ("Ideal","Beide Fächer arbeiten zusammen")],
 "authority":"Lipödemchirurgie und ästhetische Liposuktion sind verschiedene Dinge. Beim Lipödem hat der Erhalt des Lymphsystems Vorrang, was einen Chirurgen erfordert, der mit lymphatischer Anatomie arbeitet. Doz. Dr. Acartürk führt sowohl Lipödemchirurgie als auch Lymphödem-Mikrochirurgie durch und hat an der University of Pittsburgh zu Fettgewebstechnologien geforscht.",
 "creds":["Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie",
          "Forschung zu Fettgewebe und Stammzellen an der University of Pittsburgh",
          "Erfahrung in lymphgefäßschonender Liposuktion"],
 "sections":[
  {"id":"kisa","tag":"Kurze Antwort","h2":"Die kurze Antwort","body":[
   "Beim Lipödem sind zwei Fächer beteiligt:",
   ("ul",["<strong>Plastische und Rekonstruktive Chirurgie</strong> — führt die operative Behandlung durch. Die lymphgefäßschonende Liposuktion (WAL, PAL) gehört zu diesem Fach.",
          "<strong>Physikalische Medizin und Rehabilitation</strong> — führt die konservative Behandlung durch. Planung der Kompressionsversorgung, manuelle Lymphdrainage und Bewegungsprogramme werden hier festgelegt."]),
   ("note","Diese beiden Fächer sind keine Alternativen zueinander. Die konservative Behandlung wird auch nach der Operation fortgeführt; die Chirurgie kommt dort zum Zug, wo die konservative Behandlung nicht ausreicht.")]},
  {"id":"hangi-durumda","tag":"Zuordnung","h2":"Wann zu wem?","body":[
   ("table",["Ihre Situation","Anlaufstelle"],[
     ["Keine Diagnose, schmerzhafte Schwellung der Beine","Plastische Chirurgie oder physikalische Medizin — ein Arzt, der mit Lipödem arbeitet"],
     ["Diagnose gestellt, Schmerz beeinträchtigt den Alltag","Plastische und Rekonstruktive Chirurgie — Prüfung der Operationsfähigkeit"],
     ["Konservative Behandlung reicht nicht aus","Plastische und Rekonstruktive Chirurgie"],
     ["Kompressions- und Physiotherapieplan erforderlich","Physikalische Medizin und Rehabilitation"],
     ["Verdacht auf lymphatische Beteiligung (auch Fußschwellung)","Ein plastischer Chirurg, der Lymphödemchirurgie durchführt"],
     ["Verdacht auf hormonelle Störung","Endokrinologie — für Begleiterkrankungen"]]),
   ("note","Endokrinologie und Ernährungsfachkräfte spielen beim Lipödem eine unterstützende Rolle, behandeln die Erkrankung selbst jedoch nicht. Ein Bild, das nicht auf Diät anspricht, allein zur Ernährungsberatung zu schicken, ist der häufigste Grund für Diagnoseverzögerungen.")]},
  {"id":"cerrah-secimi","tag":"Wahl des Chirurgen","h2":"Worauf bei der Wahl des Chirurgen achten?","body":[
   "Das ist beim Lipödem der kritischste Punkt: <strong>Nicht jede Liposuktion ist Lipödemchirurgie.</strong> Die ästhetische Liposuktion zielt auf Volumenreduktion; bei der Lipödemchirurgie hat der Erhalt des Lymphsystems Vorrang. Ein mit falscher Technik durchgeführter Eingriff kann die lymphatische Struktur schädigen und das Bild verschlimmern.",
   ("h3","Angemessene Fragen"),
   ("ul",["Welche Technik verwenden Sie bei der Lipödemchirurgie? (WAL, PAL)",
          "Welchen Ansatz verfolgen Sie zum Erhalt der lymphatischen Strukturen?",
          "Wie viele Sitzungen werden nötig sein, und warum?",
          "Wie sieht der Plan für Kompressionsversorgung und Physiotherapie nach der Operation aus?",
          "Führen Sie auch Lymphödemchirurgie durch?",
          "Was ist die realistische Erwartung — verschwindet die Erkrankung oder lassen die Beschwerden nach?"]),
   ("note","Die Formulierung \"das Lipödem verschwindet vollständig\" ist ein Warnzeichen. Die Operation verringert das krankhafte Fettgewebe; sie beseitigt die Erkrankung nicht. Eine ehrliche Beurteilung spricht in messbaren Zielen: weniger Schmerz, mehr Beweglichkeit, geringeres Volumen.")]},
  {"id":"hazirlik","tag":"Vorbereitung","h2":"Wie bereiten Sie sich auf den Termin vor?","body":[
   ("ul",["<strong>Beschwerdeverlauf:</strong> wann es begann, in welcher Lebensphase (Pubertät, Schwangerschaft, Menopause)",
          "<strong>Schmerzbeschreibung:</strong> wie oft, wie stark, wodurch verstärkt",
          "<strong>Gewichtsgeschichte:</strong> die versuchten Diäten und wie Ihre Beine darauf reagierten",
          "<strong>Familienanamnese:</strong> eine ähnliche Form bei Mutter, Schwester oder Tante",
          "<strong>Frühere Behandlungen:</strong> Kompressionsversorgung, Lymphdrainage, frühere Liposuktion",
          "<strong>Fotos:</strong> von vorn, von der Seite und von hinten; idealerweise mit Veränderung über die Zeit",
          "<strong>Ihre Körpergröße und Ihr Gewicht</strong>"]),
   ("note","Das Vorhandensein und die Stärke des Schmerzes klar schildern zu können, ist sehr wichtig. Das ist der Kernbefund, der das Lipödem von einfacher Fettansammlung unterscheidet, und die Diagnose stützt sich weitgehend darauf.")]}],
 "faqs":[
  ("Welcher Arzt behandelt ein Lipödem?","Für die operative Behandlung die Plastische und Rekonstruktive Chirurgie, für die konservative Behandlung die Physikalische Medizin und Rehabilitation. Beide ergänzen einander."),
  ("Muss ich zur Ernährungsberatung?","Ernährungsunterstützung ist hilfreich — Gewichtskontrolle lindert die Beschwerden. Doch das Lipödem verschwindet nicht durch Diät. Allein zur Ernährungsberatung geschickt zu werden, ist der häufigste Grund für Diagnoseverzögerungen."),
  ("Führt jeder plastische Chirurg Lipödemoperationen durch?","Nein. Die Lipödemchirurgie erfordert die Beherrschung lymphgefäßschonender Techniken (WAL, PAL). Sie ist nicht derselbe Eingriff wie eine ästhetische Liposuktion; es ist angemessen, nach der Erfahrung des Chirurgen auf diesem Gebiet zu fragen."),
  ("Sollte ich zum Endokrinologen?","Bei Verdacht auf eine hormonelle Störung ja. Das Lipödem selbst ist jedoch keine hormonelle Erkrankung; die Endokrinologie beurteilt Begleiterkrankungen."),
  ("Wird das in staatlichen Krankenhäusern durchgeführt?","Lipödemchirurgie wird an einigen Universitäts- und Lehrkrankenhäusern durchgeführt. Die Zahl der Zentren ist begrenzt; eine Bestätigung vor der Vorstellung spart Zeit."),
  ("In welchem Stadium sollte ich mich vorstellen?","Wenn Schmerz Ihren Alltag beeinträchtigt, die Beweglichkeit eingeschränkt wird oder die Erkrankung trotz konservativer Behandlung fortschreitet, ist die Zeit für eine Beurteilung gekommen. Ein fortgeschrittenes Stadium abzuwarten ist nicht erforderlich.")],
 "related":["lipodem-nedir","lipodem","ameliyatsiz-lipodem-tedavisi","lenfodem-hangi-doktor"],
 "ctah":"Der erste Schritt zur richtigen Beurteilung",
 "ctap":"Teilen Sie uns mit, wie lange Ihre Beschwerden bestehen, wie stark der Schmerz ist und welche Behandlungen Sie versucht haben; senden Sie nach Möglichkeit Fotos."},

"ameliyatsiz-lipodem-tedavisi": {
 "crumb":"Nicht-operative Lipödembehandlung",
 "title":"Lipödem ohne Operation behandeln: Was wirkt, was nicht | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Nicht-operative Behandlung des Lipödems",
 "desc":"Ist eine nicht-operative Behandlung des Lipödems möglich? Die tatsächliche Wirkung von Kompression, Lymphdrainage, Bewegung und Ernährung — und wann eine Operation nötig wird.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Nicht-operative Behandlung des Lipödems",
 "lead":"Die ehrliche Antwort lautet: Nicht-operative Verfahren beseitigen das Lipödem nicht, sie verringern aber die Beschwerden deutlich und verlangsamen das Fortschreiten. Diese Seite erklärt, was wirklich wirkt und ab welchem Punkt eine Operation nötig wird.",
 "watopic":"nicht-operative Lipödembehandlung",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Nicht-operative Behandlung","cardsub":"Konservative Verfahren und realistische Erwartungen",
 "procedure":{"name":"Konservative Behandlung beim Lipödem",
   "how":"Kompressionsversorgung, manuelle Lymphdrainage, regelmäßige Bewegung und ein Ernährungsplan werden gemeinsam eingesetzt, um Schmerz und Ödem zu kontrollieren und das Fortschreiten zu verlangsamen.",
   "prep":"Stadieneinteilung und Anpassung von Kompressionsversorgung der richtigen Klasse.",
   "follow":"Regelmäßige Kontrolle und Beurteilung des Ansprechens.",
   "body":"Beine, Hüften, Arme"},
 "keyfacts":[("Realistisches Ziel","Schmerz verringern, Fortschreiten verlangsamen"),
             ("Was es nicht kann","Das krankhafte Fettgewebe entfernen"),
             ("Am wirksamsten","Kompression + regelmäßige Bewegung"),
             ("Zeitpunkt der Operation","Wenn Schmerz und Bewegungseinschränkung anhalten")],
 "authority":"Die Grenzen der konservativen Behandlung ehrlich zu benennen, verhindert sowohl unnötige Operationen als auch unnötiges Warten. Als Chirurg, der sowohl Lipödemchirurgie als auch Lymphödem-Mikrochirurgie durchführt, beurteilt Doz. Dr. Acartürk, welche Patientin von welchem Ansatz profitiert.",
 "creds":["Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie",
          "Forschung zu Fettgewebe und Stammzellen an der University of Pittsburgh",
          "Erfahrung in lymphgefäßschonender Liposuktion"],
 "sections":[
  {"id":"gercek","tag":"Realistischer Rahmen","h2":"Was die nicht-operative Behandlung leistet — und was nicht","body":[
   "Diese Unterscheidung sollte von Anfang an klar sein, denn Erwartungsmanagement ist Teil der Behandlung.",
   ("table",["Was sie leistet","Was sie nicht leistet"],[
     ["Verringert Schmerz und Empfindlichkeit","Entfernt das krankhafte Fettgewebe nicht"],
     ["Bringt das Ödem unter Kontrolle","Verändert die Beinform nicht dauerhaft"],
     ["Verlangsamt das Fortschreiten","Bildet die Erkrankung nicht zurück"],
     ["Entlastet das Lymphsystem","Korrigiert das Missverhältnis nicht"],
     ["Erhält die Beweglichkeit","Führt zu keiner Stadienrückbildung"]]),
   ("note","Das ist kein Bild des Scheiterns. Die konservative Behandlung ist die Grundlage des Lipödem-Managements und wird auch bei operierten Patientinnen lebenslang fortgeführt. Die Operation ersetzt sie nicht — sie kommt dort zum Zug, wo die konservative Behandlung nicht ausreicht.")]},
  {"id":"basi","tag":"Kompression","h2":"Kompressionsversorgung","body":[
   "Das ist der wirksamste Bestandteil der konservativen Behandlung. Durch Erhöhung des Gewebedrucks verringert sie die Ödemansammlung, lindert den Schmerz und kontrolliert die Volumenschwankung im Tagesverlauf.",
   ("ul",["<strong>Flachgestrickte</strong> Versorgung wird beim Lipödem meist bevorzugt — ihre festere Struktur stützt das Gewebe besser",
          "<strong>Die Kompressionsklasse</strong> sollte ärztlich festgelegt werden; eine falsche Klasse ist entweder wirkungslos oder unangenehm",
          "<strong>Maßanfertigung</strong> ist deutlich wirksamer als Konfektionsgrößen",
          "<strong>Regelmäßige Nutzung</strong> ist der gelegentlichen deutlich überlegen",
          "<strong>Ein Wechsel alle 6 Monate</strong> wird empfohlen — die Elastizität lässt mit der Zeit nach"]),
   ("note","Die Kompressionsversorgung ist der Bestandteil, mit dem die meisten Patientinnen am meisten hadern, besonders bei Hitze. Doch die regelmäßige Nutzung ist der wichtigste einzelne Faktor dafür, ob Sie von der konservativen Behandlung profitieren.")]},
  {"id":"drenaj","tag":"Lymphdrainage","h2":"Manuelle Lymphdrainage und Physiotherapie","body":[
   "Die manuelle Lymphdrainage ist eine spezielle Massagetechnik, die den Lymphfluss unterstützt. Beim Lipödem verringert sie die Ödemkomponente und verschafft Erleichterung.",
   ("ul",["Verringert Ödem und Spannungsgefühl",
          "Kann die Schmerzschwelle anheben",
          "Ihre Wirkung nimmt in Kombination mit Kompression zu",
          "Bewirkt allein keine dauerhafte Volumenänderung"]),
   ("note","Die manuelle Lymphdrainage verringert beim Lipödem das Fettgewebe nicht. Ihr Nutzen liegt bei Ödem und Erleichterung. Sie als eigenständige Behandlung darzustellen, ist deshalb nicht korrekt; sinnvoll ist sie zusammen mit Kompression und Bewegung.")]},
  {"id":"egzersiz","tag":"Bewegung","h2":"Bewegung: welche Art, und warum?","body":[
   "Bewegung ist beim Lipödem nicht zum Abnehmen wichtig, sondern um <strong>den Lymphfluss zu unterstützen und die Gelenke zu schützen</strong>. Die Wahl der richtigen Art ist hier entscheidend.",
   ("h3","Empfohlene Bewegungsformen"),
   ("ul",["<strong>Wassergymnastik und Schwimmen:</strong> der hydrostatische Druck des Wassers wirkt wie eine natürliche Kompression — die beim Lipödem am häufigsten empfohlene Bewegungsform",
          "<strong>Gehen:</strong> die Wadenmuskelpumpe unterstützt den Lymphfluss",
          "<strong>Radfahren:</strong> geringe Gelenkbelastung, wirksame Muskelpumpe",
          "<strong>Pilates und Dehnen:</strong> erhält den Bewegungsumfang"]),
   ("h3","Worauf zu achten ist"),
   ("ul",["Stoßbelastende Aktivitäten (Laufen, Springen) können den Schmerz verstärken",
          "Übermäßiges Krafttraining kann Empfindlichkeit auslösen",
          "Kompressionsversorgung während der Bewegung ist hilfreich",
          "Vor der Schmerzgrenze aufzuhören, nicht an ihr, ist wesentlich"]),
   ("note","Das Ziel der Bewegung beim Lipödem ist nicht, die Beine schlanker zu machen — das ist kein realistisches Ziel. Ziel ist es, den Lymphfluss zu unterstützen, die Gelenkgesundheit zu schützen und die Beweglichkeit zu erhalten.")]},
  {"id":"beslenme","tag":"Ernährung","h2":"Die Rolle der Ernährung","body":[
   "Es gibt keine Diät, die das Lipödem beseitigt. Ein Ernährungsplan hat jedoch zwei echte Beiträge: <strong>Gewichtskontrolle senkt die lymphatische Last</strong> und <strong>ein entzündungsarmes Muster kann Beschwerden lindern</strong>.",
   ("ul",["Ein stabiles Gewicht gehört zu den Faktoren, die das Fortschreiten verlangsamen",
          "Weniger verarbeitete Lebensmittel und Salz können das Schwellungsgefühl verringern",
          "Ausreichend Eiweiß und Flüssigkeit sind für die Gewebegesundheit wichtig",
          "Stark restriktive Diäten führen beim Lipödem nicht zum Ziel und sind nicht durchhaltbar"]),
   ("note","Zyklen strenger, restriktiver Diäten sind beim Lipödem häufig und enden meist in Enttäuschung — weil das krankhafte Fettgewebe auf diese Mühe nicht anspricht. Ein durchhaltbares Ernährungsmuster ist sowohl wirksamer als auch gesünder als aggressive Diäten. Mehr dazu auf unserer <a href=\"../lipodem-diyeti.html\">Seite zu Lipödem und Ernährung</a>.")]},
  {"id":"cerrahi","tag":"Wann Operation","h2":"Wann kommt eine Operation in Betracht?","body":[
   "Bestehen trotz regelmäßiger konservativer Behandlung folgende Punkte fort, ist die Zeit für eine chirurgische Beurteilung gekommen:",
   ("ul",["Wenn Schmerz den Alltag weiterhin beeinträchtigt",
          "Wenn das Reiben der Oberschenkel Gang und Haltung stört",
          "Wenn die Bewegungseinschränkung fortschreitet",
          "Wenn die Belastung von Knie- und Hüftgelenken Beschwerden verursacht",
          "Wenn das Stadium trotz Kompression fortschreitet",
          "Wenn die Lebensqualität deutlich gesunken ist"]),
   ("note","Ein fortgeschrittenes Stadium abzuwarten ist für eine Operation nicht erforderlich. Im Gegenteil: Ein Eingriff, bevor das Gewebe fibrotisch wird, ist technisch einfacher und liefert ein besseres Ergebnis. Für eine Patientin, die konservative Behandlung ohne Nutzen versucht hat, gibt es keinen medizinischen Grund zu warten.")]}],
 "faqs":[
  ("Verschwindet das Lipödem ohne Operation?","Nein. Nicht-operative Verfahren verringern Schmerz, kontrollieren das Ödem und verlangsamen das Fortschreiten — sie entfernen das krankhafte Fettgewebe jedoch nicht. Diesen ehrlichen Rahmen von Anfang an zu kennen, ermöglicht die richtige Entscheidung."),
  ("Welches nicht-operative Verfahren ist am wirksamsten?","Regelmäßig getragene Kompressionsversorgung und regelmäßige Bewegung. Gemeinsam angewendet ist ihre Wirkung auf Schmerz und Ödem am deutlichsten. Die manuelle Lymphdrainage bringt zusätzlichen Nutzen."),
  ("Heilt Lymphdrainage das Lipödem?","Nein. Die manuelle Lymphdrainage verringert die Ödemkomponente und verschafft Erleichterung, reduziert aber kein Fettgewebe. Sie als eigenständige Behandlung darzustellen, ist nicht korrekt."),
  ("Werden meine Beine durch Bewegung schlanker?","Beim Lipödem ist das kein realistisches Ziel. Das krankhafte Fettgewebe widersteht Bewegung. Zweck der Bewegung ist es, den Lymphfluss zu unterstützen, die Gelenke zu schützen und die Beweglichkeit zu erhalten."),
  ("Muss ich die Kompressionsversorgung ständig tragen?","Regelmäßige Nutzung ist deutlich wirksamer als gelegentliche. Tägliches Tragen wird empfohlen; bei Hitze kann das fordernd sein, es ist jedoch die wichtigste Voraussetzung dafür, von der Behandlung zu profitieren."),
  ("Wie lange sollte ich ohne Operation fortfahren?","Es gibt keine feste Regel. Halten Schmerz und Bewegungseinschränkung trotz regelmäßiger konservativer Behandlung an, ist die Zeit für eine chirurgische Beurteilung gekommen. Ein fortgeschrittenes Stadium abzuwarten ist nicht erforderlich.")],
 "related":["lipodem-nedir","lipodem","lipodem-diyeti","lipodem-hangi-doktor"],
 "ctah":"Lassen Sie uns besprechen, welcher Ansatz zu Ihnen passt",
 "ctap":"Teilen Sie uns mit, welche Behandlungen Sie derzeit anwenden, wie lange schon und wie Ihr Schmerz Ihren Alltag beeinflusst."},

"lipodem-diyeti": {
 "crumb":"Lipödem und Ernährung",
 "title":"Lipödem-Diät: Die tatsächliche Rolle der Ernährung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lipödem und Ernährung: Was hilft wirklich?",
 "desc":"Welche Rolle spielt die Ernährung beim Lipödem? Verschwindet es durch Diät, welche Ansätze lindern Beschwerden und warum restriktive Diäten nicht wirken.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Lipödem und Ernährung",
 "lead":"Es gibt keine Diät, die das Lipödem beseitigt. Das muss zu Beginn gesagt werden, denn die am häufigsten wiederholte Erfahrung bei dieser Erkrankung ist genau diese: jahrelange Diäten, verlorene Kilos und Beine, die sich nie verändern. Doch die Ernährung hat einen echten, messbaren Beitrag — nur nicht dort, wo man ihn erwartet.",
 "watopic":"Ernährung beim Lipödem",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Lipödem und Ernährung","cardsub":"Der tatsächliche Beitrag der Ernährung und seine Grenzen",
 "procedure":{"name":"Ernährungsansatz beim Lipödem",
   "how":"Ein durchhaltbares Ernährungsmuster sichert ein stabiles Gewicht, senkt die lymphatische Last und mildert die entzündliche Reaktion.",
   "prep":"Beurteilung der bisherigen Essgewohnheiten und der Gewichtsgeschichte.",
   "follow":"Auf Durchhaltbarkeit ausgerichtete Begleitung.",
   "body":"Allgemein"},
 "keyfacts":[("Was Ernährung leistet","Senkt lymphatische Last, lindert Beschwerden"),
             ("Was sie nicht leistet","Schmilzt das krankhafte Fettgewebe nicht"),
             ("Priorität","Durchhaltbarkeit, nicht Restriktion"),
             ("Warnung","Zyklen strenger Diäten bringen keinen Nutzen")],
 "authority":"Die Rolle der Ernährung beim Lipödem zu überschätzen wie zu unterschätzen schadet der Patientin. Als Chirurg, der an der University of Pittsburgh zur Biologie des Fettgewebes geforscht hat, kann Doz. Dr. Acartürk seinen Patientinnen erklären, warum dieses Gewebe der Diät widersteht.",
 "creds":["Forschung zu Fettgewebe und Stammzellen an der University of Pittsburgh",
          "Postdoktorandenzeit zu Tissue Engineering an der Carnegie Mellon University",
          "Integrierter Ansatz für Lipödem und Lymphödem"],
 "sections":[
  {"id":"neden-direnc","tag":"Warum Resistenz","h2":"Warum widersteht Lipödem-Fett der Diät?","body":[
   "Die Antwort auf diese Frage entkräftet den Vorwurf, den Betroffene jahrelang gehört haben.",
   "Fettgewebe im Körper ist nicht einheitlich. Beim Lipödem unterscheidet sich das betroffene Gewebe in Zellstruktur, Gefäßversorgung und entzündlicher Aktivität von normalem Fettgewebe. Kalorienrestriktion verringert den allgemeinen Fettspeicher des Körpers — auf dieses regionale, krankhafte Gewebe wirkt sie jedoch nicht im gleichen Maß.",
   "In der Praxis zeigt sich Folgendes: Die Patientin nimmt ab, <strong>Gesicht, Arme und Taille werden schlanker</strong>, die Beine bleiben weitgehend gleich. Das Missverhältnis kann sogar deutlicher werden.",
   ("note","Das heißt nicht, dass Diät nutzlos ist — es heißt, dass das Ziel falsch gesetzt war. Schlankere Beine können nicht das Ziel der Ernährung sein. Eine geringere lymphatische Last und weniger Beschwerden hingegen schon.")]},
  {"id":"gercek-katki","tag":"Tatsächlicher Beitrag","h2":"Der tatsächliche Beitrag der Ernährung","body":[
   ("ul",["<strong>Geringere lymphatische Last:</strong> ein niedrigerer Body-Mass-Index entlastet die Transportkapazität des Lymphsystems unmittelbar. Das ist besonders bei zu Lipo-Lymphödem fortgeschrittenen Patientinnen wichtig.",
          "<strong>Weniger Schwellungsgefühl:</strong> weniger Salz und verarbeitete Lebensmittel können das Völlegefühl im Tagesverlauf verringern",
          "<strong>Geringere Gelenkbelastung:</strong> die Last auf Knie- und Hüftgelenken sinkt",
          "<strong>Besseres Operationsergebnis:</strong> ein stabiles Gewicht ist entscheidend für den Erhalt des Ergebnisses",
          "<strong>Langsameres Fortschreiten:</strong> Gewichtszunahme gehört zu den Faktoren, die das Lipödem verschlimmern"]),
   ("note","Der Beitrag der Ernährung ist real, aber indirekt. Sie verbessert nicht das krankhafte Gewebe selbst, sondern die Last darauf und die Bedingungen darum herum.")]},
  {"id":"yaklasim","tag":"Ansatz","h2":"Welcher Ernährungsansatz?","body":[
   "Für das Lipödem gibt es kein einzelnes belegtes, standardisiertes Ernährungsprotokoll. In der Literatur werden Ansätze zur Entzündungsminderung diskutiert, doch die Evidenzlage reicht für eine eindeutige Empfehlung noch nicht aus.",
   ("h3","Sinnvolle und durchhaltbare Grundsätze"),
   ("ul",["Ausreichende Eiweißzufuhr — für Gewebegesundheit und Sättigung",
          "Weniger verarbeitete Lebensmittel und raffinierter Zucker",
          "Begrenzung von übermäßigem Salz — es beeinflusst das Schwellungsgefühl",
          "Ausreichende Flüssigkeitszufuhr",
          "Ein gemüse- und ballaststoffbetontes Muster",
          "Beibehaltung regelmäßiger Mahlzeiten"]),
   ("h3","Was zu vermeiden ist"),
   ("ul",["Sehr kalorienarme, langdauernde restriktive Diäten",
          "Diäten, die auf einer einzigen Lebensmittelgruppe beruhen",
          "Nahrungsergänzungsmittel mit dem Versprechen, \"Lipödem zu schmelzen\"",
          "Programme mit schnellen Versprechen, die sich nicht durchhalten lassen"]),
   ("note","Die Ernährungsplanung sollte individuell mit einer Ernährungsfachkraft erfolgen. Diese Seite bietet einen allgemeinen Rahmen; sie ersetzt keinen individuellen Plan.")]},
  {"id":"psikoloji","tag":"Ein wichtiger Hinweis","h2":"Der Diätzyklus und der Umgang mit sich selbst","body":[
   "Den meisten Lipödem-Betroffenen wurde jahrelang vorgeworfen, sich \"nicht genug anzustrengen\", und nach einer Weile verinnerlichen sie diesen Vorwurf selbst. Wiederholte Diätmisserfolge — die keine Misserfolge sind, sondern die Folge eines falsch gesetzten Ziels — vertiefen dieses Gefühl.",
   "Das muss klar gesagt werden: <strong>Dass Ihre Beine nicht auf Diät ansprechen, hat nichts mit Ihrer Willenskraft zu tun.</strong> Es ist das definierende Merkmal der Erkrankung. Für viele Patientinnen ist die größte Erleichterung, die die Diagnose bringt, genau diese Erkenntnis vor der Behandlung.",
   ("note","Wenn Sie mit Ihrem Essverhalten hadern oder Ihr Verhältnis zu Ihrem Körper Sie belastet, sprechen Sie es bei Ihrer Beurteilung ruhig an. Die Lipödem-Behandlung betrifft nicht nur Gewebe; dieser Weg ist Teil einer über viele Jahre reichenden Erfahrung, und Unterstützung zu suchen ist angemessen.")]}],
 "faqs":[
  ("Verschwindet das Lipödem durch Diät?","Nein. Das krankhafte Fettgewebe widersteht der Kalorienrestriktion. Beim Abnehmen wird Ihr Oberkörper schlanker, während die Beine weitgehend gleich bleiben. Das hängt mit dem Wesen der Erkrankung zusammen, nicht mit Willenskraft."),
  ("Nützt Diät dann überhaupt?","Ja, aber indirekt. Ein stabiles Gewicht senkt die lymphatische Last, entlastet die Gelenke, verringert das Schwellungsgefühl und verlangsamt das Fortschreiten. Es ist zudem entscheidend für den Erhalt des Operationsergebnisses."),
  ("Gibt es eine spezielle Diät für das Lipödem?","Es gibt kein einzelnes belegtes, standardisiertes Protokoll. Ansätze zur Entzündungsminderung werden erforscht, doch die Evidenzlage reicht für eine eindeutige Empfehlung noch nicht aus. Ein durchhaltbares, ausgewogenes Muster ist der sinnvollste Ansatz."),
  ("Hilft eine ketogene Ernährung beim Lipödem?","Manche Betroffene berichten von weniger Beschwerden, und das Thema wird erforscht; die für eine eindeutige Empfehlung nötige Evidenz liegt beim Lipödem jedoch noch nicht vor. Wird sie umgesetzt, sollte das unter ärztlicher und ernährungsfachlicher Begleitung geschehen."),
  ("Gibt es Präparate, die Lipödem schmelzen?","Nein. Für Produkte mit dieser Behauptung ist keine Wirkung beim Lipödem belegt. Die dafür aufgewendete Zeit verzögert die richtige Diagnose und Behandlung."),
  ("Ist die Ernährung nach der Operation wichtig?","Ja, sehr. Entferntes Fettgewebe kehrt nicht zurück, doch Zellen im verbleibenden Gewebe können bei Gewichtszunahme größer werden. Ein stabiles Gewicht ist der wichtigste Einzelfaktor für den Erhalt des Operationsergebnisses.")],
 "related":["lipodem-nedir","ameliyatsiz-lipodem-tedavisi","lipodem","lipodem-belirtileri"],
 "ctah":"Lassen Sie uns Ihre Ernährung und Ihren Behandlungsplan besprechen",
 "ctap":"Teilen Sie uns Ihre Gewichtsgeschichte, die versuchten Diäten und die an Ihren Beinen beobachtete Reaktion mit."},

"lipodem-evreleri": {
 "crumb":"Stadien des Lipödems",
 "title":"Stadien des Lipödems: Stadium 1–4 und Behandlung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Stadien und Typen des Lipödems",
 "desc":"Welche Stadien hat das Lipödem? Befunde der Stadien 1, 2, 3 und 4, Befallsmuster, wie die Stadieneinteilung erfolgt und welche Behandlung in welchem Stadium passt.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Stadien des Lipödems",
 "lead":"Beim Lipödem beschreibt das Stadium den Zustand der Hautoberfläche und des Fettgewebes. Die Behandlungsentscheidung stützt sich jedoch nicht allein auf das Stadium — sie stützt sich auch auf die Stärke des Schmerzes und die Bewegungseinschränkung. Schon im Stadium 1 kann die Lebensqualität deutlich beeinträchtigt sein.",
 "watopic":"Stadieneinteilung des Lipödems",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Stadien des Lipödems","cardsub":"Stadien- und Typklassifikation und passende Behandlung",
 "procedure":{"name":"Stadieneinteilung des Lipödems",
   "how":"Das Erscheinungsbild der Hautoberfläche, die Konsistenz des Fettgewebes, die Knotigkeit und eine lymphatische Beteiligung werden gemeinsam beurteilt.",
   "prep":"Untersuchung, Umfangmessungen und bei Bedarf lymphatische Bildgebung.",
   "follow":"Behandlungsplan passend zu Stadium und Beschwerdegrad.",
   "body":"Beine, Hüften, Arme"},
 "keyfacts":[("Stadium 1","Glatte Haut, feine Knötchen darunter"),
             ("Stadium 2","Unebene, wellige Hautoberfläche"),
             ("Stadium 3","Verdickte Haut, große Fettlappen"),
             ("Stadium 4","Lipo-Lymphödem — lymphatische Insuffizienz hinzugekommen")],
 "authority":"Die Stadieneinteilung bestimmt beim Lipödem die Behandlung nicht allein; Schmerz und Funktionsverlust sind mindestens ebenso wichtig. Als Chirurg, der sowohl Lipödemchirurgie als auch Lymphödem-Mikrochirurgie durchführt, kann Doz. Dr. Acartürk auch den Übergang zum Lipo-Lymphödem beurteilen.",
 "creds":["Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie",
          "Forschung zu Fettgewebe und Stammzellen an der University of Pittsburgh",
          "Vortrag auf dem Weltkongress für Lymphologie"],
 "sections":[
  {"id":"evreler","tag":"Stadien","h2":"Die Stadien des Lipödems","body":[
   ("table",["Stadium","Haut und Gewebe","Klinisches Bild"],[
     ["Stadium 1","Glatte Hautoberfläche, feine Knötchen darunter","Schmerz und leichte Blutergüsse haben begonnen; Formveränderung gering"],
     ["Stadium 2","Unebene, wellige Hautoberfläche","Knötchen treten hervor; regionale Schwellung und Empfindlichkeit nehmen zu"],
     ["Stadium 3","Verdickte Haut, große Fettlappen","Bewegung eingeschränkt; Knie- und Hüftgelenke belastet"],
     ["Stadium 4","Lipo-Lymphödem","Zum Lipödem kommt eine lymphatische Insuffizienz; auch die Füße können betroffen sein"]]),
   ("note","Im Stadium 4 tritt eine wichtige Veränderung ein: Die Verschonung der Füße, das unterscheidende Merkmal des Lipödems, geht verloren. Weil eine lymphatische Insuffizienz hinzugekommen ist, kann die Schwellung bis zum Fußrücken reichen und das Stemmer-Zeichen positiv werden. Das ändert den Behandlungsplan.")]},
  {"id":"tipler","tag":"Typen","h2":"Befallsmuster","body":[
   "Unabhängig vom Stadium wird das Lipödem auch danach eingeteilt, <strong>welche Regionen betroffen sind</strong>. Diese Einteilung fließt direkt in die Operationsplanung ein.",
   ("table",["Typ","Betroffene Region"],[
     ["Typ 1","Um Hüfte und Becken"],
     ["Typ 2","Von der Hüfte bis zu den Knien"],
     ["Typ 3","Von der Hüfte bis zu den Knöcheln"],
     ["Typ 4","Arme"],
     ["Typ 5","Nur die Waden"]]),
   "Typ 3 ist das häufigste Bild. Typ 4 (Armbefall) begleitet in etwa einem Viertel der Fälle den Beinbefall und erfordert eine gesonderte Planung.",
   ("note","Stadium und Typ werden gemeinsam beurteilt. So wird die Behandlung bei einer Patientin mit Stadium 2 – Typ 3 anders geplant als bei Stadium 2 – Typ 1; Zahl und Reihenfolge der Eingriffe richten sich danach.")]},
  {"id":"tedavi","tag":"Stadium–Behandlung","h2":"Welche Behandlung in welchem Stadium?","body":[
   ("table",["Stadium","Vorrangiges Vorgehen"],[
     ["Stadium 1","Konservative Behandlung; bei deutlichem Schmerz chirurgische Beurteilung"],
     ["Stadium 2","Konservative Behandlung + chirurgische Beurteilung (WAL/PAL)"],
     ["Stadium 3","Die Chirurgie tritt in den Vordergrund; meist mehrere Sitzungen"],
     ["Stadium 4","Auch die lymphatische Komponente ist zu behandeln — Lipödemchirurgie + Lymphödem-Ansatz"]]),
   ("note","<strong>Ein fortgeschrittenes Stadium abzuwarten ist für eine Operation nicht erforderlich.</strong> Im Gegenteil: Ein Eingriff, bevor das Gewebe fibrotisch wird, ist technisch einfacher und liefert ein besseres Ergebnis. Schon im Stadium 1 kann eine chirurgische Beurteilung angemessen sein, wenn Schmerz die Lebensqualität deutlich beeinträchtigt.")]},
  {"id":"ilerleme","tag":"Verlauf","h2":"Übergänge zwischen den Stadien","body":[
   "Das Lipödem ist eine fortschreitende Erkrankung, doch die Geschwindigkeit ist sehr unterschiedlich. Manche Betroffene bleiben jahrelang im selben Stadium, bei anderen schreitet es besonders in hormonellen Übergangsphasen rasch fort.",
   ("h3","Beschleunigende Faktoren"),
   ("ul",["Gewichtszunahme",
          "Hormonelle Übergänge (Schwangerschaft, Menopause)",
          "Bewegungsmangel",
          "Unregelmäßige Nutzung der Kompressionsversorgung",
          "Ohne Behandlung verstrichene Zeit"]),
   ("h3","Verlangsamende Faktoren"),
   ("ul",["Regelmäßige Nutzung der Kompressionsversorgung",
          "Regelmäßige Bewegung — besonders im Wasser",
          "Ein stabiles Gewicht",
          "Frühzeitiger operativer Eingriff"]),
   ("note","Stadien bilden sich nicht zurück. Die Operation kann das krankhafte Fettgewebe verringern und die Beschwerden deutlich bessern, doch Haut- und Gewebeveränderungen sind bleibend. Ein früher Eingriff beeinflusst deshalb nicht nur den Komfort, sondern auch das Langzeitergebnis.")]}],
 "faqs":[
  ("In wie viele Stadien wird das Lipödem eingeteilt?","In vier Stadien. Im Stadium 1 ist die Hautoberfläche glatt, im Stadium 2 wird sie wellig, im Stadium 3 verdickt sie sich und es bilden sich große Fettlappen, im Stadium 4 kommt eine lymphatische Insuffizienz hinzu (Lipo-Lymphödem)."),
  ("Wie erfahre ich mein Stadium?","Die Stadieneinteilung erfolgt durch klinische Untersuchung: Erscheinungsbild der Hautoberfläche, Knotigkeit, Gewebekonsistenz und Fußbeteiligung werden beurteilt. Eine sichere Stadieneinteilung anhand eines Fotos ist nicht angemessen."),
  ("In welchem Stadium wird operiert?","Das Stadium allein ist nicht entscheidend. Beeinträchtigen Schmerz und Bewegungseinschränkung die Lebensqualität, kann schon im Stadium 1 eine chirurgische Beurteilung angemessen sein. Es gibt keinen medizinischen Grund, ein fortgeschrittenes Stadium abzuwarten."),
  ("Was bedeutet Stadium 4?","Es ist der Punkt, an dem zum Lipödem eine lymphatische Insuffizienz hinzukommt — das Lipo-Lymphödem. In diesem Stadium geht die Verschonung der Füße, das unterscheidende Merkmal des Lipödems, verloren. Der Behandlungsplan muss sowohl das Fettgewebe als auch die lymphatische Komponente berücksichtigen."),
  ("Lässt sich ein Stadium zurückführen?","Nein. Die Operation kann das krankhafte Fettgewebe verringern und die Beschwerden deutlich bessern, doch Haut- und Gewebeveränderungen sind bleibend. Deshalb ist ein früher Eingriff wichtig."),
  ("Was bedeutet der Typ?","Der Typ beschreibt, welche Regionen betroffen sind — Hüften, Oberschenkel, Waden, Arme. Das Stadium zeigt den Zustand des Gewebes, der Typ die Ausbreitung. Gemeinsam bestimmen sie den Operationsplan.")],
 "related":["lipodem-nedir","lipodem-belirtileri","lipodem","lenfodem-evreleri"],
 "ctah":"Lassen Sie uns Ihr Stadium gemeinsam bestimmen",
 "ctap":"Teilen Sie uns mit, wie lange Ihre Beschwerden bestehen, wie stark der Schmerz ist, welche Regionen betroffen sind und ob eine Schwellung der Füße vorliegt; senden Sie nach Möglichkeit Fotos."},
}
