# -*- coding: utf-8 -*-
"""Almanca ceviriler — parti 5: kalan rekonstruktif sayfalar."""

T = {
"bas-boyun": {
 "crumb":"Kopf-Hals- und Kieferrekonstruktion",
 "title":"Kopf-Hals- und Kieferrekonstruktion — Freie Lappen | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Kopf-Hals- und Kieferrekonstruktion",
 "desc":"Wiederherstellung von Kiefer, Zunge, Gaumen und Gesichtsweichteilen nach Tumorchirurgie mit freien Lappen: Fibula, Radialis und ALT — Ablauf, Zeitpunkt und Ergebnisse.",
 "eyebrow":"Rekonstruktive Mikrochirurgie",
 "h1":"Kopf-Hals- und Kieferrekonstruktion",
 "lead":"Nach der Entfernung eines Tumors im Kopf-Hals-Bereich geht es nicht allein darum, ein Loch zu verschließen. Kauen, Schlucken, Sprechen und das eigene Gesicht im Spiegel wiederzuerlangen — das ist der eigentliche Maßstab. Die mikrochirurgische Rekonstruktion mit freien Lappen macht dieses Ziel erreichbar.",
 "watopic":"Kopf-Hals-Rekonstruktion",
 "about":"Kopf-Hals-Rekonstruktion",
 "card":"Kopf-Hals- und Kieferrekonstruktion","cardsub":"Wiederherstellung mit freien Lappen nach Tumorchirurgie",
 "procedure":{"name":"Rekonstruktion mit freiem Lappen",
   "how":"Gewebe wird zusammen mit seinen Blutgefäßen aus einer anderen Körperregion entnommen und im Defektbereich unter dem Mikroskop an die dortigen Gefäße angeschlossen; Knochen, Haut und Muskel werden gemeinsam übertragen.",
   "prep":"Tumorstaging, Gefäßdarstellung, Zahnbeurteilung und gemeinsame Planung im Tumorboard.",
   "follow":"Lappenüberwachung, Schluck- und Sprechrehabilitation, zahnärztliche Versorgung.",
   "body":"Kiefer, Zunge, Gaumen, Gesichtsweichteile"},
 "keyfacts":[("Erfahrung","300+ mikrochirurgische Fälle"),("Lappenerfolgsrate","97% — Weltdurchschnitt 95%"),
             ("Ehemalige Position","Direktor für Kopf-Hals-Rekonstruktion, Univ. of Pittsburgh"),
             ("Zeitpunkt","Bevorzugt in derselben Sitzung wie die Tumorentfernung")],
 "authority":"Doz. Dr. Acartürk war <strong>Direktor der Abteilung für Kopf-Hals-Rekonstruktion an der University of Pittsburgh</strong>. Er führte über 300 mikrochirurgische Eingriffe durch und senkte die Lappenverlustrate auf 3% — gegenüber 5% im weltweiten Mittel. Seine Zusatzqualifikation in Mund-, Kiefer- und Gesichtschirurgie ermöglicht es, Kieferrekonstruktion und Zahnversorgung gemeinsam zu planen.",
 "creds":["Ehem. Direktor für Kopf-Hals-Rekonstruktion, University of Pittsburgh",
          "300+ mikrochirurgische Eingriffe · 97% Lappenerfolgsrate",
          "Zusatzqualifikation Mund-, Kiefer- und Gesichtschirurgie"],
 "sections":[
  {"id":"kapsam","tag":"Umfang","h2":"Wann wird eine Rekonstruktion benötigt?","body":[
   "Tumoroperationen im Kopf-Hals-Bereich hinterlassen häufig ausgedehnte Gewebedefekte. Wird der entstandene Bereich nicht rekonstruiert, sind Kauen, Schlucken und Sprechen dauerhaft beeinträchtigt und das Gesicht verformt sich.",
   ("ul",["<strong>Unterkieferdefekte:</strong> nach Entfernung eines Tumors am Unterkiefer",
          "<strong>Oberkiefer- und Gaumendefekte:</strong> Verbindungen zwischen Mund- und Nasenhöhle",
          "<strong>Zungen- und Mundbodendefekte:</strong> Beeinträchtigung von Sprechen und Schlucken",
          "<strong>Gesichtsweichteildefekte:</strong> Wange, Lippe, Hals",
          "<strong>Strahlenschäden:</strong> Osteoradionekrose und nicht heilende Wunden"]),
   ("note","Die Rekonstruktion in derselben Sitzung wie die Tumorentfernung liefert die besten Ergebnisse. Das Gewebe ist noch nicht vernarbt, die Gefäßverhältnisse sind günstiger und der Patient durchläuft nur eine Operation.")]},
  {"id":"yontem","tag":"Verfahren","h2":"Freie Lappen und ihre Auswahl","body":[
   "Ein freier Lappen ist Gewebe, das mitsamt seinen Blutgefäßen aus einer Körperregion entnommen und in einer anderen unter dem Mikroskop an die dortigen Gefäße angeschlossen wird. Die Auswahl richtet sich danach, welches Gewebe fehlt.",
   ("table",["Lappen","Entnahmestelle","Anwendung"],[
     ["Fibula","Wadenbein","Unterkieferrekonstruktion — Knochen mit Implantatmöglichkeit"],
     ["Radialis","Unterarm","Zunge, Mundboden, dünne Weichteildefekte"],
     ["ALT","Oberschenkelvorderseite","Ausgedehnte Weichteil- und Volumendefekte"],
     ["Skapula","Schulterblatt","Kombinierte Knochen-Weichteil-Defekte"]]),
   ("h3","Warum die Fibula?"),
   "Das Wadenbein liefert einen langen, geraden Knochen, der sich in die Form des Kiefers modellieren lässt und stabil genug ist, um später <strong>Zahnimplantate</strong> zu tragen. Die Entnahme beeinträchtigt das Gehen nicht, da das Wadenbein am Körpergewicht nur geringen Anteil hat."]},
  {"id":"surec","tag":"Ablauf","h2":"Vorbereitung, Operation und Heilung","body":[
   ("steps",[
    ("SCHRITT 1 — GEMEINSAME PLANUNG","Der Umfang der Tumorentfernung wird mit dem HNO- oder MKG-Chirurgen gemeinsam festgelegt und die Rekonstruktion darauf abgestimmt."),
    ("SCHRITT 2 — BILDGEBUNG","Computertomographie, Gefäßdarstellung des Entnahmebeins und Beurteilung des Zahnstatus."),
    ("SCHRITT 3 — OPERATION","Tumorentfernung und Rekonstruktion in derselben Sitzung; je nach Umfang 8–14 Stunden."),
    ("SCHRITT 4 — ERSTE WOCHE","Engmaschige Lappenüberwachung auf der Intensiv- oder Überwachungsstation. Die kritische Phase für die Durchblutung sind die ersten 72 Stunden."),
    ("SCHRITT 5 — REHABILITATION","Schluck- und Sprechtherapie. Die Ernährungssonde wird schrittweise entfernt."),
    ("SCHRITT 6 — ZAHNVERSORGUNG","Nach Einheilung des Knochens, in der Regel nach 4–6 Monaten, können Zahnimplantate geplant werden.")]),
   ("note","Ist eine Bestrahlung vorgesehen, wird sie üblicherweise 4–6 Wochen nach der Operation begonnen. Der Zeitplan wird gemeinsam mit der Strahlentherapie festgelegt; eine abgeschlossene Wundheilung ist Voraussetzung.")]}],
 "faqs":[
  ("Wie lange dauert die Operation?","Je nach Umfang 8–14 Stunden. Tumorentfernung und Rekonstruktion erfolgen in derselben Sitzung, sodass der Patient nur einmal operiert wird."),
  ("Kann ich nach der Kieferrekonstruktion Zähne bekommen?","Ja. Der Fibulaknochen ist stabil genug für Zahnimplantate. Nach Einheilung des Knochens, meist nach 4–6 Monaten, wird die Implantatplanung begonnen."),
  ("Beeinträchtigt die Entnahme des Wadenbeins das Gehen?","Nein. Das Wadenbein trägt nur wenig zum Körpergewicht bei; das Schienbein übernimmt die Last. In den ersten Wochen wird mit Gehhilfen mobilisiert, danach kehrt das Gehen zur Norm zurück."),
  ("Kann ich nach der Bestrahlung noch rekonstruiert werden?","Ja, bestrahltes Gewebe erschwert die Operation jedoch: Die Gefäße sind geschädigt und die Heilung verläuft langsamer. In solchen Fällen ist eine Rekonstruktion mit gut durchblutetem Gewebe von außerhalb des Bestrahlungsfeldes besonders wichtig."),
  ("Wie hoch ist das Risiko, dass der Lappen verloren geht?","Die Erfolgsrate freier Lappen liegt weltweit bei etwa 95%. In der Serie von Doz. Dr. Acartürk beträgt sie 97%. Bei einem Durchblutungsproblem entscheidet ein rechtzeitiger zweiter Eingriff in den ersten Stunden häufig über die Rettung des Lappens."),
  ("Kann ich wieder normal sprechen und essen?","Das hängt vom Umfang des entfernten Gewebes ab. Die meisten Patienten kehren nach Rekonstruktion und Rehabilitation zu einer normalen Ernährung zurück; das Sprechen bessert sich über Monate. Realistische Erwartungen werden vorab gemeinsam besprochen.")],
 "ctah":"Beurteilung zur Kopf-Hals-Rekonstruktion",
 "ctap":"Teilen Sie uns Ihre Diagnose, den geplanten Operationstermin und eine eventuelle Bestrahlung mit; senden Sie nach Möglichkeit Ihre Befunde."},

"yuz-felci": {
 "crumb":"Behandlung der Fazialisparese",
 "title":"Fazialisparese: Chirurgische Behandlung und Reanimation | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Fazialisparese: Chirurgische Behandlung",
 "desc":"Chirurgische Behandlung der Gesichtslähmung: Nerventransfer, freier Muskeltransfer, statische Verfahren und Lidversorgung — Zeitpunkt und realistische Ergebnisse.",
 "eyebrow":"Rekonstruktive Mikrochirurgie",
 "h1":"Chirurgische Behandlung der Fazialisparese",
 "lead":"Eine Gesichtslähmung ist nicht nur eine Bewegungsstörung. Nicht lächeln zu können, das Auge nicht schließen zu können, beim Trinken zu verschütten — das verändert das tägliche Leben tiefgreifend. Die Chirurgie kann ein Lächeln zurückgeben, das mit dem Gesicht in Einklang steht, wenn die medikamentöse Behandlung nicht genügt hat.",
 "watopic":"Behandlung der Fazialisparese",
 "about":"Fazialisparese",
 "card":"Fazialisparese","cardsub":"Nerventransfer, Muskeltransfer und statische Verfahren",
 "procedure":{"name":"Fazialisreanimation",
   "how":"Je nach verstrichener Zeit wird der Nerv wiederhergestellt oder verlagert; ist die Muskulatur untergegangen, wird ein neuer Muskel mitsamt Gefäßen und Nerv mikrochirurgisch übertragen.",
   "prep":"Elektromyographie, Beurteilung der Ursache und Festlegung des Zeitfensters.",
   "follow":"Gesichtsphysiotherapie und Lächeltraining.","body":"Gesichtsmuskulatur"},
 "keyfacts":[("Entscheidend","Verstrichene Zeit seit Beginn"),("Unter 12 Monaten","Nerventransfer möglich"),
             ("Über 24 Monate","Freier Muskeltransfer"),("Ergänzend","Lidversorgung und statische Verfahren")],
 "authority":"Die Fazialisreanimation vereint zwei Gebiete: Mikrochirurgie und Gesichtsanatomie. Doz. Dr. Acartürk verfügt über 300+ mikrochirurgische Eingriffe und eine Zusatzqualifikation in Mund-, Kiefer- und Gesichtschirurgie; er beherrscht Nerven- und Muskeltransfer ebenso wie die feine Anatomie des Gesichts.",
 "creds":["300+ mikrochirurgische Eingriffe","Zusatzqualifikation Mund-, Kiefer- und Gesichtschirurgie",
          "Erfahrung in Gesichtsrekonstruktion an der University of Pittsburgh"],
 "sections":[
  {"id":"neden","tag":"Ursachen","h2":"Ursachen der Fazialisparese","body":[
   "Der Gesichtsnerv (Nervus facialis) steuert die mimische Muskulatur. Wird er geschädigt, erschlafft die betroffene Gesichtshälfte, das Lächeln wird asymmetrisch und das Auge lässt sich nicht vollständig schließen.",
   ("ul",["<strong>Bell-Lähmung:</strong> die häufigste Form. Die Mehrzahl erholt sich spontan innerhalb von Wochen.",
          "<strong>Nach Tumorchirurgie:</strong> Eingriffe an Ohrspeicheldrüse, Schädelbasis oder Akustikusneurinom",
          "<strong>Trauma:</strong> Schädelbasis- oder Gesichtsverletzungen",
          "<strong>Infektionen:</strong> Herpes zoster oticus, Mittelohrentzündungen",
          "<strong>Angeboren:</strong> Möbius-Syndrom und verwandte Krankheitsbilder"]),
   ("note","Bei einer Bell-Lähmung wird zunächst medikamentös behandelt und abgewartet. Die chirurgische Planung kommt in Betracht, wenn nach einer angemessenen Zeit keine Erholung eintritt oder die Ursache eine dauerhafte Nervenschädigung ist.")]},
  {"id":"zaman","tag":"Zeitpunkt","h2":"Der Zeitpunkt bestimmt das Verfahren","body":[
   "Die verstrichene Zeit ist bei der Fazialisparese der entscheidende Faktor. Wird die Muskulatur nicht innerhalb von etwa zwei Jahren von einem Nerv erreicht, geht sie dauerhaft unter — danach genügt es nicht mehr, den Nerv wiederherzustellen.",
   ("table",["Zeitraum","Zustand der Muskulatur","Chirurgische Option"],[
     ["0–6 Monate","Muskulatur erhalten","Direkte Nervennaht oder Nerventransplantat"],
     ["6–12 Monate","Muskulatur noch lebensfähig","Nerventransfer (Masseter- oder Hypoglossusnerv)"],
     ["12–24 Monate","Zunehmender Muskelschwund","Grenzbereich — nach EMG-Befund"],
     ["Über 24 Monate","Muskulatur untergegangen","Freier Muskeltransfer (Gracilis)"]]),
   ("note","Bei einer angeborenen Lähmung ist die Muskulatur nie ausgebildet worden; unabhängig vom Alter ist ein freier Muskeltransfer erforderlich.")]},
  {"id":"yontem","tag":"Verfahren","h2":"Chirurgische Verfahren","body":[
   ("h3","Nerventransfer"),
   "Ist die Muskulatur noch lebensfähig, wird ein anderer, verzichtbarer Nerv an den Gesichtsnerv angeschlossen. Am häufigsten dient der Masseternerv als Quelle: Er ist kräftig, liegt nahe und sein Ausfall hinterlässt keine wesentliche Einschränkung. Nach der Operation entsteht das Lächeln zunächst beim Zubeißen; mit der Zeit wird es durch Übung selbstständiger.",
   ("h3","Freier Muskeltransfer"),
   "Ist die Muskulatur untergegangen, wird der Gracilis-Muskel aus dem Oberschenkel mitsamt Gefäßen und Nerv entnommen und im Gesicht mikrochirurgisch angeschlossen. Damit wird ein <strong>bewegliches, eigenes Lächeln</strong> wiederhergestellt. Der Eingriff erfolgt je nach Planung ein- oder zweizeitig.",
   ("h3","Statische Verfahren"),
   "Verfahren wie Faszienzügel, Straffung oder Brauenanhebung schaffen keine Bewegung, verbessern aber die Symmetrie in Ruhe. Sie werden bei Patienten eingesetzt, für die eine ausgedehnte Operation nicht infrage kommt, oder ergänzend zu anderen Verfahren.",
   ("h3","Lidversorgung"),
   "Kann das Auge nicht geschlossen werden, ist die Hornhaut gefährdet. Ein Goldgewicht am Oberlid oder eine Straffung des Unterlids schützt das Auge. Dieser Schritt hat Vorrang vor der Ästhetik — der Erhalt des Sehvermögens steht an erster Stelle."]},
  {"id":"surec","tag":"Ablauf","h2":"Heilung und Rehabilitation","body":[
   ("steps",[
    ("SCHRITT 1 — BEURTEILUNG","Ursache, verstrichene Zeit, EMG-Befund und Zustand der Muskulatur werden zusammen bewertet."),
    ("SCHRITT 2 — PLANUNG","Verfahren, erwartetes Ergebnis und Zeitrahmen werden offen besprochen."),
    ("SCHRITT 3 — OPERATION","Je nach Verfahren 3–8 Stunden, mit 1–3 Nächten in der Klinik."),
    ("SCHRITT 4 — WARTEZEIT AUF DEN NERV","Der Nerv wächst etwa 1 mm pro Tag. Die ersten Bewegungen erscheinen nach 3–6 Monaten."),
    ("SCHRITT 5 — PHYSIOTHERAPIE","Gesichtsphysiotherapie und Lächeltraining. Diese Phase beeinflusst die Qualität des Ergebnisses unmittelbar."),
    ("SCHRITT 6 — 12–24 MONATE","Das Lächeln wird kräftiger und natürlicher. Bei Bedarf werden ergänzende Feinkorrekturen geplant.")]),
   ("note","Die Fazialisreanimation stellt kein vollkommen symmetrisches Gesicht her. Das Ziel ist ein Lächeln, das dem Gesicht nahekommt, ein geschütztes Auge und ein wiedergewonnenes Selbstvertrauen im Alltag. Diese Erwartung vorab klar zu setzen ist Teil der Behandlung.")]}],
 "faqs":[
  ("Ist es zu spät für eine Operation?","Ist die Muskulatur untergegangen, ist eine reine Nervenoperation nicht mehr sinnvoll — ein freier Muskeltransfer ist jedoch auch nach Jahren möglich. Solange eine Behandlungsoption besteht, ist es nicht zu spät."),
  ("Wann sehe ich das Ergebnis?","Der Nerv wächst etwa 1 mm pro Tag. Die ersten Bewegungen erscheinen nach 3–6 Monaten, das eigentliche Ergebnis reift über 12–24 Monate. Es ist ein geduldiger Prozess."),
  ("Wird mein Lächeln natürlich sein?","Nach einem Masseternerv-Transfer entsteht das Lächeln zunächst beim Zubeißen; durch Physiotherapie wird es mit der Zeit selbstständiger. Vollständige Symmetrie ist nicht das Ziel, ein natürlich wirkendes Lächeln jedoch erreichbar."),
  ("Hilft Physiotherapie allein?","Bei einer Bell-Lähmung mit spontaner Erholung ist Physiotherapie sehr wertvoll. Bei dauerhafter Nervenschädigung genügt sie allein nicht, ist aber nach der Operation ein unverzichtbarer Bestandteil."),
  ("Muss ich mein Auge behandeln lassen?","Wenn sich das Auge nicht schließen lässt, ja. Eine ungeschützte Hornhaut kann zu bleibendem Sehverlust führen. Die Lidversorgung ist der dringlichste Teil der Behandlung."),
  ("Was ist bei angeborener Lähmung möglich?","Da die Muskulatur nie ausgebildet wurde, ist ein freier Muskeltransfer erforderlich. Der Eingriff wird in der Regel im Schulalter geplant; sind beide Seiten betroffen, erfolgt er in zwei Sitzungen.")],
 "ctah":"Beurteilung zur Fazialisparese",
 "ctap":"Teilen Sie uns mit, wann die Lähmung begonnen hat, wodurch sie entstanden ist und welche Behandlungen erfolgt sind; senden Sie nach Möglichkeit ein Video in Ruhe und beim Lächeln."},

"el-cerrahisi": {
 "crumb":"Handchirurgie und Replantation",
 "title":"Handchirurgie und Replantation abgetrennter Gliedmaßen | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Handchirurgie und Replantation",
 "desc":"Replantation abgetrennter Finger und Gliedmaßen, Sehnen- und Nervenversorgung, Zehen-Hand-Transfer und funktionelle Wiederherstellung.",
 "eyebrow":"Rekonstruktive Mikrochirurgie",
 "h1":"Handchirurgie und Replantation",
 "lead":"Die Hand ist das Organ, mit dem wir arbeiten, berühren und uns ausdrücken. Nach einer Verletzung ist nicht die Wundheilung der Maßstab, sondern die Rückkehr der Funktion. Bei einer Abtrennung entscheiden die ersten Stunden — sie sind wertvoller als alles, was danach kommt.",
 "watopic":"Handchirurgie",
 "about":"Handchirurgie und Replantation",
 "card":"Handchirurgie und Replantation","cardsub":"Abgetrennte Gliedmaßen, Sehnen- und Nervenversorgung",
 "procedure":{"name":"Replantation",
   "how":"Am abgetrennten Glied werden zunächst Knochen stabilisiert, dann Arterien und Venen unter dem Mikroskop verbunden und anschließend Sehnen und Nerven wiederhergestellt.",
   "prep":"Sachgerechter Transport des abgetrennten Teils und rasche Aufnahme.",
   "follow":"Durchblutungsüberwachung, frühe Handtherapie und stufenweise Belastung.",
   "body":"Finger, Hand, Unterarm"},
 "keyfacts":[("Zeitfenster","Finger 12 Stunden — je früher, desto besser"),
             ("Transport","In ein feuchtes Tuch, in einen Beutel, auf Eis"),
             ("Kritisch","Der abgetrennte Teil darf Eis nicht direkt berühren"),
             ("Nachbehandlung","Handtherapie bestimmt das Ergebnis")],
 "authority":"Die Handchirurgie ist eines der Gebiete, in denen sich mikrochirurgische Erfahrung am unmittelbarsten in Funktion übersetzt. Doz. Dr. Acartürk verfügt über 300+ mikrochirurgische Eingriffe und drei Jahre allgemeinchirurgische Ausbildung vor der plastischen Chirurgie; er ist mit Gefäß- und Nervennaht ebenso vertraut wie mit der Versorgung des Traumapatienten insgesamt.",
 "creds":["300+ mikrochirurgische Eingriffe","Drei Jahre allgemeinchirurgische Ausbildung",
          "Erfahrung in Extremitätenrekonstruktion an der University of Pittsburgh"],
 "sections":[
  {"id":"acil","tag":"Notfall","h2":"Was bei einer Abtrennung zu tun ist","body":[
   "Bei einer Abtrennung von Finger oder Hand bestimmt das Vorgehen in den ersten Minuten unmittelbar die Erfolgsaussicht der Replantation.",
   ("steps",[
    ("1 — BLUTUNG STILLEN","Die Wunde mit einem sauberen Tuch abdrücken und die Hand hochhalten. Keine Aderpresse anlegen, wenn es nicht unbedingt nötig ist."),
    ("2 — DEN ABGETRENNTEN TEIL FINDEN","Auch stark beschädigte Teile mitnehmen — sie können als Gewebequelle dienen."),
    ("3 — RICHTIG VERPACKEN","In ein leicht angefeuchtetes sauberes Tuch wickeln, in einen dichten Beutel geben und den Beutel in Eiswasser legen."),
    ("4 — NICHT DIREKT AUF EIS","Der abgetrennte Teil darf Eis nicht direkt berühren. Direkter Kontakt führt zu Erfrierungsschäden und macht die Replantation unmöglich."),
    ("5 — SOFORT IN DIE KLINIK","In ein Zentrum mit mikrochirurgischer Erfahrung. Zeit ist der wichtigste Faktor.")]),
   ("note","<strong>Zeitfenster:</strong> Ein Finger ohne Muskelgewebe verträgt etwa 12 Stunden gekühlte Ischämiezeit. Bei Hand und Unterarm mit Muskelanteil verkürzt sich diese Zeit auf 6 Stunden. Je früher die Vorstellung erfolgt, desto besser das Ergebnis.")]},
  {"id":"replantasyon","tag":"Replantation","h2":"Ablauf der Replantation","body":[
   "Bei der Replantation wird ein abgetrenntes Glied in einer bestimmten Reihenfolge wieder angeschlossen: zuerst der Knochen als Gerüst, dann die Durchblutung und zuletzt die Funktion.",
   ("ul",["<strong>Knochenstabilisierung:</strong> Fixierung mit Draht oder Platte",
          "<strong>Sehnennaht:</strong> Wiederherstellung von Beuge- und Strecksehnen",
          "<strong>Arterienanschluss:</strong> Naht unter dem Mikroskop — hier kehrt die Durchblutung zurück",
          "<strong>Venenanschluss:</strong> für den Rückfluss unverzichtbar; sein Fehlen führt zum Stau",
          "<strong>Nervennaht:</strong> für die Rückkehr von Gefühl und Bewegung",
          "<strong>Hautverschluss:</strong> bei Bedarf mit Transplantat oder Lappen"]),
   ("note","Nicht jede Abtrennung ist replantierbar. Bei ausgedehnter Quetschung, langer warmer Ischämiezeit oder mehrfacher Zerstückelung kann eine Replantation aussichtslos sein. In solchen Fällen wird eine Rekonstruktion geplant, die mehr Funktion erhält.")]},
  {"id":"diger","tag":"Weitere Eingriffe","h2":"Weitere handchirurgische Eingriffe","body":[
   ("ul",["<strong>Sehnenverletzungen:</strong> Beuge- und Strecksehnennaht, sekundäre Sehnenrekonstruktion",
          "<strong>Nervenverletzungen:</strong> Nervennaht, Nerventransplantat und Nerventransfer",
          "<strong>Zehen-Hand-Transfer:</strong> mikrochirurgische Übertragung einer Zehe bei Daumenverlust",
          "<strong>Weichteildefekte:</strong> Deckung mit lokalen oder freien Lappen",
          "<strong>Kontrakturen und Narben:</strong> Wiederherstellung der Beweglichkeit bei Bewegungseinschränkung"]),
   ("h3","Zehen-Hand-Transfer"),
   "Der Daumen erbringt etwa 40% der Handfunktion. Bei Daumenverlust und fehlender Replantationsmöglichkeit wird eine Zehe mitsamt Gefäßen, Nerven und Sehnen an die Hand übertragen. Die Gangfunktion bleibt erhalten, die Greiffunktion der Hand wird wiederhergestellt."]},
  {"id":"rehab","tag":"Rehabilitation","h2":"Handtherapie und Ergebnis","body":[
   "In der Handchirurgie erbringt die Operation nur die Hälfte des Ergebnisses; die andere Hälfte leistet die Handtherapie. Ohne Therapie führen Sehnenverklebungen und Gelenksteifen dazu, dass eine technisch gelungene Operation funktionell scheitert.",
   ("ul",["Ein geschützter Bewegungsplan beginnt in der Regel in den ersten Wochen",
          "Die Rückkehr des Gefühls erstreckt sich über Monate — der Nerv wächst etwa 1 mm pro Tag",
          "Die Kälteempfindlichkeit ist in den ersten 1–2 Jahren ausgeprägt und lässt mit der Zeit nach",
          "Die Rückkehr in den Beruf hängt von der Art der Tätigkeit ab und wird schrittweise geplant"])]}],
 "faqs":[
  ("Wie lange bleibt ein abgetrennter Finger replantierbar?","Ein Finger verträgt gekühlt etwa 12 Stunden. Bei Hand und Unterarm mit Muskelgewebe verkürzt sich diese Zeit auf 6 Stunden. Bei richtiger Kühlung verlängert sich das Fenster, doch bleibt frühe Vorstellung entscheidend."),
  ("Wie wird der abgetrennte Teil transportiert?","In ein leicht angefeuchtetes sauberes Tuch wickeln, in einen dichten Beutel geben und den Beutel in Eiswasser legen. Der Teil darf Eis niemals direkt berühren — direkter Kontakt macht die Replantation unmöglich."),
  ("Funktioniert der replantierte Finger normal?","Vollständig normal in der Regel nicht. Ziel ist eine nützliche Funktion: Greifen, Halten, Gefühl. Die Kälteempfindlichkeit hält in den ersten Jahren an. Das Ergebnis hängt von Verletzungsart und Therapietreue ab."),
  ("Kehrt das Gefühl zurück?","Der genähte Nerv wächst etwa 1 mm pro Tag. Das Gefühl kehrt über Monate zurück, meist nicht auf das ursprüngliche Niveau, aber ausreichend für den Gebrauch."),
  ("Ist eine Replantation immer möglich?","Nein. Bei ausgedehnter Quetschung, langer warmer Ischämiezeit oder mehrfacher Zerstückelung kann sie aussichtslos sein. In solchen Fällen liefert eine funktionserhaltende Rekonstruktion das bessere Ergebnis."),
  ("Wie lange ist die Rückkehr in den Beruf?","Bei Bürotätigkeit einige Wochen, bei körperlicher Arbeit mehrere Monate. Der Zeitplan wird nach Verletzung und Fortschritt der Handtherapie individuell festgelegt.")],
 "ctah":"Beurteilung in der Handchirurgie",
 "ctap":"Teilen Sie uns mit, wann und wodurch die Verletzung entstanden ist und welche Behandlungen bisher erfolgten; senden Sie nach Möglichkeit Fotos und Befunde. Bei einer akuten Abtrennung suchen Sie bitte unverzüglich die nächste Notaufnahme auf."},

"yanik": {
 "crumb":"Verbrennungs- und Traumarekonstruktion",
 "title":"Verbrennungsnarben, Kontrakturen und Traumarekonstruktion | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Verbrennungs- und Traumarekonstruktion",
 "desc":"Behandlung von Verbrennungsnarben und Kontrakturen, Lösung von Bewegungseinschränkungen, Hauttransplantate, Lappen und Fetttransfer bei Narbenversorgung.",
 "eyebrow":"Rekonstruktive Chirurgie",
 "h1":"Verbrennungs- und Traumarekonstruktion",
 "lead":"Eine Verbrennung endet nicht mit dem Verheilen der Wunde. Vernarbtes Gewebe zieht sich zusammen, schränkt die Beweglichkeit ein und verändert das Aussehen. Die rekonstruktive Chirurgie löst diese Einschränkungen, gibt Funktion zurück und macht die Narben erträglicher.",
 "watopic":"Verbrennungs- und Narbenrekonstruktion",
 "about":"Verbrennungs- und Traumarekonstruktion",
 "card":"Verbrennungs- und Traumarekonstruktion","cardsub":"Narbenkontrakturen, Bewegungseinschränkung und Gewebeverlust",
 "procedure":{"name":"Rekonstruktion von Verbrennungsnarben",
   "how":"Kontrahiertes Narbengewebe wird gelöst und der entstandene Defekt je nach Bedarf mit Z-Plastik, Hauttransplantat, Lappen oder Fetttransfer gedeckt.",
   "prep":"Beurteilung von Narbenreife, Bewegungsumfang und Gewebequalität.",
   "follow":"Kompressionsversorgung, Silikonpflege und Physiotherapie.",
   "body":"Haut und Weichgewebe"},
 "keyfacts":[("Zeitpunkt","Narbe sollte in der Regel 6–12 Monate gereift sein"),
             ("Dringlichkeit","Bei Kontraktur mit Funktionsverlust früher"),
             ("Verfahren","Z-Plastik, Transplantat, Lappen, Fetttransfer"),
             ("Nachbehandlung","Kompression und Physiotherapie sind Teil der Behandlung")],
 "authority":"Die Verbrennungsrekonstruktion erfordert die gesamte Bandbreite der plastischen Chirurgie: Hauttransplantate, lokale Lappen, freie Lappen und Fetttransfer. Doz. Dr. Acartürk verbindet 300+ mikrochirurgische Eingriffe mit seiner Arbeit zu Fettgewebe und Stammzellen an der University of Pittsburgh — eine Kombination, die in der Narbenversorgung besonders wirksam ist.",
 "creds":["300+ mikrochirurgische Eingriffe","Forschung zu Fettgewebe und Stammzellen an der University of Pittsburgh",
          "Drei Jahre allgemeinchirurgische Ausbildung"],
 "sections":[
  {"id":"kontraktur","tag":"Kontraktur","h2":"Narbenkontrakturen und Bewegungseinschränkung","body":[
   "Verbrennungsnarben ziehen sich beim Heilen zusammen. Verläuft die Narbe über ein Gelenk, schränkt diese Kontraktur die Beweglichkeit ein. Hals, Achselhöhle, Ellenbeuge, Hand und Kniekehle sind die am häufigsten betroffenen Regionen.",
   ("ul",["<strong>Hals:</strong> das Kinn wird nach unten gezogen, die Kopfdrehung ist eingeschränkt",
          "<strong>Achselhöhle:</strong> der Arm lässt sich nicht vollständig heben",
          "<strong>Hand:</strong> Finger können sich nicht strecken oder beugen, die Greiffunktion leidet",
          "<strong>Gesicht:</strong> Lid- und Lippenzug, unvollständiger Augen- oder Mundschluss"]),
   ("note","Bei Kindern erschwert eine Kontraktur zusätzlich das Wachstum: Das Narbengewebe wächst nicht mit, sodass die Einschränkung mit den Jahren zunimmt. Deshalb ist bei Kindern eine frühere und gestaffelte Planung erforderlich.")]},
  {"id":"yontem","tag":"Verfahren","h2":"Chirurgische Verfahren","body":[
   ("table",["Verfahren","Anwendung","Merkmal"],[
     ["Z-Plastik","Schmale, strangförmige Narben","Verlängert die Narbe und ändert ihre Richtung; kein zusätzliches Gewebe nötig"],
     ["Hauttransplantat","Ausgedehnte Flächendefekte","Rasche Deckung; Farb- und Texturunterschiede möglich"],
     ["Gewebeexpander","Gesunde Haut in der Nachbarschaft vorhanden","Erzeugt Haut gleicher Farbe und Beschaffenheit — braucht Zeit"],
     ["Lokaler Lappen","Begrenzte Defekte","Gewebe aus der Nachbarschaft; gute Farbanpassung"],
     ["Freier Lappen","Ausgedehnte Defekte, freiliegender Knochen oder Sehne","Gut durchblutetes Gewebe von fern übertragen"],
     ["Fetttransfer","Verhärtete, verklebte Narben","Lockert das Gewebe auf und verbessert die Hautqualität"]]),
   ("h3","Fetttransfer in der Narbenbehandlung"),
   "Eigenfettgewebe gibt der Narbe nicht nur Volumen, sondern verbessert durch seine regenerativen Zellen auch die <strong>Gewebequalität</strong>. Bei verhärteten, verklebten Narben und Strahlenschäden bringt dieses Verfahren häufig deutliche Besserung. Einzelheiten auf unserer <a href=\"../yag-enjeksiyonu.html\">Seite zum Eigenfetttransfer</a>."]},
  {"id":"zaman","tag":"Zeitpunkt","h2":"Wann sollte operiert werden?","body":[
   "Eine Narbe reift über 6–12 Monate: Röte und Verhärtung nehmen ab, das Gewebe wird weicher. Eine Operation in dieser Phase kann zu unnötig ausgedehnten Eingriffen führen. Es gibt jedoch Ausnahmen:",
   ("ul",["<strong>Fortschreitende Kontraktur:</strong> nimmt die Bewegungseinschränkung zu, wird nicht abgewartet",
          "<strong>Lidzug:</strong> lässt sich das Auge nicht schließen, ist ein früher Eingriff nötig",
          "<strong>Bei Kindern:</strong> eine wachstumshemmende Kontraktur wird früher versorgt",
          "<strong>Nicht heilende Wunden:</strong> eine chronisch offene Wunde wird ohne Abwarten gedeckt"]),
   ("note","Kompressionsversorgung, Silikonpflege und Physiotherapie im Reifungsprozess verbessern das Endergebnis unmittelbar. Diese Maßnahmen sind keine Nebensache, sondern Teil der Behandlung.")]},
  {"id":"surec","tag":"Ablauf","h2":"Planung und Heilung","body":[
   ("steps",[
    ("SCHRITT 1 — BEURTEILUNG","Narbenreife, Bewegungsumfang und Gewebequalität werden untersucht; Prioritäten werden festgelegt."),
    ("SCHRITT 2 — GESTAFFELTE PLANUNG","Bei ausgedehnten Verbrennungen erfolgt die Versorgung in mehreren Sitzungen. Funktion hat Vorrang vor Aussehen."),
    ("SCHRITT 3 — OPERATION","Dauer und Klinikaufenthalt richten sich nach dem gewählten Verfahren."),
    ("SCHRITT 4 — ERSTE WOCHEN","Wundpflege, Ruhigstellung oder frühe Mobilisierung je nach Region."),
    ("SCHRITT 5 — PHYSIOTHERAPIE","Bewegungsübungen sind unverzichtbar, damit die Kontraktur nicht zurückkehrt."),
    ("SCHRITT 6 — 6–12 MONATE","Die Narbe reift und wird blasser. Bei Bedarf werden ergänzende Sitzungen geplant.")])]}],
 "faqs":[
  ("Verschwinden Verbrennungsnarben vollständig?","Nein. Eine Narbe lässt sich nicht auslöschen, aber ihr Aussehen verbessern und die Bewegungseinschränkung beseitigen. Realistische Erwartungen sind Teil der Behandlungsplanung."),
  ("Wie lange nach der Verbrennung kann operiert werden?","In der Regel wird die Narbenreifung von 6–12 Monaten abgewartet. Bei fortschreitender Kontraktur, Lidzug oder wachstumshemmender Einschränkung bei Kindern wird früher eingegriffen."),
  ("Sind mehrere Operationen nötig?","Bei ausgedehnten Verbrennungen meist ja. Die Versorgung wird gestaffelt geplant, wobei zuerst die funktionell wichtigsten Regionen behandelt werden."),
  ("Genügt eine Laserbehandlung?","Der Laser kann Röte, Textur und Verhärtung einer Narbe bessern, löst aber keine Kontraktur und ersetzt fehlendes Gewebe nicht. Er ist ein ergänzendes Verfahren, kein Ersatz für die Operation."),
  ("Übernimmt die Krankenkasse die Kosten?","Rekonstruktive Eingriffe bei Funktionsverlust werden häufig übernommen, da sie nicht als ästhetische Eingriffe gelten. Die Bedingungen unterscheiden sich und sollten vorab geklärt werden."),
  ("Wie ist das Vorgehen bei Kindern?","Da Narbengewebe nicht mitwächst, nimmt die Einschränkung mit den Jahren zu. Bei Kindern wird daher früher und in mehreren Etappen geplant, wobei die Eingriffe an die Wachstumsphasen angepasst werden.")],
 "ctah":"Beurteilung zur Verbrennungs- und Narbenrekonstruktion",
 "ctap":"Teilen Sie uns mit, wann die Verbrennung oder Verletzung geschah, welche Behandlungen erfolgten und ob eine Bewegungseinschränkung besteht; senden Sie nach Möglichkeit aktuelle Fotos."},
}
