# -*- coding: utf-8 -*-
"""Almanca ceviriler — parti 6: lenfodem kumesi (6 uydu sayfa)."""

T = {
"bacakta-lenfodem": {
 "crumb":"Beinlymphödem",
 "title":"Lymphödem am Bein: Symptome und Behandlung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lymphödem am Bein: Symptome und Behandlung",
 "desc":"Welche Symptome hat ein Beinlymphödem, wie entsteht es, mit welchen Erkrankungen wird es verwechselt und wie wird es behandelt? Operative Optionen nach Stadium und mikrochirurgische Behandlung.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Lymphödem am Bein: Symptome und Behandlung",
 "lead":"Wenn die Schwellung im Bein im Lauf des Tages zunimmt und morgens zurückgeht, wenn die Schuhe drücken und ein Bein dicker ist als das andere — dann ist das womöglich keine Frage des Gewichts. Das Beinlymphödem beginnt unauffällig, lässt sich im Frühstadium aber mikrochirurgisch behandeln.",
 "watopic":"Behandlung des Beinlymphödems",
 "about":"Beinlymphödem",
 "aboutType":"MedicalCondition",
 "card":"Lymphödem am Bein","cardsub":"Diagnostik und operative Behandlung des Lymphödems der unteren Extremität",
 "procedure":{"name":"Lymphödemchirurgie der unteren Extremität",
   "how":"Blockierte Lymphbahnen im Bein werden unter dem Mikroskop mit benachbarten Venen verbunden (LVA); im fortgeschrittenen Stadium werden vaskularisierter Lymphknotentransfer und Reduktionschirurgie geplant.",
   "prep":"Untersuchung, Umfangmessungen, Lymphmapping mittels ICG-Lymphographie oder Lymphszintigraphie.",
   "follow":"Kompressionsversorgung, frühe Mobilisation und bei Bedarf Lymphödem-Physiotherapie.",
   "body":"Lymphsystem von Bein und Fuß"},
 "keyfacts":[("Unterscheidendes Merkmal","Die Schwellung reicht bis Fußrücken und Zehen"),
             ("Stemmer","Positiv, wenn die Haut über der Zehe nicht abhebbar ist"),
             ("Frühstadium","LVA — die schonendste Option"),
             ("Entscheidend","Einseitige Schwellung ist immer abzuklären")],
 "authority":"Das Beinlymphödem ist ein schwierigeres Gebiet als das Armlymphödem: Die Schwerkraft erhöht die lymphatische Last, die Wege sind länger und das Infektionsrisiko ist höher. Mit über 300 mikrochirurgischen Fällen an der University of Pittsburgh arbeitet Doz. Dr. Acartürk an Lymphbahnen von 0,3–0,8 mm Durchmesser und nimmt an den Arbeiten der europäischen lymphatischen Mikrochirurgie-Gruppe teil.",
 "creds":["Ehem. Direktor für Kopf-Hals-Rekonstruktion, University of Pittsburgh — 300+ mikrochirurgische Fälle",
          "Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie",
          "Vortrag auf dem Weltkongress für Lymphologie"],
 "sections":[
  {"id":"belirti","tag":"Symptome","h2":"Symptome des Beinlymphödems","body":[
   "Das Beinlymphödem beginnt meist unbemerkt. In der Frühphase nimmt die Schwellung im Lauf des Tages zu und geht über Nacht weitgehend zurück. Wegen dieser Schwankung führen Betroffene den Zustand auf Müdigkeit oder salziges Essen zurück und suchen monatelang keinen Arzt auf.",
   ("h3","Frühe Befunde"),
   ("ul",["Schwellung, die gegen Abend zunimmt und morgens geringer ist",
          "Der Sockenbund hinterlässt einen tiefen Abdruck",
          "Die Schuhe drücken abends",
          "Gefühl von Fülle und Schwere im Bein",
          "Zunehmender Umfangunterschied zwischen beiden Beinen"]),
   ("h3","Befunde im fortgeschrittenen Stadium"),
   ("ul",["Schwellung, die bei Hochlagerung nicht zurückgeht",
          "Verdickung und Verhärtung der Haut",
          "Wiederkehrende Erysipel-Schübe — Fieber, Rötung, Schmerz",
          "Kastenförmige Zehen",
          "Lymphaustritt aus der Haut (Lymphorrhoe) und warzenartige Veränderungen"]),
   ("note","<strong>Stemmer-Zeichen:</strong> Versuchen Sie, die Haut über der zweiten Zehe mit den Fingern abzuheben. Ist sie verdickt und nicht abhebbar, ist das Zeichen positiv und spricht für ein Lymphödem. Ein einfacher, aber wertvoller Untersuchungsbefund — er allein sichert die Diagnose jedoch nicht.")]},
  {"id":"neden","tag":"Ursachen","h2":"Warum entsteht ein Beinlymphödem?","body":[
   "Die Ursachen des Lymphödems der unteren Extremität unterscheiden sich von denen am Arm. Am Arm folgt das Bild meist einer Brustkrebsbehandlung; am Bein ist die Ursachenvielfalt größer.",
   ("ul",["<strong>Gynäkologische und urologische Krebstherapien:</strong> Leisten- und Beckenlymphknotenentfernung bei Gebärmutter-, Eierstock- und Prostatakrebs",
          "<strong>Bestrahlung:</strong> Die Bestrahlung des Beckens vernarbt die Lymphbahnen",
          "<strong>Wiederkehrende Erysipele:</strong> Jeder Schub schädigt die lymphatische Struktur weiter — ein Teufelskreis",
          "<strong>Melanomchirurgie:</strong> nach Leistenlymphknotenentfernung",
          "<strong>Primäres Lymphödem:</strong> angeborene Unterentwicklung des Lymphsystems; kann in der Pubertät oder im Erwachsenenalter auftreten",
          "<strong>Trauma und große orthopädische Eingriffe</strong>"]),
   ("note","Der erste Schritt beim Beinlymphödem ist der Ausschluss einer zugrunde liegenden Abflussbehinderung. Bei einseitiger, rasch einsetzender und schmerzhafter Schwellung müssen eine tiefe Beinvenenthrombose und eine Raumforderung im Becken abgeklärt werden. Ohne diese Beurteilung sollte die Diagnose Lymphödem nicht gestellt werden.")]},
  {"id":"ayirici","tag":"Differentialdiagnose","h2":"Ist eine Beinschwellung immer ein Lymphödem?","body":[
   "Nein. Mehrere unterschiedliche Zustände führen zu Schwellungen am Bein, und ihre Behandlung unterscheidet sich grundlegend. Die am häufigsten verwechselten Bilder:",
   ("table",["Zustand","Unterscheidendes Merkmal"],[
     ["Lymphödem","Schwellung reicht bis Fußrücken und Zehen; Stemmer positiv; meist einseitig"],
     ["Lipödem","Schwellung endet am Knöchel — Manschettenzeichen; Füße frei; symmetrisch; druckschmerzhaft"],
     ["Venöse Insuffizienz","Nimmt abends zu, geht bei Hochlagerung rasch zurück; Krampfadern und Hautverfärbung begleiten"],
     ["Kardiales/renales/hepatisches Ödem","Symmetrisch an beiden Beinen; Dellen bei Druck; systemische Grunderkrankung"],
     ["Tiefe Beinvenenthrombose","Plötzlicher Beginn, Schmerz, Überwärmung — dringliche Abklärung"]]),
   "Lymphödem und Lipödem können auch gemeinsam vorliegen; das nennt man <strong>Lipo-Lymphödem</strong>. Einen ausführlichen Vergleich finden Sie auf unserer <a href=\"../lipodem-cerrahisi.html\">Seite zur Lipödemchirurgie</a>."]},
  {"id":"tedavi","tag":"Behandlung","h2":"Behandlung des Beinlymphödems","body":[
   "Die Behandlung wird nach Stadium geplant. Der Grundsatz lautet: <strong>ein Eingriff, solange die Lymphbahnen noch arbeiten</strong>, ist weit wirksamer als einer nach eingetretener Gewebeverhärtung.",
   ("h3","Konservative Behandlung"),
   "Die komplexe physikalische Entstauungstherapie — manuelle Lymphdrainage, Bandagierung, Kompressionsstrümpfe und Bewegung — ist die Grundlage der Behandlung und wird auch nach einer Operation fortgeführt. Sie beseitigt die Blockade selbst jedoch nicht.",
   ("h3","LVA — lymphovenöse Anastomose"),
   "Funktionierende Lymphbahnen im Bein werden unter dem Mikroskop mit benachbarten Venen verbunden. Die Schnitte sind klein, die Heilung rasch. Im Frühstadium, solange sich die Bahnen noch kontrahieren, ist dies die wirksamste Option.",
   ("h3","Vaskularisierter Lymphknotentransfer"),
   "Eine Gruppe eigener Lymphknoten wird mitsamt den versorgenden Gefäßen ins Bein verlagert. Bevorzugt im fortgeschrittenen Stadium und bei bestrahlter Leistenregion.",
   ("h3","Reduktionschirurgie"),
   "Ist das Volumen durch Fettgewebe und Fibrose gestiegen, verringern Liposuktion und Exzision das Beinvolumen. Der Lymphfluss wird dadurch nicht wiederhergestellt, die Last aber deutlich gesenkt; meist wird sie mit anderen Verfahren kombiniert.",
   ("note","Beim Beinlymphödem ist die Verringerung wiederkehrender Erysipele ein ebenso wichtiges Ziel wie die Volumenreduktion. Jeder Schub schädigt die lymphatische Struktur weiter; seltenere Schübe verlangsamen das Fortschreiten der Erkrankung.")]},
  {"id":"gunluk","tag":"Alltag","h2":"Alltag mit Beinlymphödem","body":[
   ("ul",["<strong>Hautpflege ist die wichtigste Schutzmaßnahme.</strong> Trockene Haut reißt ein, und über den Riss eindringende Bakterien verursachen ein Erysipel. Tägliches Eincremen sollte nicht vernachlässigt werden.",
          "<strong>Auf Fußpflege achten:</strong> Pilzinfektionen beginnen in den Zehenzwischenräumen und sind die häufigste Eintrittspforte für Erysipele",
          "<strong>Vor Verletzungen schützen:</strong> nicht barfuß gehen, Nägel nicht zu kurz schneiden",
          "<strong>Bewegung hilft:</strong> Gehen und Wadenmuskelarbeit unterstützen den Lymphfluss",
          "<strong>Auf Langstreckenflügen</strong> werden Kompressionsstrümpfe und häufige Bewegung empfohlen",
          "<strong>Gewichtskontrolle</strong> senkt die lymphatische Last unmittelbar"]),
   ("note","Fieber, ausgedehnte Rötung des Beins und Überwärmung kündigen ein Erysipel an. Dieses Bild erfordert unverzüglich eine antibiotische Behandlung; ein Aufschub verschlimmert den Schub und erhöht die lymphatische Schädigung.")]}],
 "faqs":[
  ("Ist die Schwellung im Bein ein Lymphödem oder ein Ödem?","Eine Schwellung, die bei Druck eine tiefe Delle hinterlässt, bei Hochlagerung rasch zurückgeht und an beiden Beinen symmetrisch ist, spricht eher für ein systemisches Ödem. Beim Lymphödem reicht die Schwellung bis Fußrücken und Zehen, das Stemmer-Zeichen ist positiv und sie ist meist einseitig. Die sichere Abgrenzung erfolgt durch Untersuchung und Bildgebung."),
  ("Geht ein Beinlymphödem weg?","Ein Versprechen vollständiger Heilung wäre unredlich. Im Frühstadium kann die Mikrochirurgie das Volumen jedoch deutlich verringern, Erysipele werden seltener und die Abhängigkeit von Kompressionsstrümpfen nimmt ab. Mit fortschreitendem Stadium wird das Ziel, die Erkrankung zu kontrollieren und die Funktion zu erhalten."),
  ("Ist eine Behandlung ohne Operation möglich?","Die komplexe Entstauungstherapie und Kompressionsversorgung sind die Grundlage der Behandlung und halten bei vielen Patienten das Volumen unter Kontrolle. Sie lösen die Blockade selbst jedoch nicht. Bei Patienten im geeigneten Stadium bietet die Chirurgie die Möglichkeit, an der Ursache anzusetzen."),
  ("Welche Operation wird beim Beinlymphödem durchgeführt?","Im Frühstadium steht die LVA im Vordergrund. Im fortgeschrittenen Stadium werden vaskularisierter Lymphknotentransfer und Reduktionschirurgie einzeln oder kombiniert geplant. Die Entscheidung richtet sich nach Stadium, Bildgebungsbefunden und Dauer der Schwellung."),
  ("Muss ich nach der Operation Kompressionsstrümpfe tragen?","In der ersten Zeit ja. Mit der Zeit nimmt der Bedarf bei vielen Patienten ab, ein vollständiges Weglassen ist jedoch nicht immer möglich. Das hängt vom Stadium und vom Operationsergebnis ab."),
  ("Warum sind Erysipel-Schübe so wichtig?","Jeder Schub hinterlässt bleibende Schäden an den Lymphbahnen und lässt das Stadium fortschreiten. Schübe zu verhindern — Hautpflege, Behandlung von Fußpilz, Schutz vor Verletzungen — ist untrennbarer Teil der Behandlung.")],
 "related":["lenfodem","lenfodem-belirtileri","kolda-lenfodem","lipodem"],
 "ctah":"Beurteilung des Beinlymphödems",
 "ctap":"Teilen Sie uns mit, seit wann die Schwellung besteht, ob sie ein- oder beidseitig ist, welche Operationen oder Bestrahlungen erfolgt sind und ob Erysipele aufgetreten sind; senden Sie nach Möglichkeit ein Foto beider Beine."},

"kolda-lenfodem": {
 "crumb":"Armlymphödem",
 "title":"Armlymphödem nach Brustkrebs: Symptome und Behandlung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Armlymphödem: Symptome und Behandlung",
 "desc":"Armlymphödem nach Brustkrebsbehandlung: Symptome, Risikofaktoren, Vorbeugung und mikrochirurgische Behandlungsoptionen (LVA, Lymphknotentransfer).",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Armlymphödem und Behandlung nach Brustkrebs",
 "lead":"Für viele Patientinnen ist die Schwellung, die nach Abschluss der Brustkrebsbehandlung im Arm beginnt, die am längsten anhaltende Nebenwirkung dieser Behandlung. Sie ist jedoch keine unvermeidliche Folge mehr: Im Frühstadium lässt sie sich mikrochirurgisch angehen, und sie kann bereits während der ursprünglichen Operation verhindert werden.",
 "watopic":"Behandlung des Armlymphödems",
 "about":"Armlymphödem",
 "aboutType":"MedicalCondition",
 "card":"Lymphödem am Arm","cardsub":"Operative Behandlung des Armlymphödems nach Brustkrebs",
 "procedure":{"name":"Lymphödemchirurgie der oberen Extremität",
   "how":"Blockierte Lymphbahnen im Arm werden unter dem Mikroskop mit benachbarten Venen verbunden; Narbengewebe in der Achselhöhle wird gelöst und bei Bedarf ein vaskularisierter Lymphknotentransfer durchgeführt.",
   "prep":"Umfangmessungen, ICG-Lymphographie, Beurteilung der Achselhöhle und der Bestrahlungsanamnese.",
   "follow":"Kompressionsarmstrumpf, Schulterbeweglichkeitsübungen und Lymphödem-Physiotherapie.",
   "body":"Lymphsystem des Arms"},
 "keyfacts":[("Risiko","Axilladissektion + Bestrahlung birgt das höchste Risiko"),
             ("Zeitpunkt","Beginnt meist in den ersten 2 Jahren"),
             ("Frühstadium","Volumenkontrolle mit LVA möglich"),
             ("Vorbeugung","LYMPHA — ein schützender Ansatz während der Operation")],
 "authority":"Die Chirurgie des Armlymphödems erfordert Kenntnisse in Brustchirurgie und Mikrochirurgie zugleich. Doz. Dr. Acartürk führt sowohl Brustrekonstruktionen als auch lymphatische Mikrochirurgie durch; mit 300+ mikrochirurgischen Fällen und einer Lappenerfolgsrate von 97% führt er diese beiden Gebiete in einem Plan zusammen.",
 "creds":["300+ mikrochirurgische Eingriffe · 97% Lappenerfolgsrate",
          "Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie",
          "Integrierter Ansatz für Brustrekonstruktion und lymphatische Chirurgie"],
 "sections":[
  {"id":"belirti","tag":"Symptome","h2":"Symptome des Armlymphödems","body":[
   "Das Armlymphödem wird häufig gespürt, bevor eine messbare Schwellung auftritt. Die meisten Patientinnen beschreiben zuerst ein <strong>Gefühl von Schwere und Spannung</strong>.",
   ("h3","Frühe Warnzeichen"),
   ("ul",["Gefühl von Fülle, Schwere oder Spannung im Arm",
          "Uhr, Ring oder Armband werden eng",
          "Der Hemdärmel sitzt nur auf einer Seite eng",
          "Spannung und Glanz der Haut",
          "Gefühl verminderter Armbeweglichkeit"]),
   ("h3","Befunde im etablierten Stadium"),
   ("ul",["Messbarer Unterschied im Armumfang (meist 2 cm und mehr)",
          "Schwellung, die bei Hochhalten des Arms nicht zurückgeht",
          "Verdickung und Verhärtung der Haut",
          "Wiederkehrende Erysipel-Schübe",
          "Schwellung von Handrücken und Fingern"]),
   ("note","Eine Schwellung in den ersten Wochen nach der Operation ist meist ein vorübergehendes Ödem infolge des Eingriffs und kein Lymphödem. Hält die Schwellung jedoch länger als 3 Monate an oder beginnt sie später, muss sie abgeklärt werden.")]},
  {"id":"risk","tag":"Risiko","h2":"Wer hat ein höheres Risiko?","body":[
   "Nicht jede wegen Brustkrebs behandelte Patientin entwickelt ein Lymphödem. Das Risiko richtet sich nach dem Umfang der durchgeführten Behandlung.",
   ("table",["Faktor","Auswirkung auf das Risiko"],[
     ["Sentinel-Lymphknotenbiopsie","Geringes Risiko — nur wenige Knoten werden entfernt"],
     ["Axilläre Lymphknotendissektion","Deutliche Risikoerhöhung — die axilläre Lymphstruktur ist weitgehend betroffen"],
     ["Bestrahlung der Achselhöhle","Erhöht das Risiko zusätzlich; kombiniert mit Dissektion höchstes Risiko"],
     ["Wiederkehrende Infektionen","Jeder Schub verringert die lymphatische Reserve"],
     ["Hoher Body-Mass-Index","Erhöht die lymphatische Last"],
     ["Trauma oder Operation am Arm","Belastet die vorhandene Reserve"]]),
   ("note","Das Lymphödem beginnt meist innerhalb der ersten 2 Jahre nach Behandlungsende, kann aber auch Jahre später auftreten. Deshalb wird bei Risikopatientinnen eine regelmäßige Kontrolle des Armumfangs empfohlen.")]},
  {"id":"onleme","tag":"Vorbeugung","h2":"Ist es vermeidbar?","body":[
   "Die wichtigste Entwicklung der letzten Jahre in der Lymphödemchirurgie betrifft nicht die Behandlung, sondern die <strong>Vorbeugung</strong>.",
   ("h3","LYMPHA — vorbeugende lymphovenöse Anastomose"),
   "Während der Axilladissektion werden die durchtrennten Lymphbahnen in derselben Sitzung mit einer benachbarten Vene verbunden. So wird von vornherein ein Abflussweg für die Lymphe geschaffen. Dieses Vorgehen wird mit dem Ziel eingesetzt, die Rate an Lymphödemen bei Risikopatientinnen zu senken.",
   ("h3","Früherkennung"),
   "Eine Umfangmessung des Arms vor der Operation und die regelmäßige Kontrolle danach ermöglichen es, ein Lymphödem zu erfassen, bevor es sichtbar wird. Eine im Stadium 0 erfasste Patientin hat die breiteste Auswahl an Behandlungsoptionen.",
   ("ul",["Vor der Operation sollte eine Ausgangsmessung erfolgen",
          "In den ersten 2 Jahren engmaschiger, danach jährlich",
          "Ein Gefühl von Schwere und Spannung ist ernst zu nehmen — nicht auf Messwerte warten",
          "Hautpflege und Infektionsschutz ab dem ersten Tag"])]},
  {"id":"tedavi","tag":"Behandlung","h2":"Behandlung des Armlymphödems","body":[
   ("h3","Konservative Behandlung"),
   "Manuelle Lymphdrainage, Bandagierung, Kompressionsarmstrümpfe und Bewegung bilden die Grundlage der Behandlung und werden auch nach einer Operation fortgeführt.",
   ("h3","LVA"),
   "Funktionierende Lymphbahnen im Arm werden unter dem Mikroskop mit Venen verbunden. Der Eingriff erfolgt über kleine Schnitte, der Klinikaufenthalt ist kurz. Im Frühstadium ist dies die wirksamste Option.",
   ("h3","Vaskularisierter Lymphknotentransfer"),
   "Aus einer gesunden Region entnommene Lymphknoten werden mit ihren versorgenden Gefäßen in die Achselhöhle verlagert. Dass dabei gut durchblutetes Gewebe in bestrahltes und vernarbtes Achselgewebe gebracht wird, ist ein zusätzlicher Vorteil.",
   ("h3","Narbenlösung"),
   "Dichtes Narbengewebe in der Achselhöhle schränkt sowohl den Lymphfluss als auch die Schulterbeweglichkeit ein. Die Lösung, gemeinsam mit einem Transfer geplant, verbessert das Ergebnis deutlich.",
   ("h3","Reduktionschirurgie"),
   "Bei einem durch Fettgewebe und Fibrose vergrößerten Arm verringert die Liposuktion das Volumen. Sie wird im fortgeschrittenen Stadium mit anderen Verfahren kombiniert.",
   ("note","Bei geplanter Brustrekonstruktion kann die Lymphödemchirurgie in derselben Sitzung erfolgen. Das erspart der Patientin einen zweiten Eingriff. Einzelheiten auf unserer <a href=\"../meme-rekonstruksiyonu.html\">Seite zur Brustrekonstruktion</a>.")]}],
 "faqs":[
  ("Bekommt jede Patientin nach einer Brustkrebsoperation ein Lymphödem?","Nein. Das Risiko richtet sich nach der durchgeführten Behandlung. Nach einer Sentinel-Lymphknotenbiopsie ist es gering, während es bei kombinierter Axilladissektion und Bestrahlung deutlich steigt."),
  ("Wann beginnt das Lymphödem?","Meist innerhalb der ersten 2 Jahre nach Behandlungsende. Es kann jedoch auch Jahre später auftreten, weshalb die Nachsorge langfristig angelegt sein sollte."),
  ("Ist die Schwellung in meinem Arm ein Lymphödem?","Ein messbarer Umfangunterschied gegenüber dem anderen Arm, ein Schweregefühl und ein enger werdender Ring oder eine enge Uhr sprechen für ein Lymphödem. Eine Schwellung in den ersten Wochen nach der Operation ist meist ein vorübergehendes Wundödem. Die Abgrenzung erfolgt durch Untersuchung und Messung."),
  ("Bessert sich das durch eine Operation?","Im Frühstadium kann die LVA das Volumen deutlich verringern und die Abhängigkeit vom Kompressionsarmstrumpf abnehmen. Im fortgeschrittenen Stadium erreichen Lymphknotentransfer und Reduktionschirurgie eine Kontrolle. Ein Versprechen vollständiger Heilung wäre unredlich; das Ziel ist Volumenreduktion, seltenere Infektionen und Wiederherstellung der Funktion."),
  ("Kann man einem Lymphödem vorbeugen?","Bei Risikopatientinnen wird der vorbeugende LVA-Ansatz (LYMPHA) während der Axilladissektion mit dem Ziel eingesetzt, die Rate an Lymphödemen zu senken. Zur Früherkennung wird zudem eine Ausgangsmessung vor der Operation empfohlen."),
  ("Soll ich meinen Arm schonen?","Nein. Die früher empfohlenen strengen Einschränkungen gelten nicht mehr. Schrittweise gesteigerte Bewegung und normale Nutzung sind förderlich. Zu vermeiden sind plötzliche Überlastung und Verletzungen."),
  ("Darf an diesem Arm Blutdruck gemessen und Blut abgenommen werden?","Die traditionelle Empfehlung lautet, den Arm der operierten Seite zu meiden. Die Evidenzlage ist umstritten, doch wenn eine Wahl besteht, ist die Nutzung des anderen Arms eine sinnvolle Vorsichtsmaßnahme.")],
 "related":["lenfodem","meme-rek","lenfodem-belirtileri","bacakta-lenfodem"],
 "ctah":"Beurteilung des Armlymphödems",
 "ctap":"Teilen Sie uns den Umfang Ihrer Brustkrebsbehandlung mit (Art der Operation, Lymphknotendissektion, Bestrahlung), wann die Schwellung begann und Ihre Armumfangmessungen; senden Sie nach Möglichkeit ein Foto beider Arme."},

"lenfodem-belirtileri": {
 "crumb":"Lymphödem-Symptome",
 "title":"Lymphödem-Symptome: Frühe Zeichen und Selbstkontrolle | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lymphödem-Symptome und frühe Zeichen",
 "desc":"Welche Symptome hat ein Lymphödem? Frühe Befunde, Stemmer-Zeichen, Methoden zur Selbstkontrolle und wann ärztlicher Rat einzuholen ist.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Lymphödem-Symptome und frühe Zeichen",
 "lead":"Beim Lymphödem ist Zeit das Wertvollste. Wer erfasst wird, solange die Lymphbahnen noch arbeiten, hat viele Behandlungsoptionen; nach eingetretener Gewebeverhärtung werden sie knapp. Diese Seite erklärt, was Sie wann ernst nehmen sollten.",
 "watopic":"Lymphödem-Symptome",
 "about":"Lymphödem",
 "aboutType":"MedicalCondition",
 "card":"Lymphödem-Symptome","cardsub":"Frühe Befunde und Selbstkontrolle",
 "procedure":{"name":"Diagnostische Beurteilung des Lymphödems",
   "how":"Umfangmessungen, Stemmer-Zeichen, Hautqualität und Infektionsanamnese werden gemeinsam beurteilt; bei Bedarf erfolgt ein Lymphmapping mittels ICG-Lymphographie oder Lymphszintigraphie.",
   "prep":"Dauer der Schwellung, Operations- und Bestrahlungsanamnese.",
   "follow":"Behandlungsplan nach Stadium und regelmäßige Messkontrollen.",
   "body":"Lymphsystem"},
 "keyfacts":[("Erstes Zeichen","Meist ein Gefühl von Schwere und Spannung"),
             ("Stemmer","Positiv, wenn die Haut nicht abhebbar ist"),
             ("Warnung","Schwellung über 3 Monate sollte abgeklärt werden"),
             ("Entscheidend","Im Stadium 0 sind die Optionen am breitesten")],
 "authority":"Die Früherkennung des Lymphödems bestimmt den Behandlungserfolg unmittelbar. Doz. Dr. Acartürk ist Mikrochirurg, nimmt an den Arbeiten der europäischen lymphatischen Mikrochirurgie-Gruppe teil und hat auf dem Weltkongress für Lymphologie vorgetragen; mit 300+ mikrochirurgischen Fällen überführt er die Stadieneinteilung in einen Behandlungsplan.",
 "creds":["Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie",
          "Vortrag auf dem Weltkongress für Lymphologie",
          "300+ mikrochirurgische Fälle an der University of Pittsburgh"],
 "sections":[
  {"id":"erken","tag":"Frühe Zeichen","h2":"Die frühesten Symptome: gespürt, bevor sie messbar sind","body":[
   "Das erste Symptom eines Lymphödems ist meist keine sichtbare Schwellung. Die meisten Betroffenen beschreiben eine <strong>Veränderung des Gefühls</strong>, bevor ein messbarer Unterschied entstanden ist.",
   ("ul",["Schwere, Fülle oder Spannung in Arm oder Bein",
          "Ring, Uhr, Armband oder Socke werden eng",
          "Kleidung sitzt nur auf einer Seite eng",
          "Spannung oder Glanz der Haut",
          "Leichtes Gefühl eingeschränkter Gelenkbeweglichkeit"]),
   ("note","Betroffene erklären diese Symptome häufig mit \"ich habe zugenommen\" oder \"ich bin müde\" und schieben sie monatelang auf. Dabei ist gerade dies die für die Behandlung wertvollste Phase. Diese Beschwerden sollten auch dann beurteilt werden, wenn die Messwerte noch normal sind.")]},
  {"id":"yerlesmis","tag":"Etabliertes Stadium","h2":"Befunde des etablierten Lymphödems","body":[
   ("ul",["<strong>Anhaltende Schwellung:</strong> Ödem, das bei Hochlagerung nicht zurückgeht",
          "<strong>Messbarer Unterschied:</strong> Umfangdifferenz gegenüber der Gegenseite",
          "<strong>Dellenbildung:</strong> Im Frühstadium bleibt bei Druck eine Delle; im fortgeschrittenen Stadium nicht, weil das Gewebe verhärtet ist",
          "<strong>Hautveränderungen:</strong> Verdickung, Verhärtung, Orangenhaut",
          "<strong>Wiederkehrende Erysipele:</strong> Schübe mit Fieber, Rötung und Schmerz",
          "<strong>Lymphorrhoe:</strong> Austritt klarer Flüssigkeit aus der Haut",
          "<strong>Funktionsverlust:</strong> Bewegungseinschränkung, Schwierigkeiten im Alltag"]),
   ("note","<strong>Das Ausbleiben der Delle</strong> bedeutet nicht, dass das Ödem zurückgegangen ist — im Gegenteil, es zeigt, dass das Gewebe fibrotisch verhärtet ist, und weist auf ein fortgeschritteneres Stadium hin. Diese Unterscheidung ändert den Behandlungsplan unmittelbar.")]},
  {"id":"kontrol","tag":"Selbstkontrolle","h2":"Selbstkontrolle: worauf sollten Sie achten?","body":[
   ("steps",[
    ("1 — STEMMER-ZEICHEN","Versuchen Sie, die Haut über Ihrer zweiten Zehe (oder Ihrem zweiten Finger) mit Daumen und Zeigefinger abzuheben. Ist die Haut verdickt und nicht abhebbar, ist das Zeichen positiv."),
    ("2 — UMFANGMESSUNG","Messen Sie beide Gliedmaßen mit einem Maßband an denselben Stellen. Wählen Sie feste Bezugspunkte (etwa 10 cm oberhalb des Ellenbogens). Der Unterschied zwischen beiden Seiten sollte verfolgt werden."),
    ("3 — DELLENTEST","Drücken Sie 10 Sekunden mit dem Finger auf die geschwollene Stelle. Eine verbleibende Delle zeigt ein Ödem an; ihr Ausbleiben kann auf eine Gewebeverhärtung im fortgeschrittenen Stadium hindeuten."),
    ("4 — SYMMETRIE UND FUSS/HAND","Ist die Schwellung einseitig? Reicht sie bis Fußrücken und Zehen? Diese Befunde sprechen für ein Lymphödem."),
    ("5 — FOTODOKUMENTATION","Fotografieren Sie beide Gliedmaßen monatlich gemeinsam, im selben Winkel und Licht. Das ist der praktischste Weg, langsame Veränderungen zu bemerken.")]),
   ("note","Diese Kontrollen ersetzen keine ärztliche Untersuchung; sie sollen Ihnen helfen, Veränderungen zu bemerken und rechtzeitig vorstellig zu werden.")]},
  {"id":"nezaman","tag":"Wann zum Arzt","h2":"Wann sollten Sie ärztlichen Rat einholen?","body":[
   ("ul",["Wenn die Schwellung <strong>länger als 3 Monate</strong> anhält",
          "Bei neu aufgetretener Schwellung nach einer Krebsbehandlung, insbesondere nach Lymphknotendissektion oder Bestrahlung",
          "Wenn Sie einen wachsenden Umfangunterschied zwischen beiden Gliedmaßen bemerken",
          "Wenn das Stemmer-Zeichen positiv ist",
          "Wenn Sie einen Erysipel-Schub hatten"]),
   ("note","<strong>Situationen, die eine dringliche Abklärung erfordern:</strong> Eine plötzliche, schmerzhafte, einseitige Schwellung kann auf eine tiefe Beinvenenthrombose hindeuten. Fieber, ausgedehnte Rötung und Überwärmung kündigen ein Erysipel an und erfordern unverzüglich Antibiotika. Warten Sie in beiden Fällen nicht ab.")]},
  {"id":"karisan","tag":"Verwechselte Zustände","h2":"Mit dem Lymphödem verwechselte Zustände","body":[
   ("table",["Zustand","Unterscheidendes Merkmal"],[
     ["Lipödem","Symmetrisch; endet am Knöchel (Manschettenzeichen); druckschmerzhaft; Stemmer negativ"],
     ["Venöse Insuffizienz","Geht bei Hochlagerung rasch zurück; Krampfadern und Hautverfärbung begleiten"],
     ["Kardiales/renales/hepatisches Ödem","Beidseits symmetrisch; deutliche Dellenbildung; systemische Grunderkrankung"],
     ["Tiefe Beinvenenthrombose","Plötzlicher Beginn, Schmerz, Überwärmung — dringlich"],
     ["Adipositas","Generalisiert; Stemmer negativ; Verteilung proportional"]]),
   "Die Abgrenzung zwischen Lymphödem und Lipödem ist besonders wichtig, weil sich die Behandlungen unterscheiden und beide gemeinsam vorliegen können. Einzelheiten auf unserer <a href=\"../lipodem-belirtileri.html\">Seite zu Lipödem-Symptomen</a>."]}],
 "faqs":[
  ("Was ist das erste Symptom eines Lymphödems?","Meist keine sichtbare Schwellung, sondern eine Veränderung des Gefühls: Schwere, Fülle oder Spannung im betroffenen Glied. Auch ein enger werdender Ring, eine enge Uhr oder Socke ist ein frühes Warnzeichen."),
  ("Was ist das Stemmer-Zeichen und wie prüft man es?","Sie versuchen, die Haut über der zweiten Zehe oder dem zweiten Finger abzuheben. Ist die Haut verdickt und nicht abhebbar, ist das Zeichen positiv und spricht für ein Lymphödem. Es ist einfach, aber wertvoll; allein sichert es die Diagnose nicht."),
  ("Wenn die Schwellung keine Delle hinterlässt, ist es dann kein Lymphödem?","Im Gegenteil. Im Frühstadium bleibt eine Delle; im fortgeschrittenen Stadium ist das Gewebe fibrotisch verhärtet und es bleibt keine Delle. Das Ausbleiben kann auf ein fortgeschritteneres Stadium hindeuten."),
  ("Verursacht ein Lymphödem Schmerzen?","Beim Lymphödem stehen Schwere und Spannung im Vordergrund; ausgeprägte Schmerzen sind untypisch. Druckschmerz spricht eher für ein Lipödem. Plötzlicher starker Schmerz erfordert eine dringliche Abklärung auf Infektion oder Gefäßverschluss."),
  ("Welcher Unterschied in Zentimetern ist bedeutsam?","Ein Umfangunterschied von etwa 2 cm oder mehr zwischen beiden Gliedmaßen gilt als klinisch bedeutsam. Auch kleinere Unterschiede erfordern jedoch eine Verlaufskontrolle — besonders bei Risikopatienten zählt die Richtung der Veränderung mehr als der Absolutwert."),
  ("Wenn die Schwellung abends zunimmt und morgens zurückgeht, ist es ein Lymphödem?","Diese Schwankung ist typisch für ein frühes Lymphödem, tritt aber auch bei venöser Insuffizienz auf. Zur Abgrenzung werden Fuß- und Zehenbeteiligung, Stemmer-Zeichen und Symmetrie beurteilt.")],
 "related":["lenfodem","lenfodem-evreleri","lenfodem-neden-olur","bacakta-lenfodem"],
 "ctah":"Lassen Sie uns Ihre Symptome beurteilen",
 "ctap":"Teilen Sie uns mit, seit wann die Schwellung besteht, welches Glied betroffen ist und ob sie ein- oder beidseitig ist, sowie welche Operationen oder Bestrahlungen erfolgt sind; senden Sie nach Möglichkeit ein Foto beider Gliedmaßen."},

"lenfodem-neden-olur": {
 "crumb":"Ursachen des Lymphödems",
 "title":"Warum entsteht ein Lymphödem? Ursachen und Risikofaktoren | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Warum entsteht ein Lymphödem? Ursachen und Risikofaktoren",
 "desc":"Warum entsteht ein Lymphödem? Primäre und sekundäre Ursachen, Risiko nach Krebstherapie, Infektionen und genetische Faktoren — und wie sich das Risiko senken lässt.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Warum entsteht ein Lymphödem?",
 "lead":"Ein Lymphödem entsteht, wenn sich Lymphflüssigkeit im Gewebe ansammelt. Die eigentliche Frage lautet jedoch: Wodurch kam es zu dieser Ansammlung? Die Ursache richtig zu verstehen bestimmt unmittelbar sowohl den Behandlungsplan als auch die Strategie zur Risikosenkung.",
 "watopic":"Ursachen des Lymphödems",
 "about":"Lymphödem",
 "aboutType":"MedicalCondition",
 "card":"Ursachen des Lymphödems","cardsub":"Primäre und sekundäre Ursachen, Risikofaktoren",
 "procedure":{"name":"Ätiologische Beurteilung des Lymphödems",
   "how":"Beginn der Schwellung, frühere Operationen und Bestrahlungen, Infektions- und Familienanamnese werden gemeinsam beurteilt; bei Bedarf wird die lymphatische Struktur bildgebend untersucht.",
   "prep":"Ausführliche Anamnese und vorhandene medizinische Unterlagen.",
   "follow":"Ursachengerichteter Behandlungsplan und Empfehlungen zur Risikosenkung.",
   "body":"Lymphsystem"},
 "keyfacts":[("Häufigste Ursache","Nach Krebstherapie (sekundär)"),
             ("Primär","Angeborene Unterentwicklung des Lymphsystems"),
             ("Auslöser","Infektionen erhöhen den Schaden mit jedem Schub"),
             ("Beeinflussbar","Gewicht, Infektionen, Hautpflege")],
 "authority":"Die Ursache eines Lymphödems richtig zu bestimmen verhindert unnötige Behandlungen und ermöglicht zugleich die richtige Operation. Als Chirurg, der sowohl Rekonstruktionen nach onkologischen Eingriffen als auch lymphatische Mikrochirurgie durchführt, beurteilt Doz. Dr. Acartürk diese beiden Gebiete gemeinsam.",
 "creds":["Ehem. Direktor für Kopf-Hals-Rekonstruktion, University of Pittsburgh",
          "300+ mikrochirurgische Eingriffe · 97% Lappenerfolgsrate",
          "Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie"],
 "sections":[
  {"id":"mekanizma","tag":"Mechanismus","h2":"Wie entsteht ein Lymphödem?","body":[
   "Das Lymphsystem ist ein feines Kanalnetz, das die zwischen den Geweben anfallende eiweißreiche Flüssigkeit sammelt und in den Kreislauf zurückführt. Anders als das vom Herzen angetriebene Gefäßsystem hat es keine zentrale Pumpe; es arbeitet über Muskelbewegung und Kontraktionen der Kanalwand.",
   "Ist dieses Netz blockiert oder wird seine Transportkapazität überschritten, sammelt sich Flüssigkeit im Gewebe. Anfangs besteht diese Ansammlung nur aus Flüssigkeit und ist reversibel. Mit der Zeit entstehen <strong>Fetteinlagerung und Fibrose</strong>, das Gewebe verhärtet und das Bild wird dauerhaft.",
   ("note","Der entscheidende Punkt: Das Lymphödem ist kein statischer Zustand, sondern ein fortschreitender Prozess. Ein früher Eingriff, solange die Bahnen noch arbeiten, ist weit wirksamer als einer nach eingetretener Gewebeverhärtung.")]},
  {"id":"sekonder","tag":"Sekundär","h2":"Ursachen des sekundären Lymphödems (am häufigsten)","body":[
   "Die große Mehrheit der Fälle ist sekundär — das Lymphsystem war also zunächst normal und wurde später geschädigt.",
   ("h3","Krebstherapien"),
   ("ul",["<strong>Lymphknotendissektion:</strong> Entfernung von Lymphknoten bei Brust-, gynäkologischen und urologischen Krebserkrankungen sowie beim Melanom",
          "<strong>Bestrahlung:</strong> vernarbt die Lymphbahnen und senkt die Transportkapazität",
          "<strong>Der Tumor selbst:</strong> kann Lymphwege direkt blockieren"]),
   ("h3","Infektionen"),
   ("ul",["<strong>Wiederkehrende Erysipele:</strong> Jeder Schub hinterlässt bleibende Schäden an den Lymphbahnen und erhöht das Risiko des nächsten Schubs — ein Teufelskreis",
          "<strong>Filariose:</strong> die weltweit häufigste parasitäre Ursache des Lymphödems; in der Türkei kommt sie nicht vor"]),
   ("h3","Trauma und Operationen"),
   ("ul",["Ausgedehnte Weichteilverletzungen und Verbrennungen",
          "Große orthopädische und gefäßchirurgische Eingriffe",
          "Ausgedehntes Narbengewebe"]),
   ("h3","Weitere"),
   ("ul",["Chronische venöse Insuffizienz — erhöht mit der Zeit die lymphatische Last (Phlebolymphödem)",
          "Adipositas — ein hoher Body-Mass-Index belastet die lymphatische Transportkapazität",
          "Länger dauernde Immobilität"])]},
  {"id":"primer","tag":"Primär","h2":"Primäres Lymphödem: angeborene Ursachen","body":[
   "Das primäre Lymphödem beruht auf einer angeborenen Unterentwicklung des Lymphsystems. Es ist weit seltener als das sekundäre und wird nach dem Alter beim Auftreten benannt:",
   ("table",["Typ","Auftreten","Anmerkung"],[
     ["Kongenitales Lymphödem","Bei Geburt oder in den ersten 2 Jahren","Die Milroy-Krankheit gehört zu dieser Gruppe"],
     ["Lymphoedema praecox","Zwischen Pubertät und 35 Jahren","Häufigste primäre Form; bei Frauen verbreiteter"],
     ["Lymphoedema tarda","Nach dem 35. Lebensjahr","Selten; sekundäre Ursachen sind zuvor auszuschließen"]]),
   ("note","Bei einem nach dem 35. Lebensjahr beginnenden Lymphödem ohne erkennbare Ursache muss vor der Diagnose eines primären Lymphödems eine zugrunde liegende Raumforderung oder Abflussbehinderung abgeklärt werden. Dieser Schritt darf nicht übersprungen werden.")]},
  {"id":"risk","tag":"Risikofaktoren","h2":"Risikoerhöhende und beeinflussbare Faktoren","body":[
   "Manche Risikofaktoren lassen sich nicht ändern (etwa der Umfang einer vorangegangenen Operation), andere liegen unmittelbar in Ihrer Hand.",
   ("table",["Faktor","Beeinflussbar?"],[
     ["Umfang der Lymphknotendissektion","Nein — das Risiko lässt sich jedoch mit vorbeugender Chirurgie (LYMPHA) senken"],
     ["Bestrahlungsanamnese","Nein"],
     ["Genetische Veranlagung","Nein"],
     ["Body-Mass-Index","Ja — Gewichtskontrolle senkt die lymphatische Last unmittelbar"],
     ["Wiederkehrende Infektionen","Ja — durch Hautpflege und frühzeitige Antibiotika"],
     ["Hautintegrität","Ja — Pflege, Schutz vor Verletzungen, Behandlung von Fußpilz"],
     ["Bewegungsmangel","Ja — regelmäßige Bewegung unterstützt den Lymphfluss"]]),
   ("note","Der Infektionsschutz ist der wichtigste der beeinflussbaren Faktoren. Jeder Erysipel-Schub verringert die lymphatische Reserve weiter; Schübe zu verhindern ist der wirksamste Weg, das Fortschreiten der Erkrankung zu verlangsamen.")]}],
 "faqs":[
  ("Ist ein Lymphödem erblich?","Beim primären Lymphödem spielt eine genetische Veranlagung eine Rolle und eine Familienanamnese kann vorliegen. Die Mehrzahl der Fälle ist jedoch sekundär — sie entsteht nach Krebstherapie, Infektion oder Trauma und ist nicht erblich."),
  ("Ist ein Lymphödem Krebs?","Nein. Das Lymphödem ist eine Zirkulationsstörung durch Ansammlung von Lymphflüssigkeit. Das Lymphom ist eine Krebserkrankung des Lymphsystems und wird von der Hämatologie-Onkologie behandelt. Außer der Namensähnlichkeit besteht kein Zusammenhang."),
  ("Folgt jeder Lymphknotenoperation ein Lymphödem?","Nein. Das Risiko richtet sich nach der Zahl der entfernten Knoten und danach, ob eine Bestrahlung hinzukam. Nach einer Sentinel-Lymphknotenbiopsie ist es gering, bei ausgedehnter Dissektion mit Bestrahlung steigt es deutlich."),
  ("Bessert Gewichtsabnahme ein Lymphödem?","Sie behebt es nicht allein, trägt aber deutlich bei. Ein hoher Body-Mass-Index belastet die lymphatische Transportkapazität; Gewichtskontrolle verringert die bestehende Schwellung und verbessert die Behandlungsergebnisse."),
  ("Warum sind Erysipele so bedeutsam?","Jeder Schub hinterlässt bleibende Schäden an den Lymphbahnen und lässt das Stadium fortschreiten. Ein durchgemachter Schub erhöht zudem das Risiko des nächsten. Diesen Kreis zu durchbrechen ist untrennbarer Teil der Behandlung."),
  ("Verursachen Flugreisen ein Lymphödem?","Es gibt keinen starken Beleg dafür, dass ein Flug allein ein Lymphödem auslöst. Bei Risikopersonen sind Kompressionsversorgung und häufige Bewegung auf Langstreckenflügen jedoch eine sinnvolle Vorsichtsmaßnahme.")],
 "related":["lenfodem","lenfodem-belirtileri","lenfodem-evreleri","kolda-lenfodem"],
 "ctah":"Lassen Sie uns die Ursache gemeinsam beurteilen",
 "ctap":"Teilen Sie uns mit, wann die Schwellung begann, welche Operationen und Bestrahlungen erfolgt sind, Ihre Infektionsanamnese und ob in Ihrer Familie Ähnliches vorkommt."},

"lenfodem-hangi-doktor": {
 "crumb":"Welche Fachrichtung behandelt ein Lymphödem",
 "title":"Welche Fachrichtung behandelt ein Lymphödem? | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Welche Fachrichtung behandelt ein Lymphödem?",
 "desc":"An welche Abteilung sollten Sie sich beim Lymphödem wenden? Die Rollen von plastischer Chirurgie, physikalischer Medizin und weiteren Fächern, wann welcher Arzt, und wie Sie sich auf den Termin vorbereiten.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Welche Fachrichtung behandelt ein Lymphödem?",
 "lead":"Das Lymphödem ist nicht die Erkrankung eines einzigen Fachs. Betroffene wandern deshalb häufig zwischen Abteilungen und erreichen die richtige Adresse erst Monate später. Diese Seite erklärt klar, an wen Sie sich wann wenden sollten.",
 "watopic":"die richtige Fachrichtung beim Lymphödem",
 "about":"Lymphödem",
 "aboutType":"MedicalCondition",
 "card":"Welche Fachrichtung?","cardsub":"Die richtige Zuordnung beim Lymphödem",
 "procedure":{"name":"Chirurgische Beurteilung beim Lymphödem",
   "how":"Die plastische und rekonstruktive Chirurgie setzt mit lymphatischer Mikrochirurgie unmittelbar an der Blockade an: LVA, vaskularisierter Lymphknotentransfer und Reduktionschirurgie.",
   "prep":"Stadieneinteilung, Bildgebung und Durchsicht früherer Behandlungen.",
   "follow":"Langfristige, gemeinsam mit der Physiotherapie geführte Nachsorge.",
   "body":"Lymphsystem"},
 "keyfacts":[("Operative Behandlung","Plastische und Rekonstruktive Chirurgie"),
             ("Konservative Behandlung","Physikalische Medizin und Rehabilitation"),
             ("Ideal","Beide Fächer arbeiten zusammen"),
             ("Warnung","Die zugrunde liegende Ursache ist zuerst abzuklären")],
 "authority":"Die Lymphödem-Mikrochirurgie ist ein eigenes Gebiet innerhalb der plastischen Chirurgie — nicht jeder plastische Chirurg führt diese Eingriffe durch. Doz. Dr. Acartürk hat an der University of Pittsburgh 300+ mikrochirurgische Fälle durchgeführt, nimmt an den Arbeiten der europäischen lymphatischen Mikrochirurgie-Gruppe teil und hat auf dem Weltkongress für Lymphologie vorgetragen.",
 "creds":["Ehem. Direktor für Kopf-Hals-Rekonstruktion, University of Pittsburgh — 300+ mikrochirurgische Fälle",
          "Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie",
          "Vortrag auf dem Weltkongress für Lymphologie"],
 "sections":[
  {"id":"kisa","tag":"Kurze Antwort","h2":"Die kurze Antwort","body":[
   "Beim Lymphödem sind zwei Hauptfächer beteiligt, und beide werden gebraucht:",
   ("ul",["<strong>Plastische und Rekonstruktive Chirurgie</strong> — führt die operative Behandlung durch. Lymphatische Mikrochirurgie (LVA), vaskularisierter Lymphknotentransfer und Reduktionschirurgie gehören zu diesem Fach.",
          "<strong>Physikalische Medizin und Rehabilitation</strong> — führt die konservative Behandlung durch. Komplexe Entstauungstherapie, manuelle Lymphdrainage, Bandagierung und die Planung der Kompressionsversorgung erfolgen hier."]),
   ("note","Diese beiden Fächer sind keine Alternativen, sondern ergänzen einander. Die Physiotherapie wird nach der Operation fortgeführt; die Chirurgie kommt bei Patienten zum Zug, deren Zustand physiotherapeutisch nicht zu kontrollieren ist. Die besten Ergebnisse erzielen Zentren, in denen beide zusammenarbeiten.")]},
  {"id":"hangi-durumda","tag":"Zuordnung","h2":"Wann zu wem?","body":[
   ("table",["Ihre Situation","Anlaufstelle"],[
     ["Neue Schwellung, keine Diagnose","Zunächst ein Arzt, der die Ursache abklärt: Hausarzt oder der zuständige Facharzt"],
     ["Arm-/Beinschwellung nach Krebstherapie","Plastische Chirurgie + physikalische Medizin (gemeinsam)"],
     ["Diagnose gestellt, Physiotherapie reicht nicht","Plastische und Rekonstruktive Chirurgie — Prüfung der Operationsfähigkeit"],
     ["Frühstadium, Interesse an operativen Optionen","Plastische und Rekonstruktive Chirurgie (lymphatische Mikrochirurgie)"],
     ["Wiederkehrende Erysipele","Infektiologie + das Lymphödem-Team"],
     ["Plötzliche schmerzhafte einseitige Schwellung","Notaufnahme — ein Gefäßverschluss ist auszuschließen"]]),
   ("note","Eine plötzliche, schmerzhafte, einseitige Schwellung wirft die Möglichkeit einer tiefen Beinvenenthrombose auf und ist ein Notfall. Die Lymphödem-Beurteilung erfolgt, nachdem diese Möglichkeit ausgeschlossen wurde.")]},
  {"id":"branslar","tag":"Fachrichtungen","h2":"Die Rolle weiterer Fachrichtungen","body":[
   ("ul",["<strong>Onkologie:</strong> Betreuung und Zuweisung während laufender Krebstherapie",
          "<strong>Allgemeinchirurgie / Gynäkologie / Urologie:</strong> Verlaufskontrolle und frühe Zuweisung nach Lymphknotendissektion",
          "<strong>Radiologie:</strong> Lymphmapping mittels Lymphszintigraphie, MR-Lymphangiographie und ICG-Lymphographie",
          "<strong>Kardiologie / Nephrologie:</strong> Ausschluss systemischer Ödemursachen",
          "<strong>Gefäßchirurgie:</strong> Abgrenzung venöser Insuffizienz und tiefer Beinvenenthrombose",
          "<strong>Infektiologie:</strong> Management wiederkehrender Erysipele",
          "<strong>Dermatologie:</strong> Hautkomplikationen und Pilzinfektionen"])]},
  {"id":"hazirlik","tag":"Vorbereitung","h2":"Wie bereiten Sie sich auf den Termin vor?","body":[
   "Zur richtigen Abteilung zu gehen ist wichtig — ebenso, vorbereitet zu erscheinen. Was Sie mitbringen sollten:",
   ("ul",["<strong>Operationsberichte:</strong> insbesondere ob eine Lymphknotendissektion erfolgte und wie viele Knoten entfernt wurden",
          "<strong>Angaben zur Bestrahlung:</strong> welche Region, wie viele Sitzungen",
          "<strong>Bildgebungsbefunde:</strong> falls bereits eine Lymphszintigraphie oder MRT erfolgt ist",
          "<strong>Umfangmessungen:</strong> frühere Messprotokolle, sofern vorhanden",
          "<strong>Fotos:</strong> die die Veränderung der Schwellung im Zeitverlauf zeigen",
          "<strong>Infektionsanamnese:</strong> wie viele Erysipel-Schübe, und wann",
          "<strong>Ihre Medikamente und Angaben zur Kompressionsversorgung</strong>"]),
   ("note","<strong>Wann die Schwellung begann</strong> und <strong>wie lange sie besteht</strong>, gehören zu den entscheidendsten Angaben bei der Frage der Operationsfähigkeit. Diese beiden Fragen klar beantworten zu können, erhöht den Wert Ihres Termins unmittelbar.")]},
  {"id":"cerrah-secimi","tag":"Wahl des Chirurgen","h2":"Worauf bei der Wahl eines Lymphödem-Chirurgen achten?","body":[
   "Die lymphatische Mikrochirurgie ist das technisch anspruchsvollste Teilgebiet der plastischen Chirurgie: Es wird mit Bahnen von 0,3–0,8 mm Durchmesser gearbeitet. Nicht jeder plastische Chirurg führt diese Eingriffe durch. Angemessene Fragen:",
   ("ul",["Wie viel mikrochirurgische Erfahrung? Wie viele Fälle?",
          "Kann im Zentrum eine ICG-Lymphographie oder Lymphszintigraphie durchgeführt werden?",
          "Wird gemeinsam mit einem Physiotherapie-Team gearbeitet?",
          "Wird klar erklärt, welche Operation in welchem Stadium empfohlen wird?",
          "Werden realistische Erwartungen besprochen — oder wird vollständige Heilung versprochen?"]),
   ("note","Ein Versprechen vollständiger Heilung ist beim Lymphödem ein Warnzeichen. Eine ehrliche Beurteilung spricht in messbaren Zielen: Volumenreduktion, seltenere Infektionen und geringere Abhängigkeit von der Kompressionsversorgung.")]}],
 "faqs":[
  ("Welche Fachrichtung behandelt ein Lymphödem?","Für die operative Behandlung die Plastische und Rekonstruktive Chirurgie, für die konservative Behandlung die Physikalische Medizin und Rehabilitation. Diese beiden Fächer ergänzen einander, sie sind keine Alternativen."),
  ("Sollte ich zuerst zur Physiotherapie?","Die Physiotherapie ist die Grundlage der Behandlung und für die meisten Patienten der erste Schritt. Wichtig ist jedoch, im Frühstadium auch die operativen Optionen zu prüfen, denn ein Eingriff, solange die Lymphbahnen arbeiten, ist wirksamer als nach eingetretener Gewebeverhärtung. Idealerweise laufen beide Beurteilungen parallel."),
  ("Führt jeder plastische Chirurg Lymphödemoperationen durch?","Nein. Die lymphatische Mikrochirurgie erfordert eigene Erfahrung; unter dem Mikroskop wird mit Bahnen von 0,3–0,8 mm Durchmesser gearbeitet. Es ist angemessen, nach der mikrochirurgischen Erfahrung des Chirurgen und den bildgebenden Möglichkeiten des Zentrums zu fragen."),
  ("Werden diese Operationen in staatlichen Krankenhäusern durchgeführt?","Lymphatische Mikrochirurgie wird an einigen Universitäts- und Lehrkrankenhäusern durchgeführt. Die Zahl der Zentren ist begrenzt; vor einer Vorstellung zu prüfen, ob ein Zentrum auf diesem Gebiet arbeitet, spart Zeit."),
  ("Welche Untersuchungen werden beim Lymphödem angefordert?","Am häufigsten ICG-Lymphographie und Lymphszintigraphie; in fortgeschrittenen und komplexen Fällen kann die MR-Lymphangiographie bevorzugt werden. Umfangmessungen und klinische Beurteilung erfolgen bei jedem Patienten."),
  ("Ist eine Zweitmeinung sinnvoll?","Ja, besonders bei einer Operationsentscheidung. Beim Lymphödem bestimmen Stadium und Bildgebungsbefunde die Behandlungsoption unmittelbar; die Beurteilung eines anderen Zentrums kann Ihre Entscheidung klären.")],
 "related":["lenfodem","lenfodem-belirtileri","lenfodem-evreleri","lipodem-hangi-doktor"],
 "ctah":"Der erste Schritt zur richtigen Abteilung",
 "ctap":"Teilen Sie uns mit, wann die Schwellung begann, welche Behandlungen erfolgt sind und welche Befunde Ihnen vorliegen; wir bestimmen gemeinsam, welche Beurteilung für Sie geeignet ist."},

"lenfodem-evreleri": {
 "crumb":"Stadien des Lymphödems",
 "title":"Stadien des Lymphödems: ISL-Klassifikation und Behandlung | Doz. Dr. T. Oğuz Acartürk",
 "ogtitle":"Stadien des Lymphödems und ihre Behandlung",
 "desc":"Welche Stadien hat das Lymphödem? Befunde der ISL-Stadien 0, 1, 2 und 3, wie die Stadieneinteilung erfolgt und welche Behandlung in welchem Stadium geeignet ist.",
 "eyebrow":"Mikrochirurgie-Programm",
 "h1":"Stadien des Lymphödems",
 "lead":"Das Stadium ist die wichtigste Einzelinformation, die beim Lymphödem die Behandlungsoption bestimmt. Dieselbe Schwellung erfordert in verschiedenen Stadien eine völlig andere Behandlung. Diese Seite erklärt, was die Stadien bedeuten und was in jedem möglich ist.",
 "watopic":"Stadieneinteilung des Lymphödems",
 "about":"Lymphödem",
 "aboutType":"MedicalCondition",
 "card":"Stadien des Lymphödems","cardsub":"ISL-Klassifikation und Behandlung nach Stadium",
 "procedure":{"name":"Stadieneinteilung des Lymphödems",
   "how":"Nach der Klassifikation der International Society of Lymphology (ISL) werden klinische Befunde, Gewebekonsistenz und Bildgebung gemeinsam beurteilt, um das Stadium zu bestimmen.",
   "prep":"Umfangmessungen, Stemmer-Zeichen, ICG-Lymphographie oder Lymphszintigraphie.",
   "follow":"Stadiengerechter Behandlungsplan und regelmäßige Neubeurteilung.",
   "body":"Lymphsystem"},
 "keyfacts":[("Stadium 0","In der Bildgebung erkennbar, keine Schwellung"),
             ("Stadium 1","Geht bei Hochlagerung teilweise zurück, hinterlässt Dellen"),
             ("Stadium 2","Geht bei Hochlagerung nicht zurück, Gewebe verhärtet"),
             ("Stadium 3","Deutliches Volumen, Hautverdickung")],
 "authority":"Die Stadieneinteilung ist der Rahmen, der die Behandlung bestimmt, reicht allein jedoch nicht aus — sie muss zusammen mit den Bildgebungsbefunden interpretiert werden. Als Mikrochirurg, der an den Arbeiten der europäischen lymphatischen Mikrochirurgie-Gruppe teilnimmt und auf dem Weltkongress für Lymphologie vorgetragen hat, beurteilt Doz. Dr. Acartürk beide Datenquellen gemeinsam.",
 "creds":["Teilnahme an der europäischen Gruppe für lymphatische Mikrochirurgie",
          "Vortrag auf dem Weltkongress für Lymphologie",
          "300+ mikrochirurgische Fälle an der University of Pittsburgh"],
 "sections":[
  {"id":"isl","tag":"ISL-Klassifikation","h2":"Das ISL-Stadiensystem","body":[
   "Die Klassifikation der International Society of Lymphology (ISL) ist der weltweit anerkannte Rahmen. Die Stadien beschreiben den Zustand des Gewebes und seine Reversibilität.",
   ("table",["Stadium","Klinische Befunde","Gewebezustand"],[
     ["Stadium 0 (latent)","Keine sichtbare Schwellung; Betroffene können Schwere verspüren","Transportkapazität vermindert, Gewebe normal"],
     ["Stadium 1","Schwellung nimmt im Tagesverlauf zu, geht bei Hochlagerung teilweise zurück; Dellen bei Druck","Flüssigkeitsansammlung überwiegt, reversibel"],
     ["Stadium 2","Geht bei Hochlagerung nicht zurück; Dellenbildung nimmt ab","Fibrose und Fetteinlagerung haben begonnen"],
     ["Stadium 3 (Elephantiasis)","Deutliche Volumenzunahme, verdickte Haut, warzenartige Veränderungen","Fortgeschrittene Fibrose, dauerhafte Gewebeveränderung"]]),
   ("note","<strong>Stadium 0 ist das wertvollste Stadium.</strong> Es besteht keine sichtbare Schwellung, doch in der Bildgebung zeigt sich eine verminderte Transportkapazität. Bei einem in diesem Stadium erfassten Patienten stehen vorbeugende und schonendste Optionen zur Verfügung. Deshalb ist die regelmäßige Kontrolle bei Risikopatienten so wichtig.")]},
  {"id":"tedavi","tag":"Stadium–Behandlung","h2":"Welche Behandlung in welchem Stadium?","body":[
   "Das Stadium bestimmt unmittelbar, welche operative Option anwendbar ist. Die Grundlogik lautet: <strong>Arbeiten die Lymphbahnen noch, wird der Fluss umgeleitet; arbeiten sie nicht mehr, wird neues Gewebe gebracht oder das Volumen reduziert.</strong>",
   ("table",["Stadium","Vorrangiges Vorgehen"],[
     ["Stadium 0","Verlaufskontrolle, Hautpflege, Risikosenkung; bei ausgewählten Patienten vorbeugende LVA"],
     ["Stadium 1","LVA — die schonendste und wirksamste Option"],
     ["Stadium 2","LVA und/oder vaskularisierter Lymphknotentransfer"],
     ["Stadium 3","Lymphknotentransfer + Reduktionschirurgie (Liposuktion, Exzision)"]]),
   ("note","Diese Tabelle ist ein Rahmen, keine Verordnung. Die endgültige Entscheidung fällt zusammen mit der Frage, ob in der Bildgebung funktionierende Lymphbahnen sichtbar sind, der Dauer der Schwellung, der Infektionsanamnese und dem Allgemeinzustand. Zwei Patienten im selben Stadium können unterschiedliche Operationen empfohlen bekommen.")]},
  {"id":"nasil","tag":"Wie bestimmt","h2":"Wie wird das Stadium bestimmt?","body":[
   "Die Stadieneinteilung erfolgt nicht durch bloßes Betrachten; klinische Untersuchung und Bildgebung werden gemeinsam genutzt.",
   ("h3","Klinische Beurteilung"),
   ("ul",["Umfangmessungen — im Vergleich zur Gegenseite",
          "Dellentest — Flüssigkeit oder Fibrose",
          "Stemmer-Zeichen",
          "Hautqualität und -dicke",
          "Infektionsanamnese und -häufigkeit"]),
   ("h3","Bildgebung"),
   ("ul",["<strong>ICG-Lymphographie:</strong> eine Echtzeitkarte funktionierender Lymphbahnen. Entscheidend für die LVA-Planung.",
          "<strong>Lymphszintigraphie:</strong> Beurteilung des Lymphflusses und der Knotenbeteiligung",
          "<strong>MR-Lymphangiographie:</strong> detaillierte anatomische Darstellung; in fortgeschrittenen und komplexen Fällen"]),
   ("note","Klinisches Stadium und Bildgebungsbefunde decken sich nicht immer. Bei einem klinisch als Stadium 2 erscheinenden Patienten können in der ICG-Untersuchung noch funktionierende Bahnen vorhanden sein — was die LVA in Betracht kommen lässt. Deshalb sollte eine Operationsentscheidung nicht ohne Bildgebung fallen.")]},
  {"id":"ilerleme","tag":"Verlauf","h2":"Übergänge zwischen den Stadien und der Faktor Zeit","body":[
   "Das Lymphödem ist eine fortschreitende Erkrankung, doch die Geschwindigkeit des Fortschreitens ist sehr unterschiedlich. Manche Betroffene bleiben jahrelang im Stadium 1, bei anderen schreitet das Bild rasch fort.",
   ("h3","Beschleunigende Faktoren"),
   ("ul",["Wiederkehrende Erysipele — der stärkste Beschleuniger",
          "Gewichtszunahme",
          "Unregelmäßige Nutzung der Kompressionsversorgung",
          "Ohne Behandlung verstrichene Zeit",
          "Zusätzliche Traumata oder Operationen"]),
   ("h3","Verlangsamende Faktoren"),
   ("ul",["Regelmäßige Nutzung der Kompressionsversorgung",
          "Hautpflege und Infektionsschutz",
          "Gewichtskontrolle",
          "Regelmäßige Bewegung",
          "Frühzeitiger operativer Eingriff"]),
   ("note","Lässt sich ein Stadium zurückführen? Im Frühstadium — solange die Flüssigkeitsansammlung überwiegt — ist unter Behandlung eine deutliche Rückbildung möglich. Nach eingetretener Fibrose ist die Gewebeveränderung dauerhaft; dann ist das Ziel, das Volumen zu senken und das Fortschreiten aufzuhalten.")]}],
 "faqs":[
  ("In wie viele Stadien wird das Lymphödem eingeteilt?","In vier, nach der Klassifikation der International Society of Lymphology (ISL): Stadium 0 (latent), Stadium 1, Stadium 2 und Stadium 3 (Elephantiasis). Die Stadien beschreiben den Zustand des Gewebes und seine Reversibilität."),
  ("Was bedeutet Stadium 0?","Es besteht keine sichtbare Schwellung, doch die lymphatische Transportkapazität ist vermindert und dies zeigt sich in der Bildgebung. Betroffene können Schwere oder Spannung verspüren. Es ist das Stadium mit den breitesten Behandlungsoptionen."),
  ("In welchem Stadium wird operiert?","In den Stadien 1 und 2 steht die LVA im Vordergrund, sofern die Lymphbahnen noch arbeiten. In den Stadien 2–3 werden vaskularisierter Lymphknotentransfer und Reduktionschirurgie geplant. Die Entscheidung fällt zusammen mit den Bildgebungsbefunden."),
  ("Lässt sich ein Stadium zurückführen?","Im Frühstadium, solange die Flüssigkeitsansammlung überwiegt, ist unter Behandlung eine deutliche Rückbildung möglich. Nach eingetretener Fibrose ist die Gewebeveränderung dauerhaft; dann ist das Ziel, das Volumen zu senken und das Fortschreiten aufzuhalten."),
  ("Was geschieht, wenn mein Stadium fortschreitet?","Die Behandlungsoptionen werden knapper. Während im Frühstadium die LVA als schonendstes Verfahren möglich ist, werden im fortgeschrittenen Stadium umfangreichere Eingriffe nötig. Zudem steigen Infektionsrisiko und Funktionsverlust."),
  ("Ist das Stadium weiter fortgeschritten, wenn keine Delle bleibt?","In der Regel ja. Im Frühstadium bleibt bei Druck eine Delle; mit fibrotischer Verhärtung bleibt keine mehr. Das ist ein wichtiger Untersuchungsbefund für ein fortgeschrittenes Bild.")],
 "related":["lenfodem","lenfodem-belirtileri","lenfodem-neden-olur","lenfodem-hangi-doktor"],
 "ctah":"Lassen Sie uns Ihr Stadium gemeinsam bestimmen",
 "ctap":"Teilen Sie uns mit, wie lange die Schwellung besteht, ob sie bei Hochlagerung zurückgeht, Ihre Erysipel-Anamnese und vorhandene Bildgebungsbefunde; senden Sie nach Möglichkeit ein Foto."},
}
