# -*- coding: utf-8 -*-
"""Ingilizce ceviriler — parti 5: kalan rekonstruktif ve estetik sayfalar."""

STEPS = lambda op, days, back: ("steps",[
 ("STEP 1 — FIRST CONTACT","Initial contact via WhatsApp or the form, based on your expectations, medical history and any photographs."),
 ("STEP 2 — EXAMINATION AND PLANNING","Assessment of your anatomy and open discussion of applicable techniques, risks and realistic expectations."),
 ("STEP 3 — PREPARATION","Blood tests, anaesthetic assessment, adjustment of smoking and blood-thinning medication."),
 ("STEP 4 — SURGERY", op),
 ("STEP 5 — FIRST DAYS", days),
 ("STEP 6 — RETURN AND FOLLOW-UP", back)])

T = {
"bas-boyun": {
 "crumb":"Head, Neck and Jaw Reconstruction",
 "title":"Head, Neck and Jaw Reconstruction — Microsurgical Repair | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Head, Neck and Jaw Reconstruction",
 "desc":"Reconstruction of the jaw, oral cavity and neck after cancer surgery using free tissue transfer. Fibula flap, microsurgical technique and restoring speech and swallowing.",
 "eyebrow":"Reconstructive Surgery",
 "h1":"Head, neck and jaw reconstruction",
 "lead":"Tissue loss after removal of head and neck cancers is one of the most demanding areas of reconstruction in the body. Here the aim is not only appearance but the restoration of speech, chewing and swallowing.",
 "watopic":"head and neck reconstruction",
 "about":"Head and neck reconstruction",
 "card":"Head & neck reconstruction","cardsub":"Free tissue transfer to the jaw, oral cavity and neck",
 "procedure":{"name":"Head and Neck Reconstruction with Free Tissue Transfer",
   "how":"Bone, muscle or skin taken with its blood vessels from another part of the body is connected under the microscope to the neck vessels and transferred to the defect.",
   "prep":"Joint planning with the oncology team, vascular mapping and three-dimensional modelling where required.",
   "follow":"Intensive care monitoring, observation of tissue perfusion, speech and swallowing therapy.",
   "body":"Jaw, oral cavity, neck, skull base"},
 "keyfacts":[("Experience","Former Director of Head & Neck Reconstruction, Univ. of Pittsburgh"),
             ("Cases","300+ microsurgical procedures"),("Flap survival","100% (Pittsburgh period)"),
             ("Duration","10–12 hours on average")],
 "authority":"Head and neck reconstruction lies at the centre of Assoc. Prof. Dr. Acarturk's academic career. In 2011 he was appointed <strong>Director of Head & Neck Reconstruction</strong> at the Department of Plastic Surgery, University of Pittsburgh. During that post he performed more than 300 microsurgical head and neck operations, achieving a rate of flap survival not previously reached in that department.",
 "creds":["Former Director of Head & Neck Reconstruction, University of Pittsburgh","300+ microsurgical head and neck cases","Subspecialty in Oral & Maxillofacial Surgery — Turkish Ministry of Health"],
 "sections":[
  {"id":"neden","tag":"Scope","h2":"Why these reconstructions are different","body":[
   "The head and neck contain many functions within a small volume: speech, chewing, swallowing, breathing and facial expression. Removing cancer with safe margins usually leaves a defect involving bone, muscle, mucosa and skin at the same time.",
   "Repairing that loss is markedly harder than microsurgical reconstruction elsewhere in the body. The three-dimensional geometry of the region is complex, the transferred tissue must satisfy both form and function, and surgery often takes 10–12 hours — longer still in cases involving the skull base.",
   ("note","These operations are not the work of a single surgeon. They are planned together with ENT, surgical oncology, radiation oncology, dentistry, and speech and swallowing therapy teams. In centres unable to work across disciplines, the result is inevitably limited.")]},
  {"id":"yontem","tag":"Method","h2":"Tissue transfers used","body":[
   ("h3","Fibula free flap"),
   "The fibula in the lower leg is taken with its vessels and overlying skin paddle. It is shaped and plated to the contour of the jaw and connected to the neck vessels. Because it provides bone of a quality that can carry dental implants, it is the standard for reconstruction of the lower jaw.",
   ("h3","Radial forearm flap"),
   "Its thin, pliable structure makes it the choice for reconstruction of the oral mucosa and tongue, preserving the mobility needed for speech and swallowing.",
   ("h3","Anterolateral thigh flap"),
   "Used for large soft tissue defects. Its thickness can be adjusted and the donor scar is concealed on the thigh.",
   ("h3","Scapula and latissimus dorsi flaps"),
   "Used in complex cases requiring bone and large-volume muscle together.",
   ("ul",["Vessels of the transferred tissue are connected under the microscope at roughly 1–2 mm in diameter",
          "Tissue perfusion is monitored closely for the first 72 hours",
          "Secondary revision and dental rehabilitation are planned where needed"])]},
  {"id":"surec","tag":"Process","h2":"Surgery and recovery","body":[
   ("steps",[
    ("STEP 1 — JOINT PLANNING","The area to be removed and the resulting defect are determined in advance with the oncology team; the donor site is selected."),
    ("STEP 2 — SURGERY","Tumour removal and reconstruction are performed in the same session, with two teams working simultaneously."),
    ("STEP 3 — FIRST 72 HOURS","Regular monitoring of tissue perfusion in intensive care. This period is decisive for the outcome."),
    ("STEP 4 — FIRST 6 WEEKS","Wound healing, nutritional support and the start of speech and swallowing therapy."),
    ("STEP 5 — 3–12 MONTHS","Secondary revisions where needed, dental implants and care of irradiated tissue.")]),
   ("note","Healing is slower and the risk of complications higher in tissue that has received radiotherapy. In such cases, fat tissue and stem-cell assisted treatments may be used as an adjunct to improve tissue quality.")]}],
 "faqs":[
  ("How long do these operations take?","On average 10–12 hours. In complex cases involving the skull base they can exceed 24 hours. The duration depends on the size of the defect and how many teams work simultaneously."),
  ("What happens if the transferred tissue fails?","The risk of flap loss in microsurgery is around 5% worldwide. When recognised early, the tissue can be salvaged by urgent vascular revision, which is why monitoring in the first 72 hours is critical."),
  ("Will my speech and swallowing return to normal?","That is the aim, but the outcome depends on the amount and site of tissue removed. Speech and swallowing therapy is an integral part of the process; regaining function may take months."),
  ("Can I have teeth fitted to my jaw?","Dental implants can be placed in a lower jaw reconstructed with a fibula flap. Timing is determined by bone consolidation and radiotherapy status."),
  ("Will taking bone from my leg affect my walking?","The fibula is not the main weight-bearing bone. Walking function is preserved after its removal; supported walking and physiotherapy are needed in the first weeks.")],
 "ctah":"Assessment and second opinion",
 "ctap":"Send us your current diagnosis, the surgery planned or already performed, your radiotherapy history and any imaging. We will get back to you to coordinate with your oncology team."},

"yuz-felci": {
 "crumb":"Facial Paralysis Surgery",
 "title":"Facial Paralysis Surgery — Dynamic Muscle Transfer and Smile Reconstruction | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Facial Paralysis: Surgical Treatment and Smile Reconstruction",
 "desc":"Surgical options in facial paralysis: nerve transfer, dynamic smile reconstruction with free muscle transfer, eyelid protection and symmetry procedures.",
 "eyebrow":"Reconstructive Surgery",
 "h1":"Facial paralysis surgery and smile reconstruction",
 "lead":"Facial paralysis is not only a problem of appearance. An eye that cannot close threatens sight, an immobile mouth makes speaking and eating difficult, and the inability to smile affects social life deeply. Microsurgery can restore the movement that has been lost.",
 "watopic":"facial paralysis surgery",
 "about":"Facial palsy",
 "card":"Facial paralysis surgery","cardsub":"Dynamic reconstruction with nerve and free muscle transfer",
 "procedure":{"name":"Dynamic Facial Reconstruction with Free Muscle Transfer",
   "how":"A muscle segment taken with its vessels and nerve from the thigh or chest is transferred to the face; its vessels and nerve are connected under the microscope to provide a voluntary smile.",
   "prep":"Determining the duration and type of paralysis and assessing muscle viability with EMG.",
   "follow":"Regular facial rehabilitation to learn to use the new movement.","body":"Face"},
 "keyfacts":[("Decisive factor","Time elapsed since onset"),("Early stage","Nerve repair / transfer"),
             ("Late stage","Free muscle transfer"),("First movement","4–6 months after surgery")],
 "authority":"Dynamic reconstruction in facial paralysis sits where microsurgery meets nerve surgery. Assoc. Prof. Dr. Acarturk was part of the facial paralysis team during his post at the University of Pittsburgh, gaining extensive experience in dynamic reconstruction with microsurgery and free muscle transfer.",
 "creds":["Member of the facial paralysis team at the University of Pittsburgh","Experience in free muscle transfer and nerve transfer","Subspecialty in Oral & Maxillofacial Surgery"],
 "sections":[
  {"id":"neden","tag":"The Basics","h2":"Why does facial paralysis occur?","body":[
   "The facial nerve drives the muscles of facial expression. Loss of its function causes one-sided immobility. The main causes are:",
   ("ul",["<strong>Bell's palsy</strong> — resolves spontaneously in most cases, but a proportion are left with permanent loss",
          "<strong>Tumour surgery</strong> — particularly acoustic neuroma and parotid gland tumours",
          "<strong>Trauma</strong> — facial fractures and lacerations",
          "<strong>Congenital</strong> — Möbius syndrome and other developmental causes",
          "<strong>Infection</strong> — shingles and middle ear infections"]),
   ("note","The most decisive factor in surgical planning is the time elapsed since the paralysis. Without nerve stimulation, the muscles of expression begin to waste irreversibly after roughly 18–24 months. That threshold determines which operation is possible.")]},
  {"id":"secenek","tag":"Surgical Options","h2":"Treatment options","body":[
   ("h3","Early stage — nerve repair and transfer"),
   "If the muscles are still viable, the goal is to bring stimulation to them. A divided nerve can be repaired directly, a nerve graft can be interposed, or a branch of another nerve (the masseteric nerve, the opposite facial nerve) can be directed to the target. Because these methods reactivate your own muscles, they give the most natural result.",
   ("h3","Late stage — free muscle transfer"),
   "If the muscles have wasted, a new muscle is required. A segment of the gracilis muscle is taken from the thigh with its vessels and nerve, transferred to the face and connected microsurgically. Stimulated by the opposite facial nerve or the masseteric nerve, it produces a voluntary smile.",
   ("h3","Static support"),
   "Procedures that do not create movement but preserve symmetry and function: a gold weight in the eyelid, brow suspension, suspension of the corner of the mouth with fascial strips. These may be preferred alone in patients whose general condition is poor.",
   ("note","An eye that cannot close dries the cornea and can lead to permanent loss of sight. Eye protection is therefore the first issue to be addressed, before smile reconstruction.")]},
  {"id":"surec","tag":"Process","h2":"Process and expectations","body":[
   ("steps",[
    ("STEP 1 — ASSESSMENT","The cause, duration and degree of paralysis; measurement of muscle viability with EMG; checking eye health."),
    ("STEP 2 — PLANNING","Which method is appropriate, how many stages are needed and realistic expectations are discussed openly."),
    ("STEP 3 — SURGERY","3–8 hours depending on the method. In free muscle transfer, microsurgical vessel and nerve connections are made."),
    ("STEP 4 — 4–6 MONTHS","The nerve reaches the transferred muscle and the first movements appear. This waiting period is unavoidable."),
    ("STEP 5 — REHABILITATION","Facial physiotherapy teaches conscious use of the new movement. This stage determines the quality of the result.")]),
   "Assoc. Prof. Dr. Acarturk was part of the facial paralysis team during his post at the University of Pittsburgh, gaining extensive experience in dynamic reconstruction through microsurgery and muscle transfer."]}],
 "faqs":[
  ("My paralysis happened years ago — is it too late?","No. Even if the muscles have wasted, a new source of movement can be created with free muscle transfer. Time changes the method, not the availability of an option."),
  ("When will I be able to smile after surgery?","The nerve usually reaches the transferred muscle and the muscle begins to work at 4–6 months. Making the movement natural and voluntary, together with physiotherapy, can take up to a year."),
  ("Will my smile match the other side?","The aim is to approach symmetry as closely as possible. Transfers powered by the opposite facial nerve produce a more spontaneous smile; those powered by the masseteric nerve initially require conscious effort."),
  ("My eye will not close — what should be done first?","Eye protection takes priority. Artificial tears, taping at night and, if necessary, a gold weight in the upper lid protect the cornea. This is addressed before smile reconstruction."),
  ("Is Botox used in facial paralysis?","Yes, but for a different purpose: to balance excessive movement on the healthy side, or to reduce the involuntary contractions (synkinesis) that can appear after paralysis.")],
 "ctah":"Facial paralysis assessment",
 "ctap":"Tell us when the paralysis began, its cause and the treatments applied, and send videos or photographs if you have them."},

"el-cerrahisi": {
 "crumb":"Hand Surgery and Replantation",
 "title":"Hand Surgery and Limb Replantation — Reattaching Amputated Digits | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Hand Surgery and Limb Replantation",
 "desc":"Replantation of amputated fingers and limbs, toe-to-hand transfer, tendon and nerve repair, and secondary reconstruction after hand trauma.",
 "eyebrow":"Reconstructive Surgery",
 "h1":"Hand surgery and limb replantation",
 "lead":"The hand carries more function per square centimetre than any other part of the body. Losing a finger affects not only appearance but grip, work and every detail of daily life. Microsurgery makes it possible to reattach severed limbs and rebuild lost function.",
 "watopic":"hand surgery and replantation",
 "about":"Hand reconstruction",
 "card":"Hand surgery","cardsub":"Replantation, digit transfer and functional reconstruction",
 "procedure":{"name":"Limb Replantation",
   "how":"The bone in the amputated part is fixed, then the artery, vein, nerves and tendons are repaired in turn under the microscope to restore circulation.",
   "prep":"Correct preservation of the amputated part, control of bleeding and transfer to an emergency centre.",
   "follow":"Circulation monitoring, early hand therapy and prolonged rehabilitation.",
   "body":"Hand, fingers, upper limb"},
 "keyfacts":[("Critical window","Up to 12 hours for a finger (cooled)"),
             ("First aid","Part in clean gauze, in a bag on iced water"),
             ("Technique","Microsurgical vessel and nerve repair"),("Rehabilitation","Determines the outcome")],
 "authority":"Hand surgery and replantation have been among Assoc. Prof. Dr. Acarturk's areas of intensive work since his residency. He gained comprehensive experience in hand surgery, limb amputation and complex injuries at the University of Pittsburgh, and performs toe-to-hand transfer and brachial plexus surgery on volunteer missions in Vietnam.",
 "creds":["Hand surgery and replantation practice at the University of Pittsburgh","Toe-to-hand transfer on volunteer missions in Vietnam","Three years of general and vascular surgery training"],
 "sections":[
  {"id":"acil","tag":"Emergency","h2":"What to do first in a limb amputation","body":[
   "The success of replantation depends directly on what is done in the first hours. If the amputated part is preserved correctly, the window can extend to 12 hours at finger level in cooled tissue; for amputations above the wrist, which contain muscle, it is under 6 hours.",
   ("h3","How to preserve the amputated part"),
   ("ul",["Wrap the part in clean, slightly moist gauze",
          "Place it in a waterproof bag and seal it",
          "Put the bag into a container of iced water",
          "<strong>Do not let the part touch ice or water directly</strong> — the tissue will freeze or swell",
          "Control bleeding with firm pressure using a clean cloth; do not apply a tourniquet"]),
   ("note","This page is not a substitute for emergency medical care. In a limb amputation, call emergency services immediately and ask to be directed to a centre able to perform replantation. Time is the most decisive factor.")]},
  {"id":"kapsam","tag":"Scope","h2":"Procedures performed","body":[
   ("h3","Replantation"),
   "Reattachment of an amputated finger or limb. The bone is fixed first, then the artery, vein, nerves and tendons are repaired under the microscope. Amputations of the thumb and of multiple fingers are given priority.",
   ("h3","Toe-to-hand transfer"),
   "Where a finger cannot be salvaged or is congenitally absent, a toe is transferred to the hand with its vessels and nerves. It restores grip function particularly in thumb loss, and is among the procedures Assoc. Prof. Dr. Acarturk performs frequently on volunteer missions in Vietnam.",
   ("h3","Tendon and nerve repair"),
   "Microsurgical repair of tendons and nerves in lacerating injuries. Where nerve loss is extensive, a nerve graft is interposed.",
   ("h3","Secondary reconstruction"),
   "Planned procedures for limitations remaining after initial treatment: tendon transfers, release of contractures, soft tissue reconstruction and joint corrections."]},
  {"id":"rehab","tag":"Rehabilitation","h2":"The decisive role of rehabilitation","body":[
   "In hand surgery, the operation is only part of the result. Repaired tendons adhere if left immobile, joints stiffen and function does not return even if the nerve recovers. Hand therapy therefore begins within days of surgery and continues for months.",
   ("ul",["Protected motion exercises in the early period",
          "Oedema control and scar management",
          "Sensory re-education — the brain relearning as the nerve recovers",
          "Gradual building of grip strength"]),
   ("note","A replanted finger surviving does not mean function has returned. The true measure of success is whether the hand becomes usable again in daily life — and that depends on rehabilitation as much as on surgery.")]}],
 "faqs":[
  ("Within how many hours can an amputated finger be reattached?","With correct cold-chain preservation, the window can extend to 12 hours for finger-level amputations. For amputations above the wrist containing muscle it is under 6 hours, as muscle is far more sensitive to ischaemia."),
  ("Can every amputated part be reattached?","No. Replantation may not be appropriate in crush injuries, amputations at multiple levels and where the tissue is heavily contaminated. The patient's general condition and associated injuries also influence the decision."),
  ("Will the reattached finger work as before?","A full return to previous function is rare. The goal is a finger that contributes to grip, has partial sensation and is pain-free. The outcome depends on the level of amputation and on rehabilitation."),
  ("Will taking a toe affect my walking?","Removal of the second toe does not meaningfully affect walking. Supported walking is needed in the first weeks, after which normal activity resumes."),
  ("When will sensation return after nerve repair?","A nerve advances roughly 1 mm per day. Reaching the fingertip from the repair site can take months; the quality of sensation depends on age and the type of injury.")],
 "ctah":"Hand surgery assessment",
 "ctap":"Describe the injury you sustained, the treatments applied and the limitations that remain; send photographs and imaging reports if you have them."},

"yanik": {
 "crumb":"Burn, Trauma and Post-Radiation Reconstruction",
 "title":"Burn, Trauma and Post-Radiotherapy Tissue Reconstruction | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Burn, Trauma and Post-Radiation Reconstruction",
 "desc":"Scar and contracture surgery after burns, reconstruction of tissue loss after trauma, and fat and stem-cell assisted treatment of irradiated tissue.",
 "eyebrow":"Reconstructive Surgery",
 "h1":"Burn, trauma and post-radiation reconstruction",
 "lead":"Tissue damage after burns, trauma and radiotherapy does not merely leave a scar; it restricts movement, causes pain and sometimes prevents wounds from closing. In these conditions the aim is not to hide the scar but to restore the function and quality of the tissue.",
 "watopic":"burn and trauma reconstruction",
 "about":"Scar and contracture reconstruction",
 "card":"Burn and trauma reconstruction","cardsub":"Tissue reconstruction in scars, contractures and radiation damage",
 "procedure":{"name":"Scar Contracture Reconstruction",
   "how":"The restricting scar tissue is released and the resulting defect is covered with a skin graft, local tissue flaps or free tissue transfer.",
   "prep":"Waiting for the scar to mature, measuring joint range of motion and preparing for physiotherapy.",
   "follow":"Compression garments, silicone application, splinting and regular physiotherapy.",
   "body":"Any region of the body"},
 "keyfacts":[("Waiting time","6–12 months for scar maturation"),("Priority","Joint movement and function"),
             ("Methods","Graft, local flap, free tissue"),("Radiation damage","Fat and stem-cell assisted treatment")],
 "authority":"Burn and trauma reconstruction is an area Assoc. Prof. Dr. Acarturk worked in during both his military service and his academic career. He gained experience in burn treatment and war injuries during his post at Gülhane Military Medical Academy, and contributed as a researcher at the University of Pittsburgh to work on fat and stem-cell assisted treatment of irradiated tissue.",
 "creds":["Experience in burn treatment and war injuries at GATA","Stem cell and tissue engineering research at the University of Pittsburgh","Three years of trauma and vascular surgery training"],
 "sections":[
  {"id":"skar","tag":"After Burns","h2":"Scar and contracture surgery","body":[
   "Scar tissue formed as a burn heals contracts over time. When that contraction crosses a joint it restricts movement — it can prevent the head from turning at the neck, the arm from lifting at the axilla, or the fingers from opening in the hand. This is called a <strong>contracture</strong> and requires surgery.",
   ("h3","Methods used"),
   ("ul",["<strong>Z-plasty and local flaps:</strong> the direction of the scar line is changed to redistribute tension. Effective in narrow band contractures.",
          "<strong>Skin grafting:</strong> covering large areas with a thin layer of skin taken from an intact site.",
          "<strong>Tissue expansion:</strong> adjacent healthy skin is expanded gradually and moved to replace the scar. Superior for colour match on the scalp and face.",
          "<strong>Free tissue transfer:</strong> tissue transferred with its vessels for deep and extensive losses."]),
   ("note","Timing matters in scar surgery. Operating early on an immature, red and raised scar can worsen the result. Except for contractures that threaten function, 6–12 months of waiting is usual, during which compression garments, silicone and physiotherapy are used.")]},
  {"id":"isin","tag":"Radiation Damage","h2":"Reconstruction of irradiated tissue","body":[
   "Radiotherapy is effective in cancer treatment but leaves permanent changes in the tissue it passes through: small vessels narrow, tissue hardens and blood flow decreases. Wounds close slowly in this tissue, the risk of complications after surgery rises, and ordinary reconstruction techniques fall short.",
   ("h3","Fat tissue and stem-cell assisted treatment"),
   "Cells obtained from the patient's own fat tissue, injected into the irradiated area, can improve tissue quality: the skin softens, elasticity increases and new vessel formation is supported. Assoc. Prof. Dr. Acarturk contributed as a researcher to work in this field at the University of Pittsburgh and uses the technique particularly in cancer, burn and post-radiation cases.",
   ("ul",["Injection is usually performed over several sessions",
          "It can be used to prepare tissue before major reconstruction",
          "Improved comfort is reported in painful, hardened scars"])]},
  {"id":"travma","tag":"Trauma","h2":"Tissue loss after trauma","body":[
   "Tissue loss after road traffic accidents, industrial injuries and gunshot wounds cannot be closed by simple means because bone or tendon is exposed. These cases require the upper rungs of the reconstructive ladder.",
   ("steps",[
    ("STAGE 1 — WOUND PREPARATION","Removal of dead tissue, infection control and negative pressure wound therapy where required."),
    ("STAGE 2 — SKELETAL REPAIR","Fixation of fractures and, where needed, filling of bone defects."),
    ("STAGE 3 — COVERAGE","Providing living, well-perfused cover with a local flap or free tissue transfer."),
    ("STAGE 4 — FUNCTION","Addressing tendon, nerve and joint problems in a planned sequence."),
    ("STAGE 5 — REFINEMENT","Contour corrections, fat grafting and scar revision.")]),
   "Assoc. Prof. Dr. Acarturk received intensive trauma surgery training during his residency and gained experience in burn treatment and war injuries during his post at Gülhane Military Medical Academy."]}],
 "faqs":[
  ("When can I have surgery for my burn scar?","Except for contractures that threaten function, the scar is usually allowed to mature first, which takes 6–12 months. During this period compression garments, silicone and physiotherapy improve scar quality."),
  ("Will the burn scar disappear completely?","No. Scar tissue cannot be eliminated, but its position, direction and quality can be changed. The aim is not to make it invisible but less conspicuous and no longer restricting."),
  ("Can an irradiated area be operated on?","It can, but healing is slow and the risk of complications is high. Reconstruction with your own tissue is preferred in these cases, sometimes preceded by fat grafting to improve tissue quality."),
  ("Does fat grafting really help scars?","Softening, increased elasticity and reduced pain are reported in irradiated and hardened tissue. Results vary between individuals and more than one session is usually needed."),
  ("How are burn contractures handled in children?","As a child grows, scar tissue does not grow at the same rate and contractures can recur. Periodic revisions may therefore be needed throughout the growth period, and planning accounts for this.")],
 "ctah":"Reconstruction assessment",
 "ctap":"Tell us when the injury or treatment occurred, the procedures performed and the limitations you currently have; send photographs if you have them."},

"yag-enjeksiyonu": {
 "crumb":"Fat Grafting",
 "title":"Fat Grafting (Lipofilling) and Stem-Cell Assisted Volume Restoration | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Fat Grafting and Stem-Cell Assisted Volume Restoration",
 "desc":"Facial and body volume restoration with your own fat: what lipofilling is, how long it lasts, stem cell enrichment and its use in irradiated tissue.",
 "eyebrow":"Aesthetic Surgery",
 "h1":"Fat grafting and stem-cell assisted volume restoration",
 "lead":"Your own fat tissue is the body's most compatible filler: it contains no foreign material, causes no allergy, feels natural and is permanent to the extent that it takes. And it does more than add volume — the cells within it also improve skin quality.",
 "watopic":"fat grafting",
 "about":"Autologous fat transfer",
 "card":"Fat grafting","cardsub":"Volume restoration and tissue improvement with your own fat",
 "procedure":{"name":"Autologous Fat Transfer (Lipofilling)",
   "how":"Fat harvested with fine cannulas from the abdomen or thigh is processed and purified, then injected into the target area in small volumes across multiple layers.",
   "prep":"Selection of the donor site and planning of the target volume.",
   "follow":"Avoiding pressure on the injected area, management of swelling.",
   "body":"Face, breast, buttocks, scar regions"},
 "keyfacts":[("Anaesthesia","Sedation or general"),("Durability","Fat that takes is permanent"),
             ("Take rate","Approximately 50–70%"),("Sessions","Repeated where needed")],
 "authority":"Fat tissue and stem cell technologies are at the forefront of Assoc. Prof. Dr. Acarturk's academic work. The University of Pittsburgh is an international centre in this field; he is among the first Turkish plastic surgeons to have worked with these technologies and has also consulted for stem cell companies in the United States.",
 "creds":["Adipose-derived stem cell research at the University of Pittsburgh","Postdoctoral work in tissue engineering and biomaterials at Carnegie Mellon","Consultancy in stem cell technologies in the US"],
 "sections":[
  {"id":"nedir","tag":"The Basics","h2":"What is fat grafting?","body":[
   "Lipofilling is the transfer of fat tissue from one part of the body to another after processing. For the transferred fat to survive it must develop a blood supply in its new site; it is therefore injected in fine layers rather than as a large mass.",
   "Part of the injected fat is reabsorbed in the first months. The portion that takes is permanent and gains and loses weight with the body. The average take rate is 50–70%, which is why a degree of overcorrection is planned and a second session is performed where needed.",
   ("h3","Areas of use"),
   ("ul",["<strong>Face:</strong> temples, cheekbones, hollows beneath the eyes, jawline and lip volume",
          "<strong>Breast:</strong> limited augmentation, softening of implant edges, contour correction after reconstruction",
          "<strong>Buttocks and body:</strong> volume and contour adjustment",
          "<strong>Scars and radiation damage:</strong> softening of hardened tissue"])]},
  {"id":"kokhucre","tag":"Stem Cells","h2":"The stem-cell assisted approach","body":[
   "Fat tissue contains not only volume but <strong>regenerative cells</strong>. These cells support new vessel formation, improve skin quality and contribute to tissue healing. Enriching the fat for cell content aims to increase both the take rate and the effect on the tissue.",
   "The University of Pittsburgh is an international centre in this field. Assoc. Prof. Dr. Acarturk is among the first Turkish plastic surgeons to have worked with adipose-derived stem cell technologies and uses this technique particularly in <a href=\"../yanik-travma-onarimi.html\">cancer, burn and post-radiotherapy reconstruction</a>.",
   ("note","The concept of stem cells is frequently marketed in exaggerated terms in aesthetics. Cells derived from fat tissue contribute to tissue quality, but this is not a treatment that halts or reverses ageing. Framing expectations accordingly matters.")]},
  {"id":"surec","tag":"Process","h2":"Procedure and recovery","body":[
   ("steps",[
    ("STEP 1 — PLANNING","The target area, the volume required and the donor site are determined."),
    ("STEP 2 — HARVESTING","Fat is taken from the abdomen or thigh with fine cannulas at low pressure so as not to damage the cells."),
    ("STEP 3 — PROCESSING","The fat is separated from blood and fluid and purified."),
    ("STEP 4 — INJECTION","It is placed into the target area in numerous fine tunnels, layer by layer."),
    ("STEP 5 — FIRST 3 MONTHS","Swelling resolves and reabsorption completes. The permanent result is assessed at the end of this period.")]),
   ("ul",["Pressure on the injected area should be avoided in the first week",
          "Smoking markedly reduces the survival rate of the fat cells",
          "Significant weight change affects the result",
          "A second session is planned after 3–6 months where needed"])]}],
 "faqs":[
  ("How much of the injected fat is permanent?","On average 50–70% is permanent. The remainder is reabsorbed within the first 3 months. Extra volume is therefore planned and a second session performed if needed."),
  ("What is the advantage over dermal fillers?","Because it is your own tissue there is no risk of foreign-body reaction, it feels natural and the portion that takes is permanent. It also contributes to skin quality. The disadvantages are that it is a surgical procedure and the outcome is less predictable."),
  ("Will fat grafting make my face look puffy?","It looks fuller for the first 2–3 weeks because of swelling; this is temporary. As long as excessive volume is avoided and a layered technique is used, the result is natural."),
  ("Can fat be used instead of an implant for breast augmentation?","It can be used for a limited increase. However, the volume achievable in a single session is smaller than with an implant and more than one session may be needed. The decision follows your expectations."),
  ("Does fat grafting affect breast cancer screening?","Part of the grafted fat may lead to calcifications, which can be seen on imaging but can be distinguished from cancer by an experienced radiologist. Informing the radiology team is sufficient."),
  ("I am slim — do I have enough fat?","Sufficient volume can usually be harvested from the abdomen, inner thigh or inner knee. In very slim patients the target volume may be limited; this is assessed at examination.")],
 "ctah":"Fat grafting assessment",
 "ctap":"Tell us where you would like volume, whether you have had fillers before, and send photographs if you have them."},

"kol-uyluk-germe": {
 "crumb":"Arm, Thigh and Body Lift",
 "title":"Arm Lift (Brachioplasty), Thigh and Body Lift | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Arm, Thigh and Body Lift",
 "desc":"Arm lift (brachioplasty), thigh lift and body lift after major weight loss: scar placement, the order of planning and the recovery process.",
 "eyebrow":"Aesthetic Surgery",
 "h1":"Arm, thigh and body lift",
 "lead":"Major weight loss is an achievement, but it leaves loose skin behind. The inner arms, thighs and trunk show this change most. Lifting procedures remove the excess skin so that the body matches the weight you have lost.",
 "watopic":"arm and thigh lift",
 "about":"Body contouring surgery",
 "card":"Arm and thigh lift","cardsub":"Removal of excess skin after weight loss",
 "procedure":{"name":"Brachioplasty and Thigh Lift",
   "how":"Excess skin and fat are removed along the line where the scar can best be concealed, and the underlying tissues are suspended to create contour.",
   "prep":"A stable weight and assessment of nutritional and vitamin status.",
   "follow":"Compression garments, oedema control and gradual return to activity.",
   "body":"Arm, thigh, trunk"},
 "keyfacts":[("Prerequisite","Weight stable for 6 months"),("Anaesthesia","General anaesthesia"),
             ("Scar","Permanent, along concealable lines"),("Return to work","2–3 weeks")],
 "authority":"Body contouring after major weight loss requires reconstructive discipline because of the large wound surfaces and high complication risk. Assoc. Prof. Dr. Acarturk's background in trunk and extremity reconstruction allows these operations to be staged safely.",
 "creds":["Experience in trunk and extremity reconstruction","Three years of general surgery training","Practice in managing complex wounds and tissue loss"],
 "sections":[
  {"id":"kol","tag":"Arm Lift","h2":"Arm lift (brachioplasty)","body":[
   "Sagging on the inner arm is one of the most frequent complaints after weight loss. It leads people to avoid short sleeves and to feel uncomfortable with the movement of the arm. Building muscle through exercise does not correct this sagging; the excess skin must be removed surgically.",
   ("ul",["<strong>Limited sagging:</strong> a short incision concealed in the axilla may be sufficient",
          "<strong>Marked sagging:</strong> an incision running from the axilla to the elbow along the inner arm is required",
          "Liposuction usually accompanies the procedure and softens the contour"]),
   ("note","The scar from an arm lift is permanent and its concealment is limited. The decision in this operation is made between the discomfort caused by the sagging and the acceptability of the scar. Most patients state that they prefer the scar to the sagging — but that preference must be clear beforehand.")]},
  {"id":"uyluk","tag":"Thigh Lift","h2":"Thigh lift","body":[
   "Sagging on the inner thigh causes chafing while walking, irritation and restriction in clothing choice. The incision is planned in one of two ways depending on the degree of sagging:",
   ("ul",["<strong>Groin crease incision:</strong> the scar is concealed along the underwear line. Preferred for limited sagging.",
          "<strong>Vertical incision:</strong> runs from the groin to the inner knee. Required for marked sagging; the scar is long but the result more effective."]),
   "The thigh is a sensitive area for wound healing: it is mobile, moist and subject to pressure. Wound separation and delayed healing are therefore more common here than elsewhere."]},
  {"id":"govde","tag":"Body Lift","h2":"Body lift and sequencing","body":[
   "A body lift removes excess skin entirely through an incision encircling the abdomen, waist, buttocks and outer thighs. It is performed in patients who have lost significant weight, typically after bariatric surgery.",
   ("h3","The order of planning"),
   ("ul",["The trunk and abdomen are usually addressed first — the largest change in volume is here",
          "Arm and thigh lifts are planned 3–6 months later",
          "The breasts and face are generally left until last",
          "Healing must be complete between stages"]),
   ("note","Vitamin and protein deficiencies after major weight loss directly affect wound healing. Assessing and, where needed, correcting nutritional status before surgery markedly reduces the risk of complications.")]},
  {"id":"surec","tag":"Process","h2":"The recovery process","body":[
   STEPS("Under general anaesthesia; 2–5 hours depending on the region and scope, with 1–2 nights in hospital.",
         "A compression garment is worn from day one and drains may be placed. Movement is limited in the first week.",
         "Return to desk work in 2–3 weeks. Compression continues for 6 weeks. Scars mature over the first year, during which care is critical.")]}],
 "faqs":[
  ("How long after weight loss can I have surgery?","Your weight should be stable for at least 6 months. Surgery performed too early risks the result being spoilt by subsequent weight change."),
  ("How visible will the scars be?","In these operations the scars are long and permanent. They fade over time but do not disappear entirely. Silicone care, sun protection and not smoking directly affect scar quality."),
  ("Can I have everything done in one session?","This is generally not advised. Long operating times and large wound surfaces increase risk. Staged planning is preferred for both safety and quality of result."),
  ("Wouldn't liposuction alone be enough?","Not if skin elasticity has been lost. Removing fat then makes the sagging more pronounced. In patients after weight loss, the excess skin must be removed."),
  ("When can I exercise after surgery?","Walking begins in the first days. Light exercise can be added after week 4 and weight training after week 8, gradually and with medical approval.")],
 "ctah":"Body lifting assessment",
 "ctap":"Tell us how much weight you have lost, how long your weight has been stable, whether you have had bariatric surgery, and send photographs if you have them."},

"lip-lift": {
 "crumb":"Lip Lift, Buccal Fat Removal and Otoplasty",
 "title":"Lip Lift, Buccal Fat Removal and Ear Surgery (Otoplasty) | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Lip Lift, Buccal Fat Removal and Otoplasty",
 "desc":"Lip lift, buccal fat removal and prominent ear correction (otoplasty): who they suit, the technique, scars and the recovery process.",
 "eyebrow":"Aesthetic Surgery",
 "h1":"Lip lift, buccal fat removal and ear surgery",
 "lead":"Three small-scale procedures with a large effect on facial appearance. All can be performed under local anaesthesia, recovery is short and the results are lasting. What they share: in the right patient they make a marked difference, in the wrong one they are unnecessary.",
 "watopic":"lip lift, buccal fat removal or otoplasty",
 "about":"Facial aesthetic surgery",
 "card":"Lip lift · Buccal fat · Otoplasty","cardsub":"Lip lift, cheek slimming, prominent ear correction",
 "procedure":{"name":"Lip Lift",
   "how":"A fine strip of skin is removed just beneath the base of the nose to raise the upper lip; the vermilion becomes more visible and dental show increases.",
   "prep":"Measurement of the lip-to-nose distance and assessment of dental show.",
   "follow":"Suture care and avoiding exaggerated facial movement in the first weeks.","body":"Upper lip"},
 "keyfacts":[("Anaesthesia","Local anaesthesia"),("Duration","30–60 minutes"),
             ("Suture removal","Days 5–7"),("Social return","1 week")],
 "authority":"Although small in scale, these procedures require command of facial proportions. Assoc. Prof. Dr. Acarturk's subspecialty in Oral & Maxillofacial Surgery and his background in facial skeletal surgery allow lip, cheek and ear procedures to be planned within the context of the face as a whole.",
 "creds":["Subspecialty in Oral & Maxillofacial Surgery","Ear reconstruction fellowship at the University of Helsinki","Experience in facial skeletal and soft tissue surgery"],
 "sections":[
  {"id":"liplift","tag":"Lip Lift","h2":"Lip lift","body":[
   "With age the distance between the base of the nose and the upper lip lengthens, the vermilion thins and the amount of tooth visible when smiling decreases. This gives the face an older, sterner expression. A lip lift raises the lip by removing a fine strip of skin just beneath the base of the nose.",
   ("ul",["The vermilion becomes more visible — no volume is added as with filler; existing tissue is revealed",
          "Dental show when smiling increases",
          "The result is permanent; unlike filler it does not need repeating",
          "The scar is concealed in the crease at the base of the nose"]),
   ("note","A lip lift is not an alternative to filler. Filler adds volume; a lip lift changes proportion. In patients with a long lip-to-nose distance, filler does not solve the problem and can make the upper lip look heavier.")]},
  {"id":"bisektomi","tag":"Buccal Fat","h2":"Buccal fat removal","body":[
   "Buccal fat removal is the excision, through the mouth, of part of the Bichat fat pad that lies deep within the cheeks. It reduces fullness in the mid-cheek and makes the cheekbone and jawline more defined. Because the incision is inside the mouth, no external scar forms.",
   ("h3","Who is it not suitable for?"),
   ("ul",["Those who are slim with already hollow cheeks",
          "Older patients in whom facial volume loss has begun",
          "Patients whose main problem is facial sagging"]),
   ("note","This fat pad shrinks naturally with age. Removing too much at a young age can lead to a hollow, aged appearance later. The amount removed should therefore be conservative; tissue taken cannot be replaced.")]},
  {"id":"otoplasti","tag":"Otoplasty","h2":"Prominent ear correction (otoplasty)","body":[
   "A prominent ear stands at too great an angle from the head or has underdeveloped folds. Because the social impact can be marked in childhood, early correction is often preferred.",
   ("ul",["The ear cartilage is reshaped and secured with sutures through an incision behind the ear",
          "The scar lies behind the ear and is not visible from the front",
          "Because ear growth is largely complete by 5–6 years, it can be performed before school age",
          "In adults it is performed under local anaesthesia"]),
   "Congenital absence of the ear (microtia) is a different condition requiring multi-stage reconstruction; details are on our <a href=\"../mikrotia-kulak-onarimi.html\">microtia page</a>."]},
  {"id":"surec","tag":"Process","h2":"The recovery process","body":[
   ("steps",[
    ("LIP LIFT","Sutures are removed on days 5–7. Swelling is noticeable in the first week; social return is usually 1 week. The scar fades over 3–6 months."),
    ("BUCCAL FAT REMOVAL","Soft diet and oral care for the first 3–5 days. Swelling resolves within 1–2 weeks. The result settles at 3–6 months."),
    ("OTOPLASTY","A headband is worn full-time for the first week and at night for a further 3–4 weeks. Social return in 5–7 days; exercise deferred for 4 weeks.")])]}],
 "faqs":[
  ("Will the lip lift scar be visible?","The incision is placed in the crease at the base of the nose. It stays pink for the first months and fades within 3–6 months, blending with the natural crease. Scar care and sun protection directly affect the result."),
  ("Will my cheeks hollow after buccal fat removal?","Not when a measured amount is taken. However, because this fat pad shrinks with age, removing too much at a young age can cause a hollow appearance later. A conservative approach is therefore preferred."),
  ("What is the right age for prominent ear surgery?","Ear growth is largely complete by 5–6 years, and the pre-school period is often preferred. It can also be performed at any age in adults."),
  ("Do prominent ears recur?","Partial recurrence can occur because cartilage has memory. To reduce this risk the cartilage shape is supported with permanent sutures, and compliance with the post-operative headband matters."),
  ("Can these procedures be combined?","Yes. Lip lift and buccal fat removal are frequently performed in the same session. They can also be combined with other facial procedures; planning is done at examination.")],
 "ctah":"The first step towards an assessment",
 "ctap":"Tell us which procedure interests you, what you would like to change, and send front and side photographs if you have them."},
}
