# -*- coding: utf-8 -*-
"""Ingilizce ceviriler — parti 6: lenfodem kumesi (6 uydu sayfa)."""

T = {
"bacakta-lenfodem": {
 "crumb":"Leg Lymphedema",
 "title":"Leg Lymphedema: Symptoms and Treatment | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Leg Lymphedema: Symptoms and Treatment",
 "desc":"What are the symptoms of leg lymphedema, why does it occur, which conditions is it confused with and how is it treated? Surgical options by stage and microsurgical treatment.",
 "eyebrow":"Microsurgery Programme",
 "h1":"Leg lymphedema: symptoms and treatment",
 "lead":"If the swelling in your leg increases through the day and settles by morning, if your shoes feel tight and one leg is thicker than the other — this may not be a matter of weight. Leg lymphedema begins quietly, but it can be treated microsurgically at an early stage.",
 "watopic":"leg lymphedema treatment",
 "about":"Leg Lymphedema",
 "aboutType":"MedicalCondition",
 "card":"Leg lymphedema","cardsub":"Diagnosis and surgical treatment of lower limb lymphedema",
 "procedure":{"name":"Lower Limb Lymphedema Surgery",
   "how":"Blocked lymphatic vessels in the leg are connected to neighbouring veins under the microscope (LVA); in advanced stages vascularised lymph node transfer and reduction surgery are planned.",
   "prep":"Examination, circumference measurements, lymphatic mapping with ICG lymphography or lymphoscintigraphy.",
   "follow":"Compression garments, early mobilisation and lymphedema physiotherapy where needed.",
   "body":"Lymphatic system of the leg and foot"},
 "keyfacts":[("Distinguishing sign","Swelling extends to the top of the foot and toes"),
             ("Stemmer","Positive if skin over the toe cannot be lifted"),
             ("Early stage","LVA — the least invasive option"),
             ("Critical","One-sided swelling must always be investigated")],
 "authority":"Leg lymphedema is a harder field than arm lymphedema: gravity increases the lymphatic load, the distances are longer and the risk of infection is higher. With over 300 microsurgical cases from the University of Pittsburgh, Assoc. Prof. Dr. Acarturk works on lymphatic channels 0.3–0.8 mm in diameter and participates in the work of the European lymphatic microsurgery group.",
 "creds":["Former Director of Head and Neck Reconstruction, University of Pittsburgh — 300+ microsurgical cases",
          "Participation in the European lymphatic microsurgery group",
          "Presentation at the World Congress of Lymphology"],
 "sections":[
  {"id":"belirti","tag":"Symptoms","h2":"Symptoms of leg lymphedema","body":[
   "Leg lymphedema usually begins unnoticed. In the early period the swelling increases through the day and largely settles by morning. Because of this fluctuation patients attribute it to fatigue or salty food and do not consult a doctor for months.",
   ("h3","Early findings"),
   ("ul",["Swelling that increases towards evening and lessens by morning",
          "Sock elastic leaving a deep mark on the leg",
          "Shoes feeling tight in the evening",
          "A sense of fullness and heaviness in the leg",
          "A widening difference in circumference between the two legs"]),
   ("h3","Established findings"),
   ("ul",["Swelling that does not resolve when the leg is elevated",
          "Thickening and hardening of the skin",
          "Recurrent cellulitis (erysipelas) attacks — fever, redness, pain",
          "A squared appearance of the toes",
          "Leakage from the skin (lymphorrhoea) and wart-like changes"]),
   ("note","<strong>Stemmer's sign:</strong> Try to pinch and lift the skin over the second toe. If it is thick and cannot be lifted, the sign is positive and favours lymphedema. It is a simple but valuable examination finding — though it does not establish the diagnosis on its own.")]},
  {"id":"neden","tag":"Causes","h2":"Why does leg lymphedema occur?","body":[
   "The causes of lower limb lymphedema differ from those in the arm. In the arm the picture usually follows breast cancer treatment; in the leg the range of causes is wider.",
   ("ul",["<strong>Gynaecological and urological cancer treatments:</strong> groin and pelvic lymph node dissection in uterine, ovarian and prostate cancer",
          "<strong>Radiotherapy:</strong> irradiation of the pelvis scars the lymphatic channels",
          "<strong>Recurrent cellulitis:</strong> each attack damages the lymphatic structure further — creating a vicious circle",
          "<strong>Melanoma surgery:</strong> after groin lymph node dissection",
          "<strong>Primary lymphedema:</strong> congenital underdevelopment of the lymphatic system; may appear in adolescence or adulthood",
          "<strong>Trauma and major orthopaedic surgery</strong>"]),
   ("note","The first step in leg lymphedema is to exclude an underlying obstruction. In one-sided, rapidly developing and painful swelling, deep vein thrombosis and a pelvic mass must be investigated. A diagnosis of lymphedema should not be made without this assessment.")]},
  {"id":"ayirici","tag":"Differential Diagnosis","h2":"Is leg swelling always lymphedema?","body":[
   "No. Several different conditions cause swelling in the leg and their treatments are entirely different. The most commonly confused pictures:",
   ("table",["Condition","Distinguishing feature"],[
     ["Lymphedema","Swelling extends to the top of the foot and toes; Stemmer positive; usually one-sided"],
     ["Lipedema","Swelling stops at the ankle — cuff sign; feet spared; symmetrical; painful to touch"],
     ["Venous insufficiency","Increases in the evening, settles quickly when the leg is raised; varicose veins and skin discolouration accompany it"],
     ["Cardiac/renal/hepatic oedema","Symmetrical in both legs; pits on pressure; an underlying systemic illness is present"],
     ["Deep vein thrombosis","Sudden onset, pain, increased warmth — requires urgent assessment"]]),
   "Lymphedema and lipedema may also coexist; this is called <strong>lipo-lymphedema</strong>. For a detailed comparison see our <a href=\"../lipodem-cerrahisi.html\">lipedema surgery page</a>."]},
  {"id":"tedavi","tag":"Treatment","h2":"Treatment of leg lymphedema","body":[
   "Treatment is planned according to stage. The basic principle is this: <strong>intervening while the lymphatic channels still work</strong> is far more effective than intervening after the tissue has hardened.",
   ("h3","Conservative treatment"),
   "Complex decongestive physiotherapy — manual lymphatic drainage, bandaging, compression garments and exercise — is the foundation of treatment and continues after surgery. It does not, however, remove the obstruction itself.",
   ("h3","LVA — lymphovenous anastomosis"),
   "Working lymphatic channels in the leg are connected to neighbouring veins under the microscope. The incisions are small and recovery is quick. It is the most effective option in the early stage, while the channels still contract.",
   ("h3","Vascularised lymph node transfer"),
   "A group of your own lymph nodes is moved to the leg together with its feeding vessels. It is preferred in advanced stages and in patients whose groin region has been irradiated.",
   ("h3","Reduction surgery"),
   "Where volume has increased through fat tissue and fibrosis, liposuction and excision reduce the volume of the leg. It does not restore lymphatic flow but markedly reduces the burden; it is usually planned alongside other methods.",
   ("note","In leg lymphedema, reducing recurrent cellulitis attacks is as important a goal as reducing volume. Each attack further damages the lymphatic structure; spacing the attacks out slows the progression of the disease.")]},
  {"id":"gunluk","tag":"Daily Life","h2":"Daily life with leg lymphedema","body":[
   ("ul",["<strong>Skin care is the most important protective measure.</strong> Dry skin cracks, and bacteria entering through the crack cause cellulitis. Daily moisturising should not be neglected.",
          "<strong>Pay attention to foot care:</strong> fungal infections start between the toes and are the commonest entry point for cellulitis",
          "<strong>Protect yourself from injury:</strong> avoid walking barefoot and cutting nails too short",
          "<strong>Movement helps:</strong> walking and calf muscle work support lymphatic flow",
          "<strong>On long flights</strong> compression stockings and frequent movement are advised",
          "<strong>Weight control</strong> directly reduces the lymphatic load"]),
   ("note","Fever, widespread redness of the leg and increased warmth herald cellulitis. This picture requires antibiotic treatment without delay; postponing it both worsens the attack and increases lymphatic damage.")]}],
 "faqs":[
  ("Is the swelling in my leg lymphedema or oedema?","Swelling that leaves a deep pit on pressure, settles quickly when the leg is raised and is symmetrical in both legs suggests systemic oedema. In lymphedema the swelling extends to the top of the foot and toes, Stemmer's sign is positive and it is usually one-sided. The definitive distinction is made by examination and imaging."),
  ("Does leg lymphedema go away?","A promise of complete cure would not be honest. However, in the early stage microsurgery can markedly reduce volume, cellulitis attacks become less frequent and dependence on compression garments decreases. As the stage advances, the aim becomes controlling the disease and preserving function."),
  ("Is treatment possible without surgery?","Complex decongestive physiotherapy and compression garments are the foundation of treatment and keep volume under control in many patients. They do not, however, resolve the obstruction itself. In patients at a suitable stage, surgery offers the possibility of addressing the cause."),
  ("Which operation is performed for leg lymphedema?","LVA comes to the fore in the early stage. In advanced stages vascularised lymph node transfer and reduction surgery are planned alone or together. The decision is made according to stage, imaging findings and the duration of the swelling."),
  ("Will I wear compression garments after surgery?","In the first period, yes. Over time the need decreases in many patients, but stopping altogether may not always be possible. This depends on the stage and the result of the operation."),
  ("Why do cellulitis attacks matter?","Each attack leaves permanent damage in the lymphatic channels and advances the stage of the disease. Preventing attacks — skin care, treating fungal infection, avoiding injury — is an inseparable part of treatment.")],
 "ctah":"Leg lymphedema assessment",
 "ctap":"Tell us how long the swelling has been present, whether it is one- or two-sided, any surgery or radiotherapy you have had and your history of cellulitis; if possible attach a photograph showing both legs together."},

"kolda-lenfodem": {
 "crumb":"Arm Lymphedema",
 "title":"Arm Lymphedema After Breast Cancer: Symptoms and Treatment | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Arm Lymphedema: Symptoms and Treatment",
 "desc":"Arm lymphedema after breast cancer treatment: symptoms, risk factors, prevention and microsurgical treatment options (LVA, lymph node transfer).",
 "eyebrow":"Microsurgery Programme",
 "h1":"Arm lymphedema and treatment after breast cancer",
 "lead":"For many patients, the swelling that begins in the arm after breast cancer treatment ends is the longest-lasting side effect of that treatment. But it is no longer an inevitable outcome: it can be addressed microsurgically at an early stage, and it can even be prevented during the original operation.",
 "watopic":"arm lymphedema treatment",
 "about":"Arm Lymphedema",
 "aboutType":"MedicalCondition",
 "card":"Arm lymphedema","cardsub":"Surgical treatment of arm lymphedema after breast cancer",
 "procedure":{"name":"Upper Limb Lymphedema Surgery",
   "how":"Blocked lymphatic channels in the arm are connected to neighbouring veins under the microscope; axillary scarring is released and vascularised lymph node transfer is performed where needed.",
   "prep":"Circumference measurements, ICG lymphography, assessment of the axilla and of any radiotherapy history.",
   "follow":"Compression sleeve, shoulder range-of-motion exercises and lymphedema physiotherapy.",
   "body":"Lymphatic system of the arm"},
 "keyfacts":[("Risk","Axillary dissection + radiotherapy carries the highest risk"),
             ("Timing","Usually begins within the first 2 years"),
             ("Early stage","Volume control possible with LVA"),
             ("Prevention","LYMPHA — a protective approach during surgery")],
 "authority":"Arm lymphedema surgery requires knowledge of both breast surgery and microsurgery. Assoc. Prof. Dr. Acarturk is a surgeon who performs both breast reconstruction and lymphatic microsurgery; with 300+ microsurgical cases and a 97% flap success rate, he brings these two fields into a single plan.",
 "creds":["300+ microsurgical operations · 97% flap success rate",
          "Participation in the European lymphatic microsurgery group",
          "An integrated approach to breast reconstruction and lymphatic surgery"],
 "sections":[
  {"id":"belirti","tag":"Symptoms","h2":"Symptoms of arm lymphedema","body":[
   "Arm lymphedema is often felt before any measurable swelling appears. Most patients first describe a <strong>sense of heaviness and tightness</strong>.",
   ("h3","Early warning signs"),
   ("ul",["A feeling of fullness, heaviness or tightness in the arm",
          "A watch, ring or bracelet becoming tight",
          "A shirt sleeve feeling tight on one side only",
          "Tightness and shininess of the skin",
          "A sense of reduced arm movement"]),
   ("h3","Established findings"),
   ("ul",["A measurable difference in arm circumference (usually 2 cm or more)",
          "Swelling that does not resolve when the arm is raised",
          "Thickening and hardening of the skin",
          "Recurrent cellulitis attacks",
          "Swelling of the back of the hand and fingers"]),
   ("note","Swelling in the first weeks after surgery is usually temporary oedema related to the operation and is not lymphedema. However, if swelling lasts longer than 3 months or begins later, it must be assessed.")]},
  {"id":"risk","tag":"Risk","h2":"Who is at higher risk?","body":[
   "Not every patient treated for breast cancer develops lymphedema. The risk varies with the extent of the treatment given.",
   ("table",["Factor","Effect on risk"],[
     ["Sentinel lymph node biopsy","Low risk — a limited number of nodes are removed"],
     ["Axillary lymph node dissection","Marked increase in risk — the axillary lymphatic structure is widely affected"],
     ["Radiotherapy to the axilla","Increases risk further; combined with dissection it carries the highest risk"],
     ["Recurrent infection","Each attack reduces lymphatic reserve"],
     ["High body mass index","Increases the lymphatic load"],
     ["Trauma or surgery to the arm","Strains the existing reserve"]]),
   ("note","Lymphedema most often begins within the first 2 years after treatment ends, but it can also appear years later. For this reason regular monitoring of arm circumference is advised in patients at risk.")]},
  {"id":"onleme","tag":"Prevention","h2":"Can it be prevented?","body":[
   "The most important development in lymphedema surgery in recent years has been in <strong>prevention</strong> rather than treatment.",
   ("h3","LYMPHA — preventive lymphovenous anastomosis"),
   "During axillary dissection, the divided lymphatic channels are connected to a neighbouring vein in the same session. An outlet for lymphatic flow is thus created from the outset. This approach is used with the aim of reducing the rate of lymphedema in high-risk patients.",
   ("h3","Early detection"),
   "Taking arm circumference measurements before surgery and monitoring them regularly afterwards makes it possible to catch lymphedema before it becomes visible. A patient caught at stage 0 is the patient with the widest range of treatment options.",
   ("ul",["A baseline measurement should be taken before surgery",
          "More frequent follow-up in the first 2 years, annually thereafter",
          "A sense of heaviness and tightness should be taken seriously — do not wait for measurements",
          "Skin care and infection prevention from day one"])]},
  {"id":"tedavi","tag":"Treatment","h2":"Treatment of arm lymphedema","body":[
   ("h3","Conservative treatment"),
   "Manual lymphatic drainage, bandaging, compression sleeves and exercise form the foundation of treatment and continue after surgery.",
   ("h3","LVA"),
   "Working lymphatic channels in the arm are connected to veins under the microscope. It is performed through small incisions and the hospital stay is short. It is the most effective option in the early stage.",
   ("h3","Vascularised lymph node transfer"),
   "Lymph nodes taken from a healthy region are moved to the axilla with their feeding vessels. Bringing living tissue into irradiated and scarred axillary tissue is a further benefit.",
   ("h3","Scar release"),
   "Dense scar tissue in the axilla restricts both lymphatic flow and shoulder movement. Release, planned together with transfer, markedly improves the result.",
   ("h3","Reduction surgery"),
   "In an arm enlarged by fat tissue and fibrosis, liposuction reduces volume. It is used with other methods in advanced stages.",
   ("note","In patients planning breast reconstruction, lymphedema surgery can be performed in the same session. This spares the patient a second operation. For details see our <a href=\"../meme-rekonstruksiyonu.html\">breast reconstruction page</a>.")]}],
 "faqs":[
  ("Does everyone develop lymphedema after breast cancer surgery?","No. The risk varies with the treatment given. It is low after sentinel lymph node biopsy, while it increases markedly when axillary dissection and axillary radiotherapy are combined."),
  ("When does lymphedema begin?","Most often within the first 2 years after treatment ends. However, it can also appear years later, which is why follow-up should be long-term."),
  ("Is the swelling in my arm lymphedema?","A measurable difference in arm circumference compared with the other arm, a sense of heaviness and a ring or watch becoming tight suggest lymphedema. Swelling in the first weeks after surgery is usually temporary surgical oedema. The distinction is made by examination and measurement."),
  ("Will surgery correct it?","In the early stage, LVA can markedly reduce volume and dependence on a compression sleeve may lessen. In advanced stages, lymph node transfer and reduction surgery achieve control. A promise of complete cure would not be honest; the aim is to reduce volume, space out infections and restore function."),
  ("Can lymphedema be prevented?","In high-risk patients, the preventive LVA (LYMPHA) approach performed during axillary dissection is used with the aim of reducing the rate of lymphedema. A baseline measurement before surgery is also recommended for early detection."),
  ("Should I avoid using my arm?","No. The strict restrictions once advised are no longer valid. Gradually increased exercise and normal use are beneficial. What should be avoided is sudden excessive strain and injury."),
  ("Can blood pressure be measured and blood taken from that arm?","The traditional advice is to avoid the arm on the operated side. Although the level of evidence is debated, using the other arm where there is a choice is a reasonable precaution.")],
 "ctah":"Arm lymphedema assessment",
 "ctap":"Tell us the extent of your breast cancer treatment (type of surgery, lymph node dissection, radiotherapy), when the swelling began and your arm circumference measurements; if possible attach a photograph showing both arms together."},

"lenfodem-belirtileri": {
 "crumb":"Lymphedema Symptoms",
 "title":"Lymphedema Symptoms: Early Signs and Self-Checks | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Lymphedema Symptoms and Early Signs",
 "desc":"What are the symptoms of lymphedema? Early findings, Stemmer's sign, self-check methods and when to consult a doctor.",
 "eyebrow":"Microsurgery Programme",
 "h1":"Lymphedema symptoms and early signs",
 "lead":"In lymphedema, time is the most valuable thing. A patient caught while the lymphatic channels still work has a wide range of treatment options; once the tissue hardens, the options narrow. This page explains what to take seriously, and when.",
 "watopic":"lymphedema symptoms",
 "about":"Lymphedema",
 "aboutType":"MedicalCondition",
 "card":"Lymphedema symptoms","cardsub":"Early findings and self-assessment",
 "procedure":{"name":"Lymphedema Diagnostic Assessment",
   "how":"Circumference measurements, Stemmer's sign, skin quality and infection history are assessed together; lymphatic mapping with ICG lymphography or lymphoscintigraphy is performed where needed.",
   "prep":"Duration of swelling, history of surgery and radiotherapy.",
   "follow":"A treatment plan according to stage and regular measurement follow-up.",
   "body":"Lymphatic system"},
 "keyfacts":[("First sign","Usually a sense of heaviness and tightness"),
             ("Stemmer","Positive if the skin cannot be lifted"),
             ("Warning","Swelling lasting longer than 3 months should be assessed"),
             ("Critical","Treatment options are widest at stage 0")],
 "authority":"Early diagnosis of lymphedema directly determines the success of treatment. Assoc. Prof. Dr. Acarturk is a microsurgeon who participates in the work of the European lymphatic microsurgery group and has presented at the World Congress of Lymphology; with 300+ microsurgical cases he translates staging into a treatment plan.",
 "creds":["Participation in the European lymphatic microsurgery group",
          "Presentation at the World Congress of Lymphology",
          "300+ microsurgical cases at the University of Pittsburgh"],
 "sections":[
  {"id":"erken","tag":"Early Signs","h2":"The earliest symptoms: felt before they are measured","body":[
   "The first symptom of lymphedema is usually not visible swelling. Most patients describe a <strong>change in sensation</strong> before any measurable difference has developed.",
   ("ul",["Heaviness, fullness or tightness in the arm or leg",
          "A ring, watch, bracelet or sock beginning to feel tight",
          "Clothing feeling tight on one side only",
          "Tightness or shininess of the skin",
          "A slight sense of restriction in joint movement"]),
   ("note","Patients frequently explain these symptoms away as \"I've put on weight\" or \"I'm tired\" and postpone them for months. Yet this is the most valuable period for treatment. These complaints should be assessed even if measurements are still normal.")]},
  {"id":"yerlesmis","tag":"Established Stage","h2":"Findings of established lymphedema","body":[
   ("ul",["<strong>Persistent swelling:</strong> oedema that does not resolve when the limb is elevated",
          "<strong>Measurable difference:</strong> a difference in circumference compared with the opposite limb",
          "<strong>Pitting:</strong> a pit remains on pressure in the early stage; in advanced stages it does not, because the tissue has hardened",
          "<strong>Skin changes:</strong> thickening, hardening, an orange-peel appearance",
          "<strong>Recurrent cellulitis:</strong> attacks with fever, redness and pain",
          "<strong>Lymphorrhoea:</strong> leakage of clear fluid from the skin",
          "<strong>Loss of function:</strong> restricted movement, difficulty with daily tasks"]),
   ("note","<strong>The absence of pitting</strong> does not mean the oedema has resolved — on the contrary, it shows that the tissue has hardened with fibrosis and points to a more advanced stage. This distinction directly changes the treatment plan.")]},
  {"id":"kontrol","tag":"Self-Check","h2":"Self-assessment: what should you look for?","body":[
   ("steps",[
    ("1 — STEMMER'S SIGN","Try to pinch and lift the skin over your second toe (or your second finger in the hand) between thumb and forefinger. If the skin is thick and cannot be lifted, the sign is positive."),
    ("2 — CIRCUMFERENCE MEASUREMENT","Measure both limbs at the same points with a tape measure. Choose fixed reference points (for example 10 cm above the elbow). The difference between the two sides should be monitored."),
    ("3 — PITTING TEST","Press with a finger on the swollen area for 10 seconds. A remaining pit indicates oedema; the absence of a pit may point to tissue hardening in an advanced stage."),
    ("4 — SYMMETRY AND FOOT/HAND","Is the swelling one-sided? Does it extend to the top of the foot and the toes? These findings favour lymphedema."),
    ("5 — PHOTOGRAPHIC RECORD","Photograph both limbs together monthly, at the same angle and in the same light. This is the most practical way to notice slow change.")]),
   ("note","These checks do not replace a medical examination; their purpose is to help you notice change and consult at the right time.")]},
  {"id":"nezaman","tag":"When to Consult","h2":"When should you see a doctor?","body":[
   ("ul",["If swelling lasts <strong>longer than 3 months</strong>",
          "For new swelling after cancer treatment, particularly lymph node dissection or radiotherapy",
          "If you notice a growing difference in circumference between the two limbs",
          "If Stemmer's sign is positive",
          "If you have had an episode of cellulitis"]),
   ("note","<strong>Situations requiring urgent assessment:</strong> Sudden, painful, one-sided swelling may suggest deep vein thrombosis. Fever, widespread redness and increased warmth herald cellulitis and require antibiotics without delay. Do not wait in either case.")]},
  {"id":"karisan","tag":"Confused Conditions","h2":"Conditions confused with lymphedema","body":[
   ("table",["Condition","Distinguishing feature"],[
     ["Lipedema","Symmetrical; stops at the ankle (cuff sign); painful to touch; Stemmer negative"],
     ["Venous insufficiency","Settles quickly when the leg is raised; varicose veins and skin discolouration accompany it"],
     ["Cardiac/renal/hepatic oedema","Symmetrical on both sides; marked pitting; a systemic illness is present"],
     ["Deep vein thrombosis","Sudden onset, pain, increased warmth — urgent"],
     ["Obesity","Generalised; Stemmer negative; limb distribution proportionate"]]),
   "The distinction between lymphedema and lipedema is particularly important because their treatments differ and the two may coexist. For detail see our <a href=\"../lipodem-belirtileri.html\">lipedema symptoms page</a>."]}],
 "faqs":[
  ("What is the first symptom of lymphedema?","Usually not visible swelling but a change in sensation: heaviness, fullness or tightness in the limb. A ring, watch or sock beginning to feel tight is also an early warning."),
  ("What is Stemmer's sign and how is it checked?","You try to pinch and lift the skin over the second toe or finger. If the skin is thick and cannot be lifted, the sign is positive and favours lymphedema. It is simple but valuable; it does not establish the diagnosis on its own."),
  ("If the swelling does not pit, is it not lymphedema?","On the contrary. A pit remains in the early stage; in advanced stages the tissue has hardened with fibrosis and no pit remains. The absence of pitting may point to a more advanced stage."),
  ("Does lymphedema cause pain?","Heaviness and tightness dominate in lymphedema; marked pain is not typical. Pain on touch suggests lipedema instead. Sudden severe pain requires urgent assessment for infection or vascular obstruction."),
  ("How many centimetres of difference is significant?","A difference of approximately 2 cm or more between the two limbs is considered clinically significant. Smaller differences also warrant follow-up, however — particularly in patients at risk, the direction of change matters more than the absolute value."),
  ("If swelling increases in the evening and settles by morning, is it lymphedema?","This fluctuation is typical of early-stage lymphedema, but it is also seen in venous insufficiency. Foot and toe involvement, Stemmer's sign and symmetry are assessed to distinguish them.")],
 "ctah":"Let us assess your symptoms",
 "ctap":"Tell us how long the swelling has been present, which limb is affected and whether it is one- or two-sided, and any surgery or radiotherapy you have had; if possible attach a photograph showing both limbs together."},

"lenfodem-neden-olur": {
 "crumb":"Causes of Lymphedema",
 "title":"Why Does Lymphedema Occur? Causes and Risk Factors | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Why Does Lymphedema Occur? Causes and Risk Factors",
 "desc":"Why does lymphedema occur? Primary and secondary causes, risk after cancer treatment, infection and genetic factors — and how to reduce the risk.",
 "eyebrow":"Microsurgery Programme",
 "h1":"Why does lymphedema occur?",
 "lead":"Lymphedema arises when lymphatic fluid accumulates in the tissue. But the real question is this: what caused that accumulation? Understanding the cause correctly directly determines both the treatment plan and the strategy for reducing risk.",
 "watopic":"causes of lymphedema",
 "about":"Lymphedema",
 "aboutType":"MedicalCondition",
 "card":"Causes of lymphedema","cardsub":"Primary and secondary causes, risk factors",
 "procedure":{"name":"Aetiological Assessment of Lymphedema",
   "how":"The onset of swelling, previous surgery and radiotherapy, infection history and family history are assessed together; the lymphatic structure is examined with imaging where needed.",
   "prep":"A detailed history and existing medical records.",
   "follow":"A treatment plan directed at the cause and advice on reducing risk.",
   "body":"Lymphatic system"},
 "keyfacts":[("Commonest cause","After cancer treatment (secondary)"),
             ("Primary","Congenital underdevelopment of the lymphatic system"),
             ("Trigger","Infection increases damage with each attack"),
             ("Modifiable","Weight, infection, skin care")],
 "authority":"Establishing the cause of lymphedema correctly both prevents unnecessary treatment and makes the right surgery possible. As a surgeon who performs both reconstruction after oncological surgery and lymphatic microsurgery, Assoc. Prof. Dr. Acarturk assesses these two fields together.",
 "creds":["Former Director of Head and Neck Reconstruction, University of Pittsburgh",
          "300+ microsurgical operations · 97% flap success rate",
          "Participation in the European lymphatic microsurgery group"],
 "sections":[
  {"id":"mekanizma","tag":"Mechanism","h2":"How does lymphedema develop?","body":[
   "The lymphatic system is a fine network of channels that collects protein-rich fluid accumulating between the tissues and returns it to the circulation. Unlike the vascular system driven by the heart, it has no central pump; it works through muscle movement and contractions of the channel wall.",
   "When this network is blocked or its transport capacity is exceeded, fluid accumulates in the tissue. At first this accumulation is fluid alone and is reversible. Over time <strong>fat deposition and fibrosis</strong> develop, the tissue hardens and the picture becomes permanent.",
   ("note","The critical point is this: lymphedema is not a static condition but a progressive process. Intervening early, while the channels still work, is far more effective than intervening after the tissue has hardened.")]},
  {"id":"sekonder","tag":"Secondary","h2":"Causes of secondary lymphedema (commonest)","body":[
   "The great majority of cases are secondary — that is, the lymphatic system was initially normal and was damaged later.",
   ("h3","Cancer treatments"),
   ("ul",["<strong>Lymph node dissection:</strong> removal of lymph nodes in breast, gynaecological and urological cancers and melanoma",
          "<strong>Radiotherapy:</strong> irradiation scars the lymphatic channels and lowers transport capacity",
          "<strong>The tumour itself:</strong> may block lymphatic pathways directly"]),
   ("h3","Infections"),
   ("ul",["<strong>Recurrent cellulitis (erysipelas):</strong> each attack leaves permanent damage in the lymphatic channels and raises the risk of the next attack — a vicious circle",
          "<strong>Filariasis:</strong> the parasitic disease that is the commonest cause of lymphedema worldwide; it does not occur in Türkiye"]),
   ("h3","Trauma and surgery"),
   ("ul",["Extensive soft tissue injuries and burns",
          "Major orthopaedic and vascular surgery",
          "Widespread scar tissue"]),
   ("h3","Other"),
   ("ul",["Chronic venous insufficiency — increases the lymphatic load over time (phlebolymphedema)",
          "Obesity — a high body mass index strains lymphatic transport capacity",
          "Prolonged immobility"])]},
  {"id":"primer","tag":"Primary","h2":"Primary lymphedema: congenital causes","body":[
   "Primary lymphedema is due to congenital underdevelopment of the lymphatic system. It is far rarer than secondary lymphedema and is named according to the age at which it appears:",
   ("table",["Type","Onset","Note"],[
     ["Congenital lymphedema","At birth or in the first 2 years","Milroy disease belongs to this group"],
     ["Lymphedema praecox","Between adolescence and 35","The commonest primary form; more frequent in women"],
     ["Lymphedema tarda","After 35","Rare; secondary causes must first be excluded"]]),
   ("note","In lymphedema beginning after the age of 35 with no obvious cause, an underlying mass or obstruction must be investigated before a diagnosis of primary lymphedema is made. This is a step that should not be skipped.")]},
  {"id":"risk","tag":"Risk Factors","h2":"Factors that raise risk — and those you can change","body":[
   "Some risk factors cannot be changed (such as the extent of previous surgery); others are directly within your control.",
   ("table",["Factor","Modifiable?"],[
     ["Extent of lymph node dissection","No — though risk can be reduced with preventive surgery (LYMPHA)"],
     ["History of radiotherapy","No"],
     ["Genetic predisposition","No"],
     ["Body mass index","Yes — weight control directly reduces the lymphatic load"],
     ["Recurrent infection","Yes — through skin care and early antibiotics"],
     ["Skin integrity","Yes — moisturising, avoiding injury, treating fungal infection"],
     ["Immobility","Yes — regular exercise supports lymphatic flow"]]),
   ("note","Preventing infection is the most important of the modifiable factors. Each episode of cellulitis reduces lymphatic reserve a little further; preventing attacks is the most effective way to slow the progression of the disease.")]}],
 "faqs":[
  ("Is lymphedema hereditary?","Genetic predisposition plays a role in primary lymphedema and a family history may be present. However, the majority of cases are secondary — that is, they develop after cancer treatment, infection or trauma and are not hereditary."),
  ("Is lymphedema cancer?","No. Lymphedema is a circulatory disorder caused by accumulation of lymphatic fluid. Lymphoma is a cancer of the lymphatic system treated by haematology-oncology. Beyond the similarity of the names, they are unrelated."),
  ("Does lymphedema follow every lymph node operation?","No. The risk varies with the number of nodes removed and whether radiotherapy was added. It is low after sentinel lymph node biopsy, while it increases markedly when wide dissection and radiotherapy are combined."),
  ("Will losing weight correct lymphedema?","It will not correct it on its own but contributes markedly. A high body mass index strains lymphatic transport capacity; weight control both reduces existing swelling and improves treatment outcomes."),
  ("Why is cellulitis so important?","Each attack leaves permanent damage in the lymphatic channels and advances the stage of the disease. Having one attack also raises the risk of the next. Breaking this cycle is an inseparable part of treatment."),
  ("Does air travel cause lymphedema?","There is no strong evidence that a flight alone initiates lymphedema. However, wearing compression garments and moving frequently on long flights is a reasonable precaution for people at risk.")],
 "ctah":"Let us assess the cause together",
 "ctap":"Tell us when the swelling began, any surgery and radiotherapy you have had, your history of infection and whether anyone in your family has a similar condition."},

"lenfodem-hangi-doktor": {
 "crumb":"Which Specialist Treats Lymphedema",
 "title":"Which Specialist Treats Lymphedema? Where to Go | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Which Specialist Treats Lymphedema?",
 "desc":"Which department should you consult for lymphedema? The roles of plastic surgery, physical medicine and other specialties, who to see when, and how to prepare for your appointment.",
 "eyebrow":"Microsurgery Programme",
 "h1":"Which specialist treats lymphedema?",
 "lead":"Lymphedema is not the disease of a single specialty. Patients therefore often move between departments and reach the right address months later. This page explains plainly which specialist you should see, and when.",
 "watopic":"the right specialist for lymphedema",
 "about":"Lymphedema",
 "aboutType":"MedicalCondition",
 "card":"Which specialist?","cardsub":"Finding the right specialty for lymphedema",
 "procedure":{"name":"Surgical Assessment for Lymphedema",
   "how":"Plastic and reconstructive surgery addresses the obstruction directly with lymphatic microsurgery: LVA, vascularised lymph node transfer and reduction surgery.",
   "prep":"Staging, imaging and review of previous treatments.",
   "follow":"Long-term follow-up conducted together with physiotherapy.",
   "body":"Lymphatic system"},
 "keyfacts":[("Surgical treatment","Plastic and Reconstructive Surgery"),
             ("Conservative treatment","Physical Medicine and Rehabilitation"),
             ("Ideal","The two specialties working together"),
             ("Warning","The underlying cause must be investigated first")],
 "authority":"Lymphedema microsurgery is a distinct field within plastic surgery — not every plastic surgeon performs these operations. Assoc. Prof. Dr. Acarturk has performed 300+ microsurgical cases at the University of Pittsburgh, participates in the work of the European lymphatic microsurgery group and has presented at the World Congress of Lymphology.",
 "creds":["Former Director of Head and Neck Reconstruction, University of Pittsburgh — 300+ microsurgical cases",
          "Participation in the European lymphatic microsurgery group",
          "Presentation at the World Congress of Lymphology"],
 "sections":[
  {"id":"kisa","tag":"Short Answer","h2":"The short answer","body":[
   "Two main specialties are involved in lymphedema, and both are necessary:",
   ("ul",["<strong>Plastic and Reconstructive Surgery</strong> — conducts surgical treatment. Lymphatic microsurgery (LVA), vascularised lymph node transfer and reduction surgery belong to this field.",
          "<strong>Physical Medicine and Rehabilitation</strong> — conducts conservative treatment. Complex decongestive physiotherapy, manual lymphatic drainage, bandaging and compression garment planning are carried out here."]),
   ("note","These two specialties are not alternatives to one another but complementary. Physiotherapy continues after surgery; surgery comes into play for the patient whose condition cannot be controlled by physiotherapy. The best results are obtained in centres where the two work together.")]},
  {"id":"hangi-durumda","tag":"Referral","h2":"Who should you see, and when?","body":[
   ("table",["Your situation","Department to consult"],[
     ["New swelling, no diagnosis made","First a doctor who will investigate the cause: your family doctor or the relevant specialist"],
     ["Arm/leg swelling after cancer treatment","Plastic surgery + physical medicine (together)"],
     ["Diagnosed, receiving physiotherapy but not sufficient","Plastic and reconstructive surgery — assessment for surgical candidacy"],
     ["Early stage, wishing to learn surgical options","Plastic and reconstructive surgery (lymphatic microsurgery)"],
     ["Recurrent cellulitis attacks","Infectious diseases + the lymphedema team"],
     ["Sudden painful one-sided swelling","Emergency department — vascular obstruction must be excluded"]]),
   ("note","Sudden, painful, one-sided swelling raises the possibility of deep vein thrombosis and is an emergency. Lymphedema assessment follows once that possibility has been excluded.")]},
  {"id":"branslar","tag":"Specialties","h2":"The role of other specialties","body":[
   ("ul",["<strong>Oncology:</strong> follow-up and referral of the patient still undergoing cancer treatment",
          "<strong>General surgery / gynaecology / urology:</strong> monitoring and early referral of the patient who has had lymph node dissection",
          "<strong>Radiology:</strong> lymphatic mapping with lymphoscintigraphy, MR lymphangiography and ICG lymphography",
          "<strong>Cardiology / nephrology:</strong> exclusion of systemic causes of oedema",
          "<strong>Vascular surgery:</strong> distinguishing venous insufficiency and deep vein thrombosis",
          "<strong>Infectious diseases:</strong> management of recurrent cellulitis",
          "<strong>Dermatology:</strong> skin complications and fungal infections"])]},
  {"id":"hazirlik","tag":"Preparation","h2":"How should you prepare for your appointment?","body":[
   "Going to the right department matters, and so does arriving prepared. What to bring with you:",
   ("ul",["<strong>Operation reports:</strong> particularly whether lymph node dissection was performed and how many nodes were removed",
          "<strong>Radiotherapy details:</strong> which region, how many sessions",
          "<strong>Imaging records:</strong> if lymphoscintigraphy or MRI has been performed before",
          "<strong>Circumference measurements:</strong> any previous measurement records",
          "<strong>Photographs:</strong> showing how the swelling has changed over time",
          "<strong>Infection history:</strong> how many episodes of cellulitis, and when",
          "<strong>Your medications and compression garment details</strong>"]),
   ("note","<strong>When the swelling began</strong> and <strong>how long it has lasted</strong> are among the most decisive pieces of information in deciding surgical candidacy. Being able to answer these two questions clearly directly increases the value of your appointment.")]},
  {"id":"cerrah-secimi","tag":"Choosing a Surgeon","h2":"What to look for when choosing a lymphedema surgeon","body":[
   "Lymphatic microsurgery is the most technically demanding subfield of plastic surgery: it involves working with channels 0.3–0.8 mm in diameter. Not every plastic surgeon performs these operations. Reasonable questions to ask:",
   ("ul",["How much microsurgical experience? How many cases?",
          "Can ICG lymphography or lymphoscintigraphy be performed at the centre?",
          "Is the work done together with a physiotherapy team?",
          "Is it explained clearly which operation is advised at which stage?",
          "Are realistic expectations discussed — or is a complete cure promised?"]),
   ("note","A promise of complete cure is a warning sign in lymphedema. An honest assessment speaks in terms of measurable goals: reduction in volume, fewer infections and less dependence on compression garments.")]}],
 "faqs":[
  ("Which specialist treats lymphedema?","Plastic and Reconstructive Surgery for surgical treatment, Physical Medicine and Rehabilitation for conservative treatment. These two specialties are complementary, not alternatives."),
  ("Should I go to physiotherapy first?","Physiotherapy is the foundation of treatment and is the first step for most patients. However, assessing surgical options in the early stage is also important, because intervening while the lymphatic channels still work is more effective than intervening after the tissue has hardened. Ideally the two assessments run in parallel."),
  ("Does every plastic surgeon perform lymphedema surgery?","No. Lymphatic microsurgery requires separate experience; it involves working under the microscope with channels 0.3–0.8 mm in diameter. It is reasonable to ask about the surgeon's microsurgical experience and the centre's imaging facilities."),
  ("Are these operations performed in state hospitals?","Lymphatic microsurgery is performed at some university and training-and-research hospitals. The number of centres is limited; confirming that a centre works in this field before applying will save time."),
  ("Which investigations are requested for lymphedema?","ICG lymphography and lymphoscintigraphy are most often used; MR lymphangiography may be preferred in advanced and complex cases. Circumference measurements and clinical assessment are performed in every patient."),
  ("Is it right to seek a second opinion?","Yes, particularly for a surgical decision. In lymphedema the stage and imaging findings directly determine the treatment option; an assessment from a different centre may clarify your decision.")],
 "ctah":"The first step towards the right department",
 "ctap":"Tell us when the swelling began, which treatments you have received and what reports you hold; we will determine together which assessment suits you."},

"lenfodem-evreleri": {
 "crumb":"Lymphedema Stages",
 "title":"Lymphedema Stages: ISL Classification and Treatment | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Lymphedema Stages and Their Treatment",
 "desc":"What are the stages of lymphedema? Findings of ISL stages 0, 1, 2 and 3, how staging is performed and which treatment is appropriate at each stage.",
 "eyebrow":"Microsurgery Programme",
 "h1":"Stages of lymphedema",
 "lead":"Stage is the single most important piece of information determining the treatment option in lymphedema. The same swelling requires a completely different treatment at different stages. This page explains what the stages mean and what is possible in each.",
 "watopic":"lymphedema staging",
 "about":"Lymphedema",
 "aboutType":"MedicalCondition",
 "card":"Lymphedema stages","cardsub":"ISL classification and treatment by stage",
 "procedure":{"name":"Lymphedema Staging",
   "how":"Clinical findings, tissue consistency and imaging are assessed together according to the International Society of Lymphology (ISL) classification to determine the stage.",
   "prep":"Circumference measurements, Stemmer's sign, ICG lymphography or lymphoscintigraphy.",
   "follow":"A treatment plan appropriate to the stage and regular reassessment.",
   "body":"Lymphatic system"},
 "keyfacts":[("Stage 0","Detected on imaging, no swelling"),
             ("Stage 1","Partly resolves on elevation, pits on pressure"),
             ("Stage 2","Does not resolve on elevation, tissue hardens"),
             ("Stage 3","Marked volume, skin thickening")],
 "authority":"Staging is the framework that determines treatment but is not sufficient on its own — it must be interpreted together with imaging findings. As a microsurgeon who participates in the work of the European lymphatic microsurgery group and has presented at the World Congress of Lymphology, Assoc. Prof. Dr. Acarturk assesses these two sets of data together.",
 "creds":["Participation in the European lymphatic microsurgery group",
          "Presentation at the World Congress of Lymphology",
          "300+ microsurgical cases at the University of Pittsburgh"],
 "sections":[
  {"id":"isl","tag":"ISL Classification","h2":"The ISL staging system","body":[
   "The classification of the International Society of Lymphology (ISL) is the framework accepted worldwide. The stages describe the condition of the tissue and its reversibility.",
   ("table",["Stage","Clinical findings","Tissue state"],[
     ["Stage 0 (latent)","No visible swelling; the patient may feel heaviness","Transport capacity reduced, tissue normal"],
     ["Stage 1","Swelling increases through the day, partly resolves on elevation; pits on pressure","Fluid accumulation predominates, reversible"],
     ["Stage 2","Does not resolve on elevation; pitting gradually diminishes","Fibrosis and fat deposition have begun"],
     ["Stage 3 (elephantiasis)","Marked increase in volume, thickened skin, wart-like changes","Advanced fibrosis, permanent tissue change"]]),
   ("note","<strong>Stage 0 is the most valuable stage.</strong> There is no visible swelling but a reduction in transport capacity is detected on imaging. In a patient caught at this stage, preventive and least invasive options are available. This is why regular follow-up matters in patients at risk.")]},
  {"id":"tedavi","tag":"Stage–Treatment","h2":"Which treatment at which stage?","body":[
   "Stage directly determines which surgical option is applicable. The basic logic is this: <strong>if the lymphatic channels still work, redirect the flow; if they do not, bring in new tissue or reduce the volume.</strong>",
   ("table",["Stage","Priority approach"],[
     ["Stage 0","Follow-up, skin care, risk reduction; preventive LVA in selected patients"],
     ["Stage 1","LVA — the least invasive and most effective option"],
     ["Stage 2","LVA and/or vascularised lymph node transfer"],
     ["Stage 3","Lymph node transfer + reduction surgery (liposuction, excision)"]]),
   ("note","This table is a framework, not a prescription. The final decision is made together with whether working lymphatic channels are visible on imaging, the duration of the swelling, the history of infection and the patient's general condition. Two patients at the same stage may be offered different operations.")]},
  {"id":"nasil","tag":"How It Is Determined","h2":"How is the stage determined?","body":[
   "Staging is not done by looking alone; clinical examination and imaging are used together.",
   ("h3","Clinical assessment"),
   ("ul",["Circumference measurements — compared with the opposite limb",
          "Pitting test — fluid or fibrosis",
          "Stemmer's sign",
          "Skin quality and thickness",
          "History and frequency of infection"]),
   ("h3","Imaging"),
   ("ul",["<strong>ICG lymphography:</strong> a real-time map of working lymphatic channels. Decisive in planning LVA.",
          "<strong>Lymphoscintigraphy:</strong> assessment of lymphatic flow and nodal involvement",
          "<strong>MR lymphangiography:</strong> detailed anatomical imaging; in advanced and complex cases"]),
   ("note","Clinical stage and imaging findings do not always coincide. A patient who appears clinically stage 2 may still have working channels on ICG — which raises the possibility of LVA. For this reason a surgical decision should not be made without imaging.")]},
  {"id":"ilerleme","tag":"Progression","h2":"Movement between stages, and time","body":[
   "Lymphedema is a progressive disease, but the rate of progression varies greatly from person to person. Some patients remain at stage 1 for years, while in others the picture advances rapidly.",
   ("h3","Factors that accelerate progression"),
   ("ul",["Recurrent cellulitis attacks — the strongest accelerator",
          "Weight gain",
          "Irregular use of compression garments",
          "Time passed without treatment",
          "Additional trauma or surgery"]),
   ("h3","Factors that slow progression"),
   ("ul",["Regular use of compression garments",
          "Skin care and infection prevention",
          "Weight control",
          "Regular movement and exercise",
          "Early surgical intervention"]),
   ("note","Can a stage be reversed? In the early stage — while fluid accumulation predominates — marked regression is possible with treatment. Once fibrosis is established, the tissue change is permanent; at this stage the aim is to reduce volume and halt progression.")]}],
 "faqs":[
  ("How many stages of lymphedema are there?","Four, according to the International Society of Lymphology (ISL) classification: stage 0 (latent), stage 1, stage 2 and stage 3 (elephantiasis). The stages describe the condition of the tissue and its reversibility."),
  ("What does stage 0 mean?","There is no visible swelling, but lymphatic transport capacity is reduced and this is detected on imaging. The patient may feel heaviness or tightness. It is the stage at which treatment options are widest."),
  ("At which stage is surgery performed?","At stages 1 and 2, LVA comes to the fore if the lymphatic channels still work. At stages 2–3, vascularised lymph node transfer and reduction surgery are planned. The decision is made together with imaging findings."),
  ("Can a stage be reversed?","In the early stage, while fluid accumulation predominates, marked regression is possible with treatment. Once fibrosis is established the tissue change is permanent; at this stage the aim is to reduce volume and halt progression."),
  ("What happens if my stage advances?","Treatment options narrow. Whereas LVA, the least invasive method, is possible in the early stage, more extensive surgery becomes necessary in advanced stages. The risk of infection and loss of function also increase."),
  ("If it does not pit, is the stage more advanced?","Usually yes. A pit remains in the early stage; as the tissue hardens with fibrosis no pit remains. This is an important examination finding indicating that the picture has advanced.")],
 "ctah":"Let us determine your stage together",
 "ctap":"Tell us how long the swelling has lasted, whether it resolves on elevation, your history of cellulitis and any imaging results you have; attach a photograph if possible."},
}
