# -*- coding: utf-8 -*-
"""Ingilizce ceviriler — parti 4: estetik cerrahi sayfalari."""

STEPS = lambda op, days, back: ("steps",[
 ("STEP 1 — FIRST CONTACT","Initial contact via WhatsApp or the form, based on your expectations, medical history and any photographs."),
 ("STEP 2 — EXAMINATION AND PLANNING","Assessment of your anatomy and open discussion of applicable techniques, risks and realistic expectations."),
 ("STEP 3 — PREPARATION","Blood tests, anaesthetic assessment, adjustment of smoking and blood-thinning medication."),
 ("STEP 4 — SURGERY", op),
 ("STEP 5 — FIRST DAYS", days),
 ("STEP 6 — RETURN AND FOLLOW-UP", back)])

T = {
"meme-estetigi": {
 "crumb":"Breast Aesthetics",
 "title":"Breast Aesthetics: Augmentation, Reduction and Lift | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Breast Aesthetics: Augmentation, Reduction and Lift",
 "desc":"Breast augmentation, reduction and lift (mastopexy): implant selection, scar patterns, breastfeeding, recovery and frequently asked questions.",
 "eyebrow":"Aesthetic Surgery",
 "h1":"Breast aesthetics: augmentation, reduction, lift",
 "lead":"There is no single right answer in breast surgery. The right answer is the plan that fits your proportions, your tissue quality and the way you live. Some patients want volume, others want to reduce the load; for most, the real issue is regaining shape and lift.",
 "watopic":"breast aesthetic surgery",
 "about":"Breast aesthetic surgery",
 "card":"Breast aesthetics","cardsub":"Augmentation, reduction and lift",
 "procedure":{"name":"Breast Aesthetic Surgery",
   "how":"Depending on the goal, an implant is placed, breast tissue is reduced and reshaped, or the breast tissue is repositioned higher on the chest wall.",
   "prep":"Examination, measurements, breast imaging and implant planning.",
   "follow":"Sports bra, lifting restrictions and scheduled reviews.","body":"Breast"},
 "keyfacts":[("Anaesthesia","General anaesthesia"),("Duration","1.5–3 hours"),
             ("Return to work","5–10 days"),("Exercise","After 4–6 weeks")],
 "authority":"In breast aesthetics, Assoc. Prof. Dr. Acarturk uses a reduction technique that <strong>leaves less scarring and lifts the breast further</strong> than the approach favoured by his American colleagues. Because of this, surgeons in Pittsburgh referred to him in particular those younger patients for whom the aesthetic result was paramount.",
 "creds":["A breast reduction technique that leaves less scarring","High-volume breast surgery practice in the US through peer referrals","An integrated approach informed by breast reconstruction experience"],
 "sections":[
  {"id":"buyutme","tag":"Augmentation","h2":"Breast augmentation","body":[
   "Performed for volume loss, a congenitally small breast or emptying after pregnancy. The aim is not a large breast but a volume that harmonises with your body and looks natural.",
   ("h3","Choosing an implant"),
   ("ul",["<strong>Placement:</strong> under the muscle, over the muscle or dual plane. Your tissue thickness is decisive; in thin tissue, a submuscular position gives a more natural result.",
          "<strong>Shape:</strong> round implants add fullness to the upper pole; teardrop implants create a more natural slope.",
          "<strong>Surface and size:</strong> chosen according to the width of your chest. An implant larger than your anatomy can carry leads to sagging and tissue thinning in the long term."]),
   ("h3","Augmentation with fat grafting"),
   "A limited increase in volume can be achieved with your own fat tissue. It contains no foreign material and feels natural, but the increase is smaller than with an implant and part of the grafted fat is reabsorbed.",
   ("note","Implants are not lifetime devices. They may need to be replaced over the years; regular review and imaging where indicated are part of the plan.")]},
  {"id":"kucultme","tag":"Reduction","h2":"Breast reduction","body":[
   "Breast reduction is not merely an aesthetic preference. Large breasts cause back, neck and shoulder pain, bra strap grooving, fungal infection beneath the breast and postural problems. The phrase patients use most often afterwards is \"I wish I had done this sooner.\"",
   "Assoc. Prof. Dr. Acarturk uses a technique that <strong>leaves less scarring and lifts the breast further</strong> than the approach common among his American colleagues; younger patients for whom appearance was paramount were referred to him for this reason.",
   ("h3","Scar patterns"),
   ("ul",["<strong>Vertical scar (lollipop):</strong> around the areola and vertically downwards. Preferred for moderate reductions.",
          "<strong>Inverted T (anchor):</strong> a horizontal line in the inframammary fold in addition to the vertical scar. Required for very large volumes."]),
   ("note","Reduction also lifts the breast; a separate mastopexy is not required. Breastfeeding remains possible for most patients, but because the milk ducts are involved it cannot be guaranteed.")]},
  {"id":"dikleştirme","tag":"Lift","h2":"Breast lift (mastopexy)","body":[
   "Pregnancy, breastfeeding, weight change and gravity gradually move breast tissue downwards. Mastopexy raises the breast to where it should sit and repositions the nipple, without adding or removing tissue.",
   ("ul",["Sagging only: mastopexy alone is sufficient",
          "Sagging plus volume loss: mastopexy combined with an implant",
          "Sagging plus excess volume: a reduction addresses both at once"]),
   "Which group you fall into is determined by the position of the nipple relative to the inframammary fold. This distinction directly changes the surgical plan."]},
  {"id":"surec","tag":"Process","h2":"The recovery process","body":[
   STEPS("1.5–3 hours under general anaesthesia, usually with one night in hospital.",
         "Support with a sports bra. A feeling of tightness in the first days is normal; pain is well controlled.",
         "Return to desk work in 5–10 days. Heavy lifting and exercise are deferred for 4–6 weeks. The final shape settles at 3–6 months and scars fade within a year.")]}],
 "faqs":[
  ("Can I breastfeed after surgery?","In augmentation the milk ducts are usually untouched and breastfeeding is possible. In reduction and lift surgery some ducts may be affected; most patients can still breastfeed, but it cannot be guaranteed. Share your plans before surgery."),
  ("How visible will the scars be?","Scars are red and prominent in the first months, then fade towards skin tone by the end of the first year. Silicone tape, sun protection and not smoking directly affect scar quality."),
  ("Do implants last a lifetime?","No. Implants are medical devices that may require replacement over time. No fixed lifespan can be guaranteed; regular review and imaging where indicated are recommended."),
  ("Will breast reduction be covered by insurance?","Where back and neck pain and skin problems caused by large breasts are documented, some policies provide cover. Conditions vary by policy and should be clarified before surgery."),
  ("Will surgery interfere with my mammograms?","No. Special imaging techniques (the Eklund view) are used in patients with implants. Your breast cancer screening continues on its normal schedule; simply inform the radiology team."),
  ("Will I lose sensation in the nipple?","Temporary changes in sensation are common and largely resolve over months. Permanent reduction in sensation is uncommon but possible; the risk is slightly higher in reduction than in augmentation.")],
 "ctah":"Breast aesthetic assessment",
 "ctap":"Share what you would like to change, your pregnancy and breastfeeding plans, any previous breast surgery, and your height and weight."},

"yuz-germe": {
 "crumb":"Facelift",
 "title":"Facelift and Neck Rejuvenation — SMAS Techniques | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Facelift and Neck Rejuvenation",
 "desc":"What a facelift involves: SMAS and deep plane techniques, planning together with a neck lift, scar placement and the recovery process.",
 "eyebrow":"Aesthetic Surgery",
 "h1":"Facelift and neck rejuvenation",
 "lead":"Ageing is not simply sagging skin: the fat pads descend, volume is lost and the muscle layer slackens. Tightening skin alone produces a taut but still aged face. The right result comes from returning the tissues to where they belong.",
 "watopic":"facelift surgery",
 "about":"Rhytidectomy",
 "card":"Facelift","cardsub":"Face and neck rejuvenation using SMAS and deep plane techniques",
 "procedure":{"name":"Facelift (Rhytidectomy)",
   "how":"The SMAS layer beneath the skin is released and repositioned upwards and backwards; excess skin is then removed without creating tension.",
   "prep":"Examination, photographic analysis, blood tests and smoking cessation.",
   "follow":"Facial dressing, management of swelling, resting with the head elevated in the first week.","body":"Face and neck"},
 "keyfacts":[("Anaesthesia","General anaesthesia"),("Duration","4–6 hours"),
             ("Social return","2–3 weeks"),("Longevity","8–12 years")],
 "authority":"What determines the result in a facelift is correct handling of the deep tissues, not the skin. Assoc. Prof. Dr. Acarturk's background in head and neck reconstruction and facial skeletal surgery gives him command of every layer of facial anatomy. His subspecialty in Oral & Maxillofacial Surgery is a qualification held by few plastic surgeons.",
 "creds":["Subspecialty in Oral & Maxillofacial Surgery","Former Director of Head & Neck Reconstruction, University of Pittsburgh","Experience in fat grafting and stem-cell assisted volume restoration"],
 "sections":[
  {"id":"teknik","tag":"Technique","h2":"The SMAS and deep plane approach","body":[
   "Beneath the skin of the face lies a layer of muscle and connective tissue called the SMAS. This is the structure that actually descends with ageing. In a modern facelift the skin is only a covering; the load is carried by the SMAS layer.",
   ("ul",["<strong>SMAS plication:</strong> the layer is folded and suspended. Less invasive, suitable for moderate laxity.",
          "<strong>SMAS ectomy:</strong> a strip is excised from the layer to create tension.",
          "<strong>Deep plane:</strong> the SMAS and skin are raised and repositioned as a single unit. This gives a stronger, longer-lasting result in the midface and nasolabial region."]),
   ("note","A \"pulled\" appearance is the result of over-tightening the skin. When the SMAS layer carries the load, skin tension stays low, expression remains natural and scar quality is markedly better.")]},
  {"id":"boyun","tag":"Neck","h2":"Planning together with a neck lift","body":[
   "The face and neck cannot be considered separately. A slack neck beneath a rejuvenated face undermines the whole result. Three distinct problems may coexist in the neck:",
   ("ul",["Fat accumulation beneath the chin — removed with liposuction",
          "Separation of the platysma muscle in the midline forming bands — repaired with sutures (platysmaplasty)",
          "Excess, slackened skin — suspended through the incision behind the ear"]),
   "Which of these components you have is determined at examination, and the plan is built accordingly."]},
  {"id":"tamamlayici","tag":"Complementary","h2":"Complementary procedures","body":[
   "A facelift corrects sagging but <strong>does not restore lost volume</strong>. Most plans therefore include fat grafting: the temples, cheekbones and hollows beneath the eyes are filled with your own fat.",
   ("ul",["<a href=\"../goz-kapagi-estetigi.html\">Eyelid surgery</a> — frequently combined to remove the tired look from the eyes",
          "<a href=\"../yag-enjeksiyonu.html\">Fat grafting</a> — restoration of lost volume",
          "Brow lift — where forehead and brow descent is marked",
          "Skin resurfacing — for pigmentation and fine lines, after healing is complete"]),
   ("note","A facelift does not change skin quality. Pigmentation, fine lines and pore problems are not corrected by surgery; these require separate resurfacing treatments, usually planned after healing is complete.")]},
  {"id":"surec","tag":"Process","h2":"The recovery process","body":[
   STEPS("4–6 hours under general anaesthesia, with one night in hospital.",
         "Facial dressing and drains. Swelling and bruising peak on days 4–7; resting with the head elevated is necessary in the first week.",
         "Sutures are removed on days 7–10. Most patients return to social life in 2–3 weeks. Swelling fully resolves and scars fade over 6–12 months."),
   ("ul",["Smoking impairs wound healing and significantly increases the risk of skin loss — it should be stopped at least 4 weeks beforehand",
          "Heavy exercise and bending forward are restricted for the first 3 weeks",
          "Hair colouring is usually deferred for 4–6 weeks"])]}],
 "faqs":[
  ("How long does a facelift last?","Surgery turns the clock back but does not stop it. In a well-planned lift carried by the SMAS layer, the result is generally maintained for 8–12 years; ageing continues from that point."),
  ("Where are the scars?","Incisions are hidden within the hairline, in the natural crease in front of the ear and behind the ear. Correctly planned, they lie in the shadow of the hair and ear and are not noticeable at normal distance."),
  ("Do thread lifts replace a facelift?","No. Threads provide a limited, temporary effect that usually disappears within 1–2 years. They are not an alternative to surgical lifting where sagging is marked."),
  ("At what age should a facelift be done?","Tissue condition, not age, is decisive. Most patients are between 45 and 65, though it may be appropriate earlier for those who age early or have lost significant weight."),
  ("Will my expression change?","The aim is to preserve expression. When the load is placed on the SMAS layer rather than the skin, expression stays natural. Temporary weakness from nerve irritation is uncommon and usually resolves within weeks."),
  ("When can I attend a business meeting?","Bruising is usually coverable at around 2 weeks, and feeling comfortable takes about 3. If you have an important event, allow at least 4 weeks.")],
 "ctah":"Facelift assessment",
 "ctap":"Tell us what bothers you most, any previous aesthetic procedures, and send front and side photographs if you have them."},

"goz-kapagi": {
 "crumb":"Eyelid Surgery",
 "title":"Eyelid Surgery (Blepharoplasty) — Upper and Lower Lids | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Eyelid Surgery (Blepharoplasty)",
 "desc":"Upper and lower eyelid surgery: drooping lids, under-eye bags, local anaesthesia, recovery and frequently asked questions.",
 "eyebrow":"Aesthetic Surgery",
 "h1":"Eyelid surgery (blepharoplasty)",
 "lead":"The eye area is the first part of the face to age. Drooping upper lids make the gaze look tired and, when advanced, narrow the field of vision; lower lid bags make even a well-rested person look exhausted. Blepharoplasty changes expression markedly through a small procedure.",
 "watopic":"eyelid surgery",
 "about":"Blepharoplasty",
 "card":"Eyelid surgery","cardsub":"Upper and lower lids, under-eye bags",
 "procedure":{"name":"Blepharoplasty",
   "how":"Excess skin and, where needed, fat is removed from the upper lid through the natural crease; in the lower lid the fat pads are redistributed or reduced.",
   "prep":"Eye examination, visual field testing where indicated and assessment for dry eye.",
   "follow":"Cold compresses, eye drops and avoiding straining in the first week.","body":"Eyelids"},
 "keyfacts":[("Anaesthesia","Usually local + sedation"),("Duration","45–90 minutes"),
             ("Suture removal","Days 5–7"),("Social return","7–10 days")],
 "authority":"The eye region is the part of facial anatomy that demands the finest detail. Drawing on his background in facial skeletal surgery and head and neck reconstruction, Assoc. Prof. Dr. Acarturk assesses the eyelid together with the surrounding structures, and also provides surgical solutions for eyelid problems caused by facial paralysis.",
 "creds":["Subspecialty in Oral & Maxillofacial Surgery","Experience in eyelid reconstruction in facial paralysis","Practice in facial skeletal and orbital surgery"],
 "sections":[
  {"id":"ust","tag":"Upper Lid","h2":"Upper eyelid surgery","body":[
   "Over time the skin of the upper lid slackens and droops towards the lash line. This gives the gaze a tired and severe expression; when advanced it rests on the lashes, narrowing the visual field and causing constant contraction of the forehead muscles.",
   "Excess skin is removed through the <strong>natural crease of the lid</strong>. Because the scar lies within this crease, it is largely concealed once healed. The fat pad at the inner corner is reduced where required.",
   ("note","Brow descent can be mistaken for eyelid laxity. If the real problem is a descended brow, eyelid surgery alone will leave the result insufficient and may even pull the brow lower. The distinction is made at examination.")]},
  {"id":"alt","tag":"Lower Lid","h2":"Lower eyelid and under-eye bags","body":[
   "Fullness of the lower lid usually arises not from excess skin but from <strong>fat pads pushing forwards</strong>. Removing skin alone therefore does not correct it and can cause the lid to be pulled downwards.",
   ("ul",["<strong>Transconjunctival approach:</strong> the incision is made inside the lid, leaving no external scar. Preferred in younger patients without excess skin.",
          "<strong>Fat repositioning:</strong> rather than removing the fat entirely, it is spread into the hollow beneath the eye, preventing a hollow, shadowed appearance.",
          "<strong>Skin incision approach:</strong> used through a fine incision beneath the lashes where there is marked excess skin."]),
   ("note","Under-eye darkness does not always come from bags. Where it is caused by vessels showing through thin skin or by pigmentation, surgery will not correct it; this distinction must be made beforehand.")]},
  {"id":"surec","tag":"Process","h2":"The recovery process","body":[
   STEPS("Local anaesthesia with sedation is sufficient for most patients; the procedure takes 45–90 minutes and you go home the same day.",
         "Regular cold compresses for the first 48 hours. Swelling and bruising peak on days 2–3; sleeping with the head elevated speeds recovery.",
         "Sutures are removed on days 5–7. Most patients return to social life with make-up in 7–10 days; fine swelling may persist for a few weeks more."),
   ("ul",["Avoid heavy lifting and bending forward in the first week",
          "Contact lenses are usually deferred for 2 weeks",
          "Dryness at screens is common; artificial tears are recommended",
          "Sunglasses and sun protection should be used in the first months"])]}],
 "faqs":[
  ("Is eyelid surgery covered by insurance?","Where drooping of the upper lid narrows the visual field and this is documented by visual field testing, some policies provide cover. Conditions vary by policy."),
  ("How many years before it needs repeating?","The result of upper lid surgery is generally maintained for 10 years or more. Where lower lid fat has been repositioned the result is long lasting; further work may be needed years later as ageing continues."),
  ("Will my eyes look slanted?","In a correctly planned blepharoplasty the shape of the eye does not change. Removing too much skin or failing to support the lower lid can cause this appearance, which is why measurement matters more than the amount of tissue removed."),
  ("What is the difference from Botox?","Botox reduces lines caused by muscle movement; it does not correct drooping skin or fat bags. The two are not alternatives but solutions to different problems, and can be planned together."),
  ("I have dry eyes — can I still have surgery?","This must be declared beforehand. Dry eye can worsen temporarily after surgery; in that case planning is more conservative and made together with your ophthalmologist.")],
 "ctah":"Eyelid assessment",
 "ctap":"Tell us what bothers you about the appearance, whether you have any complaints about your vision, and send close-up photographs if you have them."},

"karin-germe": {
 "crumb":"Tummy Tuck",
 "title":"Tummy Tuck (Abdominoplasty) — Muscle Repair and Recovery | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Tummy Tuck (Abdominoplasty)",
 "desc":"Abdominoplasty: who is a suitable candidate, repair of muscle separation (diastasis), how mini abdominoplasty differs, scar placement and the recovery process.",
 "eyebrow":"Aesthetic Surgery",
 "h1":"Tummy tuck (abdominoplasty)",
 "lead":"Pregnancy and major weight loss leave two lasting marks on the abdomen: slack excess skin and abdominal muscles separated in the midline. Neither returns with diet or exercise. A tummy tuck repairs the skin and the muscle wall together.",
 "watopic":"tummy tuck surgery",
 "about":"Abdominoplasty",
 "card":"Tummy tuck","cardsub":"Repair of excess skin and separated abdominal muscles",
 "procedure":{"name":"Abdominoplasty",
   "how":"Excess skin and fat are removed through an incision along the bikini line, the separated abdominal muscles are brought together in the midline with sutures and the navel is reshaped.",
   "prep":"A stable target weight, smoking cessation, blood tests and hernia assessment where indicated.",
   "follow":"Compression garment, early walking, lifting restrictions.","body":"Abdomen"},
 "keyfacts":[("Anaesthesia","General anaesthesia"),("Duration","2–4 hours"),
             ("Hospital","1–2 nights"),("Return to work","2–3 weeks")],
 "authority":"A tummy tuck is as much a functional repair of the abdominal wall as an aesthetic procedure. Assoc. Prof. Dr. Acarturk's three years of general surgery training and his experience in abdominal wall reconstruction allow muscle repair and any accompanying hernia to be addressed safely in the same operation.",
 "creds":["Three years of general surgery training — abdominal wall and hernia surgery","Experience in trunk and abdominal reconstruction","Command of abdominal anatomy through DIEP flap surgery"],
 "sections":[
  {"id":"kimler","tag":"Who It Is For","h2":"Who is it suitable for?","body":[
   ("ul",["Those whose abdominal skin has slackened and muscles separated after pregnancy",
          "Those with sagging abdominal skin after significant weight loss",
          "Those with lower abdominal sagging that does not respond to diet and exercise",
          "Those whose weight is stable and who can maintain it"]),
   ("h3","Who is it not suitable for?"),
   ("ul",["Those planning significant weight loss — surgery should follow, not precede, the target weight",
          "Those planning pregnancy in the near future — pregnancy separates the repaired muscle wall again",
          "Those unable to stop smoking — the risk of impaired healing and tissue loss increases markedly"]),
   ("note","A tummy tuck is not a weight loss method. It removes regional fat and excess skin; it does not reduce overall weight. Framing expectations this way is the single strongest predictor of satisfaction.")]},
  {"id":"diastazis","tag":"Muscle Repair","h2":"Diastasis: separated abdominal muscles","body":[
   "During pregnancy the growing uterus pushes the two straight abdominal muscles apart from the midline. After birth these muscles often do not return to their original position and the connective tissue between them remains stretched. This is called <strong>rectus diastasis</strong>.",
   "Diastasis does more than create a bulging abdomen; it also causes back pain, problems with intra-abdominal pressure and postural difficulty. Exercises such as sit-ups or planks do not close the gap and can widen it.",
   "In a tummy tuck these muscles are brought back together in the midline with sutures. The waist narrows and the abdominal wall regains functional strength. This is the functional rather than aesthetic side of the operation.",
   ("note","If an umbilical hernia is present it can be repaired during the same operation. Screening for hernia at examination, with imaging where required, is standard practice.")]},
  {"id":"tipler","tag":"Method","h2":"Full and mini abdominoplasty","body":[
   ("table",["","Full abdominoplasty","Mini abdominoplasty"],[
    ["Scope","Above and below the navel","Below the navel only"],
    ["Navel","Reshaped","Left in place"],
    ["Muscle repair","Along the full midline","Lower region only"],
    ["Scar","Longer, along the bikini line","Shorter"],
    ["Suitable candidate","Marked sagging and diastasis","Limited lower abdominal laxity"]]),
   "Liposuction accompanies most tummy tuck plans; shaping the waist and flanks determines the coherence of the result. Where sagging affects the whole trunk, a <a href=\"../kol-uyluk-germe.html\">body lift</a> may be considered."]},
  {"id":"surec","tag":"Process","h2":"The recovery process","body":[
   STEPS("2–4 hours under general anaesthesia, with 1–2 nights in hospital and drains placed.",
         "You walk slightly bent forward in the first days; this is normal and resolves within a few days. Early walking matters because it reduces the risk of clots.",
         "A compression garment is worn for 6 weeks. Return to desk work in 2–3 weeks; heavy exercise is deferred for 6–8 weeks. The final shape settles at 6 months."),
   ("ul",["Clot prevention: early mobilisation, compression stockings and anticoagulants where indicated",
          "No heavy lifting for the first 6 weeks",
          "Silicone tape and sun protection should be continued throughout the first year"])]}],
 "faqs":[
  ("Where is the scar and how long is it?","The incision is placed along the bikini line at a level that underwear can conceal. Its length depends on how much skin is removed; with marked sagging it extends between the hip bones. The scar is permanent but fades over time."),
  ("Can I become pregnant after surgery?","Medically yes, but pregnancy separates the repaired muscle wall again and re-stretches the skin. If you are planning a pregnancy, it is better to postpone surgery."),
  ("What is the difference between a tummy tuck and liposuction?","Liposuction only removes fat and suits patients with good skin quality. If the skin has slackened or the muscles have separated, liposuction alone is insufficient and can even worsen sagging."),
  ("How will my navel look?","In a full abdominoplasty the navel stays in place, the surrounding skin is pulled down and the navel is brought out through the new skin. A fine scar forms around it and becomes indistinct over time."),
  ("When can I start exercising?","Walking begins in the first days. Light cardio can be added after week 4 and abdominal exercises after week 8, gradually and with medical approval."),
  ("Will I lose sensation?","Temporary numbness below the navel is expected and largely returns over months. A small area of permanent reduced sensation is possible.")],
 "ctah":"Tummy tuck assessment",
 "ctap":"Share your pregnancy history, your weight change, how long your current weight has been stable, and photographs if you have them."},

"liposuction": {
 "crumb":"Liposuction and Body Contouring",
 "title":"Liposuction and Body Contouring | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Liposuction and Body Contouring",
 "desc":"What liposuction is, who it suits, VASER and power-assisted techniques, contouring with fat transfer, recovery and realistic expectations.",
 "eyebrow":"Aesthetic Surgery",
 "h1":"Liposuction and body contouring",
 "lead":"Liposuction is not a weight loss method; it removes regional fat deposits that resist diet and exercise and rebalances your proportions. In the right patient it produces a dramatic change in contour, in the wrong one disappointment. The difference begins with correct candidacy.",
 "watopic":"liposuction",
 "about":"Liposuction",
 "card":"Liposuction","cardsub":"Regional fat removal and body contouring",
 "procedure":{"name":"Liposuction",
   "how":"After tumescent fluid is infiltrated, subcutaneous fat is aspirated in a controlled manner through cannulas inserted via small incisions.",
   "prep":"A stable target weight, assessment of skin elasticity and compression garment fitting.",
   "follow":"Compression garments, lymphatic drainage massage and gradual return to activity.",
   "body":"Abdomen, waist, thighs, arms, back, under the chin"},
 "keyfacts":[("Anaesthesia","General or sedation"),("Duration","1–3 hours"),
             ("Compression","4–6 weeks"),("Final shape","3–6 months")],
 "authority":"Assoc. Prof. Dr. Acarturk is among the first Turkish plastic surgeons to have worked on adipose tissue and adipose-derived stem cell technologies at the University of Pittsburgh. This background allows him to treat liposuction not merely as fat removal but as a contouring tool in which the harvested tissue can be reused.",
 "creds":["Adipose tissue and stem cell research at the University of Pittsburgh","Experience in lymphatic-sparing liposuction techniques","Body contouring integrated with fat transfer"],
 "sections":[
  {"id":"kimler","tag":"Who It Is For","h2":"Who is the right candidate?","body":[
   "The most important factor in liposuction is not the amount of fat removed but <strong>the skin's capacity to retract</strong>. After fat is removed the skin must adapt to the new volume; in skin that has lost its elasticity, fat removal makes sagging visible.",
   ("ul",["Those close to their ideal weight but with regional fat deposits",
          "Those whose skin elasticity is preserved",
          "Those with a lifestyle that will maintain their weight",
          "Those with realistic expectations"]),
   ("note","If the skin has slackened, liposuction alone is insufficient. It then needs to be planned together with a <a href=\"../karin-germe.html\">tummy tuck</a> or an <a href=\"../kol-uyluk-germe.html\">arm or thigh lift</a>. Making this distinction in advance removes the most common cause of dissatisfaction.")]},
  {"id":"teknik","tag":"Technique","h2":"Techniques used","body":[
   ("ul",["<strong>Tumescent liposuction:</strong> a special fluid is infiltrated first; bleeding and pain are reduced and fat separates more easily. This underlies all methods.",
          "<strong>VASER (ultrasound assisted):</strong> ultrasound energy selectively breaks down fat cells. It offers an advantage in fibrous areas and in defining muscle contours.",
          "<strong>PAL (power assisted):</strong> a vibrating cannula allows work in dense tissue with less trauma.",
          "<strong>WAL (water-jet assisted):</strong> a water jet separates fat gently and, because it spares lymphatic structures, is preferred in <a href=\"../lipodem-cerrahisi.html\">lipedema surgery</a>."]),
   ("h3","Contouring with fat transfer"),
   "Harvested fat does not have to be discarded. It can be processed and transferred to areas where volume is desired, such as the buttocks, breast or face. This allows both slimming and volume enhancement in the same session. Details are on our <a href=\"../yag-enjeksiyonu.html\">fat grafting page</a>.",
   ("note","There is a limit to how much fat can safely be removed in a single session. Exceeding it disturbs fluid and electrolyte balance and creates serious risk. Where large areas are involved, treatment is divided into sessions.")]},
  {"id":"surec","tag":"Process","h2":"The recovery process","body":[
   STEPS("1–3 hours depending on the number of areas. Same-day discharge for limited areas; one night in hospital for larger ones.",
         "A compression garment is worn from day one. Bruising and swelling peak on days 3–5; some leakage in the first days is normal.",
         "Return to desk work in 3–7 days. Compression is worn for 4–6 weeks and exercise resumes gradually after 4 weeks. The final shape settles at 3–6 months."),
   ("ul",["Manual lymphatic drainage speeds the resolution of swelling",
          "Firmness and irregularity in the early period are normal and soften over time",
          "Maintaining the result depends on weight stability"])]}],
 "faqs":[
  ("Does the fat come back?","The removed fat cells do not return. However, if you gain weight the remaining fat cells enlarge and fat distribution may change, which can spoil the result."),
  ("Does liposuction remove cellulite?","No. Cellulite arises from the connective tissue bands tethering the skin and is not corrected by fat removal. In some cases it can even appear more visible afterwards."),
  ("How much weight will I lose?","Liposuction is not a weight loss method. The change on the scale is usually a few kilograms; the real difference is in measurements and clothing size."),
  ("Will my skin be uneven?","Firmness and a wavy sensation are normal in the early period and soften over months. The risk of permanent irregularity depends on cannula size and technique; it can be corrected with fat grafting if needed."),
  ("Is general anaesthesia essential?","Sedation with local anaesthesia may be sufficient for limited areas. General anaesthesia is preferred for larger areas for safety."),
  ("How long must I wear the compression garment?","Usually 4–6 weeks, full-time for the first 2–3. Compression directly helps swelling resolve and the skin settle to the new contour.")],
 "ctah":"Liposuction assessment",
 "ctap":"Tell us which areas concern you, your height and weight, and how long your weight has been stable; add photographs if you have them."},

"jinekomasti": {
 "crumb":"Gynecomastia",
 "title":"Gynecomastia Surgery (Male Breast Enlargement) | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Gynecomastia: Male Breast Enlargement and Its Surgical Treatment",
 "desc":"What gynecomastia is, its causes, how it differs from simple fatty tissue, surgical options, scar placement and the recovery process.",
 "eyebrow":"Aesthetic Surgery",
 "h1":"Gynecomastia (male breast enlargement)",
 "lead":"Gynecomastia is enlargement of breast tissue in men. It affects roughly one in three men at some point in life. It does not resolve with exercise or diet, because the problem is glandular tissue rather than fat. Surgery is the only lasting and effective solution.",
 "watopic":"gynecomastia surgery",
 "about":"Gynecomastia",
 "card":"Gynecomastia","cardsub":"Surgical treatment of male breast enlargement",
 "procedure":{"name":"Gynecomastia Surgery",
   "how":"Glandular tissue is excised through an incision at the lower border of the areola; surrounding fat is removed with liposuction to give the chest wall a natural male contour.",
   "prep":"Hormonal assessment, review of medication and substance use, breast ultrasound where indicated.",
   "follow":"Compression vest, restriction of heavy exercise.","body":"Chest"},
 "keyfacts":[("Prevalence","~30% of men"),("Anaesthesia","General or sedation"),
             ("Duration","1–2 hours"),("Return to work","3–7 days")],
 "authority":"What determines the result in gynecomastia surgery is the balance between removing the glandular tissue completely and leaving a natural contour on the chest wall. Assoc. Prof. Dr. Acarturk's background in breast surgery and body contouring allows both goals to be pursued together.",
 "creds":["Many years of practice in breast surgery","Experience in liposuction and contour surgery","Active surgical practice in the United States and Türkiye"],
 "sections":[
  {"id":"nedir","tag":"The Basics","h2":"What is gynecomastia and why does it occur?","body":[
   "Gynecomastia is enlargement of the male breast gland due to hormonal imbalance. It must be distinguished from simple fat accumulation (pseudogynecomastia): glandular tissue is felt as a firm disc beneath the areola, whereas fat is soft and diffuse.",
   ("h3","Main causes"),
   ("ul",["<strong>Puberty:</strong> the most common cause. The majority resolve spontaneously within 1–2 years.",
          "<strong>Medication:</strong> some blood pressure drugs, gastric medicines, antidepressants and prostate drugs",
          "<strong>Anabolic steroids and performance enhancers</strong>",
          "<strong>Hormonal disorders:</strong> thyroid, liver and testicular conditions",
          "<strong>Weight gain and ageing</strong>"]),
   ("note","An underlying cause should be investigated before surgery. One-sided, rapidly growing or firm and irregular masses require further investigation. In cases beginning at puberty, 1–2 years of observation is usual.")]},
  {"id":"derece","tag":"Grading","h2":"Grading and choice of method","body":[
   ("table",["Grade","Appearance","Approach"],[
    ["Grade 1","Limited enlargement around the areola, no excess skin","Gland excision ± liposuction"],
    ["Grade 2","Moderate enlargement, limited excess skin","Gland excision + liposuction"],
    ["Grade 3","Marked enlargement with excess skin","Excision + liposuction + skin tightening"],
    ["Grade 4","Female breast appearance, low nipple position","Excision + skin removal + nipple repositioning"]]),
   "In grades 1 and 2 the incision remains at the lower border of the areola and the scar is hidden in the colour transition. Grades 3 and 4 may require additional incisions; this is discussed openly during planning.",
   ("note","Performing liposuction alone is the most common reason gynecomastia recurs. Glandular tissue cannot be removed by liposuction; it remains as a firm disc beneath the areola and the complaint persists.")]},
  {"id":"surec","tag":"Process","h2":"The recovery process","body":[
   STEPS("1–2 hours under general anaesthesia or sedation, with same-day discharge for most patients.",
         "A compression vest is worn from day one. Bruising and swelling peak on days 3–5.",
         "Return to desk work in 3–7 days. Compression is worn for 4–6 weeks and chest exercises are deferred for 6 weeks. The final shape settles at 3–6 months."),
   ("ul",["Temporary firmness beneath the areola is normal",
          "Temporary change in nipple sensation may occur and returns over months",
          "Maintaining the result depends on weight stability and avoiding steroids"])]}],
 "faqs":[
  ("Will exercise resolve it?","No. Exercise can reduce fatty tissue but does not remove glandular tissue. The firm tissue beneath the areola does not respond to exercise; surgery is required."),
  ("Does it recur after surgery?","When the glandular tissue is fully removed, recurrence is not expected. However, anabolic steroid use, significant weight gain or a new hormonal problem can restart the process."),
  ("Will the scar be visible?","The incision is placed at the lower border of the areola, in the transition between dark and light skin. Scars healing along this line become indistinct over time. Higher grades may require additional scars."),
  ("Can it be operated on during puberty?","Usually 1–2 years of observation is advised, as most cases resolve spontaneously. However, where the social and psychological impact is marked and the picture has stabilised, earlier surgery may be considered."),
  ("Is it covered by insurance?","In some circumstances, particularly with pain and documented hormonal pathology, cover may be available. Conditions vary by policy."),
  ("When can I train my chest again?","Usually after 6 weeks, gradually and with medical approval. Heavy chest exercise started too early increases swelling and delays healing.")],
 "ctah":"Gynecomastia assessment",
 "ctap":"Tell us how long it has been present, any medication or supplements you use, and send front and side photographs if you have them."},
}
