# -*- coding: utf-8 -*-
"""Ingilizce ceviriler — parti 2: lenfodem, meme rekonstruksiyonu, mikrotia."""

T = {
"meme-rek": {
 "crumb":"Breast Reconstruction",
 "title":"Breast Reconstruction After Cancer — DIEP Flap and Implant | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Breast Reconstruction After Breast Cancer",
 "desc":"Breast reconstruction after mastectomy: DIEP flap using your own tissue, implant-based reconstruction, immediate versus delayed planning, and combined treatment of arm lymphedema.",
 "eyebrow":"Reconstructive Surgery",
 "h1":"Breast reconstruction after breast cancer",
 "lead":"Breast reconstruction is not the end of cancer treatment; it is part of recovery. It can be performed with your own tissue or with an implant, at the same time as the mastectomy or after treatment is complete. The right timing determines your options.",
 "watopic":"breast reconstruction",
 "about":"Breast reconstruction",
 "card":"Breast reconstruction","cardsub":"Reconstruction after cancer using your own tissue or an implant",
 "procedure":{"name":"Breast Reconstruction with a DIEP Flap",
   "how":"Skin, fat and their supplying vessels are taken from the lower abdomen without cutting muscle, then connected microsurgically to the chest vessels and shaped into a breast.",
   "prep":"Joint planning with the oncology team, vascular mapping (CT angiography) and review of the radiotherapy schedule.",
   "follow":"Monitoring of tissue perfusion, abdominal care and nipple reconstruction at a second stage.",
   "body":"Breast"},
 "keyfacts":[("Timing","Immediate or delayed"),("Own tissue","DIEP, TRAM, latissimus dorsi"),
             ("Implant","Tissue expander + implant"),("Additional option","Simultaneous lymphedema treatment")],
 "authority":"Breast reconstruction requires microsurgery and aesthetic surgery to be considered together. Assoc. Prof. Dr. Acarturk has many years of practice in both free tissue transfer and breast aesthetics; because he also performs lymphedema microsurgery, he is able to plan breast reconstruction and arm lymphedema treatment <strong>in the same operation</strong>.",
 "creds":["300+ free tissue transfer procedures","Simultaneous planning with lymphedema microsurgery","Breast surgery practice in the United States and peer referrals"],
 "sections":[
  {"id":"zamanlama","tag":"Timing","h2":"Immediate or delayed?","body":[
   ("h3","Immediate reconstruction"),
   "Performed during the same operation as the mastectomy. Because the breast skin is preserved, the result is usually more natural, the patient never experiences a period without a breast, and the total number of operations is reduced. It is preferred where radiotherapy is not anticipated.",
   ("h3","Delayed reconstruction"),
   "Performed after oncological treatment, particularly radiotherapy, is complete. Implants perform less well in irradiated tissue, so reconstruction with your own tissue comes to the fore in patients who receive radiotherapy.",
   ("note","The decision should be made together with your breast surgeon and radiation oncologist. Seeing a plastic surgeon <strong>before</strong> the mastectomy markedly widens the options available to you. Reconstruction does not make cancer follow-up more difficult and does not increase the risk of recurrence.")]},
  {"id":"yontem","tag":"Method","h2":"Reconstruction methods","body":[
   ("h3","DIEP flap — using your own tissue"),
   "Skin and fat from the lower abdomen are transferred to the chest with their supplying vessels. <strong>The abdominal muscle is not cut</strong>, which distinguishes this from the older TRAM technique; abdominal strength is preserved and the risk of hernia is reduced. The result is soft, drapes naturally and changes with your body as your weight changes.",
   ("h3","Implant-based reconstruction"),
   "A tissue expander is placed first and gradually filled over several weeks to stretch the skin, then replaced with a permanent implant. It involves a shorter operation and faster recovery, but the risk of capsular contracture is high in irradiated tissue.",
   ("h3","Latissimus dorsi flap"),
   "Muscle and skin taken from the back, usually combined with an implant. It is an option for patients whose abdominal tissue is insufficient or who have had previous abdominal surgery.",
   ("h3","Volume refinement with fat grafting"),
   "Your own fat tissue is used to correct contour irregularities and to improve the quality of irradiated skin. This is usually a complementary stage."]},
  {"id":"lenfodem","tag":"Additional Option","h2":"Combined treatment with arm lymphedema","body":[
   "Removal of the axillary lymph nodes and radiotherapy can lead to lymphedema of the arm. In patients planned for breast reconstruction, both problems can be addressed <strong>in a single operation</strong>: vascularised lymph node transfer can be performed at the same time as the tissue transfer.",
   "This spares the patient a second major operation and allows early intervention for lymphedema. For details, see our <a href=\"../lenfodem-lipodem-cerrahisi.html\">lymphedema surgery page</a>.",
   ("note","If you notice early signs such as a feeling of heaviness in the arm, or rings and watches becoming tight, do not wait. In lymphedema, early intervention is markedly more effective than treatment after tissue hardening has set in.")]},
  {"id":"surec","tag":"Process","h2":"Process and recovery","body":[
   ("steps",[
    ("STEP 1 — JOINT PLANNING","Decision on timing and method together with the breast surgeon and radiation oncologist."),
    ("STEP 2 — PREPARATION","Vascular mapping, assessment of abdominal tissue, smoking cessation and general preparation."),
    ("STEP 3 — SURGERY","6–8 hours for a DIEP flap; shorter for implant-based reconstruction. Hospital stay of 3–5 days."),
    ("STEP 4 — FIRST 6 WEEKS","Lifting restrictions, abdominal care and a gradual return to activity."),
    ("STEP 5 — 3–6 MONTHS","Symmetry adjustments, surgery to the opposite breast if needed, and nipple–areola reconstruction.")])]}],
 "faqs":[
  ("Does reconstruction hide a recurrence?","No. Studies show that breast reconstruction does not increase the risk of recurrence and does not make follow-up more difficult. Your oncological follow-up continues as normal."),
  ("What is the difference between DIEP and TRAM?","In a DIEP flap the abdominal muscle is not cut; only the vessels are dissected out of the muscle, so abdominal strength is preserved and the risk of hernia is reduced. In a TRAM flap part of the muscle is taken with the tissue."),
  ("What if I am going to have radiotherapy?","Implants perform less well in irradiated tissue and the risk of capsular contracture increases. For this reason, reconstruction with your own tissue and delayed reconstruction are generally preferred in patients who will receive radiotherapy."),
  ("Will I regain sensation?","Sensation in the transferred tissue is initially limited. Partial sensation may return over time; in some cases nerve coaptation can also be performed with the aim of restoring sensation."),
  ("What kind of scar will I have on my abdomen?","The incision is placed along the bikini line, similar to an abdominoplasty, and the navel is reshaped. The abdomen is also flattened as a result."),
  ("Only one breast was removed — can symmetry be achieved?","Yes. Reduction, lifting or augmentation of the opposite breast can be performed to achieve symmetry. This is usually planned as a second stage.")],
 "ctah":"Breast reconstruction assessment",
 "ctap":"Send us your diagnosis, the surgery planned or already performed, your radiotherapy status and any imaging you have. We will get back to you to coordinate with your oncology team."},

"mikrotia": {
 "crumb":"Microtia — Ear Reconstruction",
 "title":"Microtia Surgery (Congenital Absence of the Ear) and Ear Reconstruction | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Microtia: Congenital Absence of the Ear and Its Surgical Reconstruction",
 "desc":"What is microtia and at what age is it operated on? Ear reconstruction using rib cartilage, the surgical stages, hearing and the recovery process.",
 "eyebrow":"Reconstructive Surgery",
 "h1":"Microtia: congenital absence of the ear and its reconstruction",
 "lead":"Microtia is the congenital underdevelopment or absence of the outer ear. It occurs in roughly one in every 6,000–10,000 births. Using the child's own rib cartilage, a new ear framework can be sculpted to build a natural-looking ear that lasts a lifetime.",
 "watopic":"microtia (ear reconstruction)",
 "about":"Microtia",
 "card":"Microtia reconstruction","cardsub":"Rib cartilage reconstruction for congenital absence of the ear",
 "procedure":{"name":"Microtia Reconstruction",
   "how":"A three-dimensional ear framework is carved from the patient's own rib cartilage, placed under the skin, and at a later stage the ear is elevated from the head to create its natural projection.",
   "prep":"Assessment of cartilage maturity and chest development; hearing tests and CT imaging where required.",
   "follow":"Wound care, avoidance of pressure on the ear and planned reviews between stages.",
   "body":"Ear"},
 "keyfacts":[("Incidence","1 in 6,000–10,000 births"),("Age at surgery","Usually 8–10 years"),
             ("Technique","Autologous rib cartilage"),("Stages","Planned in 2–3 stages")],
 "authority":"Microtia reconstruction demands manual skill in cartilage carving and experience across many cases. Assoc. Prof. Dr. Acarturk worked on ear reconstruction during his fellowship at the University of Helsinki, and performs microtia reconstruction regularly on the volunteer surgical missions he joins in Vietnam each year.",
 "creds":["University of Helsinki — microsurgery and ear reconstruction fellowship","Regular microtia surgery on volunteer missions in Vietnam","Subspecialty in Oral & Maxillofacial Surgery"],
 "sections":[
  {"id":"nedir","tag":"The Basics","h2":"What is microtia?","body":[
   "Microtia results from development of the outer ear that fails to complete during the early weeks of pregnancy. It is more often one-sided and most commonly affects the right ear. Absence of the outer ear is frequently accompanied by a narrow ear canal or none at all (atresia).",
   ("h3","Grading"),
   ("ul",["<strong>Grade 1:</strong> The ear is small but most structures are recognisable.",
          "<strong>Grade 2:</strong> The lower part of the ear is present; the upper structures have not developed.",
          "<strong>Grade 3:</strong> The most common form. Only a peanut-shaped cartilage remnant and an earlobe are present; the ear canal is usually absent.",
          "<strong>Grade 4 (anotia):</strong> Ear tissue is entirely absent."]),
   ("note","Microtia most often occurs in isolation, but it can be part of a syndrome. The first assessment is therefore not limited to the ear; facial symmetry, jaw development and hearing are examined together.")]},
  {"id":"isitme","tag":"Hearing","h2":"Hearing and speech development","body":[
   "The outer ear collects sound, but the real work of hearing is done by the inner ear. In one-sided microtia with a healthy opposite ear, speech development is usually normal. Even so, there may be difficulty locating the direction of sound and distinguishing speech in noisy environments.",
   "In bilateral microtia the situation is different: hearing support must be provided <strong>early</strong>. This can be achieved with bone-conduction hearing devices and is critical for speech development.",
   ("note","Hearing assessment is separate from, and takes priority over, reconstruction of the outer ear. It is planned together with audiology and ENT teams; reconstructing the ear does not by itself improve hearing.")]},
  {"id":"yontem","tag":"Surgery","h2":"Surgical method and stages","body":[
   "The gold standard is to sculpt a three-dimensional ear framework from <strong>the child's own rib cartilage</strong>. Because it is the child's own tissue there is no risk of rejection, it grows with the child and it lasts a lifetime.",
   ("h3","Why 8–10 years of age?"),
   ("ul",["Rib cartilage only reaches the thickness needed to carve a framework at this age",
          "The ear reaches roughly 85% of its adult size, allowing symmetry with the opposite ear",
          "The child is mature enough to take part in post-operative care",
          "It falls before the school years, when appearance becomes more significant"]),
   ("h3","The stages"),
   ("steps",[
    ("STAGE 1 — FRAMEWORK","Rib cartilage is harvested, carved into an ear framework and placed into a skin pocket prepared at the ear site."),
    ("STAGE 2 — EARLOBE","The existing earlobe is moved into the correct position and integrated with the framework. In some plans this is combined with the first stage."),
    ("STAGE 3 — ELEVATION","The ear is elevated from the head and tissue and a skin graft are placed behind it to give the ear its natural angle and depth.")]),
   "Usually 4–6 months are left between stages. This time is needed for the tissue to settle and for its blood supply to mature."]},
  {"id":"deneyim","tag":"Experience","h2":"Experience in this field","body":[
   "Microtia reconstruction is one of the areas of plastic surgery that most depends on repetition and manual skill. Cartilage carving directly determines whether the result will look natural.",
   "Assoc. Prof. Dr. Acarturk takes part in volunteer surgical missions in Vietnam each year, performing microtia reconstruction, cleft lip and palate repair and brachial plexus surgery. Ear reconstruction was also among his areas of work during his fellowship at the University of Helsinki.",
   ("note","Rushing microtia reconstruction can permanently limit the result, both because of insufficient cartilage and because of symmetry. Correct timing is no less important than correct technique.")]}],
 "faqs":[
  ("What is the right age for microtia surgery?","Because the rib cartilage must reach sufficient thickness and the ear must approach adult size, 8–10 years is generally recommended. This range may vary in bilateral cases and according to chest development."),
  ("How many operations are needed?","Usually 2–3 stages are planned, with 4–6 months between them. The number of stages depends on the grade of microtia and the tissue available."),
  ("Does taking cartilage from the ribs harm the child?","The donor cartilage area regenerates over time and chest development proceeds normally. Pain in the chest is expected in the first days after surgery and is managed."),
  ("Does the surgery improve hearing?","No. Reconstruction of the outer ear restores appearance; hearing is a separate matter, assessed together with audiology and ENT teams. Bone-conduction devices or separate hearing surgery are planned where required."),
  ("Is a prosthetic ear an option?","Adhesive or implant-retained prostheses are an option in some situations, particularly where cartilage is insufficient or the patient does not want surgery. However, reconstruction with the patient's own tissue is permanent and requires no daily care."),
  ("Will there be visible scars?","Scars form behind the ear and on the chest. The chest incision is hidden in the inframammary fold and the scars behind the ear lie in the shadow of the ear and hair; they become less noticeable over time.")],
 "ctah":"Microtia assessment",
 "ctap":"Send us your child's age, which ear is affected, any hearing test results and photographs. We will get back to you to arrange a planning consultation."},

"rinoplasti": {
 "crumb":"Rhinoplasty",
 "title":"Rhinoplasty — Natural Results and Breathing | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Rhinoplasty: Functional and Aesthetic Nasal Surgery",
 "desc":"What is rhinoplasty, the difference between open and closed technique, treating a deviated septum at the same time, the recovery process and what to know about revision rhinoplasty.",
 "eyebrow":"Aesthetic Surgery",
 "h1":"Rhinoplasty (nose reshaping surgery)",
 "lead":"A good rhinoplasty is a nose that does not look operated on. The aim is a result that harmonises with the rest of the face, ages naturally, and considers breathing at least as much as appearance.",
 "watopic":"rhinoplasty",
 "about":"Rhinoplasty",
 "card":"Rhinoplasty","cardsub":"Functional and aesthetic nasal surgery",
 "procedure":{"name":"Rhinoplasty",
   "how":"The bone and cartilage framework of the nose is reshaped using an open or closed technique; cartilage grafts are added for support where needed and the septum is corrected.",
   "prep":"Examination, assessment of breathing, photographic analysis and blood tests.",
   "follow":"Care of the splint and any packing, management of swelling, sun protection during the first year.",
   "body":"Nose"},
 "keyfacts":[("Anaesthesia","General anaesthesia"),("Duration","2–4 hours"),
             ("Social return","7–10 days"),("Final shape","12–18 months")],
 "authority":"Turkish surgeons have an internationally recognised body of experience in rhinoplasty. Assoc. Prof. Dr. Acarturk continued that experience at the University of Pittsburgh, where his colleagues came to refer nearly all of the rhinoplasty patients who approached them to him. His subspecialty in Oral & Maxillofacial Surgery allows him to assess the nose and the facial skeleton together.",
 "creds":["High-volume rhinoplasty practice at the University of Pittsburgh through peer referrals","Subspecialty in Oral & Maxillofacial Surgery","Experience in facial fractures and facial skeletal surgery"],
 "sections":[
  {"id":"kimler","tag":"Who It Is For","h2":"Who is rhinoplasty suitable for?","body":[
   "Rhinoplasty is performed to improve the appearance of the nose, its breathing function, or both. The most common reasons for consultation are:",
   ("ul",["A bony or cartilaginous prominence on the nasal dorsum (a hump)",
          "A drooping, wide or poorly defined nasal tip",
          "A nose that appears large or small relative to the face",
          "Deviation and asymmetry",
          "Difficulty breathing due to a deviated septum or enlarged turbinates",
          "A deformity or breathing problem left by a previous operation"]),
   "Nasal growth is complete at around 16 years of age in girls and 17–18 in boys; surgery is planned once this growth is complete.",
   ("note","Rhinoplasty is facial surgery, not merely nasal surgery. Decisions taken without considering the chin, the slope of the forehead and overall facial proportions produce results that are technically successful but do not suit the face.")]},
  {"id":"teknik","tag":"Technique","h2":"Open and closed technique","body":[
   ("h3","Open rhinoplasty"),
   "A small incision is made in the columella, the strip of skin between the nostrils, and the skin of the nose is lifted. The surgeon sees the entire framework directly, so asymmetries, graft placement and tip shaping are handled with greater control. The columellar scar becomes indistinct within a few months.",
   ("h3","Closed rhinoplasty"),
   "All incisions remain inside the nose, leaving no external scar. Swelling is less and recovery faster. It is preferred in noses with a symmetrical framework requiring limited correction.",
   ("h3","Preservation approach"),
   "These techniques aim to reposition the nasal dorsum while disturbing its natural structure as little as possible. In suitable anatomy they can produce a more natural dorsal line and less swelling.",
   ("note","The choice of technique should follow your anatomy, not the surgeon's habit. In revision cases, marked asymmetries and noses requiring cartilage support, the open technique is generally safer.")]},
  {"id":"nefes","tag":"Function","h2":"Breathing and the septum","body":[
   "Breathing is an inseparable part of nasal surgery. An operation that improves appearance while ignoring a breathing problem lowers the patient's quality of life.",
   ("ul",["<strong>Deviated septum:</strong> deviation of the wall dividing the nose; corrected in the same session (septorhinoplasty)",
          "<strong>Turbinate enlargement:</strong> reduction of the structures inside the nose",
          "<strong>Nasal valve narrowing:</strong> inward collapse of the nostril, supported with cartilage grafts"]),
   "Cartilage taken from the septum is also used as a graft to support the nasal tip. This makes it possible to address both function and shape in a single operation.",
   ("note","Health insurance coverage depends on whether the procedure has a functional component. It is worth clarifying this during the planning consultation.")]},
  {"id":"surec","tag":"Process","h2":"The recovery process","body":[
   ("steps",[
    ("STEP 1 — FIRST CONTACT","Initial contact via WhatsApp or the form, based on your expectations, medical history and any photographs."),
    ("STEP 2 — EXAMINATION AND PLANNING","Assessment of your anatomy and open discussion of applicable techniques, risks and realistic expectations."),
    ("STEP 3 — PREPARATION","Blood tests, anaesthetic assessment, adjustment of smoking and blood-thinning medication."),
    ("STEP 4 — SURGERY","2–4 hours under general anaesthesia, usually with one night in hospital."),
    ("STEP 5 — FIRST DAYS","A splint on the nasal dorsum and silicone packing if required. Ice and sleeping with the head elevated for the first 48 hours; bruising and swelling peak on days 3–5."),
    ("STEP 6 — RETURN AND FOLLOW-UP","The splint is removed on day 7 and most patients return to social life within 7–10 days. Swelling at the tip resolves gradually over 12–18 months.")]),
   ("ul",["Glasses should not rest on the nasal dorsum for the first 6 weeks",
          "Avoid heavy exercise and bending forward for the first 3 weeks",
          "Sun protection should not be neglected during the first year"])]}],
 "faqs":[
  ("Will my breathing improve after rhinoplasty?","If there is a deviated septum, turbinate enlargement or valve narrowing, these can be corrected in the same session and breathing usually improves markedly. This is assessed during examination."),
  ("When will I see the result?","The general shape is apparent once the splint is removed, but swelling at the tip resolves slowly. The final result takes 12–18 months, and longer in thick-skinned noses."),
  ("Does the open technique leave a scar?","The columellar scar fades within a few months and is not noticeable at normal conversational distance. Scar care during this period is important."),
  ("When can revision rhinoplasty be performed?","Because the tissues must soften and swelling must fully resolve, revision is generally planned at least 12 months after the first operation. Revision is technically more demanding than primary surgery."),
  ("Is the surgery very painful?","Rhinoplasty is less painful than most people expect. The main discomfort is the sensation of a blocked nose; modern silicone splints with airway channels markedly reduce this."),
  ("Will my nose change as I age?","Every nose ages. In a well-planned rhinoplasty the support structures are preserved, so the tip does not drop excessively over time; in noses from which too much tissue has been removed, collapse can occur with age.")],
 "ctah":"Rhinoplasty assessment",
 "ctap":"Tell us what you would like to change, whether you have any breathing complaints, and send front and side photographs if you have them."},
}
