# -*- coding: utf-8 -*-
"""Ingilizce ceviriler — parti 7: lipodem kumesi (6 uydu sayfa)."""

T = {
"lipodem-nedir": {
 "crumb":"What Is Lipedema",
 "title":"What Is Lipedema? Causes, Symptoms and Treatment | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"What Is Lipedema? Causes and Treatment",
 "desc":"What is lipedema, why does it occur, how does it differ from obesity and cellulite? Symptoms, stages, diagnosis and lymphatic-sparing surgical treatment options.",
 "eyebrow":"Microsurgery Programme",
 "h1":"What is lipedema?",
 "lead":"If your legs look out of proportion with the rest of your body, if they hurt when touched, and if your upper body slims down when you lose weight while your legs stay the same — this is not a matter of willpower. Lipedema is a disease that needs to be recognised, and it affects around 10% of women.",
 "watopic":"lipedema",
 "about":"Lipedema",
 "aboutType":"MedicalCondition",
 "card":"What is lipedema","cardsub":"Definition, causes and treatment approach",
 "procedure":{"name":"Lipedema Surgery — Lymphatic-Sparing Liposuction",
   "how":"Diseased fat tissue is removed using WAL (water-jet assisted) or PAL (power assisted) techniques while preserving lymphatic structures.",
   "prep":"Examination, staging, lymphatic imaging where indicated and compression garment fitting.",
   "follow":"Compression garments, early mobilisation and manual lymphatic drainage where needed.",
   "body":"Legs, hips, arms"},
 "keyfacts":[("Prevalence","Around 10% of women"),
             ("Distinguishing sign","Feet are spared — the cuff sign"),
             ("Main complaint","Pain, tenderness, easy bruising"),
             ("Relation to weight","Does not resolve with dieting")],
 "authority":"Lipedema surgery requires command of liposuction techniques that spare the lymphatic system. Assoc. Prof. Dr. Acarturk is among the first Turkish plastic surgeons to have worked on adipose tissue and stem cell technologies at the University of Pittsburgh; as a surgeon who also performs lymphedema microsurgery, he works with lymphatic anatomy in daily practice.",
 "creds":["Adipose tissue and stem cell research at the University of Pittsburgh",
          "Participation in the European lymphatic microsurgery group",
          "Presentation at the World Congress of Lymphology"],
 "sections":[
  {"id":"tanim","tag":"Definition","h2":"What is lipedema?","body":[
   "Lipedema is a chronic condition in which fat tissue increases abnormally and <strong>symmetrically</strong>, accompanied by pain and tenderness on touch. It is seen almost exclusively in women.",
   "Accumulation concentrates in the hips, thighs and calves; the arms are involved in around a quarter of cases. The upper body is usually spared. <strong>The feet are not involved</strong> — producing a sharp transition at the ankle known as the <strong>cuff sign</strong>, the most typical finding in lipedema.",
   ("h3","Three features that define lipedema"),
   ("ul",["<strong>Symmetry:</strong> both sides are affected similarly",
          "<strong>Pain:</strong> tenderness on touch and easy bruising — the most important feature distinguishing lipedema from simple fat accumulation",
          "<strong>Resistance to diet:</strong> when weight is lost the upper body slims down while the regional accumulation remains"]),
   ("note","Lipedema is not a weight problem. Calorie restriction and exercise reduce overall fat mass but do not affect the diseased fat tissue. Patients are therefore often accused of \"not trying hard enough\" — when the problem lies not in willpower but in the tissue itself.")]},
  {"id":"neden","tag":"Causes","h2":"Why does lipedema occur?","body":[
   "The cause of lipedema is not fully known, but two factors stand out: <strong>hormonal transitions</strong> and <strong>genetic predisposition</strong>.",
   ("ul",["<strong>Hormonal periods:</strong> the condition most often begins during puberty, pregnancy or the menopause. This points to the role of oestrogen in fat tissue distribution.",
          "<strong>Family history:</strong> a similar body shape is found in the mother, aunt or sister of a significant proportion of patients",
          "<strong>Occurrence in women:</strong> it is extremely rare in men and usually accompanied by a hormonal disorder",
          "<strong>Microcirculation and inflammation:</strong> increased small-vessel permeability and low-grade inflammation have been shown in affected tissue — explaining the pain and easy bruising"]),
   ("note","Lipedema is not a consequence of obesity. However, the two can coexist and obesity aggravates lipedema. Weight control does not eliminate the disease but reduces symptoms and the lymphatic load.")]},
  {"id":"fark","tag":"Differential Diagnosis","h2":"How it differs from obesity, cellulite and lymphedema","body":[
   "Lipedema is most often confused with these three conditions. The distinction matters because it changes the treatment entirely.",
   ("table",["Feature","Lipedema","Obesity","Lymphedema"],[
     ["Distribution","Regional — hips, thighs, calves","Spread across the whole body","Usually a single limb"],
     ["Symmetry","Symmetrical","Symmetrical","Frequently asymmetrical"],
     ["Foot involvement","Absent — cuff sign","Variable","Present — top of foot and toes"],
     ["Pain","Marked, on touch","Absent","Heaviness predominates"],
     ["Bruising","Bruises easily","Normal","Normal"],
     ["On losing weight","Regional accumulation remains","Reduces proportionally","Unchanged"],
     ["Stemmer's sign","Negative","Negative","Positive"]]),
   ("h3","How it differs from cellulite"),
   "Cellulite is a change in the appearance of subcutaneous fat and is <strong>painless</strong>. In lipedema, pain and tenderness dominate the picture. Cellulite is a cosmetic condition; lipedema is a progressive disease.",
   ("note","Lipedema and lymphedema may also coexist. In untreated lipedema the increasing tissue volume eventually exceeds the transport capacity of the lymphatic system and lymphedema is added to the picture; this is called <strong>lipo-lymphedema</strong>. For detail see our <a href=\"../lenfodem-lipodem-cerrahisi.html\">lymphedema page</a>.")]},
  {"id":"tani","tag":"Diagnosis","h2":"How is lipedema diagnosed?","body":[
   "There is no blood test or definitive imaging method for lipedema. The diagnosis is <strong>clinical</strong> — made from the history and examination.",
   ("h3","What is assessed in making the diagnosis"),
   ("ul",["When and in which period the symptoms began",
          "A history of pain on touch and easy bruising",
          "Symmetry and sparing of the feet",
          "The response to attempts at weight loss",
          "Family history",
          "Skin and tissue consistency, nodularity",
          "Stemmer's sign — negative in lipedema"]),
   "Imaging is used where lymphatic involvement is suspected or for differential diagnosis; it is not required to make the diagnosis of lipedema.",
   ("note","Years of diagnostic delay are very common in lipedema. Most patients are given a diagnosis of obesity at their first consultation and sent away with advice to diet. The correct diagnosis is valuable in itself in preventing the disease from progressing.")]},
  {"id":"tedavi","tag":"Treatment","h2":"Treatment of lipedema","body":[
   ("h3","Conservative treatment"),
   "Compression garments, manual lymphatic drainage, regular movement and weight control form the foundation of treatment. These approaches relieve symptoms and slow progression, but they do not remove the diseased fat tissue. For detail see our <a href=\"../ameliyatsiz-lipodem-tedavisi.html\">non-surgical treatment page</a>.",
   ("h3","Surgical treatment — lymphatic-sparing liposuction"),
   "Lipedema surgery is a medical treatment, not a cosmetic procedure. The aim is not to reduce volume but to remove the diseased fat tissue <strong>while preserving lymphatic structures</strong>, reduce pain and restore movement.",
   ("ul",["<strong>WAL (water-jet assisted):</strong> a fine water jet gently separates fat cells from the surrounding tissue; lymphatic vessels and nerves are largely preserved",
          "<strong>PAL (power assisted):</strong> a vibrating cannula breaks down fibrotic and dense tissue with less trauma; preferred in advanced stages"]),
   ("note","Surgery does not eliminate the disease; it reduces the diseased fat tissue. Removed tissue does not return, but the condition persists in the remaining tissue. Compression garments, movement and a stable weight therefore remain part of treatment after surgery.")]}],
 "faqs":[
  ("What is lipedema, in short?","A chronic condition in which fat tissue increases symmetrically and abnormally, accompanied by pain on touch. It is seen almost exclusively in women, concentrates in the hips and legs, and the feet are spared."),
  ("Is lipedema a weight problem?","No. The diseased fat tissue resists calorie restriction and exercise. When weight is lost the upper body slims down while the regional accumulation remains — and the disproportion may even become more obvious."),
  ("Does lipedema occur only in women?","Almost entirely. It is extremely rare in men and, when it occurs, there is usually an underlying hormonal disorder."),
  ("Is lipedema dangerous?","It is not directly life-threatening, but it is progressive. Over time movement becomes restricted, the knee and hip joints are strained, and lymphedema may be added because of the burden placed on the lymphatic system."),
  ("Does lipedema go away?","The disease does not disappear completely. However, conservative treatment can relieve symptoms, and surgery can reduce the diseased fat tissue and markedly improve pain and restricted movement."),
  ("Are lipedema and lymphedema the same?","No. Lipedema is a disease of fat tissue, is symmetrical and is painful. Lymphedema is an accumulation of lymphatic fluid, is usually one-sided and involves the feet. The two may also coexist (lipo-lymphedema).")],
 "ctah":"The first step in lipedema assessment",
 "ctap":"Tell us when your symptoms began, how severe the pain is and which treatments you have tried; if possible attach photographs of your legs from the front and side."},

"lipodem-belirtileri": {
 "crumb":"Lipedema Symptoms",
 "title":"Lipedema Symptoms: How Is It Recognised? | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Lipedema Symptoms and How to Recognise Them",
 "desc":"What are the symptoms of lipedema and how is it recognised? The cuff sign, pain and bruising, early findings and self-check methods.",
 "eyebrow":"Microsurgery Programme",
 "h1":"Lipedema symptoms: how is it recognised?",
 "lead":"Lipedema is diagnosed, on average, years late. The reason for this delay is not that the condition is rare — it is that its symptoms are mistaken for a weight problem. This page sets out the findings that distinguish lipedema from other conditions.",
 "watopic":"lipedema symptoms",
 "about":"Lipedema",
 "aboutType":"MedicalCondition",
 "card":"Lipedema symptoms","cardsub":"Distinguishing findings and self-assessment",
 "procedure":{"name":"Lipedema Diagnostic Assessment",
   "how":"Pain, symmetry, sparing of the feet, response to weight loss and tissue consistency are assessed together to reach a clinical diagnosis.",
   "prep":"The period in which symptoms began and family history.",
   "follow":"A treatment plan according to stage.",
   "body":"Legs, hips, arms"},
 "keyfacts":[("Cuff sign","Swelling stops at the ankle, feet spared"),
             ("Pain","Tenderness on touch is typical"),
             ("Bruising","Bruises appear after even minor knocks"),
             ("Symmetry","Both sides affected similarly")],
 "authority":"Recognising lipedema correctly both ends unnecessary cycles of dieting and makes the right treatment possible. As a surgeon who performs both lipedema surgery and lymphedema microsurgery, Assoc. Prof. Dr. Acarturk assesses the two pictures together.",
 "creds":["Participation in the European lymphatic microsurgery group",
          "Adipose tissue and stem cell research at the University of Pittsburgh",
          "An integrated approach to lipedema and lymphedema"],
 "sections":[
  {"id":"temel","tag":"Core Symptoms","h2":"The core symptoms of lipedema","body":[
   ("ul",["<strong>A disproportionate body shape:</strong> a slim upper body with markedly full hips and legs",
          "<strong>The cuff sign:</strong> swelling stops sharply at the ankle while the feet remain normal",
          "<strong>Pain on touch:</strong> tenderness at even light pressure — the most distinguishing finding",
          "<strong>Easy bruising:</strong> bruises appear after knocks too minor to remember",
          "<strong>Symmetry:</strong> both legs are affected similarly",
          "<strong>Resistance to diet:</strong> when weight is lost the upper body slims down while the legs stay the same",
          "<strong>Nodular tissue:</strong> small granular structures felt beneath the skin",
          "<strong>A sense of heaviness and tightness:</strong> increasing particularly at the end of the day"]),
   ("note","Not all of these findings need to be present together. However, when the triad of <strong>pain, symmetry and sparing of the feet</strong> is present, lipedema should be strongly considered.")]},
  {"id":"baslangic","tag":"Onset","h2":"The onset of lipedema: first findings","body":[
   "Lipedema usually begins during a hormonal transition: puberty, pregnancy or the menopause. The onset is insidious and is generally attributed to weight gain.",
   ("ul",["Trousers beginning to feel tight relative to the upper body",
          "The inner thighs touching and rubbing",
          "A sense of heaviness in the legs at the end of the day",
          "Unexpected tenderness after massage or pressure",
          "Bruises with no remembered cause"]),
   ("note","A leg shape that begins in adolescence and is explained away as \"being overweight\" deserves careful assessment, particularly where there is a family history. Early diagnosis is the only effective way of slowing progression to an advanced stage.")]},
  {"id":"kontrol","tag":"Self-Check","h2":"Self-assessment: four simple questions","body":[
   ("steps",[
    ("1 — LOOK AT YOUR FEET","Does the swelling stop at your ankle while your feet remain normal? Is there a clear transition line at the ankle? This is the cuff sign and favours lipedema."),
    ("2 — PRESS","Do you feel pain when you press with moderate force on your thigh or calf? This tenderness is typical of lipedema; it is absent in simple fat accumulation."),
    ("3 — CHECK SYMMETRY","Are both legs affected similarly? Lipedema is symmetrical; marked one-sidedness suggests lymphedema."),
    ("4 — THINK ABOUT YOUR WEIGHT HISTORY","When you lose weight, do your face, arms and waist slim down while your legs stay the same? This resistance is the distinguishing feature of lipedema.")]),
   ("note","These questions do not replace a medical examination. Their purpose is to help you realise that a picture explained for years as a \"weight problem\" may in fact be a condition that needs assessment.")]},
  {"id":"karisan","tag":"Confused Conditions","h2":"Conditions confused with lipedema","body":[
   ("table",["Condition","Distinguishing feature"],[
     ["Obesity","Fat spread across the whole body; no pain; reduces proportionally with weight loss"],
     ["Cellulite","Only a change in skin appearance; painless"],
     ["Lymphedema","Usually one-sided; top of the foot and toes involved; Stemmer positive"],
     ["Venous insufficiency","Settles quickly when the leg is raised; varicose veins accompany it"],
     ["Cardiac/renal oedema","Pits on pressure; a systemic illness is present"]]),
   "For a comparative table with lymphedema see our <a href=\"../lenfodem-belirtileri.html\">lymphedema symptoms page</a>."]},
  {"id":"nezaman","tag":"When to Consult","h2":"When should you see a doctor?","body":[
   ("ul",["If your legs are painful on touch",
          "If regional accumulation does not change despite your efforts to lose weight",
          "If you bruise easily",
          "If your legs are out of proportion with your upper body",
          "If rubbing of the thighs when walking affects your daily life",
          "If there is a similar body shape in your family"]),
   ("note","There is no blood test or definitive imaging for the diagnosis of lipedema; the diagnosis is clinical. Being able to describe your symptoms in detail — particularly the presence of pain — is therefore the most critical part of the diagnosis.")]}],
 "faqs":[
  ("How is lipedema recognised?","Four findings are assessed together: pain on touch, symmetry, sparing of the feet (the cuff sign) and resistance to weight loss. When these four are present together, lipedema is strongly considered."),
  ("What is the cuff sign?","The swelling stopping sharply at the ankle while the feet remain normal. It is the most typical finding in lipedema and the most practical feature distinguishing it from lymphedema — in which the swelling extends to the top of the foot and toes."),
  ("Why do I bruise easily with lipedema?","Small-vessel permeability is increased in the affected tissue and the capillaries are more fragile. Bruises can therefore appear after knocks too minor to remember."),
  ("My legs hurt — is it lipedema?","Pain on touch is the most distinguishing finding in lipedema, but it does not establish the diagnosis on its own. Symmetry, sparing of the feet and the response to weight loss must be assessed together."),
  ("Which test is used to diagnose lipedema?","There is no blood test or imaging method that establishes the diagnosis; it is made by clinical examination and history. Imaging is used where lymphatic involvement is suspected or for differential diagnosis."),
  ("Are there symptoms in the early stage?","Yes, but they are subtle: heaviness at the end of the day, unexpected tenderness, bruises with no remembered cause and trousers feeling tight relative to the upper body. This period is generally attributed to weight gain and missed.")],
 "ctah":"Let us assess your symptoms",
 "ctap":"Tell us when your symptoms began, how severe the pain is and about your experiences with weight loss; if possible attach photographs of your legs from the front and side."},

"lipodem-hangi-doktor": {
 "crumb":"Which Specialist Treats Lipedema",
 "title":"Which Specialist Treats Lipedema? Where to Go | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Which Specialist Treats Lipedema?",
 "desc":"Which department should you consult for lipedema? The roles of plastic surgery, physical medicine and other specialties, what to look for when choosing a surgeon, and appointment preparation.",
 "eyebrow":"Microsurgery Programme",
 "h1":"Which specialist treats lipedema?",
 "lead":"Most lipedema patients reach the right department years late. Along the way there are dietitians, endocrinologists and aesthetic clinics; the common thread is that the picture is mistaken for a weight problem. This page gives directions.",
 "watopic":"the right specialist for lipedema",
 "about":"Lipedema",
 "aboutType":"MedicalCondition",
 "card":"Which specialist?","cardsub":"Finding the right specialty for lipedema",
 "procedure":{"name":"Surgical Assessment for Lipedema",
   "how":"Plastic and reconstructive surgery removes diseased fat tissue using liposuction techniques that preserve lymphatic structures.",
   "prep":"Staging, differential diagnosis and lymphatic imaging where needed.",
   "follow":"Long-term follow-up conducted together with physiotherapy.",
   "body":"Legs, hips, arms"},
 "keyfacts":[("Surgical treatment","Plastic and Reconstructive Surgery"),
             ("Conservative treatment","Physical Medicine and Rehabilitation"),
             ("Important","Not every liposuction is lipedema surgery"),
             ("Ideal","The two specialties working together")],
 "authority":"Lipedema surgery and aesthetic liposuction are different undertakings. In lipedema the priority is preserving the lymphatic system, which requires a surgeon who works with lymphatic anatomy. Assoc. Prof. Dr. Acarturk performs both lipedema surgery and lymphedema microsurgery and has worked on adipose tissue technologies at the University of Pittsburgh.",
 "creds":["Participation in the European lymphatic microsurgery group",
          "Adipose tissue and stem cell research at the University of Pittsburgh",
          "Experience in lymphatic-sparing liposuction"],
 "sections":[
  {"id":"kisa","tag":"Short Answer","h2":"The short answer","body":[
   "Two specialties are involved in lipedema:",
   ("ul",["<strong>Plastic and Reconstructive Surgery</strong> — conducts surgical treatment. Lymphatic-sparing liposuction (WAL, PAL) belongs to this field.",
          "<strong>Physical Medicine and Rehabilitation</strong> — conducts conservative treatment. Compression garment planning, manual lymphatic drainage and exercise programmes are arranged here."]),
   ("note","These two specialties are not alternatives to one another. Conservative treatment continues after surgery; surgery comes into play at the point where conservative treatment is not enough.")]},
  {"id":"hangi-durumda","tag":"Referral","h2":"Who should you see, and when?","body":[
   ("table",["Your situation","Department to consult"],[
     ["No diagnosis, painful swelling in the legs","Plastic surgery or physical medicine — a doctor who works with lipedema"],
     ["Diagnosed, pain affecting daily life","Plastic and reconstructive surgery — assessment for surgical candidacy"],
     ["Receiving conservative treatment, not sufficient","Plastic and reconstructive surgery"],
     ["Compression garment and physiotherapy plan needed","Physical Medicine and Rehabilitation"],
     ["Suspected lymphatic involvement (swelling of the feet too)","A plastic surgeon who performs lymphedema surgery"],
     ["Suspected hormonal disorder","Endocrinology — for accompanying conditions"]]),
   ("note","Endocrinologists and nutrition specialists play a supporting role in lipedema but do not treat the disease itself. Referring a picture that does not resolve with dieting to a dietitian alone is the commonest reason for diagnostic delay.")]},
  {"id":"cerrah-secimi","tag":"Choosing a Surgeon","h2":"What to look for when choosing a surgeon","body":[
   "This is the most critical issue in lipedema: <strong>not every liposuction is lipedema surgery.</strong> Aesthetic liposuction focuses on reducing volume; in lipedema surgery the priority is preserving the lymphatic system. A procedure performed with the wrong technique can damage the lymphatic structure and worsen the picture.",
   ("h3","Reasonable questions to ask"),
   ("ul",["Which technique do you use in lipedema surgery? (WAL, PAL)",
          "What approach do you take to preserving lymphatic structures?",
          "How many sessions will be needed, and why?",
          "What is the plan for compression garments and physiotherapy after surgery?",
          "Do you also perform lymphedema surgery?",
          "What is the realistic expectation — will the disease resolve, or will the symptoms lessen?"]),
   ("note","The phrase \"lipedema resolves completely\" is a warning sign. Surgery reduces the diseased fat tissue; it does not eliminate the disease. An honest assessment speaks in terms of measurable goals: less pain, more movement, reduced volume.")]},
  {"id":"hazirlik","tag":"Preparation","h2":"How should you prepare for your appointment?","body":[
   ("ul",["<strong>Symptom history:</strong> when it began, in which period (puberty, pregnancy, menopause)",
          "<strong>Description of pain:</strong> how often, how severe, what makes it worse",
          "<strong>Weight history:</strong> the diets you have tried and how your legs responded",
          "<strong>Family history:</strong> a similar shape in your mother, sister or aunt",
          "<strong>Previous treatments:</strong> compression garments, lymphatic drainage, any previous liposuction",
          "<strong>Photographs:</strong> from the front, side and back; ideally showing change over time",
          "<strong>Your height and weight</strong>"]),
   ("note","Being able to describe the presence and severity of pain clearly is very important. This is the core finding distinguishing lipedema from simple fat accumulation, and the diagnosis rests largely on it.")]}],
 "faqs":[
  ("Which specialist treats lipedema?","Plastic and Reconstructive Surgery for surgical treatment, Physical Medicine and Rehabilitation for conservative treatment. The two complement one another."),
  ("Do I need to see a dietitian?","Nutritional support is helpful — weight control eases lipedema symptoms. But lipedema does not resolve with dieting. Being referred to a dietitian alone is the commonest reason for diagnostic delay."),
  ("Does every plastic surgeon perform lipedema surgery?","No. Lipedema surgery requires command of lymphatic-sparing techniques (WAL, PAL). It is not the same procedure as aesthetic liposuction; it is reasonable to ask about the surgeon's experience in this field."),
  ("Should I see an endocrinologist?","If a hormonal disorder is suspected, yes. However, lipedema itself is not a hormonal disease; endocrinology assesses accompanying conditions."),
  ("Is it performed in state hospitals?","Lipedema surgery is performed at some university and training-and-research hospitals. The number of centres is limited; confirming before applying will save time."),
  ("At which stage should I seek surgery?","If pain is affecting your daily life, if movement is beginning to be restricted, or if the condition is progressing despite conservative treatment, the time for assessment has come. There is no need to wait for an advanced stage.")],
 "ctah":"The first step towards the right assessment",
 "ctap":"Tell us how long your symptoms have lasted, how severe the pain is and which treatments you have tried; attach photographs if possible."},

"ameliyatsiz-lipodem-tedavisi": {
 "crumb":"Non-Surgical Lipedema Treatment",
 "title":"Non-Surgical Lipedema Treatment: What Works and What Does Not | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Non-Surgical Lipedema Treatment",
 "desc":"Is non-surgical treatment of lipedema possible? The real effect of compression garments, lymphatic drainage, exercise and nutrition — and when surgery becomes necessary.",
 "eyebrow":"Microsurgery Programme",
 "h1":"Non-surgical treatment of lipedema",
 "lead":"The honest answer is this: non-surgical methods do not eliminate lipedema, but they markedly reduce symptoms and slow the progression of the disease. This page explains what genuinely works and at what point surgery becomes necessary.",
 "watopic":"non-surgical lipedema treatment",
 "about":"Lipedema",
 "aboutType":"MedicalCondition",
 "card":"Non-surgical treatment","cardsub":"Conservative methods and realistic expectations",
 "procedure":{"name":"Conservative Treatment in Lipedema",
   "how":"Compression garments, manual lymphatic drainage, regular movement and a nutrition plan are applied together to control pain and oedema and slow progression.",
   "prep":"Staging and fitting for garments of the correct compression class.",
   "follow":"Regular follow-up and assessment of the response to treatment.",
   "body":"Legs, hips, arms"},
 "keyfacts":[("Realistic goal","Reducing pain, slowing progression"),
             ("What it cannot do","Remove the diseased fat tissue"),
             ("Most effective","Compression garments + regular movement"),
             ("Time for surgery","If pain and restricted movement persist")],
 "authority":"Explaining the limits of conservative treatment honestly prevents both unnecessary surgery and unnecessary waiting. As a surgeon who performs both lipedema surgery and lymphedema microsurgery, Assoc. Prof. Dr. Acarturk assesses which patient will benefit from which approach.",
 "creds":["Participation in the European lymphatic microsurgery group",
          "Adipose tissue and stem cell research at the University of Pittsburgh",
          "Experience in lymphatic-sparing liposuction"],
 "sections":[
  {"id":"gercek","tag":"Realistic Framework","h2":"What non-surgical treatment does — and does not do","body":[
   "This distinction needs to be clear from the outset, because managing expectations is part of the treatment.",
   ("table",["What non-surgical treatment does","What it does not do"],[
     ["Reduces pain and tenderness","Does not remove the diseased fat tissue"],
     ["Brings oedema under control","Does not permanently change the shape of the legs"],
     ["Slows progression","Does not reverse the disease"],
     ["Eases the lymphatic load","Does not correct the disproportion"],
     ["Preserves mobility","Does not achieve regression of stage"]]),
   ("note","This is not a picture of failure. Conservative treatment is the foundation of lipedema management and continues lifelong even in patients who have surgery. Surgery does not replace conservative treatment — it comes into play where conservative treatment is not enough.")]},
  {"id":"basi","tag":"Compression","h2":"Compression garments","body":[
   "This is the most effective component of conservative treatment. By increasing tissue pressure it reduces the accumulation of oedema, eases pain and controls fluctuation in volume through the day.",
   ("ul",["<strong>Flat-knit</strong> garments are generally preferred in lipedema — their firmer structure gives better tissue support",
          "<strong>The compression class</strong> should be determined by a doctor; the wrong class is either ineffective or uncomfortable",
          "<strong>Made-to-measure</strong> garments are far more effective than off-the-shelf sizes",
          "<strong>Regular use</strong> is markedly superior to intermittent use",
          "<strong>Replacement every 6 months</strong> is advised — elasticity is lost over time"]),
   ("note","Compression garments are the component most patients struggle with, particularly in hot weather. Yet regular use is the single most important factor determining whether you will benefit from conservative treatment.")]},
  {"id":"drenaj","tag":"Lymphatic Drainage","h2":"Manual lymphatic drainage and physiotherapy","body":[
   "Manual lymphatic drainage is a specialised massage technique that supports lymphatic flow. In lipedema it reduces the oedema component and provides relief.",
   ("ul",["Reduces oedema and the sensation of tightness",
          "May raise the pain threshold",
          "Its effect increases when applied together with compression garments",
          "Does not on its own produce a lasting change in volume"]),
   ("note","Manual lymphatic drainage does not reduce fat tissue in lipedema. Its benefit lies in oedema and relief. Presenting it as a treatment in its own right is therefore not correct; it is meaningful alongside compression and movement.")]},
  {"id":"egzersiz","tag":"Exercise","h2":"Exercise: which type, and why?","body":[
   "Exercise matters in lipedema not for losing weight but for <strong>supporting lymphatic flow and protecting the joints</strong>. Choosing the right type is decisive here.",
   ("h3","Recommended exercise"),
   ("ul",["<strong>Water-based exercise and swimming:</strong> the hydrostatic pressure of water provides natural compression — the most recommended form of exercise in lipedema",
          "<strong>Walking:</strong> the calf muscle pump supports lymphatic flow",
          "<strong>Cycling:</strong> low joint load, effective muscle pump",
          "<strong>Pilates and stretching:</strong> preserves range of movement"]),
   ("h3","Points to watch"),
   ("ul",["High-impact activities (running, jumping) may increase pain",
          "Excessive weight training may trigger tenderness",
          "Wearing compression garments during exercise is helpful",
          "Stopping before pain rather than at the limit of pain is essential"]),
   ("note","The aim of exercise in lipedema is not to slim the legs — that is not a realistic goal. The aim is to support lymphatic flow, protect joint health and maintain mobility.")]},
  {"id":"beslenme","tag":"Nutrition","h2":"The role of nutrition","body":[
   "There is no diet that eliminates lipedema. However, a nutrition plan has two genuine contributions: <strong>weight control reduces the lymphatic load</strong> and <strong>a pattern that reduces inflammation may ease symptoms</strong>.",
   ("ul",["A stable weight is one of the factors that slows the progression of lipedema",
          "Reducing processed food and excess salt may lessen the sensation of swelling",
          "Adequate protein and water intake matter for tissue health",
          "Highly restrictive diets do not achieve the goal in lipedema and are not sustainable"]),
   ("note","Cycles of strict, restrictive dieting are common in lipedema and usually end in disappointment — because the diseased fat tissue does not respond to that effort. A sustainable eating pattern is both more effective and healthier than aggressive dieting. For more see our <a href=\"../lipodem-diyeti.html\">lipedema and nutrition page</a>.")]},
  {"id":"cerrahi","tag":"When Surgery","h2":"When does surgery come into consideration?","body":[
   "If the following persist despite regular conservative treatment, the time for surgical assessment has come:",
   ("ul",["If pain continues to affect daily life",
          "If rubbing of the thighs disturbs walking and posture",
          "If restriction of movement is progressing",
          "If the load on the knee and hip joints is causing symptoms",
          "If the stage is advancing despite compression garments",
          "If quality of life has fallen markedly"]),
   ("note","There is no need to wait for an advanced stage before surgery. On the contrary, intervening before the tissue becomes fibrotic is both technically easier and gives a better result. There is no medical reason for a patient who has tried conservative treatment without benefit to wait.")]}],
 "faqs":[
  ("Does lipedema resolve without surgery?","No. Non-surgical methods reduce pain, control oedema and slow progression — but they do not remove the diseased fat tissue. Knowing this honest framework from the outset allows you to make the right decision."),
  ("Which non-surgical method is most effective?","Regularly worn compression garments and regular movement. Applied together, their effect on pain and oedema is most marked. Manual lymphatic drainage adds further benefit."),
  ("Will lymphatic drainage cure lipedema?","No. Manual lymphatic drainage reduces the oedema component and provides relief, but it does not reduce fat tissue. Presenting it as a treatment in its own right is not correct."),
  ("Will exercise slim my legs?","This is not a realistic goal in lipedema. The diseased fat tissue resists exercise. The purpose of exercise is to support lymphatic flow, protect the joints and maintain mobility."),
  ("Should I wear compression garments all the time?","Regular use is markedly more effective than intermittent use. Daily use is advised; it can be demanding in hot weather but it is the most important condition for benefiting from treatment."),
  ("How long should I continue without surgery?","There is no fixed rule. If pain and restricted movement persist despite regular conservative treatment, the time for surgical assessment has come. There is no need to wait for an advanced stage.")],
 "ctah":"Let us discuss which approach suits you",
 "ctap":"Tell us which treatments you are currently using, how long you have been using them and how your pain affects your daily life."},

"lipodem-diyeti": {
 "crumb":"Lipedema and Nutrition",
 "title":"Lipedema Diet: The Real Role of Nutrition | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Lipedema and Nutrition: What Actually Helps?",
 "desc":"What is the role of nutrition in lipedema? Does dieting resolve lipedema, which approaches ease symptoms, and why restrictive diets do not work.",
 "eyebrow":"Microsurgery Programme",
 "h1":"Lipedema and nutrition",
 "lead":"There is no diet that eliminates lipedema. This needs saying at the outset, because the most repeated experience in this condition is exactly that: years of dieting, kilos lost, and legs that never change. But nutrition does have a real, measurable contribution — just not where it is expected.",
 "watopic":"nutrition in lipedema",
 "about":"Lipedema",
 "aboutType":"MedicalCondition",
 "card":"Lipedema and nutrition","cardsub":"The real contribution of nutrition, and its limits",
 "procedure":{"name":"Nutritional Approach in Lipedema",
   "how":"A sustainable eating pattern maintains a stable weight, reduces the lymphatic load and eases the inflammatory response.",
   "prep":"Assessment of current eating habits and weight history.",
   "follow":"Follow-up focused on sustainability.",
   "body":"General"},
 "keyfacts":[("What diet does","Reduces lymphatic load, eases symptoms"),
             ("What it does not do","Does not melt the diseased fat tissue"),
             ("Priority","Sustainability, not restriction"),
             ("Warning","Cycles of strict dieting bring no benefit")],
 "authority":"Both overstating and dismissing the role of nutrition in lipedema harms the patient. As a surgeon who has researched adipose tissue biology at the University of Pittsburgh, Assoc. Prof. Dr. Acarturk is in a position to explain to his patients why this tissue resists dieting.",
 "creds":["Adipose tissue and stem cell research at the University of Pittsburgh",
          "Postdoctoral work in tissue engineering at Carnegie Mellon University",
          "An integrated approach to lipedema and lymphedema"],
 "sections":[
  {"id":"neden-direnc","tag":"Why Resistance","h2":"Why does lipedema fat resist dieting?","body":[
   "The answer to this question invalidates the accusation patients have heard for years.",
   "Fat tissue in the body is not uniform. In lipedema the affected tissue differs from normal fat tissue in cell structure, vascularity and inflammatory activity. Calorie restriction reduces the body's general fat store — but it does not affect this regional, diseased tissue to the same degree.",
   "What is seen in practice is this: the patient loses weight, <strong>her face, arms and waist slim down</strong>, and her legs stay largely the same. The disproportion may even become more obvious.",
   ("note","This does not mean dieting is useless — it means the goal has been set wrongly. Slimming the legs cannot be the aim of nutrition. But reducing the lymphatic load and easing symptoms can be.")]},
  {"id":"gercek-katki","tag":"Real Contribution","h2":"The real contribution of nutrition","body":[
   ("ul",["<strong>Reduced lymphatic load:</strong> a lower body mass index directly eases the transport burden on the lymphatic system. This matters particularly in patients who have progressed to lipo-lymphedema.",
          "<strong>Less sensation of swelling:</strong> restricting excess salt and processed food may reduce the feeling of puffiness through the day",
          "<strong>Less joint load:</strong> the burden on the knee and hip joints is reduced",
          "<strong>Better surgical outcome:</strong> a stable weight is decisive in maintaining the result after surgery",
          "<strong>Slower progression:</strong> weight gain is one of the factors that aggravates lipedema"]),
   ("note","The contribution of nutrition is real but indirect. It improves not the diseased tissue itself but the load upon it and the conditions around it.")]},
  {"id":"yaklasim","tag":"Approach","h2":"Which nutritional approach?","body":[
   "There is no single proven, standardised dietary protocol for lipedema. Approaches aimed at reducing inflammation are discussed in the literature, but the level of evidence is not yet sufficient for a definitive recommendation.",
   ("h3","Reasonable and sustainable principles"),
   ("ul",["Adequate protein intake — for tissue health and satiety",
          "Reducing processed food and refined sugar",
          "Limiting excess salt — it affects the sensation of swelling",
          "Adequate water intake",
          "A pattern based on vegetables and fibre",
          "Maintaining regular meals"]),
   ("h3","What to avoid"),
   ("ul",["Very low calorie, prolonged restrictive diets",
          "Diets based on a single food group",
          "Supplements sold with the claim that they \"melt lipedema\"",
          "Programmes promising rapid results that cannot be sustained"]),
   ("note","Nutritional planning should be individualised with a dietitian. This page offers a general framework; it does not replace an individual plan.")]},
  {"id":"psikoloji","tag":"An Important Note","h2":"The diet cycle and how you treat yourself","body":[
   "Most lipedema patients have been accused for years of \"not trying hard enough\", and after a while they internalise that accusation themselves. Repeated dietary failures — which are not failures at all but the consequence of a wrongly set goal — deepen that feeling.",
   "This needs saying plainly: <strong>your legs not responding to dieting has nothing to do with your willpower.</strong> It is the defining feature of the disease. For many patients, learning this before treatment is the greatest relief the diagnosis brings.",
   ("note","If you are struggling with your eating pattern, or if your relationship with your body is wearing you down, do not hesitate to mention it at your assessment. Lipedema treatment is not only about tissue; this process is part of an experience that spans many years, and seeking support is appropriate.")]}],
 "faqs":[
  ("Does lipedema resolve with dieting?","No. The diseased fat tissue resists calorie restriction. When you lose weight your upper body slims down while your legs stay largely the same. This has to do with the nature of the disease, not with willpower."),
  ("So is there any benefit to dieting?","Yes, but indirectly. A stable weight reduces the lymphatic load, eases joint load, lessens the sensation of swelling and slows the progression of the disease. It is also decisive in maintaining the result after surgery."),
  ("Is there a special diet for lipedema?","There is no single proven, standardised protocol. Approaches aimed at reducing inflammation are being researched, but the level of evidence is not yet sufficient for a definitive recommendation. A sustainable, balanced pattern is the most reasonable approach."),
  ("Does a ketogenic diet help in lipedema?","Some patients report a reduction in symptoms and the subject is being researched, but the level of evidence needed for a definitive recommendation in lipedema has not yet been established. If it is to be followed, it should be under medical and dietetic supervision."),
  ("Are there supplements that melt lipedema?","No. Products sold with this claim have no proven effect on lipedema. Time spent on them delays correct diagnosis and treatment."),
  ("Does nutrition matter after surgery?","Yes, very much. Removed fat tissue does not return, but cells in the remaining tissue can enlarge with weight gain. A stable weight is the single most important factor in maintaining the surgical result.")],
 "ctah":"Let us discuss your nutrition and treatment plan",
 "ctap":"Tell us about your weight history, the diets you have tried and the response you observed in your legs."},

"lipodem-evreleri": {
 "crumb":"Lipedema Stages",
 "title":"Lipedema Stages: Stages 1–4 and Their Treatment | Assoc. Prof. Dr. T. Oguz Acarturk",
 "ogtitle":"Lipedema Stages and Types",
 "desc":"What are the stages of lipedema? Findings of stages 1, 2, 3 and 4, patterns of involvement, how staging is performed and the appropriate treatment at each stage.",
 "eyebrow":"Microsurgery Programme",
 "h1":"Stages of lipedema",
 "lead":"In lipedema, stage describes the condition of the skin surface and the fat tissue. But the treatment decision rests not only on stage — it also rests on the severity of pain and restriction of movement. Quality of life may be markedly affected even at stage 1.",
 "watopic":"lipedema staging",
 "about":"Lipedema",
 "aboutType":"MedicalCondition",
 "card":"Lipedema stages","cardsub":"Stage and type classification, and matching treatment",
 "procedure":{"name":"Lipedema Staging",
   "how":"The appearance of the skin surface, the consistency of the fat tissue, nodularity and lymphatic involvement are assessed together to determine the stage.",
   "prep":"Examination, circumference measurements and lymphatic imaging where needed.",
   "follow":"A treatment plan matched to stage and symptom level.",
   "body":"Legs, hips, arms"},
 "keyfacts":[("Stage 1","Smooth skin, fine nodules beneath"),
             ("Stage 2","Uneven, wavy skin surface"),
             ("Stage 3","Thickened skin, large fat lobes"),
             ("Stage 4","Lipo-lymphedema — lymphatic insufficiency added")],
 "authority":"Staging alone does not determine treatment in lipedema; pain and loss of function matter at least as much as stage. As a surgeon who performs both lipedema surgery and lymphedema microsurgery, Assoc. Prof. Dr. Acarturk is also able to assess the transition to lipo-lymphedema.",
 "creds":["Participation in the European lymphatic microsurgery group",
          "Adipose tissue and stem cell research at the University of Pittsburgh",
          "Presentation at the World Congress of Lymphology"],
 "sections":[
  {"id":"evreler","tag":"Stages","h2":"The stages of lipedema","body":[
   ("table",["Stage","Skin and tissue","Clinical picture"],[
     ["Stage 1","Smooth skin surface, fine nodules beneath","Pain and easy bruising have begun; shape change is mild"],
     ["Stage 2","Uneven, wavy skin surface","Nodules become prominent; regional swelling and tenderness increase"],
     ["Stage 3","Thickened skin, large fat lobes","Movement is restricted; the knee and hip joints are strained"],
     ["Stage 4","Lipo-lymphedema","Lymphatic insufficiency is added to lipedema; the feet may also be involved"]]),
   ("note","An important change occurs at stage 4: the sparing of the feet, the distinguishing feature of lipedema, is lost. Because lymphatic insufficiency has been added, swelling may extend to the top of the foot and Stemmer's sign may become positive. This changes the treatment plan.")]},
  {"id":"tipler","tag":"Types","h2":"Patterns of involvement","body":[
   "Separately from stage, lipedema is also classified according to <strong>which regions are involved</strong>. This classification is used directly in surgical planning.",
   ("table",["Type","Region involved"],[
     ["Type 1","Around the hips and pelvis"],
     ["Type 2","From the hips to the knees"],
     ["Type 3","From the hips to the ankles"],
     ["Type 4","Arms"],
     ["Type 5","Calves only"]]),
   "Type 3 is the commonest picture. Type 4 (arm involvement) accompanies leg involvement in around a quarter of cases and requires separate planning.",
   ("note","Stage and type are assessed together. For example, treatment in a stage 2 – type 3 patient is planned differently from a stage 2 – type 1 patient; the number and order of procedures are determined accordingly.")]},
  {"id":"tedavi","tag":"Stage–Treatment","h2":"Which treatment at which stage?","body":[
   ("table",["Stage","Priority approach"],[
     ["Stage 1","Conservative treatment; surgical assessment if pain is marked"],
     ["Stage 2","Conservative treatment + surgical assessment (WAL/PAL)"],
     ["Stage 3","Surgery comes to the fore; usually more than one session"],
     ["Stage 4","The lymphatic component must also be addressed — lipedema surgery + a lymphedema approach"]]),
   ("note","<strong>There is no need to wait for an advanced stage before surgery.</strong> On the contrary, intervening before the tissue becomes fibrotic is technically easier and gives a better result. Even at stage 1, surgical assessment may be appropriate if pain is markedly affecting quality of life.")]},
  {"id":"ilerleme","tag":"Progression","h2":"Movement between stages","body":[
   "Lipedema is a progressive disease, but the rate of progression varies greatly from person to person. Some patients remain at the same stage for years, while others progress rapidly, particularly during hormonal transitions.",
   ("h3","Factors that accelerate progression"),
   ("ul",["Weight gain",
          "Hormonal transitions (pregnancy, menopause)",
          "Immobility",
          "Irregular use of compression garments",
          "Time passed without treatment"]),
   ("h3","Factors that slow progression"),
   ("ul",["Regular use of compression garments",
          "Regular movement — particularly water-based exercise",
          "A stable weight",
          "Early surgical intervention"]),
   ("note","Stages do not reverse. Surgery can reduce the diseased fat tissue and markedly improve symptoms, but changes in the skin and tissue are permanent. Early intervention therefore affects not only comfort but the long-term result.")]}],
 "faqs":[
  ("How many stages of lipedema are there?","Four stages are defined. At stage 1 the skin surface is smooth, at stage 2 it becomes wavy, at stage 3 it thickens and large fat lobes form, and at stage 4 lymphatic insufficiency is added (lipo-lymphedema)."),
  ("How do I find out my stage?","Staging is done by clinical examination: the appearance of the skin surface, nodularity, tissue consistency and foot involvement are assessed. Definitive staging from a photograph is not appropriate."),
  ("At which stage is surgery performed?","Stage alone is not decisive. If pain and restricted movement are affecting quality of life, surgical assessment may be appropriate even at stage 1. There is no medical reason to wait for an advanced stage."),
  ("What does stage 4 mean?","It is the point at which lymphatic insufficiency is added to lipedema — lipo-lymphedema. At this stage the sparing of the feet, the distinguishing feature of lipedema, is lost. The treatment plan must address both the fat tissue and the lymphatic component."),
  ("Can a stage be reversed?","No. Surgery can reduce the diseased fat tissue and markedly improve symptoms, but changes in the skin and tissue are permanent. This is why early intervention matters."),
  ("What does type mean?","Type describes which regions are involved — hips, thighs, calves, arms. Stage shows the condition of the tissue, type shows the distribution. Together they determine the surgical plan.")],
 "ctah":"Let us determine your stage together",
 "ctap":"Tell us how long your symptoms have lasted, how severe the pain is, which regions are affected and whether there is any swelling of your feet; attach photographs if possible."},
}
