# -*- coding: utf-8 -*-
"""Mikrocerrahi ve rekonstruktif cerrahi sayfalari."""

MICRO = [
{
 "key":"lipodem",
 "authority":"Lipödem cerrahisi, lenfatik sistemi koruyan liposuction tekniklerine hâkimiyet gerektirir. Doç. Dr. Acartürk, Pittsburgh Üniversitesi'nde yağ dokusu ve kök hücre teknolojileri üzerine çalışmış ilk Türk plastik cerrahlardan biridir; aynı zamanda lenfödem mikrocerrahisi yapan bir cerrah olarak lenfatik anatomiye günlük pratikte hâkimdir. Bu iki alanın birleşimi, lipödem cerrahisinde dokunun korunarak çalışılmasını mümkün kılar.",
 "creds":["Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım","Pittsburgh Üniversitesi'nde yağ dokusu ve kök hücre araştırmaları","Dünya Lenfödem Kongresi'nde bildiri sunumu"], "slug":"lipodem-cerrahisi.html", "prio":"0.9",
 "crumb":"Lipödem Cerrahisi",
 # HUB sayfasi: ticari sorguyu ("lipodem ameliyati/cerrahisi/operasyonu") sahiplenir.
 # "nedir", "belirtileri", "evreleri" cikarildi — ucunun de adanmis uydu sayfasi var
 # (lipodem-nedir, lipodem-belirtileri, lipodem-evreleri) ve hub onlarla yarisiyordu.
 "title":"Lipödem Cerrahisi: WAL ve PAL ile Lipödem Ameliyatı | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lipödem Cerrahisi: WAL ve PAL ile Lipödem Ameliyatı",
 "desc":"Lipödem ameliyatı nasıl yapılır? Lenfatik koruyucu WAL ve PAL liposuction teknikleri, kimlere uygundur, iyileşme süreci ve cerrahi sonrası beklentiler.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Lipödem cerrahisi ve ameliyat süreci",
 "lead":"Lipödem, neredeyse yalnızca kadınlarda görülen, bacaklarda ve sıklıkla kollarda simetrik yağ birikimiyle seyreden kronik bir hastalıktır. Diyet ve egzersize direnç gösterir, dokunmakla ağrı yapar ve zamanla yürüyüşü bozar. Kilo problemi değildir; tanınması gereken bir hastalıktır.",
 "watopic":"lipödem tedavisi",
 "about":"Lipödem", "aboutType":"MedicalCondition",
 "card":"Lipödem cerrahisi", "cardsub":"Lenfatik koruyucu liposuction ile ağrı ve hacim azaltma",
 "procedure":{"name":"Lipödem Cerrahisi — Lenfatik Koruyucu Liposuction",
   "how":"WAL (su jeti destekli) veya PAL (güç destekli) tekniklerle, lenfatik yapılar korunarak hastalıklı yağ dokusunun uzaklaştırılması.",
   "prep":"Muayene, evreleme, gerektiğinde lenfatik görüntüleme ve bası giysisi ölçüsü.",
   "follow":"Bası giysisi kullanımı, erken hareket ve gerektiğinde manuel lenf drenajı.",
   "body":"Bacaklar, kalça, kollar"},
 "keyfacts":[("Görülme","Kadınlarda %10'a varan sıklık"),("Ana şikâyet","Ağrı, hassasiyet, kolay morarma"),
             ("Yöntem","WAL / PAL liposuction"),("Seans","Alan genişliğine göre 1–3")],
 "sections":[
  {"id":"nedir","tag":"Temel Bilgi","h2":"Lipödem nedir?","body":[
   "Lipödem, yağ dokusunun anormal ve simetrik biçimde arttığı, ağrı ve dokunma hassasiyetiyle seyreden kronik bir hastalıktır. Yağ birikimi vücudun üst yarısını genellikle korur; kalça, uyluk ve baldırlarda yoğunlaşır. Ayaklar tipik olarak etkilenmez — bu, ayak bileğinde beliren keskin geçişe <strong>kelepçe belirtisi</strong> adını verdiren en tanıdık bulgudur.",
   "Hastalık sıklıkla hormonal geçiş dönemlerinde başlar: ergenlik, gebelik veya menopoz. Ailesel yatkınlık belirgindir. Buna rağmen tanı yıllarca gecikir; birçok hasta obeziteyle veya \"iradesizlikle\" suçlanır. Oysa lipödemdeki yağ dokusu, kalori kısıtlamasına ve egzersize direnç gösterir.",
   ("h3","Obezite ve selülitten farkı"),
   ("ul",["<strong>Obezitede</strong> yağ birikimi tüm vücuda yayılır ve kilo kaybıyla orantılı olarak azalır. Lipödemde bölgesel birikim kilo kaybına rağmen sürer.",
          "<strong>Selülit</strong> cilt altı yağ dokusunun görünüm değişikliğidir, ağrı yapmaz. Lipödemde ağrı ve hassasiyet tabloyu belirler.",
          "<strong>Ödemde</strong> parmakla bastırınca çukurlaşma olur ve bacak yükseltilince şişlik azalır. Lipödemde bunların ikisi de tipik değildir."]),
   ("note","Lipödem tanısı klinik muayeneyle konur. Ağrı, simetri, ayakların korunması ve kilo kaybına direnç birlikte değerlendirilir. Tanının gecikmesi hastalığın ilerlemesine ve zamanla lenfatik sisteme yük binmesine yol açar.")]},
  {"id":"evre","tag":"Evreleme","h2":"Lipödem evreleri","body":[
   "Evreleme, cilt yüzeyinin ve yağ dokusunun görünümüne göre yapılır. Evre, hangi tedavinin uygun olduğunu ve kaç seans gerekebileceğini belirler.",
   ("table",["Evre","Cilt ve doku","Klinik tablo"],[
     ["Evre 1","Cilt yüzeyi düz, altta ince nodüller","Ağrı ve kolay morarma başlamıştır; şekil bozukluğu hafiftir"],
     ["Evre 2","Cilt yüzeyi düzensiz, dalgalı görünüm","Nodüller belirginleşir; bölgesel şişlik ve hassasiyet artar"],
     ["Evre 3","Kalınlaşmış cilt, büyük yağ lopları","Hareket kısıtlanır; diz ve kalça eklemleri zorlanır"],
     ["Evre 4","Lipo-lenfödem","Lipödeme lenfatik yetmezlik eklenmiştir; ayaklar da tutulabilir"]]),
   "Evre ilerledikçe yalnızca görünüm değil, işlev de bozulur. Uyluk içlerinin birbirine sürtmesi yürüyüş biçimini değiştirir, bu da zamanla diz ve bel ağrılarına yol açar. Bu nedenle lipödem cerrahisi, estetik bir tercih değil işlevi koruma girişimidir.",
   ("h3","Lipo-lenfödem: iki hastalığın birleştiği nokta"),
   "Uzun süre tedavi edilmeyen lipödemde artan doku hacmi lenfatik sistemin taşıma kapasitesini aşar. Bu noktada tabloya lenfödem eklenir ve tedavi planı her iki bileşeni birden kapsamak zorunda kalır. <a href=\"lenfodem-lipodem-cerrahisi.html\">Lenfödem sayfamızda</a> bu ayrımı ayrıntılı bulabilirsiniz."]},
  {"id":"tedavi","tag":"Tedavi","h2":"Cerrahi tedavi: lenfatik koruyucu liposuction","body":[
   "Lipödem cerrahisi tıbbi bir tedavidir. Amaç hacim küçültmek değil, hastalıklı yağ dokusunu <strong>lenfatik yapılar korunarak</strong> uzaklaştırmak, ağrıyı azaltmak ve hareket kabiliyetini geri kazandırmaktır. Bu nedenle teknik, estetik liposuction'dan belirgin biçimde farklıdır.",
   ("h3","WAL — su jeti destekli liposuction"),
   "İnce bir su jeti yağ hücrelerini çevre dokudan nazikçe ayırır. Lenf damarları ve sinirler büyük ölçüde korunur, kanama ve morarma azalır. Geniş alanların tek seansta güvenle çalışılmasına imkân verir.",
   ("h3","PAL — güç destekli liposuction"),
   "Titreşimli kanül, fibrotik ve sert yağ dokusunu daha az travmayla parçalar. İleri evrede, dokunun sertleştiği bölgelerde tercih edilir.",
   ("ul",["Kanüller lenfatik akım yönüne paralel ilerletilir",
          "Tümesan sıvı planı doku ödemini en aza indirecek şekilde ayarlanır",
          "Geniş alanlar güvenlik açısından birkaç seansa bölünür",
          "İşlem sonrası bası giysisi kullanımı tedavinin ayrılmaz parçasıdır"]),
   ("note","Lipödem cerrahisi hastalığı tümüyle ortadan kaldırmaz; hastalıklı yağ dokusunu azaltır. Alınan doku geri gelmez, ancak kalan dokuda hastalık sürer. Bu nedenle ameliyat sonrası bası giysisi, hareket ve beslenme düzeni uzun vadeli sonucu belirler.")]},
  {"id":"surec","tag":"Süreç","h2":"Ameliyat ve iyileşme süreci","body":[
   ("steps",[
    ("1. ADIM — ÖN GÖRÜŞME","WhatsApp veya form üzerinden ilk temas. Ne kadar süredir devam ettiği, ağrının şiddeti, önceki tedaviler ve varsa fotoğraflarınız üzerinden ilk yönlendirme."),
    ("2. ADIM — MUAYENE VE EVRELEME","Çevre ölçümleri, cilt ve doku değerlendirmesi, lenfatik tutulum şüphesinde görüntüleme."),
    ("3. ADIM — PLANLAMA","Hangi bölgelerin hangi sırayla çalışılacağı, seans sayısı, riskler ve beklenen kazanım açıkça konuşulur."),
    ("4. ADIM — AMELİYAT","Tam donanımlı hastane koşullarında, genel ya da sedasyon eşliğinde. Süre çalışılacak alana göre değişir."),
    ("5. ADIM — İLK 6 HAFTA","Bası giysisi, erken yürüyüş, gerektiğinde manuel lenf drenajı. Ödem bu dönemde kademeli çözülür."),
    ("6. ADIM — 3–6 AY","Son şekil bu dönemde oturur. Ağrıdaki azalma çoğu hastada daha erken fark edilir.")]),
   ("note","<strong>Şehir dışı ve yurt dışı hastalar için:</strong> Ön değerlendirme çevrim içi görüşme ve gönderdiğiniz görüntülerle yapılır. Ameliyat ve kontroller tek seyahat programına toplanacak şekilde planlanır, sonraki takipler çevrim içi sürdürülür.")]}],
 "faqs":[
  ("Lipödem ameliyatı estetik liposuction ile aynı şey mi?","Hayır. Lipödem cerrahisi tıbbi bir tedavidir; amaç hastalıklı yağ dokusunun lenfatik yapılar korunarak uzaklaştırılması ve ağrının azaltılmasıdır. Kanül seçimi, giriş yönleri, tümesan sıvı planı ve seans sayısı estetik liposuction'dan farklıdır."),
  ("Ameliyattan sonra ağrı geçer mi?","Hastaların büyük bölümünde dokunma hassasiyeti ve ağrıda belirgin azalma bildirilmektedir; bu çoğu zaman hacimdeki değişimden önce fark edilir. Ancak sonuç evreye ve kalan doku miktarına göre değişir, garanti edilemez."),
  ("Kaç seans gerekir?","Etkilenen alanın genişliğine ve evreye göre değişir. Güvenlik ve iyileşme kalitesi açısından geniş alanlar genellikle 2–3 seansa bölünür. Seanslar arasında en az birkaç hafta bırakılır."),
  ("Ameliyat sonrası kilo alırsam yağ geri gelir mi?","Alınan yağ hücreleri geri gelmez. Ancak lipödem kronik bir hastalıktır ve kalan dokuda sürer; belirgin kilo alımı sonucu olumsuz etkileyebilir."),
  ("Bası giysisini ne kadar kullanmam gerekir?","Genellikle ilk 6 hafta gün boyu, sonrasında azaltılarak. Süre evreye, çalışılan alana ve iyileşme hızına göre kişiselleştirilir."),
  ("Lipödemim var mı, nasıl anlarım?","Bacaklarda simetrik şişlik, dokunmakla ağrı, kolay morarma, ayak bileğinde keskin geçiş ve kilo kaybına rağmen devam eden bölgesel birikim tipik bulgulardır. Kesin tanı için hekim muayenesi gerekir.")],
 "related":["lipodem-nedir","lipodem-belirtileri","lipodem-evreleri","ameliyatsiz-lipodem-tedavisi","lipodem-diyeti","lipodem-hangi-doktor","lenfodem"],
 "ctah":"Lipödem değerlendirmesi için ilk adım",
 "ctap":"Ne kadar süredir devam ettiğini, ağrının günlük yaşamınızı nasıl etkilediğini ve varsa bacak fotoğraflarınızı gönderin. İlk yönlendirme için size dönüş yapılır."},

{
 "key":"mikrotia",
 "authority":"Mikrotia onarımı, kıkırdak oymacılığında el becerisi ve çok sayıda vaka deneyimi gerektiren bir alandır. Doç. Dr. Acartürk, Helsinki Üniversitesi'ndeki fellowship döneminde kulak onarımları üzerine çalışmış; her yıl Vietnam'da yürüttüğü gönüllü cerrahi misyonlarda mikrotia onarımını düzenli olarak uygulamaktadır.",
 "creds":["Helsinki Üniversitesi — mikrocerrahi ve kulak onarımı fellowship'i","Vietnam gönüllü cerrahi misyonlarında düzenli mikrotia cerrahisi","Ağız, Yüz ve Çene Cerrahisi üst uzmanlığı"], "slug":"mikrotia-kulak-onarimi.html", "prio":"0.85",
 "crumb":"Mikrotia — Kulak Onarımı",
 "title":"Mikrotia (Doğuştan Kulak Yokluğu) Ameliyatı ve Kulak Onarımı | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Mikrotia: Doğuştan Kulak Yokluğu ve Cerrahi Onarımı",
 "desc":"Mikrotia nedir, hangi yaşta ameliyat edilir? Kaburga kıkırdağı ile kulak rekonstrüksiyonu, aşamalar, işitme ve iyileşme süreci. Doç. Dr. T. Oğuz Acartürk.",
 "eyebrow":"Rekonstrüktif Cerrahi",
 "h1":"Mikrotia: doğuştan kulak yokluğu ve onarımı",
 "lead":"Mikrotia, kulak kepçesinin doğuştan gelişmemiş ya da eksik gelişmiş olmasıdır. Yaklaşık her 6–10 bin doğumda bir görülür. Çocuğun kendi kaburga kıkırdağından yeni bir kulak iskeleti şekillendirilerek, doğal görünümlü ve ömür boyu kalıcı bir kulak inşa edilebilir.",
 "watopic":"mikrotia (kulak yokluğu) onarımı",
 "about":"Mikrotia", "aboutType":"MedicalCondition",
 "card":"Mikrotia onarımı", "cardsub":"Doğuştan kulak yokluğunda kaburga kıkırdağı ile rekonstrüksiyon",
 "procedure":{"name":"Mikrotia Rekonstrüksiyonu",
   "how":"Hastanın kendi kaburga kıkırdağından üç boyutlu bir kulak iskeleti şekillendirilir, cilt altına yerleştirilir ve sonraki aşamada kulak baştan ayrılarak doğal açısı verilir.",
   "prep":"Kıkırdak olgunluğunun ve göğüs kafesi gelişiminin değerlendirilmesi; işitme testi ve gerektiğinde tomografi.",
   "follow":"Yara bakımı, kulağa bası uygulanmasının önlenmesi ve aşamalar arası planlı kontroller.",
   "body":"Kulak"},
 "keyfacts":[("Sıklık","6–10 bin doğumda bir"),("Ameliyat yaşı","Genellikle 8–10 yaş"),
             ("Yöntem","Otolog kaburga kıkırdağı"),("Aşama","2–3 aşamalı planlama")],
 "sections":[
  {"id":"nedir","tag":"Temel Bilgi","h2":"Mikrotia nedir?","body":[
   "Mikrotia, kulak kepçesinin gebeliğin erken haftalarında tamamlanamayan gelişimi sonucu ortaya çıkar. Tek taraflı olması daha sıktır ve çoğunlukla sağ kulağı etkiler. Kulak kepçesinin yokluğuna sıklıkla dış kulak yolunun dar olması veya hiç bulunmaması (atrezi) eşlik eder.",
   ("h3","Derecelendirme"),
   ("ul",["<strong>Derece 1:</strong> Kulak küçüktür ancak yapıların çoğu tanınabilir.",
          "<strong>Derece 2:</strong> Kulağın alt kısmı belirgin, üst yapılar gelişmemiştir.",
          "<strong>Derece 3:</strong> En sık görülen biçim. Yalnızca fıstık şeklinde bir kıkırdak artığı ve kulak memesi vardır; dış kulak yolu genellikle yoktur.",
          "<strong>Derece 4 (anotia):</strong> Kulak dokusu tamamen yoktur."]),
   ("note","Mikrotia çoğu zaman tek başına görülür, ancak bazı sendromların parçası olabilir. Bu nedenle ilk değerlendirme yalnızca kulakla sınırlı kalmaz; yüz simetrisi, çene gelişimi ve işitme birlikte incelenir.")]},
  {"id":"isitme","tag":"İşitme","h2":"İşitme ve konuşma gelişimi","body":[
   "Kulak kepçesi sesi toplar, ancak işitmenin asıl işini iç kulak yapar. Tek taraflı mikrotiada karşı kulak sağlıklıysa çocuk genellikle normal konuşma gelişimi gösterir. Yine de sesin yönünü belirlemede ve gürültülü ortamda konuşmayı ayırt etmede güçlük olabilir.",
   "Çift taraflı mikrotiada durum farklıdır: işitme desteği <strong>erken dönemde</strong> sağlanmalıdır. Bu, kemik iletimli işitme cihazlarıyla yapılabilir ve konuşma gelişimi için kritik önemdedir.",
   ("note","İşitme değerlendirmesi kulak kepçesi onarımından bağımsız ve önceliklidir. Odyoloji ve kulak burun boğaz ekibiyle birlikte planlanır; kepçe onarımı işitmeyi tek başına düzeltmez.")]},
  {"id":"yontem","tag":"Cerrahi","h2":"Cerrahi yöntem ve aşamalar","body":[
   "Altın standart, çocuğun <strong>kendi kaburga kıkırdağından</strong> üç boyutlu bir kulak iskeleti şekillendirilmesidir. Kendi dokusu olduğu için reddedilme riski yoktur, çocukla birlikte büyür ve ömür boyu kalıcıdır.",
   ("h3","Neden 8–10 yaş?"),
   ("ul",["Kaburga kıkırdağı ancak bu yaşlarda iskeleti oyacak kalınlığa ulaşır",
          "Kulak bu yaşta erişkin boyutunun yaklaşık %85'ine gelir, karşı kulakla simetri kurulabilir",
          "Çocuk ameliyat sonrası bakıma katılabilecek olgunluğa erişir",
          "Okul çağında görünümün önem kazandığı dönemin öncesine denk gelir"]),
   ("h3","Aşamalar"),
   ("steps",[
    ("1. AŞAMA — İSKELET","Kaburga kıkırdağı alınır, kulak iskeleti oyularak şekillendirilir ve kulak bölgesinde hazırlanan cilt cebine yerleştirilir."),
    ("2. AŞAMA — KULAK MEMESİ","Mevcut kulak memesi doğru konuma taşınır ve iskeletle bütünleştirilir. Bazı planlarda birinci aşamayla birleştirilir."),
    ("3. AŞAMA — KULAĞIN AYRILMASI","Kulak baştan ayrılarak arkasına doku ve deri grefti yerleştirilir; kulağa doğal açısı ve derinliği kazandırılır.")]),
   "Aşamalar arasında genellikle 4–6 ay bırakılır. Bu süre dokunun yerleşmesi ve kan dolaşımının olgunlaşması için gereklidir."]},
  {"id":"deneyim","tag":"Deneyim","h2":"Bu alandaki deneyim","body":[
   "Mikrotia onarımı, plastik cerrahinin en çok tekrar ve el becerisi gerektiren alanlarından biridir. Kıkırdak oymacılığı, sonucun doğal görünüp görünmeyeceğini doğrudan belirler.",
   "Doç. Dr. Acartürk, her yıl Vietnam'da gönüllü cerrahi misyonlara katılmakta; bu programlarda mikrotia onarımı, dudak–damak yarığı ve brakiyal pleksus cerrahisi uygulamaktadır. Helsinki Üniversitesi'ndeki fellowship döneminde de kulak onarımları çalışma alanlarından biri olmuştur.",
   ("note","Mikrotia onarımında acele etmek, hem kıkırdak yetersizliği hem de simetri açısından sonucu kalıcı olarak sınırlayabilir. Doğru zamanlama, doğru teknikten daha az önemli değildir.")]}],
 "faqs":[
  ("Mikrotia ameliyatı için doğru yaş nedir?","Kaburga kıkırdağının yeterli kalınlığa ulaşması ve kulağın erişkin boyutuna yaklaşması nedeniyle genellikle 8–10 yaş önerilir. Çift taraflı olgularda ve göğüs kafesi gelişimine göre bu aralık değişebilir."),
  ("Kaç ameliyat gerekir?","Genellikle 2–3 aşama planlanır ve aşamalar arasında 4–6 ay bırakılır. Aşama sayısı mikrotianın derecesine ve mevcut dokuya göre değişir."),
  ("Kaburgadan kıkırdak almak çocuğa zarar verir mi?","Alınan kıkırdak bölgesi zamanla kendini onarır ve göğüs kafesi gelişimi normal seyreder. Ameliyat sonrası ilk günlerde göğüs bölgesinde ağrı olması beklenir ve kontrol altına alınır."),
  ("Ameliyat işitmeyi düzeltir mi?","Hayır. Kulak kepçesi onarımı görünümü yeniden inşa eder; işitme ayrı bir konudur ve odyoloji ile kulak burun boğaz ekibiyle birlikte değerlendirilir. Gerektiğinde kemik iletimli cihazlar veya ayrı bir işitme cerrahisi planlanır."),
  ("Protez kulak bir seçenek mi?","Yapıştırmalı veya implanta tutunan protezler bazı durumlarda seçenektir; özellikle kıkırdak yetersizse veya hasta cerrahi istemiyorsa. Ancak kendi dokusuyla yapılan onarım kalıcıdır ve günlük bakım gerektirmez."),
  ("Ameliyattan sonra iz kalır mı?","Kulak arkasında ve göğüste izler oluşur. Göğüsteki kesi meme altı katlantısına gizlenir, kulak arkasındaki izler saç ve kulak gölgesinde kalır; zamanla belirginlikleri azalır.")],
 "related":["bas-boyun","yuz-felci","kulak-estetigi"],
 "ctah":"Mikrotia değerlendirmesi için ilk adım",
 "ctap":"Çocuğunuzun yaşını, mikrotianın hangi kulakta olduğunu, varsa işitme testi sonuçlarını ve fotoğrafları gönderin. Planlama görüşmesi için size dönüş yapılır."},

{
 "key":"bas-boyun",
 "authority":"Baş–boyun rekonstrüksiyonu, Doç. Dr. Acartürk'ün akademik kariyerinin merkezindeki alandır. 2011 yılında Pittsburgh Üniversitesi Plastik Cerrahi Bölümü'ne <strong>Baş–Boyun Onarımları Direktörü</strong> olarak atanmış, bu görevi sırasında 300'ün üzerinde baş–boyun mikrocerrahi ameliyatı gerçekleştirmiş ve bu vakalarda o bölümde daha önce ulaşılmamış bir oranda doku yaşayabilirliği sağlamıştır.",
 "creds":["Pittsburgh Üniversitesi Baş–Boyun Onarımları eski Direktörü","300+ baş–boyun mikrocerrahi vakası","Ağız, Yüz ve Çene Cerrahisi üst uzmanlığı — T.C. Sağlık Bakanlığı"], "slug":"bas-boyun-cene-rekonstruksiyonu.html", "prio":"0.8",
 "crumb":"Baş, Boyun ve Çene Rekonstrüksiyonu",
 "title":"Baş, Boyun ve Çene Rekonstrüksiyonu — Mikrocerrahi Onarım | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Baş, Boyun ve Çene Rekonstrüksiyonu",
 "desc":"Kanser cerrahisi sonrası çene, ağız içi ve boyun bölgesinin serbest doku aktarımıyla onarımı. Fibula flebi, mikrocerrahi teknikler, konuşma ve yutma işlevinin geri kazanılması.",
 "eyebrow":"Rekonstrüktif Cerrahi",
 "h1":"Baş, boyun ve çene rekonstrüksiyonu",
 "lead":"Baş–boyun bölgesindeki kanserlerin çıkarılması sonrası oluşan doku kayıpları, vücudun en zorlu onarım alanlarından birini oluşturur. Burada amaç yalnızca görünümü değil, konuşmayı, çiğnemeyi ve yutmayı geri kazandırmaktır.",
 "watopic":"baş–boyun rekonstrüksiyonu",
 "about":"Baş ve boyun rekonstrüksiyonu", "aboutType":"MedicalProcedure",
 "card":"Baş–boyun onarımı", "cardsub":"Çene, ağız içi ve boyun bölgesinde serbest doku aktarımı",
 "procedure":{"name":"Serbest Doku Aktarımı ile Baş–Boyun Rekonstrüksiyonu",
   "how":"Vücudun başka bir bölgesinden damarlarıyla birlikte alınan kemik, kas veya deri dokusu, mikroskop altında boyun damarlarına bağlanarak defekt bölgesine aktarılır.",
   "prep":"Onkolojik ekiple ortak planlama, damar haritalaması ve gerektiğinde üç boyutlu modelleme.",
   "follow":"Yoğun bakım takibi, doku dolaşımının izlenmesi, konuşma ve yutma terapisi.",
   "body":"Çene, ağız içi, boyun, kafa kaidesi"},
 "keyfacts":[("Deneyim","Pittsburgh Ü. Baş–Boyun Onarımları Direktörlüğü"),("Vaka","300+ mikrocerrahi vaka"),
             ("Doku yaşayabilirliği","%100 (Pittsburgh dönemi)"),("Ameliyat süresi","Ortalama 10–12 saat")],
 "sections":[
  {"id":"neden","tag":"Kapsam","h2":"Bu onarımlar neden özeldir?","body":[
   "Baş–boyun bölgesi, küçük bir hacimde çok sayıda işlevi barındırır: konuşma, çiğneme, yutma, nefes alma ve yüz ifadesi. Kanserin güvenli sınırlarla çıkarılması genellikle kemik, kas, mukoza ve deriyi aynı anda etkileyen bir kayıp bırakır.",
   "Bu kaybın onarımı, vücudun diğer bölgelerindeki mikrocerrahi onarımlardan belirgin biçimde zordur. Bölgenin üç boyutlu geometrisi karmaşıktır, aktarılan dokunun hem şekli hem işlevi karşılaması gerekir ve ameliyat çoğu zaman 10–12 saat sürer; kafa kaidesini ilgilendiren olgularda daha da uzayabilir.",
   ("note","Bu ameliyatlar tek bir cerrahın işi değildir. Kulak burun boğaz, onkolojik cerrahi, radyasyon onkolojisi, diş hekimliği, konuşma ve yutma terapisi ekipleriyle birlikte planlanır. Çok disiplinli çalışamayan merkezlerde sonuç kaçınılmaz olarak sınırlanır.")]},
  {"id":"yontem","tag":"Yöntem","h2":"Kullanılan doku aktarımları","body":[
   ("h3","Fibula (kaval kemiği) serbest flebi"),
   "Alt bacaktaki fibula kemiği, damarları ve üzerindeki deri adasıyla birlikte alınır. Çene kemiğinin şekline göre oyulup plaklanır ve boyun damarlarına bağlanır. Diş implantı taşıyabilecek kalitede kemik sağladığı için alt çene onarımının standardıdır.",
   ("h3","Ön kol radial flebi"),
   "İnce ve esnek yapısıyla ağız içi mukoza ve dil onarımlarında tercih edilir. Konuşma ve yutma için gereken hareketliliği korur.",
   ("h3","Anterolateral uyluk flebi"),
   "Geniş yumuşak doku kayıplarında kullanılır. Kalınlığı ayarlanabilir, uyluk bölgesinde iz gizlenebilir.",
   ("h3","Skapula ve latissimus dorsi flepleri"),
   "Kemik ve büyük hacimli kas dokusunun birlikte gerektiği karmaşık olgularda kullanılır.",
   ("ul",["Aktarılan dokunun damarları mikroskop altında yaklaşık 1–2 mm çapında bağlanır",
          "Doku dolaşımı ilk 72 saat boyunca yakından izlenir",
          "Gerektiğinde ikincil düzeltme ve diş rehabilitasyonu planlanır"])]},
  {"id":"surec","tag":"Süreç","h2":"Ameliyat ve iyileşme","body":[
   ("steps",[
    ("1. ADIM — ORTAK PLANLAMA","Onkolojik ekiple birlikte çıkarılacak alanın ve oluşacak defektin önceden belirlenmesi; verici bölge seçimi."),
    ("2. ADIM — AMELİYAT","Tümör çıkarımı ve rekonstrüksiyon aynı seansta yapılır. İki ekip eş zamanlı çalışır."),
    ("3. ADIM — İLK 72 SAAT","Yoğun bakımda doku dolaşımının düzenli takibi. Bu dönem sonucun belirleyici aşamasıdır."),
    ("4. ADIM — İLK 6 HAFTA","Yara iyileşmesi, beslenme desteği, konuşma ve yutma terapisinin başlaması."),
    ("5. ADIM — 3–12 AY","Gerektiğinde ikincil düzeltmeler, diş implantı ve radyoterapi sonrası doku bakımı.")]),
   ("note","Radyoterapi almış dokularda iyileşme yavaşlar ve komplikasyon riski artar. Bu olgularda yağ dokusu ve kök hücre destekli tedaviler, doku kalitesini iyileştirmek için tamamlayıcı olarak kullanılabilir.")]}],
 "faqs":[
  ("Bu ameliyatlar ne kadar sürer?","Ortalama 10–12 saat sürer. Kafa kaidesini ilgilendiren karmaşık olgularda 24 saati aşabilir. Süre, defektin büyüklüğüne ve kaç ekibin eş zamanlı çalıştığına bağlıdır."),
  ("Aktarılan doku tutmazsa ne olur?","Mikrocerrahide doku kaybı riski dünya ortalamasında yaklaşık %5'tir. Erken fark edildiğinde acil damar revizyonu ile doku kurtarılabilir; bu nedenle ilk 72 saatteki takip kritik önemdedir."),
  ("Konuşmam ve yutmam eskisi gibi olur mu?","Amaç budur, ancak sonuç çıkarılan dokunun miktarına ve yerine bağlıdır. Konuşma ve yutma terapisi bu sürecin ayrılmaz parçasıdır; işlevin geri kazanılması aylar sürebilir."),
  ("Çeneme diş yapılabilir mi?","Fibula flebi ile onarılan alt çeneye diş implantı yerleştirilebilir. Zamanlama, kemiğin kaynaması ve radyoterapi durumu birlikte değerlendirilerek belirlenir."),
  ("Bacağımdan kemik alınması yürüyüşümü etkiler mi?","Fibula, vücut ağırlığını taşıyan ana kemik değildir. Alınmasından sonra yürüme işlevi korunur; ilk haftalarda destekle yürüme ve fizyoterapi gerekir.")],
 "related":["mikrotia","yuz-felci","yanik"],
 "ctah":"Değerlendirme ve ikinci görüş",
 "ctap":"Mevcut tanınızı, planlanan ya da geçirilmiş cerrahiyi, radyoterapi öykünüzü ve varsa görüntülerinizi gönderin. Onkolojik ekibinizle koordinasyon için size dönüş yapılır."},

{
 "key":"yuz-felci",
 "authority":"Yüz felcinde dinamik onarım, mikrocerrahi ile sinir cerrahisinin kesiştiği noktadadır. Doç. Dr. Acartürk, Pittsburgh Üniversitesi'ndeki görevi sırasında yüz felci ekibinin içinde yer almış; mikrocerrahi ve serbest kas aktarımıyla dinamik onarım konusunda geniş bir deneyim edinmiştir.",
 "creds":["Pittsburgh Üniversitesi yüz felci ekibinde görev","Serbest kas transferi ve sinir aktarımı deneyimi","Ağız, Yüz ve Çene Cerrahisi üst uzmanlığı"], "slug":"yuz-felci-tedavisi.html", "prio":"0.8",
 "crumb":"Yüz Felci Cerrahisi",
 "title":"Yüz Felci Ameliyatı — Dinamik Kas Aktarımı ve Gülümseme Onarımı | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Yüz Felci: Cerrahi Tedavi ve Gülümseme Onarımı",
 "desc":"Yüz felcinde cerrahi tedavi seçenekleri: sinir aktarımı, serbest kas transferi ile dinamik gülümseme onarımı, göz kapağı ve simetri düzeltmeleri.",
 "eyebrow":"Rekonstrüktif Cerrahi",
 "h1":"Yüz felci cerrahisi ve gülümseme onarımı",
 "lead":"Yüz felci yalnızca bir görünüm sorunu değildir. Gözün kapanamaması görmeyi tehdit eder, ağzın hareketsizliği konuşmayı ve yemeyi zorlaştırır, gülümseyememek sosyal yaşamı derinden etkiler. Mikrocerrahi, kaybedilen hareketi geri kazandırabilir.",
 "watopic":"yüz felci cerrahisi",
 "about":"Fasiyal paralizi", "aboutType":"MedicalCondition",
 "card":"Yüz felci cerrahisi", "cardsub":"Sinir aktarımı ve serbest kas transferiyle dinamik onarım",
 "procedure":{"name":"Serbest Kas Transferi ile Dinamik Yüz Onarımı",
   "how":"Uyluk veya göğüs bölgesinden damar ve siniriyle birlikte alınan bir kas dilimi yüze aktarılır; mikroskop altında damarları ve siniri bağlanarak istemli gülümseme hareketi sağlanır.",
   "prep":"Felcin süresi ve tipinin belirlenmesi, EMG ile kas canlılığının değerlendirilmesi.",
   "follow":"Yüz rehabilitasyonu ve hareketin öğrenilmesi için düzenli fizyoterapi.",
   "body":"Yüz"},
 "keyfacts":[("Belirleyici","Felcin üzerinden geçen süre"),("Erken dönem","Sinir onarımı / aktarımı"),
             ("Geç dönem","Serbest kas transferi"),("Hareket başlangıcı","Ameliyattan 4–6 ay sonra")],
 "sections":[
  {"id":"neden","tag":"Temel Bilgi","h2":"Yüz felci neden olur?","body":[
   "Yüz siniri (fasiyal sinir), yüzün mimik kaslarını çalıştıran sinirdir. Bu sinirin işlevini kaybetmesi tek taraflı hareketsizliğe yol açar. Başlıca nedenler:",
   ("ul",["<strong>Bell felci</strong> — çoğu olguda kendiliğinden düzelir, ancak bir bölümünde kalıcı kayıp olur",
          "<strong>Tümör cerrahisi</strong> — özellikle akustik nörinom ve parotis bezi tümörleri",
          "<strong>Travma</strong> — yüz kırıkları ve kesici yaralanmalar",
          "<strong>Doğuştan</strong> — Möbius sendromu ve diğer gelişimsel nedenler",
          "<strong>Enfeksiyon</strong> — zona ve orta kulak enfeksiyonları"]),
   ("note","Cerrahi planlamada en belirleyici etken, felcin üzerinden geçen süredir. Mimik kasları sinir uyarısı almadan yaklaşık 18–24 ay sonra geri dönüşsüz olarak erimeye başlar. Bu eşik, hangi ameliyatın mümkün olduğunu belirler.")]},
  {"id":"secenek","tag":"Cerrahi Seçenekler","h2":"Tedavi seçenekleri","body":[
   ("h3","Erken dönem — sinir onarımı ve aktarımı"),
   "Kaslar hâlâ canlıysa, hedef sinire uyarı taşımaktır. Kesilen sinir doğrudan onarılabilir, araya sinir grefti konabilir ya da başka bir sinirin (masseter siniri, karşı yüz siniri) dalı hedefe yönlendirilebilir. Bu yöntemler kendi kaslarınızı yeniden çalıştırdığı için en doğal sonucu verir.",
   ("h3","Geç dönem — serbest kas transferi"),
   "Kaslar eridiyse yeni bir kas gerekir. Uyluktan (gracilis kası) damar ve siniriyle birlikte alınan bir dilim yüze aktarılır, mikroskop altında damarları ve siniri bağlanır. Kas, karşı yüz sinirinden ya da çiğneme sinirinden aldığı uyarıyla istemli gülümseme hareketini üretir.",
   ("h3","Statik destekler"),
   "Hareket sağlamayan ancak simetriyi ve işlevi koruyan girişimlerdir: göz kapağına altın ağırlık yerleştirilmesi, kaş askısı, ağız köşesinin fasya şeritleriyle askıya alınması. Genel durumu ağır hastalarda tek başına da tercih edilebilir.",
   ("note","Göz kapağının kapanamaması korneayı kurutur ve kalıcı görme kaybına yol açabilir. Bu nedenle göz koruması, gülümseme onarımından önce ele alınması gereken ilk başlıktır.")]},
  {"id":"surec","tag":"Süreç","h2":"Süreç ve beklentiler","body":[
   ("steps",[
    ("1. ADIM — DEĞERLENDİRME","Felcin nedeni, süresi ve derecesi; EMG ile kas canlılığının ölçülmesi; göz sağlığının kontrolü."),
    ("2. ADIM — PLANLAMA","Hangi yöntemin uygun olduğu, kaç aşama gerekeceği ve gerçekçi beklentiler açıkça konuşulur."),
    ("3. ADIM — AMELİYAT","Yönteme göre 3–8 saat arası. Serbest kas transferinde mikrocerrahi damar ve sinir bağlantıları yapılır."),
    ("4. ADIM — 4–6 AY","Sinir, aktarılan kasa ulaşır ve ilk hareketler görülmeye başlar. Bu süre beklemeyi gerektirir."),
    ("5. ADIM — REHABİLİTASYON","Yüz fizyoterapisi ile hareketin bilinçli kullanımı öğrenilir. Sonucun kalitesini belirleyen aşamadır.")]),
   "Doç. Dr. Acartürk, Pittsburgh Üniversitesi'ndeki görevi sırasında yüz felci ekibinin içinde yer almış; mikrocerrahi ve kas aktarımıyla dinamik onarım konusunda geniş bir deneyim edinmiştir."]}],
 "faqs":[
  ("Yüz felcim yıllar önce oldu, geç kaldım mı?","Hayır. Kaslar erimiş olsa bile serbest kas transferi ile yeni bir hareket kaynağı oluşturulabilir. Süre yöntemi değiştirir, seçeneği ortadan kaldırmaz."),
  ("Ameliyattan sonra ne zaman gülümseyebilirim?","Sinirin aktarılan kasa ulaşması ve kasın çalışmaya başlaması genellikle 4–6 ay sürer. Hareketin doğal ve istemli hâle gelmesi fizyoterapiyle birlikte bir yılı bulabilir."),
  ("Gülümsemem karşı tarafla aynı olur mu?","Amaç simetriye mümkün olduğunca yaklaşmaktır. Karşı yüz sinirinden beslenen transferlerde gülümseme daha kendiliğinden olur; çiğneme sinirinden beslenenlerde başlangıçta bilinçli çaba gerekir."),
  ("Gözüm kapanmıyor, önce ne yapılmalı?","Göz koruması önceliklidir. Yapay gözyaşı, gece kapatma ve gerekirse üst kapağa altın ağırlık yerleştirilmesi korneayı korur. Bu, gülümseme onarımından önce ele alınır."),
  ("Botoks yüz felcinde kullanılır mı?","Evet, ancak farklı bir amaçla: sağlam taraftaki aşırı hareketi dengelemek veya felç sonrası ortaya çıkan istemsiz kasılmaları (sinkinezi) azaltmak için tamamlayıcı olarak kullanılabilir.")],
 "related":["bas-boyun","mikrotia","goz-kapagi"],
 "ctah":"Yüz felci değerlendirmesi",
 "ctap":"Felcin ne zaman başladığını, nedenini, uygulanan tedavileri ve varsa video ya da fotoğraflarınızı gönderin. Hangi seçeneklerin uygun olduğunu birlikte değerlendirelim."},

{
 "key":"meme-rek",
 "authority":"Meme rekonstrüksiyonu, mikrocerrahi ile estetik cerrahinin birlikte düşünülmesini gerektirir. Doç. Dr. Acartürk hem serbest doku aktarımında hem meme estetiğinde uzun yıllara dayanan pratiğe sahiptir; ayrıca lenfödem mikrocerrahisi yaptığı için meme rekonstrüksiyonunu kol lenfödemi tedavisiyle <strong>aynı seansta</strong> planlayabilmektedir.",
 "creds":["300+ serbest doku aktarımı deneyimi","Lenfödem mikrocerrahisiyle eş zamanlı planlama imkânı","Amerika'da meme cerrahisi pratiği ve meslektaş yönlendirmeleri"], "slug":"meme-rekonstruksiyonu.html", "prio":"0.85",
 "crumb":"Meme Rekonstrüksiyonu",
 "title":"Meme Kanseri Sonrası Meme Rekonstrüksiyonu — DIEP ve İmplant | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Meme Kanseri Sonrası Meme Rekonstrüksiyonu",
 "desc":"Mastektomi sonrası meme rekonstrüksiyonu: DIEP flebi ile kendi dokunuzla onarım, implantla rekonstrüksiyon, eş zamanlı ve gecikmiş planlama, kol lenfödemi ile birlikte tedavi.",
 "eyebrow":"Rekonstrüktif Cerrahi",
 "h1":"Meme kanseri sonrası meme rekonstrüksiyonu",
 "lead":"Meme rekonstrüksiyonu, kanser tedavisinin sonu değil, iyileşmenin parçasıdır. Kendi dokunuzla ya da implantla yapılabilir; mastektomiyle aynı seansta ya da tedavi tamamlandıktan sonra planlanabilir. Doğru zamanlama, seçeneklerinizi belirler.",
 "watopic":"meme rekonstrüksiyonu",
 "about":"Meme rekonstrüksiyonu", "aboutType":"MedicalProcedure",
 "card":"Meme rekonstrüksiyonu", "cardsub":"Kanser sonrası kendi dokunuzla veya implantla onarım",
 "procedure":{"name":"DIEP Flebi ile Meme Rekonstrüksiyonu",
   "how":"Alt karın bölgesinden kas kesilmeden, yalnızca deri, yağ ve besleyici damarlar alınarak göğüs damarlarına mikrocerrahi ile bağlanır ve meme şekillendirilir.",
   "prep":"Onkolojik ekiple ortak planlama, damar haritalaması (BT anjiyografi) ve radyoterapi takviminin değerlendirilmesi.",
   "follow":"Doku dolaşımının izlenmesi, karın bölgesi bakımı ve ikinci aşamada meme başı rekonstrüksiyonu.",
   "body":"Meme"},
 "keyfacts":[("Zamanlama","Eş zamanlı veya gecikmiş"),("Kendi dokusu","DIEP, TRAM, latissimus dorsi"),
             ("Protez","Doku genişletici + implant"),("Ek imkân","Kol lenfödemiyle eş zamanlı tedavi")],
 "sections":[
  {"id":"zamanlama","tag":"Zamanlama","h2":"Eş zamanlı mı, sonra mı?","body":[
   ("h3","Eş zamanlı (immediate) rekonstrüksiyon"),
   "Mastektomi ile aynı ameliyatta yapılır. Meme cildi korunduğu için sonuç genellikle daha doğaldır, hasta memesiz bir dönem yaşamaz ve toplam ameliyat sayısı azalır. Radyoterapi gerekmeyeceği öngörülen olgularda tercih edilir.",
   ("h3","Gecikmiş (delayed) rekonstrüksiyon"),
   "Onkolojik tedavi, özellikle radyoterapi tamamlandıktan sonra yapılır. Işın görmüş dokuda implantın başarısı düşer; bu nedenle radyoterapi alan hastalarda kendi dokusuyla onarım öne çıkar.",
   ("note","Rekonstrüksiyon kararı, meme cerrahınız ve radyasyon onkoloğunuzla birlikte verilmelidir. Mastektomiden <strong>önce</strong> plastik cerrahla görüşmek, elinizdeki seçenekleri belirgin biçimde genişletir. Rekonstrüksiyon kanser takibini zorlaştırmaz ve nüks riskini artırmaz.")]},
  {"id":"yontem","tag":"Yöntem","h2":"Rekonstrüksiyon yöntemleri","body":[
   ("h3","DIEP flebi — kendi dokunuzla"),
   "Alt karın bölgesindeki deri ve yağ dokusu, besleyici damarlarıyla birlikte alınıp göğse aktarılır. <strong>Karın kası kesilmez</strong>, bu yönüyle eski TRAM yönteminden ayrılır; karın gücü korunur ve fıtık riski azalır. Sonuç yumuşaktır, doğal sarkma davranışı gösterir ve kilo değişimlerinde vücutla birlikte hareket eder.",
   ("h3","İmplantla rekonstrüksiyon"),
   "Önce bir doku genişletici yerleştirilir, haftalar içinde kademeli doldurularak cilt gerdirilir, ardından kalıcı implantla değiştirilir. Daha kısa ameliyat ve daha hızlı iyileşme sağlar; ancak ışın görmüş dokuda kapsül kontraktürü riski yüksektir.",
   ("h3","Latissimus dorsi flebi"),
   "Sırttan alınan kas ve deri dokusu, çoğu zaman implantla birlikte kullanılır. Karın dokusu yetersiz olan ya da daha önce karın ameliyatı geçirmiş hastalarda seçenektir.",
   ("h3","Yağ enjeksiyonu ile hacimlendirme"),
   "Kendi yağ dokunuz, kontur düzensizliklerini gidermek ve ışın görmüş cildin kalitesini iyileştirmek için kullanılır. Genellikle tamamlayıcı bir aşamadır."]},
  {"id":"lenfodem","tag":"Ek İmkân","h2":"Kol lenfödemi ile birlikte tedavi","body":[
   "Koltuk altı lenf nodlarının çıkarılması ve radyoterapi, kolda lenfödeme yol açabilir. Meme rekonstrüksiyonu planlanan hastalarda bu iki sorun <strong>tek ameliyatta</strong> ele alınabilir: doku aktarımıyla eş zamanlı olarak vaskülarize lenf nodu transferi yapılabilir.",
   "Bu yaklaşım hastayı ikinci bir büyük ameliyattan kurtarır ve lenfödeme erken dönemde müdahale imkânı verir. Ayrıntılar için <a href=\"lenfodem-lipodem-cerrahisi.html\">lenfödem cerrahisi sayfamıza</a> bakabilirsiniz.",
   ("note","Kolunuzda ağırlık hissi, yüzük ya da saatin sıkması gibi erken bulgular fark ederseniz beklemeyin. Lenfödemde erken dönem girişimler, doku sertleşmesi yerleştikten sonra yapılanlardan belirgin şekilde daha etkilidir.")]},
  {"id":"surec","tag":"Süreç","h2":"Süreç ve iyileşme","body":[
   ("steps",[
    ("1. ADIM — ORTAK PLANLAMA","Meme cerrahı ve radyasyon onkoloğuyla birlikte zamanlama ve yöntem kararı."),
    ("2. ADIM — HAZIRLIK","Damar haritalaması, karın dokusunun değerlendirilmesi, sigara bırakma ve genel hazırlık."),
    ("3. ADIM — AMELİYAT","DIEP'te 6–8 saat; implantla rekonstrüksiyonda daha kısa. Hastanede 3–5 gün."),
    ("4. ADIM — İLK 6 HAFTA","Ağır kaldırma kısıtlaması, karın bölgesi bakımı, kademeli aktiviteye dönüş."),
    ("5. ADIM — 3–6 AY","Simetri düzeltmeleri, karşı memeye gerekirse müdahale, meme başı ve areola rekonstrüksiyonu.")])]}],
 "faqs":[
  ("Rekonstrüksiyon kanserin tekrarını gizler mi?","Hayır. Yapılan çalışmalar meme rekonstrüksiyonunun nüks riskini artırmadığını ve takibi zorlaştırmadığını göstermektedir. Onkolojik takibiniz normal şekilde sürer."),
  ("DIEP ile TRAM arasındaki fark nedir?","DIEP'te karın kası kesilmez, yalnızca damarlar kas içinden ayrıştırılır; karın gücü korunur ve fıtık riski azalır. TRAM'da ise kasın bir bölümü dokuyla birlikte alınır."),
  ("Radyoterapi alacaksam ne yapmalıyım?","Işın görmüş dokuda implantın başarısı düşer ve kapsül kontraktürü riski artar. Bu nedenle radyoterapi planlanan hastalarda genellikle kendi dokusuyla onarım ve gecikmiş rekonstrüksiyon tercih edilir."),
  ("Yeniden hissedebilecek miyim?","Aktarılan dokuda duyu başlangıçta azdır. Zamanla kısmi duyu geri dönebilir; bazı olgularda sinir bağlantısı da yapılarak duyunun geri kazanılması hedeflenebilir."),
  ("Karnımda nasıl bir iz kalır?","Kesi, karın germe ameliyatındakine benzer biçimde bikini hattına yerleştirilir. Göbek yeniden şekillendirilir. Karın bölgesi aynı zamanda düzleşir."),
  ("Tek memem alındı, simetri sağlanabilir mi?","Evet. Karşı memeye küçültme, dikleştirme veya büyütme uygulanarak simetri kurulabilir. Bu genellikle ikinci aşamada planlanır.")],
 "related":["lenfodem","meme-estetigi","yag-enjeksiyonu"],
 "ctah":"Meme rekonstrüksiyonu değerlendirmesi",
 "ctap":"Tanınızı, planlanan ya da geçirilmiş cerrahiyi, radyoterapi durumunuzu ve varsa görüntülerinizi gönderin. Onkolojik ekibinizle koordinasyon için size dönüş yapılır."},

{
 "key":"el-cerrahisi",
 "authority":"El cerrahisi ve replantasyon, Doç. Dr. Acartürk'ün ihtisas döneminden itibaren yoğun çalıştığı alanlardandır. Pittsburgh Üniversitesi'nde el cerrahisi, uzuv kopmaları ve karmaşık yaralanmalar üzerine kapsamlı bir pratik edinmiş; Vietnam'daki gönüllü misyonlarda ayaktan ele parmak aktarımı ve brakiyal pleksus cerrahisi uygulamaktadır.",
 "creds":["Pittsburgh Üniversitesi'nde el cerrahisi ve replantasyon pratiği","Vietnam misyonlarında ayaktan ele parmak aktarımı","3 yıl genel cerrahi ve damar cerrahisi eğitimi"], "slug":"el-cerrahisi-replantasyon.html", "prio":"0.75",
 "crumb":"El Cerrahisi ve Replantasyon",
 "title":"El Cerrahisi ve Uzuv Replantasyonu — Kopan Parmak Dikimi | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"El Cerrahisi ve Uzuv Replantasyonu",
 "desc":"Kopan parmak ve uzuv replantasyonu, ayaktan ele parmak aktarımı, tendon ve sinir onarımı, el travmalarında ikincil rekonstrüksiyon.",
 "eyebrow":"Rekonstrüktif Cerrahi",
 "h1":"El cerrahisi ve uzuv replantasyonu",
 "lead":"El, insan vücudunun en yoğun işlev taşıyan bölgesidir. Bir parmağın kaybı yalnızca görünümü değil, kavramayı, çalışmayı ve günlük yaşamın her ayrıntısını etkiler. Mikrocerrahi, kopan uzuvların yerine dikilmesini ve kaybedilen işlevin yeniden inşasını mümkün kılar.",
 "watopic":"el cerrahisi ve replantasyon",
 "about":"El rekonstrüksiyonu", "aboutType":"MedicalProcedure",
 "card":"El cerrahisi", "cardsub":"Replantasyon, parmak aktarımı ve işlevsel onarım",
 "procedure":{"name":"Uzuv Replantasyonu",
   "how":"Kopan uzuvdaki kemik sabitlenir, ardından mikroskop altında atardamar, toplardamar, sinir ve tendonlar sırayla onarılarak dolaşım yeniden kurulur.",
   "prep":"Kopan parçanın doğru saklanması, kanamanın kontrolü ve acil merkeze ulaşım.",
   "follow":"Dolaşım takibi, erken el terapisi ve uzun süreli rehabilitasyon.",
   "body":"El, parmak, üst ekstremite"},
 "keyfacts":[("Kritik süre","Parmakta 12 saate kadar (soğutulmuş)"),("İlk müdahale","Parça temiz beze sarılıp buzlu suda"),
             ("Yöntem","Mikrocerrahi damar ve sinir onarımı"),("Rehabilitasyon","Sonucu belirleyen aşama")],
 "sections":[
  {"id":"acil","tag":"Acil Durum","h2":"Uzuv kopmasında ilk yapılması gerekenler","body":[
   "Replantasyonun başarısı, ilk saatlerde yapılanlara doğrudan bağlıdır. Kopan parça doğru saklanırsa, parmak seviyesinde soğutulmuş dokuda süre 12 saate kadar uzayabilir; kas içeren üst kol seviyesindeki kopmalarda ise bu süre 6 saatin altındadır.",
   ("h3","Kopan parçayı nasıl saklamalı?"),
   ("ul",["Parçayı temiz, hafif nemli bir gazlı bezle sarın",
          "Su geçirmez bir poşete koyup ağzını kapatın",
          "Poşeti buz ve su karışımı bulunan bir kaba yerleştirin",
          "<strong>Parçayı doğrudan buza veya suya temas ettirmeyin</strong> — doku donar ya da şişer",
          "Yarayı temiz bezle bastırarak kanamayı kontrol edin, turnike uygulamayın"]),
   ("note","Bu sayfa acil tıbbi yardımın yerine geçmez. Uzuv kopmasında derhal 112'yi arayın ve replantasyon yapabilen bir merkeze yönlendirilmeyi isteyin. Zaman, bu tabloda en belirleyici etkendir.")]},
  {"id":"kapsam","tag":"Kapsam","h2":"Uygulanan girişimler","body":[
   ("h3","Replantasyon"),
   "Kopan parmak veya uzvun yerine dikilmesi. Kemik sabitlenir, ardından mikroskop altında atardamar, toplardamar, sinir ve tendonlar onarılır. Başparmak ve birden fazla parmağın koptuğu olgular öncelikli değerlendirilir.",
   ("h3","Ayaktan ele parmak aktarımı"),
   "Parmağın kurtarılamadığı ya da doğuştan eksik olduğu durumlarda, ayak parmağı damar ve siniriyle birlikte ele aktarılır. Özellikle başparmak kaybında kavrama işlevini geri kazandırır. Doç. Dr. Acartürk'ün Vietnam'daki gönüllü misyonlarda sıklıkla uyguladığı girişimlerden biridir.",
   ("h3","Tendon ve sinir onarımı"),
   "Kesici yaralanmalarda tendonların ve sinirlerin mikroskop altında onarılması. Sinir kaybı geniş olduğunda araya sinir grefti yerleştirilir.",
   ("h3","İkincil rekonstrüksiyon"),
   "İlk tedavi sonrası kalan kısıtlılıklar için yapılan planlı girişimler: tendon transferleri, kontraktür açılması, yumuşak doku onarımı ve eklem düzeltmeleri."]},
  {"id":"rehab","tag":"Rehabilitasyon","h2":"Rehabilitasyonun belirleyici rolü","body":[
   "El cerrahisinde ameliyat, sonucun yalnızca bir parçasıdır. Onarılan tendonlar hareketsiz kaldığında yapışır, eklemler sertleşir ve sinir iyileşse bile işlev geri gelmez. Bu nedenle el terapisi ameliyattan sonraki günlerde başlar ve aylarca sürer.",
   ("ul",["Erken dönemde korumalı hareket egzersizleri",
          "Ödem kontrolü ve skar dokusu yönetimi",
          "Duyu eğitimi — sinir iyileşmesi sırasında beynin yeniden öğrenmesi",
          "Kavrama gücünün kademeli olarak artırılması"]),
   ("note","Replante edilen bir parmağın tutması, işlevin geri geldiği anlamına gelmez. Gerçek başarı ölçüsü, elin günlük yaşamda yeniden kullanılabilir hâle gelmesidir; bu da cerrahi kadar rehabilitasyonun sonucudur.")]}],
 "faqs":[
  ("Kopan parmak kaç saat içinde dikilebilir?","Soğuk zincirde doğru saklanan parmak seviyesindeki kopmalarda süre 12 saate kadar uzayabilir. Kas dokusu içeren el bileği üstü kopmalarda bu süre 6 saatin altındadır; kas iskemiye çok daha duyarlıdır."),
  ("Her kopan uzuv dikilebilir mi?","Hayır. Ezilme tarzı yaralanmalarda, birden fazla seviyede kopmada ve dokunun ağır kirlendiği durumlarda replantasyon uygun olmayabilir. Hastanın genel durumu ve eşlik eden yaralanmalar da kararı etkiler."),
  ("Dikilen parmak eskisi gibi çalışır mı?","Tam eski işleve dönüş nadirdir. Hedef, kavramaya katkı veren, duyusu kısmen geri gelmiş ve ağrısız bir parmaktır. Sonuç, kopma seviyesine ve rehabilitasyona bağlıdır."),
  ("Ayak parmağı alınırsa yürüyüşüm bozulur mu?","İkinci ayak parmağının alınması yürüme işlevini anlamlı ölçüde etkilemez. İlk haftalarda destekli yürüme gerekir, sonrasında normal aktiviteye dönülür."),
  ("Sinir onarımından sonra his ne zaman gelir?","Sinir günde yaklaşık 1 mm ilerler. Onarım yerinden parmak ucuna ulaşması aylar sürebilir; duyunun kalitesi yaşa ve yaralanmanın tipine göre değişir.")],
 "related":["bas-boyun","yanik","yuz-felci"],
 "ctah":"El cerrahisi değerlendirmesi",
 "ctap":"Geçirdiğiniz yaralanmayı, uygulanan tedavileri ve kalan kısıtlılıkları anlatın; varsa fotoğraf ve film raporlarınızı gönderin. İkincil onarım seçeneklerini birlikte değerlendirelim."},

{
 "key":"yanik",
 "authority":"Yanık ve travma onarımı, Doç. Dr. Acartürk'ün hem askerlik hem akademik döneminde çalıştığı alandır. Gülhane Askeri Tıp Akademisi'ndeki görevi sırasında yanık tedavisi ve savaş yaralanmaları konusunda deneyim kazanmış; Pittsburgh Üniversitesi'nde ışın görmüş dokuların yağ ve kök hücre destekli tedavisi üzerine araştırmalara katkı sağlamıştır.",
 "creds":["GATA'da yanık tedavisi ve savaş yaralanmaları deneyimi","Pittsburgh Üniversitesi'nde kök hücre ve doku mühendisliği araştırmaları","3 yıl travma ve damar cerrahisi eğitimi"], "slug":"yanik-travma-onarimi.html", "prio":"0.75",
 "crumb":"Yanık, Travma ve Işın Sonrası Onarım",
 "title":"Yanık, Travma ve Radyoterapi Sonrası Doku Onarımı | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Yanık, Travma ve Işın Tedavisi Sonrası Onarım",
 "desc":"Yanık sonrası skar ve kontraktür cerrahisi, travma sonrası doku kayıplarının onarımı, radyoterapi görmüş dokularda yağ ve kök hücre destekli tedaviler.",
 "eyebrow":"Rekonstrüktif Cerrahi",
 "h1":"Yanık, travma ve ışın tedavisi sonrası onarım",
 "lead":"Yanık, travma ve radyoterapi sonrası oluşan doku hasarı yalnızca iz bırakmaz; hareketi kısıtlar, ağrı yapar ve bazen yaraların kapanmasını engeller. Bu tablolarda amaç izi gizlemek değil, dokunun işlevini ve kalitesini geri kazandırmaktır.",
 "watopic":"yanık ve travma sonrası onarım",
 "about":"Skar ve kontraktür rekonstrüksiyonu", "aboutType":"MedicalProcedure",
 "card":"Yanık ve travma onarımı", "cardsub":"Skar, kontraktür ve ışın hasarında doku rekonstrüksiyonu",
 "procedure":{"name":"Skar Kontraktürü Rekonstrüksiyonu",
   "how":"Kısıtlayıcı skar dokusu açılır ve oluşan defekt deri grefti, lokal doku flepleri veya serbest doku aktarımıyla kapatılır.",
   "prep":"Skarın olgunlaşmasının beklenmesi, eklem hareket açıklığının ölçülmesi ve fizyoterapi hazırlığı.",
   "follow":"Bası giysisi, silikon uygulaması, atel kullanımı ve düzenli fizyoterapi.",
   "body":"Vücudun her bölgesi"},
 "keyfacts":[("Bekleme","Skarın olgunlaşması 6–12 ay"),("Öncelik","Eklem hareketi ve işlev"),
             ("Yöntem","Greft, lokal flep, serbest doku"),("Işın hasarı","Yağ ve kök hücre destekli tedavi")],
 "sections":[
  {"id":"skar","tag":"Yanık Sonrası","h2":"Skar ve kontraktür cerrahisi","body":[
   "Yanık iyileşirken oluşan skar dokusu zamanla kasılır. Bu kasılma bir eklemin üzerinden geçtiğinde hareketi kısıtlar; boyunda başın hareketini, koltuk altında kolun kalkmasını, elde parmakların açılmasını engelleyebilir. Buna <strong>kontraktür</strong> denir ve cerrahi gerektirir.",
   ("h3","Kullanılan yöntemler"),
   ("ul",["<strong>Z-plasti ve lokal flepler:</strong> Skar hattının yönü değiştirilerek gerginlik dağıtılır. Dar bantlar hâlindeki kontraktürlerde etkilidir.",
          "<strong>Deri grefti:</strong> Geniş alanlarda, sağlam bölgeden alınan ince deri tabakasıyla kapatma.",
          "<strong>Doku genişletici:</strong> Komşu sağlam deri kademeli olarak genişletilir ve skarın yerine taşınır. Saçlı deride ve yüzde renk uyumu açısından üstündür.",
          "<strong>Serbest doku aktarımı:</strong> Derin ve geniş kayıplarda, damarlarıyla birlikte aktarılan doku."]),
   ("note","Skar cerrahisinde zamanlama önemlidir. Olgunlaşmamış, kırmızı ve kabarık bir skara erken müdahale sonucu kötüleştirebilir. İşlevi tehdit eden kontraktürler dışında genellikle 6–12 ay beklenir; bu sürede bası giysisi, silikon ve fizyoterapi uygulanır.")]},
  {"id":"isin","tag":"Işın Hasarı","h2":"Radyoterapi görmüş dokuların onarımı","body":[
   "Radyoterapi kanser tedavisinde etkilidir, ancak ışın gören dokularda kalıcı değişiklikler bırakır: küçük damarlar daralır, doku sertleşir, kan akımı azalır. Bu dokularda yaralar geç kapanır, ameliyat sonrası komplikasyon riski artar ve sıradan onarım teknikleri yetersiz kalır.",
   ("h3","Yağ dokusu ve kök hücre destekli tedaviler"),
   "Hastanın kendi yağ dokusundan elde edilen hücreler, ışın görmüş bölgeye enjekte edildiğinde doku kalitesini iyileştirebilir: cilt yumuşar, esneklik artar ve yeni damar oluşumu desteklenir. Doç. Dr. Acartürk, Pittsburgh Üniversitesi'nde bu alandaki çalışmalara araştırmacı olarak katkı sağlamış ve tekniği özellikle kanser, yanık ve ışın sonrası olgularda kullanmaktadır.",
   ("ul",["Enjeksiyon genellikle birkaç seans hâlinde uygulanır",
          "Büyük onarımlar öncesi doku hazırlığı olarak kullanılabilir",
          "Ağrılı ve sert skarlarda konforu artırdığı bildirilmektedir"])]},
  {"id":"travma","tag":"Travma","h2":"Travma sonrası doku kayıpları","body":[
   "Trafik kazaları, iş kazaları ve ateşli silah yaralanmaları sonrası oluşan doku kayıpları, açıkta kalan kemik veya tendon nedeniyle basit yöntemlerle kapatılamaz. Bu olgularda onarım merdiveninin üst basamakları gerekir.",
   ("steps",[
    ("1. AŞAMA — YARA HAZIRLIĞI","Ölü dokunun temizlenmesi, enfeksiyon kontrolü ve gerektiğinde negatif basınçlı yara tedavisi."),
    ("2. AŞAMA — İSKELET ONARIMI","Kırıkların sabitlenmesi ve gerekiyorsa kemik defektinin doldurulması."),
    ("3. AŞAMA — ÖRTÜ","Lokal flep ya da serbest doku aktarımı ile canlı ve dolaşımı olan bir örtü sağlanması."),
    ("4. AŞAMA — İŞLEV","Tendon, sinir ve eklem sorunlarının planlı biçimde ele alınması."),
    ("5. AŞAMA — İNCE AYAR","Kontur düzeltmeleri, yağ enjeksiyonu ve skar revizyonu.")]),
   "Doç. Dr. Acartürk, ihtisası sırasında yoğun travma cerrahisi eğitimi almış, Gülhane Askeri Tıp Akademisi'ndeki görevi sırasında yanık tedavisi ve savaş yaralanmaları konusunda deneyim kazanmıştır."]}],
 "faqs":[
  ("Yanık izim için ne zaman ameliyat olabilirim?","İşlevi tehdit eden kontraktürler dışında genellikle skarın olgunlaşması beklenir; bu 6–12 ayı bulur. Bu süre içinde bası giysisi, silikon uygulaması ve fizyoterapi skarın kalitesini iyileştirir."),
  ("Yanık izi tamamen yok olur mu?","Hayır. Skar dokusu ortadan kaldırılamaz, ancak yeri, yönü ve kalitesi değiştirilebilir. Amaç izi görünmez kılmak değil, daha az belirgin ve işlevi kısıtlamayan bir hâle getirmektir."),
  ("Radyoterapi aldığım bölge ameliyat edilebilir mi?","Edilebilir, ancak iyileşme yavaştır ve komplikasyon riski yüksektir. Bu olgularda kendi dokusuyla onarım tercih edilir; öncesinde yağ enjeksiyonuyla doku kalitesinin iyileştirilmesi planlanabilir."),
  ("Yağ enjeksiyonu skar için gerçekten işe yarar mı?","Işın görmüş ve sertleşmiş dokularda yumuşama, esneklik artışı ve ağrıda azalma bildirilmektedir. Sonuç kişiye göre değişir ve genellikle birden fazla seans gerekir."),
  ("Çocuklarda yanık kontraktürü nasıl ele alınır?","Çocuk büyüdükçe skar dokusu aynı oranda büyümez ve kontraktür tekrarlayabilir. Bu nedenle büyüme dönemi boyunca aralıklı düzeltmeler gerekebilir; planlama buna göre yapılır.")],
 "related":["el-cerrahisi","bas-boyun","yag-enjeksiyonu"],
 "ctah":"Onarım değerlendirmesi",
 "ctap":"Yaralanmanın ya da tedavinin ne zaman olduğunu, uygulanan girişimleri ve mevcut kısıtlılıkları anlatın; varsa fotoğraflarınızı gönderin."},
]
