# -*- coding: utf-8 -*-
"""
Lenfodem uydu sayfalari — hub: lenfodem-lipodem-cerrahisi.html
Hedef sorgular ve aylik hacimler (Semrush TR):
  bacakta lenfodem belirtileri 2400 / bacaklarda lenfodem tedavisi 1300
  kolda lenfodem belirtileri 720 / kolda lenfodem tedavisi 210
  lenfodem belirtileri 1600
  lenfodem neden olur 1000
  lenfodeme hangi bolum bakar 390 (KD 6)
  lenfodem evreleri 320 (KD 6)
"""

LENFODEM_KUME = [

{"key":"bacakta-lenfodem",
 "slug":"bacakta-lenfodem.html",
 "prio":0.9,
 "crumb":"Bacakta Lenfödem",
 "title":"Bacakta Lenfödem: Belirtileri ve Tedavisi | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Bacakta Lenfödem: Belirtileri ve Tedavisi",
 "desc":"Bacakta lenfödem belirtileri nelerdir, neden olur, hangi hastalıklarla karıştırılır ve nasıl tedavi edilir? Evrelere göre cerrahi seçenekler ve mikrocerrahi tedavi.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Bacakta lenfödem: belirtileri ve tedavisi",
 "lead":"Bacaktaki şişlik akşamları artıp sabahları geçiyorsa, ayakkabı dar geliyorsa ve bir bacak diğerinden kalınsa — bu bir kilo meselesi olmayabilir. Bacak lenfödemi sinsi başlar, ama erken evrede mikrocerrahi ile tedavi edilebilir.",
 "watopic":"bacakta lenfödem tedavisi",
 "about":"Bacak Lenfödemi",
 "aboutType":"MedicalCondition",
 "card":"Bacakta lenfödem","cardsub":"Alt ekstremite lenfödeminde tanı ve cerrahi tedavi",
 "procedure":{"name":"Alt Ekstremite Lenfödem Cerrahisi",
   "how":"Bacaktaki tıkalı lenf kanalları mikroskop altında komşu venlere bağlanır (LVA); ileri evrede vaskülarize lenf nodu transferi ve azaltıcı cerrahi planlanır.",
   "prep":"Muayene, çevre ölçümleri, ICG lenfografi veya lenfosintigrafi ile lenfatik haritalama.",
   "follow":"Bası çorabı, erken mobilizasyon ve gerektiğinde lenfödem fizyoterapisi.",
   "body":"Bacak ve ayak lenfatik sistemi"},
 "keyfacts":[("Ayırt edici","Şişlik ayak sırtına ve parmaklara uzanır"),
             ("Stemmer","Ayak parmağında deri kaldırılamıyorsa pozitif"),
             ("Erken evre","LVA — en az invaziv seçenek"),
             ("Kritik","Tek taraflı şişlik her zaman araştırılmalı")],
 "authority":"Bacak lenfödemi, kol lenfödeminden daha zor bir alandır: yerçekimi lenfatik yükü artırır, mesafeler uzundur ve enfeksiyon riski yüksektir. Doç. Dr. Acartürk, Pittsburgh Üniversitesi'nde 300+ mikrocerrahi vaka deneyimiyle 0,3–0,8 mm çapındaki lenf kanallarında çalışır ve Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılmaktadır.",
 "creds":["Pittsburgh Üniversitesi Baş–Boyun Onarımları eski Direktörü — 300+ mikrocerrahi vaka",
          "Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım",
          "Dünya Lenfoloji Kongresi'nde bildiri sunumu"],
 "sections":[
  {"id":"belirti","tag":"Belirtiler","h2":"Bacakta lenfödem belirtileri","body":[
   "Bacak lenfödemi çoğu zaman fark edilmeden başlar. İlk dönemde şişlik gün içinde artar, sabahları büyük ölçüde geçer. Bu dalgalanma nedeniyle hastalar durumu yorgunluğa veya tuzlu yemeğe bağlar ve aylarca hekime başvurmaz.",
   ("h3","Erken dönem bulguları"),
   ("ul",["Akşama doğru artan, sabah azalan şişlik",
          "Çorap lastiğinin bacakta derin iz bırakması",
          "Ayakkabının akşamları dar gelmesi",
          "Bacakta dolgunluk ve ağırlık hissi",
          "İki bacak arasında belirginleşen çevre farkı"]),
   ("h3","İlerlemiş dönem bulguları"),
   ("ul",["Bacak yükseltildiğinde geçmeyen şişlik",
          "Deride kalınlaşma ve sertleşme",
          "Tekrarlayan selülit (erizipel) atakları — ateş, kızarıklık, ağrı",
          "Ayak parmaklarında kare görünüm",
          "Deriden sızıntı (lenfore) ve siğilimsi değişiklikler"]),
   ("note","<strong>Stemmer belirtisi:</strong> İkinci ayak parmağının üzerindeki deriyi parmaklarınızla tutup kaldırmayı deneyin. Kalın ve kaldırılamıyorsa bu bulgu pozitiftir ve lenfödem lehinedir. Basit ama değerli bir muayene bulgusudur — yine de tek başına tanı koydurmaz.")]},
  {"id":"neden","tag":"Nedenler","h2":"Bacakta lenfödem neden olur?","body":[
   "Alt ekstremite lenfödeminin nedenleri kol lenfödeminden farklıdır. Kolda tablo çoğunlukla meme kanseri tedavisine bağlıyken, bacakta neden çeşitliliği fazladır.",
   ("ul",["<strong>Jinekolojik ve ürolojik kanser tedavileri:</strong> rahim, yumurtalık, prostat kanserinde kasık ve pelvik lenf nodu diseksiyonu",
          "<strong>Radyoterapi:</strong> pelvis bölgesine uygulanan ışınlama lenfatik kanalları skarlaştırır",
          "<strong>Tekrarlayan selülit:</strong> her atak lenfatik yapıyı biraz daha bozar — kısır döngü oluşturur",
          "<strong>Melanom cerrahisi:</strong> kasık lenf nodu diseksiyonu sonrası",
          "<strong>Primer lenfödem:</strong> doğuştan lenfatik gelişim yetersizliği; ergenlikte veya erişkinlikte ortaya çıkabilir",
          "<strong>Travma ve büyük ortopedik cerrahiler</strong>"]),
   ("note","Bacak lenfödeminde ilk yapılması gereken, altta yatan bir tıkanıklığın dışlanmasıdır. Tek taraflı, hızlı başlayan ve ağrılı şişlikte derin ven trombozu ve pelvik kitle mutlaka araştırılmalıdır. Bu değerlendirme yapılmadan lenfödem tanısı konmamalıdır.")]},
  {"id":"ayirici","tag":"Ayırıcı Tanı","h2":"Bacak şişliği her zaman lenfödem midir?","body":[
   "Hayır. Bacakta şişlik yapan birkaç farklı durum vardır ve tedavileri tamamen farklıdır. En sık karışan tablolar:",
   ("table",["Durum","Ayırt eden özellik"],[
     ["Lenfödem","Şişlik ayak sırtına ve parmaklara uzanır; Stemmer pozitif; genellikle tek taraflı"],
     ["Lipödem","Şişlik bilekte biter — manşon belirtisi; ayaklar korunur; simetrik; dokunmakla ağrılı"],
     ["Venöz yetmezlik","Akşam artar, bacak kaldırılınca hızla geçer; varis ve deri renk değişikliği eşlik eder"],
     ["Kalp/böbrek/karaciğer kaynaklı ödem","Her iki bacakta simetrik; gode bırakır; altta sistemik hastalık vardır"],
     ["Derin ven trombozu","Ani başlangıç, ağrı, ısı artışı — acil değerlendirme gerektirir"]]),
   "Lenfödem ve lipödem birlikte de bulunabilir; buna <strong>lipo-lenfödem</strong> denir. Ayrıntılı karşılaştırma için <a href=\"lipodem-cerrahisi.html\">lipödem cerrahisi sayfamıza</a> bakabilirsiniz."]},
  {"id":"tedavi","tag":"Tedavi","h2":"Bacakta lenfödem tedavisi","body":[
   "Tedavi evreye göre planlanır. Temel ilke şudur: <strong>lenf kanalları hâlâ çalışıyorken müdahale etmek</strong>, doku sertleştikten sonra müdahale etmekten çok daha etkilidir.",
   ("h3","Konservatif tedavi"),
   "Kompleks boşaltıcı fizyoterapi — manuel lenf drenajı, bandajlama, bası çorabı ve egzersiz — tedavinin temelidir ve cerrahi sonrasında da devam eder. Ancak tıkanıklığın kendisini ortadan kaldırmaz.",
   ("h3","LVA — lenfatikovenöz anastomoz"),
   "Bacaktaki çalışan lenf kanalları mikroskop altında komşu venlere bağlanır. Kesiler küçüktür, iyileşme hızlıdır. Erken evrede — kanallar hâlâ kasılıyorken — en etkili seçenektir.",
   ("h3","Vaskülarize lenf nodu transferi"),
   "Kendi lenf nodlarınızdan bir grup, besleyici damarlarıyla birlikte bacağa taşınır. İleri evrede ve kasık bölgesi ışınlanmış hastalarda tercih edilir.",
   ("h3","Azaltıcı cerrahi"),
   "Hacim yağ dokusu ve fibrozla artmışsa, liposuction ve eksizyon ile bacak hacmi küçültülür. Lenf akımını geri getirmez ama yükü belirgin azaltır; genellikle diğer yöntemlerle birlikte planlanır.",
   ("note","Bacak lenfödeminde tekrarlayan selülit ataklarını azaltmak, hacim küçültmek kadar önemli bir hedeftir. Her atak lenfatik yapıyı daha da bozar; atakların seyrelmesi hastalığın ilerleyişini yavaşlatır.")]},
  {"id":"gunluk","tag":"Günlük Yaşam","h2":"Bacak lenfödeminde günlük yaşam","body":[
   ("ul",["<strong>Cilt bakımı en önemli koruyucu önlemdir.</strong> Kuru deri çatlar, çatlaktan giren bakteri selülit yapar. Günlük nemlendirme ihmal edilmemeli.",
          "<strong>Ayak bakımına dikkat:</strong> mantar enfeksiyonları parmak aralarından başlar ve selülitin en sık giriş kapısıdır",
          "<strong>Yaralanmalardan korunun:</strong> çıplak ayakla yürümekten, sıkı tırnak kesiminden kaçının",
          "<strong>Hareket faydalıdır:</strong> yürüyüş ve baldır kası çalışması lenf akımını destekler",
          "<strong>Uzun uçuşlarda</strong> bası çorabı ve sık hareket önerilir",
          "<strong>Kilo kontrolü</strong> lenfatik yükü doğrudan azaltır"]),
   ("note","Ateş, bacakta yaygın kızarıklık ve ısı artışı selülit habercisidir. Bu tablo gecikmeden antibiyotik tedavisi gerektirir; ertelenmesi hem atağı ağırlaştırır hem de lenfatik hasarı artırır.")]}],
 "faqs":[
  ("Bacaktaki şişlik lenfödem mi, ödem mi?","Basmakla derin çukur kalan, bacak kaldırılınca hızla geçen ve her iki bacakta simetrik olan şişlik daha çok sistemik ödemi düşündürür. Lenfödemde şişlik ayak sırtına ve parmaklara uzanır, Stemmer belirtisi pozitiftir ve genellikle tek taraflıdır. Kesin ayrım muayene ve görüntüleme ile yapılır."),
  ("Bacakta lenfödem geçer mi?","Tam şifa vaadi doğru olmaz. Ancak erken evrede mikrocerrahi ile hacim belirgin azaltılabilir, selülit atakları seyrekleşir ve bası çorabına bağımlılık azalır. Evre ilerledikçe hedef, hastalığı kontrol altına almak ve fonksiyonu korumak olur."),
  ("Ameliyat olmadan tedavi mümkün mü?","Kompleks boşaltıcı fizyoterapi ve bası çorabı tedavinin temelidir ve birçok hastada hacmi kontrol altında tutar. Ancak tıkanıklığın kendisini çözmez. Uygun evredeki hastalarda cerrahi, nedene müdahale etme imkânı sunar."),
  ("Bacak lenfödeminde hangi ameliyat yapılır?","Erken evrede LVA öne çıkar. İleri evrede vaskülarize lenf nodu transferi ve azaltıcı cerrahi tek başına veya birlikte planlanır. Karar; evre, görüntüleme bulguları ve şişliğin süresine göre verilir."),
  ("Ameliyattan sonra bası çorabı kullanacak mıyım?","İlk dönemde evet. Zamanla birçok hastada ihtiyaç azalır, ancak tamamen bırakmak her zaman mümkün olmayabilir. Bu, evreye ve ameliyatın sonucuna bağlıdır."),
  ("Selülit atakları neden önemli?","Her atak lenfatik kanallarda kalıcı hasar bırakır ve hastalığın evresini ilerletir. Atakları önlemek — cilt bakımı, mantar tedavisi, yaralanmalardan korunma — tedavinin ayrılmaz bir parçasıdır.")],
 "related":["lenfodem","lenfodem-belirtileri","kolda-lenfodem","lipodem"],
 "ctah":"Bacak lenfödemi değerlendirmesi",
 "ctap":"Şişliğin ne kadar süredir olduğunu, tek mi çift taraflı olduğunu, geçirdiğiniz ameliyat veya radyoterapiyi ve selülit öykünüzü yazın; mümkünse iki bacağı birlikte gösteren fotoğraf ekleyin."},

{"key":"kolda-lenfodem",
 "slug":"kolda-lenfodem.html",
 "prio":0.9,
 "crumb":"Kolda Lenfödem",
 "title":"Kolda Lenfödem: Meme Kanseri Sonrası Belirti ve Tedavi | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Kolda Lenfödem: Belirtileri ve Tedavisi",
 "desc":"Meme kanseri tedavisi sonrası kolda lenfödem: belirtileri, risk faktörleri, önleme ve mikrocerrahi tedavi seçenekleri (LVA, lenf nodu transferi).",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Kolda lenfödem ve meme kanseri sonrası tedavi",
 "lead":"Meme kanseri tedavisi bittikten sonra kolda başlayan şişlik, birçok hasta için tedavinin en uzun süren yan etkisidir. Ama artık kaçınılmaz bir sonuç değil: erken evrede mikrocerrahi ile müdahale edilebilir, hatta ameliyat sırasında önlenebilir.",
 "watopic":"kolda lenfödem tedavisi",
 "about":"Kol Lenfödemi",
 "aboutType":"MedicalCondition",
 "card":"Kolda lenfödem","cardsub":"Meme kanseri sonrası kol lenfödeminde cerrahi tedavi",
 "procedure":{"name":"Üst Ekstremite Lenfödem Cerrahisi",
   "how":"Koldaki tıkalı lenf kanalları mikroskop altında komşu venlere bağlanır; koltuk altı skarı serbestleştirilir ve gerektiğinde vaskülarize lenf nodu transferi uygulanır.",
   "prep":"Çevre ölçümleri, ICG lenfografi, koltuk altı bölgesinin ve radyoterapi öyküsünün değerlendirilmesi.",
   "follow":"Bası kolluğu, omuz hareket açıklığı egzersizleri ve lenfödem fizyoterapisi.",
   "body":"Kol lenfatik sistemi"},
 "keyfacts":[("Risk","Aksiller diseksiyon + radyoterapi en yüksek risk"),
             ("Zamanlama","Genellikle ilk 2 yılda başlar"),
             ("Erken evre","LVA ile hacim kontrolü mümkün"),
             ("Önleme","LYMPHA — ameliyat sırasında koruyucu yaklaşım")],
 "authority":"Kol lenfödemi cerrahisi, meme cerrahisi ve mikrocerrahiyi birlikte bilmeyi gerektirir. Doç. Dr. Acartürk hem meme rekonstrüksiyonu hem de lenfatik mikrocerrahi yapan bir cerrahtır; 300+ mikrocerrahi vakası ve %97 flep başarı oranı ile bu iki alanı aynı planda birleştirir.",
 "creds":["300+ mikrocerrahi operasyon · %97 flep başarı oranı",
          "Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım",
          "Meme rekonstrüksiyonu ve lenfatik cerrahide birleşik yaklaşım"],
 "sections":[
  {"id":"belirti","tag":"Belirtiler","h2":"Kolda lenfödem belirtileri","body":[
   "Kol lenfödemi çoğu zaman ölçülebilir bir şişlik ortaya çıkmadan önce hissedilir. Hastaların büyük kısmı ilk olarak bir <strong>ağırlık ve gerginlik hissinden</strong> söz eder.",
   ("h3","Erken uyarı bulguları"),
   ("ul",["Kolda dolgunluk, ağırlık veya gerginlik hissi",
          "Saat, yüzük veya bilekliğin sıkması",
          "Gömlek kolunun tek tarafta dar gelmesi",
          "Ciltte gerginlik, parlaklık",
          "Kol hareketlerinde azalma hissi"]),
   ("h3","Yerleşmiş dönem bulguları"),
   ("ul",["Kol çevresinde ölçülebilir fark (genellikle 2 cm ve üzeri)",
          "Kol kaldırıldığında geçmeyen şişlik",
          "Deride kalınlaşma ve sertleşme",
          "Tekrarlayan selülit atakları",
          "El sırtı ve parmaklarda şişlik"]),
   ("note","Ameliyat sonrası ilk haftalarda görülen şişlik genellikle cerrahiye bağlı geçici ödemdir ve lenfödem değildir. Ancak şişlik 3 aydan uzun sürüyorsa veya sonradan başlıyorsa mutlaka değerlendirilmelidir.")]},
  {"id":"risk","tag":"Risk","h2":"Kimlerde risk yüksek?","body":[
   "Meme kanseri tedavisi gören her hastada lenfödem gelişmez. Risk, uygulanan tedavinin kapsamına göre değişir.",
   ("table",["Faktör","Risk üzerindeki etkisi"],[
     ["Sentinel lenf nodu biyopsisi","Düşük risk — sınırlı sayıda nod çıkarılır"],
     ["Aksiller lenf nodu diseksiyonu","Belirgin risk artışı — koltuk altı lenfatik yapısı geniş ölçüde etkilenir"],
     ["Koltuk altına radyoterapi","Riski ayrıca artırır; diseksiyonla birleştiğinde en yüksek risk"],
     ["Tekrarlayan enfeksiyon","Her atak lenfatik rezervi azaltır"],
     ["Yüksek vücut kitle indeksi","Lenfatik yükü artırır"],
     ["Kolda travma veya cerrahi","Mevcut rezervi zorlar"]]),
   ("note","Lenfödem çoğunlukla tedavi bitiminden sonraki ilk 2 yıl içinde başlar, ancak yıllar sonra da ortaya çıkabilir. Bu nedenle risk grubundaki hastalarda kol çevresi ölçümlerinin düzenli takibi önerilir.")]},
  {"id":"onleme","tag":"Önleme","h2":"Önlenebilir mi?","body":[
   "Son yıllarda lenfödem cerrahisindeki en önemli gelişme, tedavi değil <strong>önleme</strong> alanında oldu.",
   ("h3","LYMPHA — koruyucu lenfatikovenöz anastomoz"),
   "Aksiller diseksiyon sırasında, kesilen lenf kanalları aynı seansta komşu bir vene bağlanır. Böylece lenf akımı için baştan bir çıkış yolu oluşturulur. Bu yaklaşım, yüksek riskli hastalarda lenfödem gelişme oranını azaltmak amacıyla uygulanmaktadır.",
   ("h3","Erken tespit"),
   "Ameliyat öncesi kol çevresi ölçümü alınması ve sonrasında düzenli takip, lenfödemi henüz gözle görülmeden yakalamayı sağlar. Evre 0'da yakalanan hasta, en geniş tedavi seçeneklerine sahip olan hastadır.",
   ("ul",["Ameliyat öncesi başlangıç ölçümü alınmalı",
          "İlk 2 yıl daha sık, sonrasında yıllık takip",
          "Ağırlık ve gerginlik hissi ciddiye alınmalı — ölçüm beklenmemeli",
          "Cilt bakımı ve enfeksiyondan korunma ilk günden itibaren"])]},
  {"id":"tedavi","tag":"Tedavi","h2":"Kolda lenfödem tedavisi","body":[
   ("h3","Konservatif tedavi"),
   "Manuel lenf drenajı, bandajlama, bası kolluğu ve egzersiz tedavinin temelini oluşturur ve cerrahi sonrasında da sürer.",
   ("h3","LVA"),
   "Koldaki çalışan lenf kanalları mikroskop altında venlere bağlanır. Küçük kesilerle yapılır, hastanede kalış kısadır. Erken evrede en etkili seçenektir.",
   ("h3","Vaskülarize lenf nodu transferi"),
   "Sağlıklı bir bölgeden alınan lenf nodları besleyici damarlarıyla koltuk altına taşınır. Işınlanmış ve skarlaşmış koltuk altı dokusuna canlı doku getirmesi ayrıca değerlidir.",
   ("h3","Skar serbestleştirme"),
   "Koltuk altındaki yoğun skar dokusu hem lenf akımını hem de omuz hareketini kısıtlar. Serbestleştirme, transfer ile birlikte planlandığında sonucu belirgin iyileştirir.",
   ("h3","Azaltıcı cerrahi"),
   "Yağ dokusu ve fibrozla hacimlenmiş kolda liposuction hacmi azaltır. İleri evrede diğer yöntemlerle birlikte kullanılır.",
   ("note","Meme rekonstrüksiyonu planlanan hastalarda lenfödem cerrahisi aynı seansta yapılabilir. Bu, hastayı ikinci bir ameliyattan kurtarır. Ayrıntılar için <a href=\"meme-rekonstruksiyonu.html\">meme rekonstrüksiyonu sayfamıza</a> bakabilirsiniz.")]}],
 "faqs":[
  ("Meme kanseri ameliyatından sonra herkeste lenfödem olur mu?","Hayır. Risk uygulanan tedaviye göre değişir. Sentinel lenf nodu biyopsisinde risk düşükken, aksiller diseksiyon ve koltuk altı radyoterapisi birlikte uygulandığında risk belirgin artar."),
  ("Lenfödem ne zaman başlar?","Çoğunlukla tedavi bitiminden sonraki ilk 2 yıl içinde. Ancak yıllar sonra da ortaya çıkabilir; bu nedenle takip uzun süreli olmalıdır."),
  ("Kolumdaki şişlik lenfödem mi?","Kol çevresinde diğer kola göre ölçülebilir fark, ağırlık hissi, yüzük veya saatin sıkması lenfödemi düşündürür. Ameliyat sonrası ilk haftalardaki şişlik ise genellikle geçici cerrahi ödemdir. Ayrım muayene ve ölçümle yapılır."),
  ("Ameliyatla düzelir mi?","Erken evrede LVA ile hacim belirgin azalabilir ve bası kolluğuna bağımlılık gerileyebilir. İleri evrede lenf nodu transferi ve azaltıcı cerrahi ile kontrol sağlanır. Tam şifa vaadi doğru olmaz; hedef hacmi azaltmak, enfeksiyonları seyreltmek ve fonksiyonu geri kazandırmaktır."),
  ("Lenfödem önlenebilir mi?","Yüksek riskli hastalarda, aksiller diseksiyon sırasında uygulanan koruyucu LVA (LYMPHA) yaklaşımı lenfödem gelişme oranını azaltmak amacıyla kullanılmaktadır. Ayrıca erken tespit için ameliyat öncesi ölçüm alınması önerilir."),
  ("Kolumu kullanmaktan kaçınmalı mıyım?","Hayır. Eskiden önerilen katı kısıtlamalar artık geçerli değil. Kademeli olarak artırılan egzersiz ve normal kullanım faydalıdır. Kaçınılması gereken şey ani aşırı zorlanma ve yaralanmadır."),
  ("Tansiyon ölçümü ve kan aldırma o koldan yapılabilir mi?","Geleneksel öneri ameliyat tarafındaki koldan kaçınmak yönündedir. Kanıt düzeyi tartışmalı olmakla birlikte, seçenek varsa diğer kolun kullanılması makul bir önlemdir.")],
 "related":["lenfodem","meme-rek","lenfodem-belirtileri","bacakta-lenfodem"],
 "ctah":"Kol lenfödemi değerlendirmesi",
 "ctap":"Meme kanseri tedavinizin kapsamını (ameliyat türü, lenf nodu diseksiyonu, radyoterapi), şişliğin ne zaman başladığını ve kol çevresi ölçümlerinizi yazın; mümkünse iki kolu birlikte gösteren fotoğraf ekleyin."},

{"key":"lenfodem-belirtileri",
 "slug":"lenfodem-belirtileri.html",
 "prio":0.9,
 "crumb":"Lenfödem Belirtileri",
 "title":"Lenfödem Belirtileri: İlk Bulgular ve Kendi Kendine Kontrol | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lenfödem Belirtileri ve Erken Bulgular",
 "desc":"Lenfödem belirtileri nelerdir? Erken dönem bulguları, Stemmer belirtisi, kendi kendine kontrol yöntemleri ve hangi durumda hekime başvurmalı.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Lenfödem belirtileri ve erken bulgular",
 "lead":"Lenfödemde en değerli şey zamandır. Lenf kanalları hâlâ çalışıyorken yakalanan hastada tedavi seçenekleri geniştir; doku sertleştikten sonra seçenekler daralır. Bu sayfa, neyi ne zaman ciddiye almanız gerektiğini anlatıyor.",
 "watopic":"lenfödem belirtileri",
 "about":"Lenfödem",
 "aboutType":"MedicalCondition",
 "card":"Lenfödem belirtileri","cardsub":"Erken bulgular ve kendi kendine kontrol",
 "procedure":{"name":"Lenfödem Tanısal Değerlendirme",
   "how":"Çevre ölçümleri, Stemmer belirtisi, deri kalitesi ve enfeksiyon öyküsü birlikte değerlendirilir; gerektiğinde ICG lenfografi veya lenfosintigrafi ile lenfatik haritalama yapılır.",
   "prep":"Şişliğin süresi, geçirilmiş ameliyat ve radyoterapi öyküsü.",
   "follow":"Evreye göre tedavi planı ve düzenli ölçüm takibi.",
   "body":"Lenfatik sistem"},
 "keyfacts":[("İlk bulgu","Genellikle ağırlık ve gerginlik hissi"),
             ("Stemmer","Deri kaldırılamıyorsa pozitif"),
             ("Uyarı","Şişlik 3 aydan uzun sürüyorsa değerlendirilmeli"),
             ("Kritik","Evre 0'da tedavi seçenekleri en geniştir")],
 "authority":"Lenfödemin erken tanısı, tedavi başarısını doğrudan belirler. Doç. Dr. Acartürk, Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılan ve Dünya Lenfoloji Kongresi'nde bildiri sunmuş bir mikrocerrahtır; 300+ mikrocerrahi vaka deneyimiyle evrelemeyi tedavi planına dönüştürür.",
 "creds":["Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım",
          "Dünya Lenfoloji Kongresi'nde bildiri sunumu",
          "Pittsburgh Üniversitesi'nde 300+ mikrocerrahi vaka"],
 "sections":[
  {"id":"erken","tag":"Erken Bulgular","h2":"En erken belirtiler: ölçülmeden önce hissedilir","body":[
   "Lenfödemin ilk belirtisi genellikle gözle görülen bir şişlik değildir. Hastaların çoğu, henüz ölçülebilir bir fark oluşmadan önce bir <strong>his değişikliği</strong> tarif eder.",
   ("ul",["Kol veya bacakta ağırlık, dolgunluk, gerginlik hissi",
          "Yüzük, saat, bileklik veya çorabın sıkmaya başlaması",
          "Giysinin tek tarafta dar gelmesi",
          "Ciltte gerginlik veya parlaklık",
          "Eklem hareketinde hafif kısıtlanma hissi"]),
   ("note","Bu belirtiler hasta tarafından sıklıkla \"kilo aldım\" veya \"yorgunum\" diye açıklanır ve aylarca ertelenir. Oysa bu dönem, tedavi açısından en değerli dönemdir. Ölçüm henüz normal olsa bile bu şikâyetler değerlendirilmelidir.")]},
  {"id":"yerlesmis","tag":"Yerleşmiş Dönem","h2":"Yerleşmiş lenfödem bulguları","body":[
   ("ul",["<strong>Kalıcı şişlik:</strong> uzuv yükseltildiğinde geçmeyen ödem",
          "<strong>Ölçülebilir fark:</strong> karşı uzuvla arada çevre farkı",
          "<strong>Gode bırakma:</strong> erken dönemde basmakla çukur kalır; ileri evrede doku sertleştiği için kalmaz",
          "<strong>Deri değişiklikleri:</strong> kalınlaşma, sertleşme, portakal kabuğu görünümü",
          "<strong>Tekrarlayan selülit:</strong> ateş, kızarıklık, ağrı ile seyreden ataklar",
          "<strong>Lenfore:</strong> deriden berrak sıvı sızması",
          "<strong>Fonksiyon kaybı:</strong> hareket kısıtlılığı, günlük işlerde zorlanma"]),
   ("note","<strong>Gode bırakmama</strong>, ödemin geçtiği anlamına gelmez — tersine, dokunun fibrozla sertleştiğini gösterir ve daha ileri bir evreye işaret eder. Bu ayrım tedavi planını doğrudan değiştirir.")]},
  {"id":"kontrol","tag":"Kendi Kontrolünüz","h2":"Kendi kendine kontrol: ne bakmalısınız?","body":[
   ("steps",[
    ("1 — STEMMER BELİRTİSİ","İkinci ayak parmağınızın (veya elde ikinci parmağınızın) üzerindeki deriyi başparmak ve işaret parmağınızla tutup kaldırmayı deneyin. Deri kalın ve kaldırılamıyorsa bulgu pozitiftir."),
    ("2 — ÇEVRE ÖLÇÜMÜ","Her iki uzuvda aynı noktalardan mezura ile ölçün. Sabit referans noktaları seçin (örneğin dirsekten 10 cm yukarı). İki taraf arasındaki fark takip edilmelidir."),
    ("3 — GODE TESTİ","Şişlik olan bölgeye 10 saniye parmakla bastırın. Kalan çukur ödemi gösterir; çukurun kalmaması ileri evrede doku sertleşmesine işaret edebilir."),
    ("4 — SİMETRİ VE AYAK/EL","Şişlik tek taraflı mı? Ayak sırtına ve parmaklara uzanıyor mu? Bu bulgular lenfödem lehinedir."),
    ("5 — FOTOĞRAF KAYDI","İki uzvu birlikte, aynı açı ve ışıkta aylık fotoğraflayın. Yavaş değişimi fark etmenin en pratik yolu budur.")]),
   ("note","Bu kontroller hekim muayenesinin yerini tutmaz; amaçları değişimi fark etmenizi ve doğru zamanda başvurmanızı sağlamaktır.")]},
  {"id":"nezaman","tag":"Ne Zaman Başvurmalı","h2":"Hangi durumda hekime başvurmalısınız?","body":[
   ("ul",["Şişlik <strong>3 aydan uzun</strong> sürüyorsa",
          "Kanser tedavisi (özellikle lenf nodu diseksiyonu veya radyoterapi) sonrası yeni başlayan şişlikte",
          "İki uzuv arasında büyüyen bir çevre farkı fark ediyorsanız",
          "Stemmer belirtisi pozitifse",
          "Selülit atağı geçirdiyseniz"]),
   ("note","<strong>Acil değerlendirme gerektiren durumlar:</strong> Ani başlayan, ağrılı, tek taraflı şişlik derin ven trombozunu düşündürebilir. Ateş, yaygın kızarıklık ve ısı artışı ise selülit habercisidir ve gecikmeden antibiyotik gerektirir. Bu iki tabloda beklemeyin.")]},
  {"id":"karisan","tag":"Karışan Durumlar","h2":"Lenfödemle karışan durumlar","body":[
   ("table",["Durum","Ayırt eden özellik"],[
     ["Lipödem","Simetrik; bilekte biter (manşon belirtisi); dokunmakla ağrılı; Stemmer negatif"],
     ["Venöz yetmezlik","Bacak kaldırılınca hızla geçer; varis ve deri renk değişikliği eşlik eder"],
     ["Kalp/böbrek/karaciğer ödemi","Her iki tarafta simetrik; gode belirgin; sistemik hastalık vardır"],
     ["Derin ven trombozu","Ani başlangıç, ağrı, ısı artışı — acil"],
     ["Obezite","Yaygın; Stemmer negatif; uzuv dağılımı orantılı"]]),
   "Lenfödem ile lipödem ayrımı özellikle önemlidir çünkü tedavileri farklıdır ve ikisi birlikte de bulunabilir. Ayrıntı için <a href=\"lipodem-belirtileri.html\">lipödem belirtileri sayfamıza</a> bakabilirsiniz."]}],
 "faqs":[
  ("Lenfödemin ilk belirtisi nedir?","Genellikle gözle görülen şişlik değil, bir his değişikliğidir: uzuvda ağırlık, dolgunluk veya gerginlik. Yüzük, saat veya çorabın sıkmaya başlaması da erken bir uyarıdır."),
  ("Stemmer belirtisi nedir, nasıl bakılır?","İkinci ayak veya el parmağının üzerindeki deriyi tutup kaldırmayı denersiniz. Deri kalın ve kaldırılamıyorsa bulgu pozitiftir ve lenfödem lehinedir. Basit ama değerli bir bulgudur; tek başına tanı koydurmaz."),
  ("Şişlik gode bırakmıyorsa lenfödem değil midir?","Tersine. Erken evrede gode kalır; ileri evrede doku fibrozla sertleştiği için gode kalmaz. Gode bırakmaması daha ileri bir evreye işaret edebilir."),
  ("Lenfödem ağrı yapar mı?","Lenfödemde ön planda ağırlık ve gerginlik hissi vardır; belirgin ağrı tipik değildir. Dokunmakla ağrı daha çok lipödemi düşündürür. Ani ve şiddetli ağrı ise enfeksiyon veya damar tıkanıklığı açısından acil değerlendirme gerektirir."),
  ("Kaç santimlik fark anlamlıdır?","İki uzuv arasında yaklaşık 2 cm veya üzerindeki çevre farkı klinik olarak anlamlı kabul edilir. Ancak daha küçük farklar da takip gerektirir — özellikle risk grubundaki hastalarda değişimin yönü, mutlak değerden daha önemlidir."),
  ("Şişlik akşam artıp sabah geçiyorsa lenfödem mi?","Bu dalgalanma erken evre lenfödemde tipiktir, ancak venöz yetmezlikte de görülür. Ayrım için ayak sırtı ve parmak tutulumu, Stemmer belirtisi ve simetri değerlendirilir.")],
 "related":["lenfodem","lenfodem-evreleri","lenfodem-neden-olur","bacakta-lenfodem"],
 "ctah":"Belirtilerinizi değerlendirelim",
 "ctap":"Şişliğin ne kadar süredir olduğunu, hangi uzuvda ve tek mi çift taraflı olduğunu, geçirdiğiniz ameliyat veya radyoterapiyi yazın; mümkünse iki uzvu birlikte gösteren fotoğraf ekleyin."},

{"key":"lenfodem-neden-olur",
 "slug":"lenfodem-neden-olur.html",
 "prio":0.85,
 "crumb":"Lenfödem Neden Olur",
 "title":"Lenfödem Neden Olur? Nedenleri ve Risk Faktörleri | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lenfödem Neden Olur? Nedenleri ve Risk Faktörleri",
 "desc":"Lenfödem neden olur? Primer ve sekonder lenfödem nedenleri, kanser tedavisi sonrası risk, enfeksiyon ve genetik faktörler — ve riski azaltmanın yolları.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Lenfödem neden olur?",
 "lead":"Lenfödem, lenf sıvısının dokuda birikmesiyle ortaya çıkar. Ama asıl soru şu: bu birikime ne yol açtı? Nedeni doğru anlamak, tedavi planını ve riski azaltma stratejisini doğrudan belirler.",
 "watopic":"lenfödem nedenleri",
 "about":"Lenfödem",
 "aboutType":"MedicalCondition",
 "card":"Lenfödem nedenleri","cardsub":"Primer ve sekonder nedenler, risk faktörleri",
 "procedure":{"name":"Lenfödem Etiyolojik Değerlendirme",
   "how":"Şişliğin başlangıcı, geçirilmiş cerrahi ve radyoterapi, enfeksiyon öyküsü ve aile öyküsü birlikte değerlendirilir; gerektiğinde görüntüleme ile lenfatik yapı incelenir.",
   "prep":"Ayrıntılı öykü ve mevcut tıbbi kayıtlar.",
   "follow":"Nedene yönelik tedavi planı ve risk azaltma önerileri.",
   "body":"Lenfatik sistem"},
 "keyfacts":[("En sık neden","Kanser tedavisi sonrası (sekonder)"),
             ("Primer","Doğuştan lenfatik gelişim yetersizliği"),
             ("Tetikleyici","Enfeksiyon her atakta hasarı artırır"),
             ("Değiştirilebilir","Kilo, enfeksiyon, cilt bakımı")],
 "authority":"Lenfödemin nedenini doğru koymak, gereksiz tedaviyi önlediği kadar doğru cerrahiyi de mümkün kılar. Doç. Dr. Acartürk, hem onkolojik cerrahi sonrası rekonstrüksiyon hem de lenfatik mikrocerrahi yapan bir cerrah olarak bu iki alanı birlikte değerlendirir.",
 "creds":["Pittsburgh Üniversitesi Baş–Boyun Onarımları eski Direktörü",
          "300+ mikrocerrahi operasyon · %97 flep başarı oranı",
          "Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım"],
 "sections":[
  {"id":"mekanizma","tag":"Mekanizma","h2":"Lenfödem nasıl oluşur?","body":[
   "Lenfatik sistem, dokular arasında biriken protein yükü yüksek sıvıyı toplayıp dolaşıma geri veren ince bir kanal ağıdır. Kalbin pompaladığı damar sistemi gibi merkezi bir pompası yoktur; kas hareketi ve kanal duvarındaki kasılmalarla çalışır.",
   "Bu ağ tıkandığında veya taşıma kapasitesi aşıldığında sıvı dokuda birikir. Başlangıçta bu birikim yalnızca sıvıdan ibarettir ve geri döndürülebilir. Zamanla ise <strong>yağ birikimi ve fibrozis</strong> gelişir, doku sertleşir ve tablo kalıcı hale gelir.",
   ("note","Kritik nokta şudur: lenfödem statik bir durum değil, ilerleyen bir süreçtir. Erken dönemde kanallar hâlâ çalışıyorken müdahale etmek, doku sertleştikten sonra müdahale etmekten çok daha etkilidir.")]},
  {"id":"sekonder","tag":"Sekonder","h2":"Sekonder lenfödem nedenleri (en sık)","body":[
   "Vakaların büyük çoğunluğu sekonderdir — yani lenfatik sistem başlangıçta normalken sonradan hasar görmüştür.",
   ("h3","Kanser tedavileri"),
   ("ul",["<strong>Lenf nodu diseksiyonu:</strong> meme, jinekolojik, ürolojik kanserler ve melanomda lenf nodlarının çıkarılması",
          "<strong>Radyoterapi:</strong> ışınlama lenfatik kanalları skarlaştırır ve taşıma kapasitesini düşürür",
          "<strong>Tümörün kendisi:</strong> lenfatik yolları doğrudan tıkayabilir"]),
   ("h3","Enfeksiyonlar"),
   ("ul",["<strong>Tekrarlayan selülit (erizipel):</strong> her atak lenfatik kanallarda kalıcı hasar bırakır ve bir sonraki atağın riskini artırır — kısır döngü",
          "<strong>Filariazis:</strong> dünya genelinde en sık lenfödem nedeni olan parazit hastalığı; Türkiye'de görülmez"]),
   ("h3","Travma ve cerrahi"),
   ("ul",["Geniş yumuşak doku yaralanmaları ve yanıklar",
          "Büyük ortopedik ve damar cerrahileri",
          "Yaygın skar dokusu"]),
   ("h3","Diğer"),
   ("ul",["Kronik venöz yetmezlik — zamanla lenfatik yükü artırır (flebolenfödem)",
          "Obezite — yüksek vücut kitle indeksi lenfatik taşıma kapasitesini zorlar",
          "Uzun süreli hareketsizlik"])]},
  {"id":"primer","tag":"Primer","h2":"Primer lenfödem: doğuştan gelen nedenler","body":[
   "Primer lenfödem, lenfatik sistemin doğuştan yetersiz gelişmesine bağlıdır. Sekonder lenfödeme göre çok daha nadirdir ve ortaya çıkış yaşına göre adlandırılır:",
   ("table",["Tip","Ortaya çıkış","Not"],[
     ["Konjenital lenfödem","Doğumda veya ilk 2 yılda","Milroy hastalığı bu grupta yer alır"],
     ["Lenfödema prekoks","Ergenlik–35 yaş arası","En sık primer form; kadınlarda daha yaygın"],
     ["Lenfödema tarda","35 yaş sonrası","Nadirdir; sekonder nedenler önce dışlanmalıdır"]]),
   ("note","35 yaşından sonra başlayan ve nedeni belli olmayan lenfödemde, primer tanısı koymadan önce altta yatan bir kitle veya tıkanıklık mutlaka araştırılmalıdır. Bu, atlanmaması gereken bir adımdır.")]},
  {"id":"risk","tag":"Risk Faktörleri","h2":"Riski artıran ve azaltılabilen faktörler","body":[
   "Bazı risk faktörleri değiştirilemez (geçirilmiş cerrahinin kapsamı gibi), bazıları ise doğrudan sizin kontrolünüzdedir.",
   ("table",["Faktör","Değiştirilebilir mi?"],[
     ["Lenf nodu diseksiyonunun kapsamı","Hayır — ancak koruyucu cerrahi (LYMPHA) ile risk azaltılabilir"],
     ["Radyoterapi öyküsü","Hayır"],
     ["Genetik yatkınlık","Hayır"],
     ["Vücut kitle indeksi","Evet — kilo kontrolü lenfatik yükü doğrudan azaltır"],
     ["Tekrarlayan enfeksiyon","Evet — cilt bakımı ve erken antibiyotik ile"],
     ["Cilt bütünlüğü","Evet — nemlendirme, yaralanmadan korunma, mantar tedavisi"],
     ["Hareketsizlik","Evet — düzenli egzersiz lenf akımını destekler"]]),
   ("note","Enfeksiyondan korunma, değiştirilebilir faktörler arasında en önemlisidir. Her selülit atağı lenfatik rezervi biraz daha azaltır; atakları önlemek hastalığın ilerleyişini yavaşlatmanın en etkili yoludur.")]}],
 "faqs":[
  ("Lenfödem kalıtsal mıdır?","Primer lenfödemde genetik yatkınlık rol oynar ve aile öyküsü bulunabilir. Ancak vakaların çoğunluğu sekonderdir — yani kanser tedavisi, enfeksiyon veya travma sonrası gelişir ve kalıtsal değildir."),
  ("Lenfödem kanser midir?","Hayır. Lenfödem, lenf sıvısının birikmesiyle oluşan bir dolaşım sorunudur. Lenfoma ise lenfatik sistemin kanseridir ve hematoloji-onkoloji tarafından tedavi edilir. İsim benzerliği dışında ilişkileri yoktur."),
  ("Her lenf nodu ameliyatından sonra lenfödem olur mu?","Hayır. Risk, çıkarılan nod sayısı ve radyoterapi eklenip eklenmediğine göre değişir. Sentinel lenf nodu biyopsisinde risk düşükken, geniş diseksiyon ve radyoterapi birlikte uygulandığında risk belirgin artar."),
  ("Kilo vermek lenfödemi düzeltir mi?","Tek başına düzeltmez ancak belirgin katkı sağlar. Yüksek vücut kitle indeksi lenfatik taşıma kapasitesini zorlar; kilo kontrolü hem mevcut şişliği azaltır hem de tedavi sonuçlarını iyileştirir."),
  ("Selülit neden bu kadar önemli?","Her atak lenfatik kanallarda kalıcı hasar bırakır ve hastalığın evresini ilerletir. Ayrıca bir atak geçirmek bir sonraki atağın riskini artırır. Bu döngüyü kırmak tedavinin ayrılmaz parçasıdır."),
  ("Uçak yolculuğu lenfödem yapar mı?","Uçuşun tek başına lenfödem başlattığına dair güçlü kanıt yoktur. Ancak risk grubundaki kişilerde uzun uçuşlarda bası giysisi kullanmak ve sık hareket etmek makul bir önlemdir.")],
 "related":["lenfodem","lenfodem-belirtileri","lenfodem-evreleri","kolda-lenfodem"],
 "ctah":"Nedenini birlikte değerlendirelim",
 "ctap":"Şişliğin ne zaman başladığını, geçirdiğiniz ameliyat ve radyoterapiyi, enfeksiyon öykünüzü ve ailenizde benzer durum olup olmadığını yazın."},

{"key":"lenfodem-hangi-doktor",
 "slug":"lenfodeme-hangi-bolum-bakar.html",
 "prio":0.85,
 "crumb":"Lenfödeme Hangi Bölüm Bakar",
 "title":"Lenfödeme Hangi Bölüm Bakar? Hangi Doktora Gitmeli | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lenfödeme Hangi Bölüm Bakar?",
 "desc":"Lenfödem için hangi bölüme başvurmalı? Plastik cerrahi, fizik tedavi ve diğer branşların rolleri, hangi durumda hangi hekime gitmeli ve randevuya nasıl hazırlanmalı.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Lenfödeme hangi bölüm bakar?",
 "lead":"Lenfödem, tek bir branşın hastalığı değil. Bu yüzden hastalar sıklıkla bölümler arasında dolaşıyor ve doğru adrese aylar sonra ulaşıyor. Bu sayfa, hangi durumda hangi hekime başvurmanız gerektiğini açıkça anlatıyor.",
 "watopic":"lenfödem için doğru bölüm",
 "about":"Lenfödem",
 "aboutType":"MedicalCondition",
 "card":"Hangi bölüm bakar?","cardsub":"Lenfödemde doğru branşa yönlendirme",
 "procedure":{"name":"Lenfödem Cerrahi Değerlendirme",
   "how":"Plastik ve rekonstrüktif cerrahi, lenfatik mikrocerrahi ile tıkanıklığa doğrudan müdahale eder: LVA, vaskülarize lenf nodu transferi ve azaltıcı cerrahi.",
   "prep":"Evreleme, görüntüleme ve önceki tedavilerin değerlendirilmesi.",
   "follow":"Fizyoterapi ile birlikte yürütülen uzun dönem takip.",
   "body":"Lenfatik sistem"},
 "keyfacts":[("Cerrahi tedavi","Plastik ve Rekonstrüktif Cerrahi"),
             ("Konservatif tedavi","Fiziksel Tıp ve Rehabilitasyon"),
             ("İdeal","İki branşın birlikte çalışması"),
             ("Uyarı","Önce altta yatan neden araştırılmalı")],
 "authority":"Lenfödem mikrocerrahisi, plastik cerrahi içinde ayrı bir uzmanlık alanıdır — her plastik cerrah bu ameliyatları yapmaz. Doç. Dr. Acartürk, Pittsburgh Üniversitesi'nde 300+ mikrocerrahi vaka gerçekleştirmiş, Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılan ve Dünya Lenfoloji Kongresi'nde bildiri sunmuş bir mikrocerrahtır.",
 "creds":["Pittsburgh Üniversitesi Baş–Boyun Onarımları eski Direktörü — 300+ mikrocerrahi vaka",
          "Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım",
          "Dünya Lenfoloji Kongresi'nde bildiri sunumu"],
 "sections":[
  {"id":"kisa","tag":"Kısa Cevap","h2":"Kısa cevap","body":[
   "Lenfödemde iki ana branş rol alır ve ikisi de gereklidir:",
   ("ul",["<strong>Plastik ve Rekonstrüktif Cerrahi</strong> — cerrahi tedaviyi yürütür. Lenfatik mikrocerrahi (LVA), vaskülarize lenf nodu transferi ve azaltıcı cerrahi bu branşın alanıdır.",
          "<strong>Fiziksel Tıp ve Rehabilitasyon</strong> — konservatif tedaviyi yürütür. Kompleks boşaltıcı fizyoterapi, manuel lenf drenajı, bandajlama ve bası giysisi planlaması bu branşta yapılır."]),
   ("note","Bu iki branş birbirinin alternatifi değil, tamamlayıcısıdır. Cerrahi sonrasında fizyoterapi devam eder; fizyoterapi ile kontrol altına alınamayan hastada cerrahi devreye girer. En iyi sonuç, iki branşın birlikte çalıştığı merkezlerde alınır.")]},
  {"id":"hangi-durumda","tag":"Yönlendirme","h2":"Hangi durumda hangi hekime?","body":[
   ("table",["Durumunuz","Başvurulacak bölüm"],[
     ["Yeni başlayan şişlik, tanı konmamış","Önce nedeni araştıracak hekim: aile hekimi veya ilgili uzman"],
     ["Kanser tedavisi sonrası kolda/bacakta şişlik","Plastik cerrahi + fizik tedavi (birlikte)"],
     ["Tanı konmuş, fizyoterapi görüyor ama yeterli gelmiyor","Plastik ve rekonstrüktif cerrahi — cerrahi adaylık değerlendirmesi"],
     ["Erken evre, cerrahi seçenekleri öğrenmek istiyor","Plastik ve rekonstrüktif cerrahi (lenfatik mikrocerrahi)"],
     ["Tekrarlayan selülit atakları","Enfeksiyon hastalıkları + lenfödem ekibi"],
     ["Ani başlayan ağrılı tek taraflı şişlik","Acil servis — damar tıkanıklığı dışlanmalı"]]),
   ("note","Ani başlayan, ağrılı ve tek taraflı şişlikte derin ven trombozu ihtimali vardır ve bu acil bir durumdur. Lenfödem değerlendirmesi bu ihtimal dışlandıktan sonra yapılır.")]},
  {"id":"branslar","tag":"Branşlar","h2":"Diğer branşların rolü","body":[
   ("ul",["<strong>Onkoloji:</strong> kanser tedavisi süren hastada takip ve yönlendirme",
          "<strong>Genel cerrahi / jinekoloji / üroloji:</strong> lenf nodu diseksiyonu yapılan hastanın izlemi ve erken yönlendirmesi",
          "<strong>Radyoloji:</strong> lenfosintigrafi, MR lenfanjiyografi ve ICG lenfografi ile lenfatik haritalama",
          "<strong>Kardiyoloji / nefroloji:</strong> sistemik ödem nedenlerinin dışlanması",
          "<strong>Damar cerrahisi:</strong> venöz yetmezlik ve derin ven trombozu ayrımı",
          "<strong>Enfeksiyon hastalıkları:</strong> tekrarlayan selülit yönetimi",
          "<strong>Dermatoloji:</strong> deri komplikasyonları ve mantar enfeksiyonları"])]},
  {"id":"hazirlik","tag":"Hazırlık","h2":"Randevuya nasıl hazırlanmalısınız?","body":[
   "Doğru bölüme gitmek kadar, o randevuya hazırlıklı gitmek de süreci hızlandırır. Yanınızda getirmeniz gerekenler:",
   ("ul",["<strong>Ameliyat raporları:</strong> özellikle lenf nodu diseksiyonu yapılıp yapılmadığı ve kaç nod çıkarıldığı",
          "<strong>Radyoterapi bilgisi:</strong> hangi bölgeye, kaç seans",
          "<strong>Görüntüleme kayıtları:</strong> daha önce lenfosintigrafi veya MR yapıldıysa",
          "<strong>Çevre ölçümleri:</strong> varsa önceki ölçüm kayıtları",
          "<strong>Fotoğraflar:</strong> şişliğin zaman içindeki değişimini gösteren",
          "<strong>Enfeksiyon öyküsü:</strong> kaç selülit atağı geçirdiniz, ne zaman",
          "<strong>Kullandığınız ilaçlar ve bası giysisi bilgisi</strong>"]),
   ("note","Şişliğin <strong>ne zaman başladığı</strong> ve <strong>ne kadar sürdüğü</strong>, cerrahi adaylık kararında en belirleyici bilgilerden biridir. Bu iki soruya net cevap verebilmek randevunuzun verimini doğrudan artırır.")]},
  {"id":"cerrah-secimi","tag":"Cerrah Seçimi","h2":"Lenfödem cerrahı seçerken nelere bakmalı?","body":[
   "Lenfatik mikrocerrahi, plastik cerrahinin en ince teknik gerektiren alt alanıdır: 0,3–0,8 mm çapındaki kanallarla çalışılır. Her plastik cerrah bu ameliyatları yapmaz. Sorulabilecek makul sorular:",
   ("ul",["Mikrocerrahi deneyimi ne kadar? Kaç vaka?",
          "Merkezde ICG lenfografi veya lenfosintigrafi yapılabiliyor mu?",
          "Fizyoterapi ekibiyle birlikte mi çalışılıyor?",
          "Hangi evrede hangi ameliyatın önerildiği açıkça anlatılıyor mu?",
          "Gerçekçi beklenti konuşuluyor mu — yoksa tam şifa mı vaat ediliyor?"]),
   ("note","Tam şifa vaadi, lenfödemde uyarı işaretidir. Dürüst bir değerlendirme; hacim azalması, enfeksiyonların seyrelmesi ve bası giysisine bağımlılığın azalması gibi ölçülebilir hedefler üzerinden konuşur.")]}],
 "faqs":[
  ("Lenfödeme hangi bölüm bakar?","Cerrahi tedavi için Plastik ve Rekonstrüktif Cerrahi, konservatif tedavi için Fiziksel Tıp ve Rehabilitasyon. Bu iki branş birbirinin alternatifi değil, tamamlayıcısıdır."),
  ("Önce fizik tedaviye mi gitmeliyim?","Fizyoterapi tedavinin temelidir ve çoğu hastada ilk basamaktır. Ancak erken evrede cerrahi seçeneklerin de değerlendirilmesi önemlidir; çünkü lenf kanalları çalışıyorken müdahale etmek, doku sertleştikten sonra müdahale etmekten daha etkilidir. İki değerlendirmenin paralel yürümesi idealdir."),
  ("Her plastik cerrah lenfödem ameliyatı yapar mı?","Hayır. Lenfatik mikrocerrahi ayrı bir deneyim gerektirir; 0,3–0,8 mm çapındaki kanallarla mikroskop altında çalışılır. Cerrahın mikrocerrahi deneyimini ve merkezin görüntüleme imkânlarını sormak makuldür."),
  ("Devlet hastanesinde bu ameliyatlar yapılıyor mu?","Bazı üniversite ve eğitim-araştırma hastanelerinde lenfatik mikrocerrahi uygulanmaktadır. Merkez sayısı sınırlıdır; başvurmadan önce merkezin bu alanda çalışıp çalışmadığını teyit etmek zaman kazandırır."),
  ("Lenfödem için hangi tetkikler isteniyor?","En sık ICG lenfografi ve lenfosintigrafi kullanılır; ileri ve karmaşık vakalarda MR lenfanjiyografi tercih edilebilir. Ayrıca çevre ölçümleri ve klinik değerlendirme her hastada yapılır."),
  ("İkinci görüş almak doğru mu?","Evet, özellikle cerrahi kararında. Lenfödemde evre ve görüntüleme bulguları tedavi seçeneğini doğrudan belirler; farklı bir merkezin değerlendirmesi kararınızı netleştirebilir.")],
 "related":["lenfodem","lenfodem-belirtileri","lenfodem-evreleri","lipodem-hangi-doktor"],
 "ctah":"Doğru bölüm için ilk adım",
 "ctap":"Şişliğin ne zaman başladığını, hangi tedavileri gördüğünüzü ve elinizdeki raporları yazın; hangi değerlendirmenin size uygun olduğunu birlikte belirleyelim."},

{"key":"lenfodem-evreleri",
 "slug":"lenfodem-evreleri.html",
 "prio":0.85,
 "crumb":"Lenfödem Evreleri",
 "title":"Lenfödem Evreleri: ISL Sınıflaması ve Tedavi Karşılığı | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lenfödem Evreleri ve Tedavi Karşılıkları",
 "desc":"Lenfödem evreleri nelerdir? ISL sınıflamasına göre Evre 0, 1, 2 ve 3 bulguları, evrelemenin nasıl yapıldığı ve her evrede hangi tedavinin uygun olduğu.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Lenfödem evreleri",
 "lead":"Evre, lenfödemde tedavi seçeneğini belirleyen tek en önemli bilgidir. Aynı şişlik farklı evrelerde tamamen farklı bir tedavi gerektirir. Bu sayfa, evrelerin ne anlama geldiğini ve her birinde neyin mümkün olduğunu anlatıyor.",
 "watopic":"lenfödem evrelemesi",
 "about":"Lenfödem",
 "aboutType":"MedicalCondition",
 "card":"Lenfödem evreleri","cardsub":"ISL sınıflaması ve evreye göre tedavi",
 "procedure":{"name":"Lenfödem Evreleme",
   "how":"Uluslararası Lenfoloji Derneği (ISL) sınıflamasına göre klinik bulgular, doku kıvamı ve görüntüleme birlikte değerlendirilerek evre belirlenir.",
   "prep":"Çevre ölçümleri, Stemmer belirtisi, ICG lenfografi veya lenfosintigrafi.",
   "follow":"Evreye uygun tedavi planı ve düzenli yeniden değerlendirme.",
   "body":"Lenfatik sistem"},
 "keyfacts":[("Evre 0","Görüntülemede saptanır, şişlik yok"),
             ("Evre 1","Kaldırınca kısmen geçer, gode bırakır"),
             ("Evre 2","Kaldırınca geçmez, doku sertleşir"),
             ("Evre 3","Belirgin hacim, deri kalınlaşması")],
 "authority":"Evreleme, tedaviyi belirleyen çerçevedir ama tek başına yeterli değildir — görüntüleme bulguları ile birlikte yorumlanmalıdır. Doç. Dr. Acartürk, Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılan ve Dünya Lenfoloji Kongresi'nde bildiri sunmuş bir mikrocerrah olarak bu iki veriyi birlikte değerlendirir.",
 "creds":["Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım",
          "Dünya Lenfoloji Kongresi'nde bildiri sunumu",
          "Pittsburgh Üniversitesi'nde 300+ mikrocerrahi vaka"],
 "sections":[
  {"id":"isl","tag":"ISL Sınıflaması","h2":"ISL evreleme sistemi","body":[
   "Uluslararası Lenfoloji Derneği'nin (ISL) sınıflaması, dünya genelinde kabul gören çerçevedir. Evreler, dokunun durumunu ve geri döndürülebilirliği tanımlar.",
   ("table",["Evre","Klinik bulgular","Doku durumu"],[
     ["Evre 0 (latent)","Görünür şişlik yok; hasta ağırlık hissedebilir","Taşıma kapasitesi azalmış, doku normal"],
     ["Evre 1","Şişlik gün içinde artar, kaldırınca kısmen geçer; gode bırakır","Sıvı birikimi baskın, geri döndürülebilir"],
     ["Evre 2","Kaldırmakla geçmez; gode giderek azalır","Fibrozis ve yağ birikimi başlamış"],
     ["Evre 3 (elefantiyaz)","Belirgin hacim artışı, deri kalınlaşması, siğilimsi değişiklikler","İleri fibrozis, kalıcı doku değişikliği"]]),
   ("note","<strong>Evre 0 en değerli evredir.</strong> Görünür şişlik yoktur ama görüntülemede taşıma kapasitesindeki azalma saptanır. Bu evrede yakalanan hastada koruyucu ve en az invaziv seçenekler devrededir. Risk grubundaki hastalarda düzenli takip bu yüzden önemlidir.")]},
  {"id":"tedavi","tag":"Evre–Tedavi","h2":"Hangi evrede hangi tedavi?","body":[
   "Evre, hangi cerrahi seçeneğin uygulanabilir olduğunu doğrudan belirler. Temel mantık şudur: <strong>lenf kanalları hâlâ çalışıyorsa akımı yeniden yönlendir; çalışmıyorsa yeni doku getir veya hacmi azalt.</strong>",
   ("table",["Evre","Öncelikli yaklaşım"],[
     ["Evre 0","Takip, cilt bakımı, risk azaltma; seçilmiş hastada koruyucu LVA"],
     ["Evre 1","LVA — en az invaziv ve en etkili seçenek"],
     ["Evre 2","LVA ve/veya vaskülarize lenf nodu transferi"],
     ["Evre 3","Lenf nodu transferi + azaltıcı cerrahi (liposuction, eksizyon)"]]),
   ("note","Bu tablo bir çerçevedir, reçete değildir. Nihai karar; görüntülemede çalışan lenf kanalı olup olmadığı, şişliğin süresi, enfeksiyon öyküsü ve hastanın genel durumu ile birlikte verilir. Aynı evredeki iki hastaya farklı ameliyat önerilebilir.")]},
  {"id":"nasil","tag":"Nasıl Belirlenir","h2":"Evre nasıl belirlenir?","body":[
   "Evreleme yalnızca bakmakla yapılmaz; klinik muayene ve görüntüleme birlikte kullanılır.",
   ("h3","Klinik değerlendirme"),
   ("ul",["Çevre ölçümleri — karşı uzuvla karşılaştırmalı",
          "Gode testi — sıvı mı, fibrozis mi",
          "Stemmer belirtisi",
          "Deri kalitesi ve kalınlığı",
          "Enfeksiyon öyküsü ve sıklığı"]),
   ("h3","Görüntüleme"),
   ("ul",["<strong>ICG lenfografi:</strong> çalışan lenf kanallarının gerçek zamanlı haritası. LVA planlamasında belirleyicidir.",
          "<strong>Lenfosintigrafi:</strong> lenf akımının ve nod tutulumunun değerlendirilmesi",
          "<strong>MR lenfanjiyografi:</strong> ayrıntılı anatomik görüntü; ileri ve karmaşık vakalarda"]),
   ("note","Klinik evre ile görüntüleme bulguları her zaman örtüşmez. Klinik olarak Evre 2 görünen bir hastada ICG'de hâlâ çalışan kanallar bulunabilir — bu, LVA'yı gündeme getirir. Bu nedenle cerrahi karar görüntüleme olmadan verilmemelidir.")]},
  {"id":"ilerleme","tag":"İlerleme","h2":"Evreler arasında geçiş ve zaman","body":[
   "Lenfödem ilerleyici bir hastalıktır, ancak ilerleme hızı kişiden kişiye çok değişir. Bazı hastalar yıllarca Evre 1'de kalırken, bazılarında tablo hızla ilerler.",
   ("h3","İlerlemeyi hızlandıran faktörler"),
   ("ul",["Tekrarlayan selülit atakları — en güçlü hızlandırıcı",
          "Kilo artışı",
          "Bası giysisinin düzensiz kullanımı",
          "Tedavisiz geçen süre",
          "Ek travma veya cerrahi"]),
   ("h3","İlerlemeyi yavaşlatan faktörler"),
   ("ul",["Düzenli bası giysisi kullanımı",
          "Cilt bakımı ve enfeksiyondan korunma",
          "Kilo kontrolü",
          "Düzenli hareket ve egzersiz",
          "Erken cerrahi müdahale"]),
   ("note","Evre geriye döndürülebilir mi? Erken evrede — sıvı birikiminin baskın olduğu dönemde — tedaviyle belirgin gerileme mümkündür. Fibrozis yerleştikten sonra doku değişikliği kalıcıdır; bu evrede hedef hacmi azaltmak ve ilerlemeyi durdurmaktır.")]}],
 "faqs":[
  ("Lenfödem kaç evreye ayrılır?","Uluslararası Lenfoloji Derneği (ISL) sınıflamasına göre dört evre vardır: Evre 0 (latent), Evre 1, Evre 2 ve Evre 3 (elefantiyaz). Evreler dokunun durumunu ve geri döndürülebilirliği tanımlar."),
  ("Evre 0 ne demek?","Görünür şişlik yoktur ancak lenfatik taşıma kapasitesi azalmıştır ve bu görüntülemede saptanır. Hasta ağırlık veya gerginlik hissedebilir. Tedavi seçeneklerinin en geniş olduğu evredir."),
  ("Hangi evrede ameliyat olunur?","Evre 1 ve 2'de, lenf kanalları çalışıyorsa LVA öne çıkar. Evre 2–3'te vaskülarize lenf nodu transferi ve azaltıcı cerrahi planlanır. Karar, görüntüleme bulgularıyla birlikte verilir."),
  ("Evre geriye döner mi?","Erken evrede, sıvı birikiminin baskın olduğu dönemde tedaviyle belirgin gerileme mümkündür. Fibrozis yerleştikten sonra doku değişikliği kalıcıdır; bu evrede hedef hacmi azaltmak ve ilerlemeyi durdurmaktır."),
  ("Evrem ilerlerse ne olur?","Tedavi seçenekleri daralır. Erken evrede en az invaziv yöntem olan LVA mümkünken, ileri evrede daha kapsamlı cerrahiler gerekir. Ayrıca enfeksiyon riski ve fonksiyon kaybı artar."),
  ("Gode bırakmıyorsa evre daha mı ileri?","Genellikle evet. Erken evrede basmakla çukur kalır; doku fibrozla sertleştikçe gode kalmaz. Bu, tablonun ilerlediğine işaret eden önemli bir muayene bulgusudur.")],
 "related":["lenfodem","lenfodem-belirtileri","lenfodem-neden-olur","lenfodem-hangi-doktor"],
 "ctah":"Evrenizi birlikte belirleyelim",
 "ctap":"Şişliğin süresini, kaldırınca geçip geçmediğini, selülit öykünüzü ve varsa görüntüleme sonuçlarınızı yazın; mümkünse fotoğraf ekleyin."},

]
