# -*- coding: utf-8 -*-
"""
Lipodem uydu sayfalari — hub: lipodem-cerrahisi.html
Hedef sorgular ve aylik hacimler (Semrush TR):
  lipodem nedir 33100
  lipodem diyeti 9900 (+ ornek menu 1600, listesi 1000, yasak yiyecekler 1000, beslenmesi 720)
  lipodem belirtileri 4400 (+ nasil anlasilir 880, baslangici 880)
  lipodem hangi doktor bakar 2400 (KD 8)
  ameliyatsiz lipodem tedavisi 2400 (KD 9) (+ egzersizleri 1600, nasil gecer 1000)
  lipodem evreleri 590
"""

LIPODEM_KUME = [

{"key":"lipodem-nedir",
 "slug":"lipodem-nedir.html",
 "prio":0.95,
 "crumb":"Lipödem Nedir",
 # "Belirtileri" cikarildi — lipodem-belirtileri.html o sorgunun adanmis sayfasi.
 "title":"Lipödem Nedir? Nedenleri ve Kimlerde Görülür | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lipödem Nedir? Nedenleri ve Tedavisi",
 "desc":"Lipödem nedir, neden olur, obezite ve selülitten farkı nedir? Belirtileri, evreleri, tanısı ve lenfatik koruyucu cerrahi tedavi seçenekleri.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Lipödem nedir?",
 "lead":"Bacaklarınız vücudunuzun geri kalanıyla orantısız duruyorsa, dokunmakla ağrıyorsa ve kilo verdiğinizde üst bedeniniz incelirken bacaklarınız aynı kalıyorsa — bu bir irade meselesi değil. Lipödem, tanınması gereken bir hastalıktır ve kadınların yaklaşık %10'unu etkiler.",
 "watopic":"lipödem",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Lipödem nedir","cardsub":"Tanım, nedenler ve tedavi yaklaşımı",
 "procedure":{"name":"Lipödem Cerrahisi — Lenfatik Koruyucu Liposuction",
   "how":"Hastalıklı yağ dokusu, lenfatik yapılar korunarak WAL (su jeti destekli) veya PAL (güç destekli) teknikle uzaklaştırılır.",
   "prep":"Muayene, evreleme, gerektiğinde lenfatik görüntüleme ve bası giysisi ölçüsü.",
   "follow":"Bası giysisi, erken mobilizasyon ve gerektiğinde manuel lenf drenajı.",
   "body":"Bacaklar, kalçalar, kollar"},
 "keyfacts":[("Görülme sıklığı","Kadınların yaklaşık %10'u"),
             ("Ayırt edici","Ayaklar korunur — manşon belirtisi"),
             ("Temel şikâyet","Ağrı, hassasiyet, kolay morarma"),
             ("Kilo ile ilişki","Diyetle geçmez")],
 "authority":"Lipödem cerrahisi, lenfatik sistemi koruyan liposuction tekniklerine hâkim olmayı gerektirir. Doç. Dr. Acartürk, Pittsburgh Üniversitesi'nde yağ dokusu ve kök hücre teknolojileri üzerine çalışmış ilk Türk plastik cerrahlardandır; aynı zamanda lenfödem mikrocerrahisi yapan bir cerrah olarak lenfatik anatomiyle günlük pratiğinde çalışır.",
 "creds":["Pittsburgh Üniversitesi'nde yağ dokusu ve kök hücre araştırmaları",
          "Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım",
          "Dünya Lenfoloji Kongresi'nde bildiri sunumu"],
 "sections":[
  {"id":"tanim","tag":"Tanım","h2":"Lipödem nedir?","body":[
   "Lipödem, yağ dokusunun anormal ve <strong>simetrik</strong> şekilde arttığı, dokunmakla ağrı ve hassasiyetin eşlik ettiği kronik bir hastalıktır. Neredeyse yalnızca kadınlarda görülür.",
   "Birikim kalça, uyluk ve baldırlarda yoğunlaşır; vakaların yaklaşık dörtte birinde kollar da tutulur. Üst beden genellikle korunur. <strong>Ayaklar tutulmaz</strong> — bu nedenle bilekte keskin bir geçiş oluşur; buna <strong>manşon belirtisi</strong> denir ve lipödemin en tipik bulgusudur.",
   ("h3","Lipödemi tanımlayan üç özellik"),
   ("ul",["<strong>Simetri:</strong> her iki taraf birbirine benzer şekilde etkilenir",
          "<strong>Ağrı:</strong> dokunmakla hassasiyet ve kolay morarma — bu, lipödemi basit yağlanmadan ayıran en önemli özelliktir",
          "<strong>Diyete direnç:</strong> kilo verildiğinde üst beden incelir, bölgesel birikim kalır"]),
   ("note","Lipödem bir kilo problemi değildir. Kalori kısıtlaması ve egzersiz genel yağ kütlesini azaltır ama hastalıklı yağ dokusuna etki etmez. Bu nedenle hastalar sıklıkla \"yeterince çabalamamakla\" suçlanır — oysa sorun iradede değil, dokunun kendisindedir.")]},
  {"id":"neden","tag":"Nedenler","h2":"Lipödem neden olur?","body":[
   "Lipödemin nedeni tam olarak bilinmemektedir, ancak iki faktör öne çıkar: <strong>hormonal geçişler</strong> ve <strong>genetik yatkınlık</strong>.",
   ("ul",["<strong>Hormonal dönemler:</strong> hastalık en sık ergenlik, gebelik veya menopoz döneminde başlar. Bu, östrojenin yağ dokusu dağılımındaki rolüne işaret eder.",
          "<strong>Aile öyküsü:</strong> hastaların önemli bir kısmında annede, teyzede veya kız kardeşte benzer vücut yapısı bulunur",
          "<strong>Kadınlarda görülmesi:</strong> erkeklerde son derece nadirdir ve genellikle hormonal bir bozukluk eşlik eder",
          "<strong>Mikrodolaşım ve inflamasyon:</strong> etkilenen dokuda küçük damar geçirgenliğinin arttığı ve düşük düzeyde inflamasyon bulunduğu gösterilmiştir — ağrı ve kolay morarmayı bu açıklar"]),
   ("note","Lipödem obezitenin bir sonucu değildir. Ancak ikisi bir arada bulunabilir ve obezite lipödemi ağırlaştırır. Kilo kontrolü hastalığı ortadan kaldırmaz ama şikâyetleri ve lenfatik yükü azaltır.")]},
  {"id":"fark","tag":"Ayırıcı Tanı","h2":"Obezite, selülit ve lenfödemden farkı","body":[
   "Lipödem en sık bu üç durumla karıştırılır. Ayrım, tedaviyi tamamen değiştirdiği için önemlidir.",
   ("table",["Özellik","Lipödem","Obezite","Lenfödem"],[
     ["Dağılım","Bölgesel — kalça, uyluk, baldır","Tüm vücuda yaygın","Genellikle tek uzuv"],
     ["Simetri","Simetrik","Simetrik","Sıklıkla asimetrik"],
     ["Ayak tutulumu","Yok — manşon belirtisi","Değişken","Var — ayak sırtı ve parmaklar"],
     ["Ağrı","Belirgin, dokunmakla","Yok","Ağırlık hissi baskın"],
     ["Morarma","Kolay morarır","Normal","Normal"],
     ["Kilo verince","Bölgesel birikim kalır","Orantılı azalır","Değişmez"],
     ["Stemmer belirtisi","Negatif","Negatif","Pozitif"]]),
   ("h3","Selülitten farkı"),
   "Selülit, deri altı yağın görünümündeki bir değişikliktir ve <strong>ağrısızdır</strong>. Lipödemde ise tabloya ağrı ve hassasiyet hâkimdir. Selülit kozmetik bir durum, lipödem ise ilerleyici bir hastalıktır.",
   ("note","Lipödem ve lenfödem birlikte de bulunabilir. Tedavi edilmeyen lipödemde artan doku hacmi zamanla lenfatik sistemin taşıma kapasitesini aşar ve tabloya lenfödem eklenir; buna <strong>lipo-lenfödem</strong> denir. Ayrıntı için <a href=\"lenfodem-lipodem-cerrahisi.html\">lenfödem sayfamıza</a> bakabilirsiniz.")]},
  {"id":"tani","tag":"Tanı","h2":"Lipödem nasıl teşhis edilir?","body":[
   "Lipödemin kan testi veya kesin bir görüntüleme yöntemi yoktur. Tanı <strong>kliniktir</strong> — yani öykü ve muayene ile konur.",
   ("h3","Tanıda değerlendirilenler"),
   ("ul",["Şikâyetlerin ne zaman ve hangi dönemde başladığı",
          "Dokunmakla ağrı ve kolay morarma öyküsü",
          "Simetri ve ayakların korunmuş olması",
          "Kilo verme çabalarına verilen yanıt",
          "Aile öyküsü",
          "Deri ve doku kıvamı, nodüler yapı",
          "Stemmer belirtisi — lipödemde negatiftir"]),
   "Görüntüleme, lenfatik tutulum şüphesinde veya ayırıcı tanı için kullanılır; lipödem tanısını koymak için zorunlu değildir.",
   ("note","Tanının yıllarca gecikmesi lipödemde çok yaygındır. Hastaların çoğu ilk başvurularında obezite tanısı alır ve diyet önerisiyle gönderilir. Doğru tanı, hastalığın ilerlemesini engellemek açısından tek başına değerlidir.")]},
  {"id":"tedavi","tag":"Tedavi","h2":"Lipödem tedavisi","body":[
   ("h3","Konservatif tedavi"),
   "Bası giysileri, manuel lenf drenajı, düzenli hareket ve kilo kontrolü tedavinin temelidir. Bu yaklaşımlar şikâyetleri hafifletir ve ilerlemeyi yavaşlatır, ancak hastalıklı yağ dokusunu ortadan kaldırmaz. Ayrıntı için <a href=\"ameliyatsiz-lipodem-tedavisi.html\">ameliyatsız tedavi sayfamıza</a> bakabilirsiniz.",
   ("h3","Cerrahi tedavi — lenfatik koruyucu liposuction"),
   "Lipödem cerrahisi kozmetik bir işlem değil, tıbbi bir tedavidir. Amaç hacim küçültmek değil; hastalıklı yağ dokusunu <strong>lenfatik yapıları koruyarak</strong> uzaklaştırmak, ağrıyı azaltmak ve hareketi geri kazandırmaktır.",
   ("ul",["<strong>WAL (su jeti destekli):</strong> ince su jeti yağ hücrelerini dokudan nazikçe ayırır; lenf damarları ve sinirler büyük ölçüde korunur",
          "<strong>PAL (güç destekli):</strong> titreşimli kanül fibrotik ve yoğun dokuyu daha az travmayla çözer; ileri evrede tercih edilir"]),
   ("note","Cerrahi hastalığı ortadan kaldırmaz; hastalıklı yağ dokusunu azaltır. Alınan doku geri gelmez, ancak hastalık kalan dokuda devam eder. Bu nedenle bası giysisi, hareket ve stabil kilo ameliyat sonrasında da tedavinin parçasıdır.")]}],
 "faqs":[
  ("Lipödem nedir, kısaca?","Yağ dokusunun simetrik ve anormal biçimde arttığı, dokunmakla ağrının eşlik ettiği kronik bir hastalıktır. Neredeyse yalnızca kadınlarda görülür, kalça ve bacaklarda yoğunlaşır ve ayaklar korunur."),
  ("Lipödem kilo problemi mi?","Hayır. Hastalıklı yağ dokusu kalori kısıtlamasına ve egzersize direnç gösterir. Kilo verildiğinde üst beden incelirken bölgesel birikim kalır — hatta orantısızlık daha belirgin hale gelebilir."),
  ("Lipödem sadece kadınlarda mı görülür?","Neredeyse tamamen. Erkeklerde son derece nadirdir ve görüldüğünde genellikle altta bir hormonal bozukluk bulunur."),
  ("Lipödem tehlikeli mi?","Hayatı doğrudan tehdit etmez, ancak ilerleyicidir. Zamanla hareket kısıtlanır, diz ve kalça eklemlerine yük biner ve lenfatik sisteme bindirdiği yük nedeniyle lenfödem eklenebilir."),
  ("Lipödem geçer mi?","Hastalık tamamen ortadan kalkmaz. Ancak konservatif tedavi ile şikâyetler hafifletilebilir, cerrahi ile hastalıklı yağ dokusu azaltılıp ağrı ve hareket kısıtlılığı belirgin şekilde düzeltilebilir."),
  ("Lipödem ile lenfödem aynı şey mi?","Hayır. Lipödem yağ dokusu hastalığıdır, simetriktir ve ağrılıdır. Lenfödem lenf sıvısının birikmesidir, genellikle tek taraflıdır ve ayak tutulumu vardır. İkisi birlikte de bulunabilir (lipo-lenfödem).")],
 "related":["lipodem","lipodem-belirtileri","lipodem-evreleri","ameliyatsiz-lipodem-tedavisi"],
 "ctah":"Lipödem değerlendirmesi için ilk adım",
 "ctap":"Şikâyetlerinizin ne zaman başladığını, ağrının şiddetini ve denediğiniz tedavileri yazın; mümkünse bacaklarınızın önden ve yandan fotoğrafını ekleyin."},

{"key":"lipodem-belirtileri",
 "slug":"lipodem-belirtileri.html",
 "prio":0.9,
 "crumb":"Lipödem Belirtileri",
 "title":"Lipödem Belirtileri: Nasıl Anlaşılır? | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lipödem Belirtileri ve Nasıl Anlaşılır",
 "desc":"Lipödem belirtileri nelerdir, nasıl anlaşılır? Manşon belirtisi, ağrı ve morarma, başlangıç bulguları ve kendi kendine kontrol yöntemleri.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Lipödem belirtileri: nasıl anlaşılır?",
 "lead":"Lipödem tanısı ortalama olarak yıllar sonra konur. Bu gecikmenin nedeni hastalığın nadir olması değil — belirtilerinin kilo problemi sanılmasıdır. Bu sayfa, lipödemi diğer durumlardan ayıran bulguları anlatıyor.",
 "watopic":"lipödem belirtileri",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Lipödem belirtileri","cardsub":"Ayırt edici bulgular ve kendi kendine kontrol",
 "procedure":{"name":"Lipödem Tanısal Değerlendirme",
   "how":"Ağrı, simetri, ayakların korunması, kilo verme yanıtı ve doku kıvamı birlikte değerlendirilerek klinik tanı konur.",
   "prep":"Şikâyetlerin başlangıç dönemi ve aile öyküsü.",
   "follow":"Evreye göre tedavi planı.",
   "body":"Bacaklar, kalçalar, kollar"},
 "keyfacts":[("Manşon belirtisi","Şişlik bilekte biter, ayaklar korunur"),
             ("Ağrı","Dokunmakla hassasiyet tipik"),
             ("Morarma","Küçük darbelerde bile morluk"),
             ("Simetri","Her iki taraf benzer şekilde")],
 "authority":"Lipödemin doğru tanınması, gereksiz diyet döngülerini sonlandırdığı kadar doğru tedaviyi de mümkün kılar. Doç. Dr. Acartürk, hem lipödem cerrahisi hem de lenfödem mikrocerrahisi yapan bir cerrah olarak iki tabloyu birlikte değerlendirir.",
 "creds":["Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım",
          "Pittsburgh Üniversitesi'nde yağ dokusu ve kök hücre araştırmaları",
          "Lipödem ve lenfödemde birleşik değerlendirme yaklaşımı"],
 "sections":[
  {"id":"temel","tag":"Temel Belirtiler","h2":"Lipödemin temel belirtileri","body":[
   ("ul",["<strong>Orantısız vücut yapısı:</strong> üst beden ince, kalça ve bacaklar belirgin şekilde dolgun",
          "<strong>Manşon belirtisi:</strong> şişlik bilekte keskin biçimde biter, ayaklar normal kalır",
          "<strong>Dokunmakla ağrı:</strong> hafif basınçta bile hassasiyet — en ayırt edici bulgudur",
          "<strong>Kolay morarma:</strong> hatırlanmayan küçük darbelerde bile morluk oluşur",
          "<strong>Simetri:</strong> her iki bacak benzer şekilde etkilenir",
          "<strong>Diyete direnç:</strong> kilo verildiğinde üst beden incelir, bacaklar aynı kalır",
          "<strong>Nodüler doku:</strong> deri altında küçük, taneli yapılar hissedilir",
          "<strong>Ağırlık ve gerginlik hissi:</strong> özellikle gün sonunda artar"]),
   ("note","Bu belirtilerin hepsinin bir arada bulunması gerekmez. Ancak <strong>ağrı, simetri ve ayakların korunması</strong> üçlüsü bir aradaysa lipödem güçlü şekilde düşünülmelidir.")]},
  {"id":"baslangic","tag":"Başlangıç","h2":"Lipödem başlangıcı: ilk bulgular","body":[
   "Lipödem çoğunlukla hormonal bir geçiş döneminde başlar: ergenlik, gebelik veya menopoz. Başlangıç dönemi sinsidir ve genellikle kilo alımına bağlanır.",
   ("ul",["Pantolonun üst bedene göre dar gelmeye başlaması",
          "Uylukların birbirine değmesi ve sürtünme",
          "Bacaklarda gün sonu ağırlık hissi",
          "Masaj veya baskı sonrası beklenmedik hassasiyet",
          "Nedeni hatırlanmayan morluklar"]),
   ("note","Ergenlikte başlayan ve \"kilolu olduğu için\" diye açıklanan bacak yapısı, aile öyküsü de varsa dikkatle değerlendirilmelidir. Erken tanı, hastalığın ileri evreye geçmesini yavaşlatan tek etkili yaklaşımdır.")]},
  {"id":"kontrol","tag":"Kendi Kontrolünüz","h2":"Kendi kendine kontrol: dört basit soru","body":[
   ("steps",[
    ("1 — AYAKLARINIZA BAKIN","Şişlik bileğinizde bitip ayaklarınız normal mi kalıyor? Bilekte belirgin bir geçiş çizgisi var mı? Bu, manşon belirtisidir ve lipödem lehinedir."),
    ("2 — BASTIRIN","Uyluk veya baldırınıza orta şiddette bastırdığınızda ağrı hissediyor musunuz? Lipödemde bu hassasiyet tipiktir; basit yağlanmada yoktur."),
    ("3 — SİMETRİYE BAKIN","İki bacak birbirine benzer şekilde mi etkilenmiş? Lipödem simetriktir; belirgin tek taraflılık lenfödemi düşündürür."),
    ("4 — KİLO GEÇMİŞİNİZİ DÜŞÜNÜN","Kilo verdiğinizde yüzünüz, kollarınız ve beliniz incelirken bacaklarınız aynı mı kalıyor? Bu direnç lipödemin ayırt edici özelliğidir.")]),
   ("note","Bu sorular hekim muayenesinin yerini tutmaz. Amaçları, yıllardır \"kilo problemi\" olarak açıklanan bir tablonun aslında değerlendirilmesi gereken bir durum olabileceğini fark etmenizi sağlamaktır.")]},
  {"id":"karisan","tag":"Karışan Durumlar","h2":"Lipödemle karışan durumlar","body":[
   ("table",["Durum","Ayırt eden özellik"],[
     ["Obezite","Yağ tüm vücuda yaygın; ağrı yok; kilo verince orantılı azalır"],
     ["Selülit","Yalnızca deri görünümü değişikliği; ağrısız"],
     ["Lenfödem","Genellikle tek taraflı; ayak sırtı ve parmaklar tutulur; Stemmer pozitif"],
     ["Venöz yetmezlik","Bacak kaldırınca hızla geçer; varis eşlik eder"],
     ["Kalp/böbrek ödemi","Gode bırakır; sistemik hastalık vardır"]]),
   "Lenfödemle karşılaştırmalı tablo için <a href=\"lenfodem-belirtileri.html\">lenfödem belirtileri sayfamıza</a> bakabilirsiniz."]},
  {"id":"nezaman","tag":"Ne Zaman Başvurmalı","h2":"Ne zaman hekime başvurmalısınız?","body":[
   ("ul",["Bacaklarınızda dokunmakla ağrı varsa",
          "Kilo verme çabalarınıza rağmen bölgesel birikim değişmiyorsa",
          "Kolay morarıyorsanız",
          "Bacaklarınız üst bedeninizle orantısızsa",
          "Yürürken uyluklarınızın sürtünmesi günlük yaşamınızı etkiliyorsa",
          "Ailenizde benzer vücut yapısı varsa"]),
   ("note","Lipödem tanısı için kan testi veya kesin bir görüntüleme yöntemi yoktur; tanı kliniktir. Bu nedenle şikâyetlerinizi ayrıntılı anlatabilmeniz — özellikle ağrının varlığını — tanının en kritik parçasıdır.")]}],
 "faqs":[
  ("Lipödem nasıl anlaşılır?","Dört bulgu birlikte değerlendirilir: dokunmakla ağrı, simetri, ayakların korunması (manşon belirtisi) ve kilo vermeye direnç. Bu dörtlü bir aradaysa lipödem güçlü şekilde düşünülür."),
  ("Manşon belirtisi nedir?","Şişliğin bilekte keskin biçimde bitmesi ve ayakların normal kalmasıdır. Lipödemin en tipik bulgusudur ve lenfödemden ayıran en pratik özelliktir — lenfödemde şişlik ayak sırtına ve parmaklara uzanır."),
  ("Lipödemde neden kolay morarıyorum?","Etkilenen dokuda küçük damarların geçirgenliği artmıştır ve kılcal damarlar daha kırılgandır. Bu nedenle hatırlanmayan küçük darbelerde bile morluk oluşabilir."),
  ("Bacaklarım ağrıyor, lipödem mi?","Dokunmakla ağrı lipödemin en ayırt edici bulgusudur, ancak tek başına tanı koydurmaz. Simetri, ayakların korunması ve kilo verme yanıtı birlikte değerlendirilmelidir."),
  ("Lipödem tanısı için hangi test yapılır?","Kesin tanı koyduran bir kan testi veya görüntüleme yöntemi yoktur; tanı klinik muayene ve öyküyle konur. Görüntüleme, lenfatik tutulum şüphesinde veya ayırıcı tanı için kullanılır."),
  ("Erken evrede belirti olur mu?","Evet, ancak siliktir: gün sonu ağırlık hissi, beklenmedik hassasiyet, nedeni hatırlanmayan morluklar ve pantolonun üst bedene göre dar gelmesi. Bu dönem genellikle kilo alımına bağlanır ve atlanır.")],
 "related":["lipodem-nedir","lipodem","lipodem-evreleri","lenfodem-belirtileri"],
 "ctah":"Belirtilerinizi değerlendirelim",
 "ctap":"Şikâyetlerinizin ne zaman başladığını, ağrının şiddetini ve kilo verme deneyimlerinizi yazın; mümkünse bacaklarınızın önden ve yandan fotoğrafını ekleyin."},

{"key":"lipodem-hangi-doktor",
 "slug":"lipodem-hangi-doktor-bakar.html",
 "prio":0.9,
 "crumb":"Lipödeme Hangi Doktor Bakar",
 "title":"Lipödeme Hangi Doktor Bakar? Hangi Bölüme Gitmeli | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lipödeme Hangi Doktor Bakar?",
 "desc":"Lipödem için hangi bölüme başvurmalı? Plastik cerrahi, fizik tedavi ve diğer branşların rolleri, cerrah seçerken nelere dikkat etmeli ve randevu hazırlığı.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Lipödeme hangi doktor bakar?",
 "lead":"Lipödem hastalarının çoğu doğru bölüme yıllar sonra ulaşıyor. Arada diyetisyenler, endokrinologlar ve estetik merkezleri var; ortak nokta ise tablonun kilo problemi sanılması. Bu sayfa doğrudan yol tarif ediyor.",
 "watopic":"lipödem için doğru bölüm",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Hangi doktor bakar?","cardsub":"Lipödemde doğru branşa yönlendirme",
 "procedure":{"name":"Lipödem Cerrahi Değerlendirme",
   "how":"Plastik ve rekonstrüktif cerrahi, lenfatik yapıları koruyan liposuction teknikleriyle hastalıklı yağ dokusunu uzaklaştırır.",
   "prep":"Evreleme, ayırıcı tanı ve gerektiğinde lenfatik görüntüleme.",
   "follow":"Fizyoterapi ile birlikte yürütülen uzun dönem takip.",
   "body":"Bacaklar, kalçalar, kollar"},
 "keyfacts":[("Cerrahi tedavi","Plastik ve Rekonstrüktif Cerrahi"),
             ("Konservatif tedavi","Fiziksel Tıp ve Rehabilitasyon"),
             ("Önemli","Her liposuction lipödem cerrahisi değildir"),
             ("İdeal","İki branşın birlikte çalışması")],
 "authority":"Lipödem cerrahisi ile estetik liposuction farklı işlerdir. Lipödemde öncelik lenfatik sistemi korumaktır; bu, lenfatik anatomiyle çalışan bir cerrah gerektirir. Doç. Dr. Acartürk hem lipödem cerrahisi hem de lenfödem mikrocerrahisi yapmaktadır ve Pittsburgh Üniversitesi'nde yağ dokusu teknolojileri üzerine çalışmıştır.",
 "creds":["Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım",
          "Pittsburgh Üniversitesi'nde yağ dokusu ve kök hücre araştırmaları",
          "Lenfatik koruyucu liposuction deneyimi"],
 "sections":[
  {"id":"kisa","tag":"Kısa Cevap","h2":"Kısa cevap","body":[
   "Lipödemde iki branş rol alır:",
   ("ul",["<strong>Plastik ve Rekonstrüktif Cerrahi</strong> — cerrahi tedaviyi yürütür. Lenfatik koruyucu liposuction (WAL, PAL) bu branşın alanıdır.",
          "<strong>Fiziksel Tıp ve Rehabilitasyon</strong> — konservatif tedaviyi yürütür. Bası giysisi planlaması, manuel lenf drenajı ve egzersiz programı bu branşta düzenlenir."]),
   ("note","Bu iki branş birbirinin alternatifi değildir. Konservatif tedavi ameliyat sonrasında da devam eder; cerrahi ise konservatif tedavinin yetmediği noktada devreye girer.")]},
  {"id":"hangi-durumda","tag":"Yönlendirme","h2":"Hangi durumda hangi hekime?","body":[
   ("table",["Durumunuz","Başvurulacak bölüm"],[
     ["Tanı konmamış, bacaklarda ağrılı şişlik","Plastik cerrahi veya fizik tedavi — lipödemle ilgilenen hekim"],
     ["Tanı kondu, ağrı günlük yaşamı etkiliyor","Plastik ve rekonstrüktif cerrahi — cerrahi adaylık değerlendirmesi"],
     ["Konservatif tedavi görüyor, yeterli gelmiyor","Plastik ve rekonstrüktif cerrahi"],
     ["Bası giysisi ve fizyoterapi planı gerekiyor","Fiziksel Tıp ve Rehabilitasyon"],
     ["Lenfatik tutulum şüphesi (ayaklarda da şişlik)","Lenfödem cerrahisi yapan plastik cerrah"],
     ["Hormonal bozukluk şüphesi","Endokrinoloji — eşlik eden durumlar için"]]),
   ("note","Endokrinoloji ve beslenme uzmanları lipödemde destekleyici rol oynar, ancak hastalığın kendisini tedavi etmez. Diyetle geçmeyen bir tablonun tek başına diyetisyene yönlendirilmesi, tanı gecikmesinin en sık nedenidir.")]},
  {"id":"cerrah-secimi","tag":"Cerrah Seçimi","h2":"Cerrah seçerken nelere dikkat etmeli?","body":[
   "Bu, lipödemde en kritik konudur: <strong>her liposuction lipödem cerrahisi değildir.</strong> Estetik amaçlı liposuction hacim küçültmeye odaklanır; lipödem cerrahisinde ise öncelik lenfatik sistemi korumaktır. Yanlış teknikle yapılan bir işlem lenfatik yapıyı zedeleyip tabloyu ağırlaştırabilir.",
   ("h3","Sorulması makul sorular"),
   ("ul",["Lipödem cerrahisinde hangi tekniği kullanıyorsunuz? (WAL, PAL)",
          "Lenfatik yapıları korumak için nasıl bir yaklaşım izliyorsunuz?",
          "Kaç seans gerekecek ve neden?",
          "Ameliyat sonrası bası giysisi ve fizyoterapi planı nedir?",
          "Lenfödem cerrahisi de yapıyor musunuz?",
          "Gerçekçi beklenti nedir — hastalık geçecek mi, şikâyetler mi azalacak?"]),
   ("note","\"Lipödem tamamen geçer\" ifadesi uyarı işaretidir. Cerrahi hastalıklı yağ dokusunu azaltır, hastalığı ortadan kaldırmaz. Dürüst bir değerlendirme; ağrının azalması, hareketin artması ve hacmin küçülmesi gibi ölçülebilir hedefler üzerinden konuşur.")]},
  {"id":"hazirlik","tag":"Hazırlık","h2":"Randevuya nasıl hazırlanmalısınız?","body":[
   ("ul",["<strong>Şikâyet geçmişi:</strong> ne zaman başladı, hangi dönemde (ergenlik, gebelik, menopoz)",
          "<strong>Ağrı tarifi:</strong> ne sıklıkta, ne şiddette, neyle artıyor",
          "<strong>Kilo geçmişi:</strong> denediğiniz diyetler ve bacaklardaki yanıt",
          "<strong>Aile öyküsü:</strong> annede, kız kardeşte, teyzede benzer yapı var mı",
          "<strong>Önceki tedaviler:</strong> bası giysisi, lenf drenajı, daha önce liposuction",
          "<strong>Fotoğraflar:</strong> önden, yandan ve arkadan; mümkünse zaman içindeki değişimi gösteren",
          "<strong>Boy ve kilo bilgisi</strong>"]),
   ("note","Ağrının varlığını ve şiddetini net anlatabilmek çok önemlidir. Lipödemi basit yağlanmadan ayıran temel bulgu budur ve tanı büyük ölçüde bu bilgiye dayanır.")]}],
 "faqs":[
  ("Lipödeme hangi doktor bakar?","Cerrahi tedavi için Plastik ve Rekonstrüktif Cerrahi, konservatif tedavi için Fiziksel Tıp ve Rehabilitasyon. İkisi birbirini tamamlar."),
  ("Diyetisyene gitmem gerekir mi?","Beslenme desteği yararlıdır — kilo kontrolü lipödem şikâyetlerini hafifletir. Ancak lipödem diyetle geçmez. Tek başına diyetisyene yönlendirilmek, tanı gecikmesinin en sık nedenidir."),
  ("Her plastik cerrah lipödem ameliyatı yapar mı?","Hayır. Lipödem cerrahisi, lenfatik yapıları koruyan tekniklere (WAL, PAL) hâkim olmayı gerektirir. Estetik liposuction ile aynı işlem değildir; cerrahın bu alandaki deneyimini sormak makuldür."),
  ("Endokrinoloğa gitmeli miyim?","Hormonal bir bozukluk şüphesi varsa evet. Ancak lipödemin kendisi hormonal bir hastalık değildir; endokrinoloji eşlik eden durumlar için değerlendirir."),
  ("Devlet hastanesinde yapılıyor mu?","Bazı üniversite ve eğitim-araştırma hastanelerinde lipödem cerrahisi uygulanmaktadır. Merkez sayısı sınırlıdır; başvurmadan önce teyit etmek zaman kazandırır."),
  ("Ameliyat için hangi evrede başvurmalıyım?","Ağrı günlük yaşamınızı etkiliyorsa, hareket kısıtlanmaya başladıysa veya konservatif tedaviye rağmen ilerleme varsa değerlendirme zamanı gelmiştir. İleri evreyi beklemek gerekmez.")],
 "related":["lipodem-nedir","lipodem","ameliyatsiz-lipodem-tedavisi","lenfodem-hangi-doktor"],
 "ctah":"Doğru değerlendirme için ilk adım",
 "ctap":"Şikâyetlerinizin süresini, ağrının şiddetini ve denediğiniz tedavileri yazın; mümkünse fotoğraf ekleyin."},

{"key":"ameliyatsiz-lipodem-tedavisi",
 "slug":"ameliyatsiz-lipodem-tedavisi.html",
 "prio":0.9,
 "crumb":"Ameliyatsız Lipödem Tedavisi",
 "title":"Ameliyatsız Lipödem Tedavisi: Ne İşe Yarar, Ne Yaramaz | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Ameliyatsız Lipödem Tedavisi",
 "desc":"Ameliyatsız lipödem tedavisi mümkün mü? Bası giysisi, lenf drenajı, egzersiz ve beslenmenin gerçek etkisi — ve cerrahinin ne zaman gerektiği.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Ameliyatsız lipödem tedavisi",
 "lead":"Bu sorunun dürüst cevabı şu: ameliyatsız yöntemler lipödemi ortadan kaldırmaz, ama şikâyetleri belirgin azaltır ve hastalığın ilerlemesini yavaşlatır. Bu sayfa, neyin gerçekten işe yaradığını ve cerrahinin hangi noktada gerektiğini anlatıyor.",
 "watopic":"ameliyatsız lipödem tedavisi",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Ameliyatsız tedavi","cardsub":"Konservatif yöntemler ve gerçekçi beklentiler",
 "procedure":{"name":"Lipödemde Konservatif Tedavi",
   "how":"Bası giysisi, manuel lenf drenajı, düzenli hareket ve beslenme düzeni birlikte uygulanarak ağrı ve ödem kontrol altına alınır, ilerleme yavaşlatılır.",
   "prep":"Evreleme ve doğru basınç sınıfında giysi ölçüsü.",
   "follow":"Düzenli takip ve tedaviye yanıtın değerlendirilmesi.",
   "body":"Bacaklar, kalçalar, kollar"},
 "keyfacts":[("Gerçekçi hedef","Ağrıyı azaltmak, ilerlemeyi yavaşlatmak"),
             ("Yapamadığı","Hastalıklı yağ dokusunu ortadan kaldırmak"),
             ("En etkili","Bası giysisi + düzenli hareket"),
             ("Cerrahi zamanı","Ağrı ve hareket kısıtlılığı sürüyorsa")],
 "authority":"Konservatif tedavinin sınırlarını dürüstçe anlatmak, hem gereksiz ameliyatı hem de gereksiz beklemeyi önler. Doç. Dr. Acartürk hem lipödem cerrahisi hem de lenfödem mikrocerrahisi yapan bir cerrah olarak, hangi hastanın hangi yaklaşımdan fayda göreceğini birlikte değerlendirir.",
 "creds":["Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım",
          "Pittsburgh Üniversitesi'nde yağ dokusu ve kök hücre araştırmaları",
          "Lenfatik koruyucu liposuction deneyimi"],
 "sections":[
  {"id":"gercek","tag":"Gerçekçi Çerçeve","h2":"Ameliyatsız tedavi ne yapar, ne yapmaz?","body":[
   "Bu ayrımı baştan netleştirmek gerekir, çünkü beklenti yönetimi tedavinin bir parçasıdır.",
   ("table",["Ameliyatsız tedavi ne yapar","Ne yapmaz"],[
     ["Ağrıyı ve hassasiyeti azaltır","Hastalıklı yağ dokusunu ortadan kaldırmaz"],
     ["Ödemi kontrol altına alır","Bacak şeklini kalıcı değiştirmez"],
     ["İlerlemeyi yavaşlatır","Hastalığı geri döndürmez"],
     ["Lenfatik yükü hafifletir","Orantısızlığı düzeltmez"],
     ["Hareket kabiliyetini korur","Evre gerilemesi sağlamaz"]]),
   ("note","Bu bir başarısızlık tablosu değil. Konservatif tedavi, lipödem yönetiminin temelidir ve ameliyat olan hastalarda da ömür boyu devam eder. Cerrahi, konservatif tedavinin yerine geçmez — yetmediği noktada devreye girer.")]},
  {"id":"basi","tag":"Bası Giysisi","h2":"Bası giysisi (kompresyon)","body":[
   "Konservatif tedavinin en etkili bileşenidir. Doku basıncını artırarak ödem birikimini azaltır, ağrıyı hafifletir ve gün içindeki hacim dalgalanmasını kontrol eder.",
   ("ul",["<strong>Düz örgü (flat knit)</strong> giysiler lipödemde genellikle tercih edilir — daha sert yapıları nedeniyle doku desteği daha iyidir",
          "<strong>Basınç sınıfı</strong> hekim tarafından belirlenmelidir; yanlış sınıf ya etkisiz kalır ya da rahatsızlık yaratır",
          "<strong>Ölçüye özel üretim</strong> hazır bedene göre çok daha etkilidir",
          "<strong>Düzenli kullanım</strong> aralıklı kullanımdan belirgin şekilde üstündür",
          "<strong>6 ayda bir yenilenmesi</strong> önerilir — esneklik zamanla kaybolur"]),
   ("note","Bası giysisi çoğu hastanın en zorlandığı bileşendir; özellikle sıcak havalarda. Ancak düzenli kullanım, konservatif tedaviden fayda görüp görmeyeceğinizi belirleyen en önemli faktördür.")]},
  {"id":"drenaj","tag":"Lenf Drenajı","h2":"Manuel lenf drenajı ve fizyoterapi","body":[
   "Manuel lenf drenajı, lenf akımını destekleyen özel bir masaj tekniğidir. Lipödemde ödem bileşenini azaltır ve rahatlama sağlar.",
   ("ul",["Ödem ve gerginlik hissini azaltır",
          "Ağrı eşiğini yükseltebilir",
          "Bası giysisi ile birlikte uygulandığında etkisi artar",
          "Tek başına kalıcı hacim değişikliği sağlamaz"]),
   ("note","Manuel lenf drenajı lipödemde yağ dokusunu azaltmaz. Faydası ödem ve rahatlama üzerinedir. Bu nedenle tek başına bir tedavi olarak sunulması doğru değildir; bası giysisi ve hareketle birlikte anlamlıdır.")]},
  {"id":"egzersiz","tag":"Egzersiz","h2":"Egzersiz: hangi tür, neden?","body":[
   "Egzersiz lipödemde kilo vermek için değil, <strong>lenf akımını desteklemek ve eklemleri korumak</strong> için önemlidir. Doğru tür seçimi burada belirleyicidir.",
   ("h3","Önerilen egzersizler"),
   ("ul",["<strong>Su içi egzersiz ve yüzme:</strong> suyun hidrostatik basıncı doğal bir kompresyon sağlar — lipödemde en çok önerilen egzersiz türüdür",
          "<strong>Yürüyüş:</strong> baldır kası pompası lenf akımını destekler",
          "<strong>Bisiklet:</strong> eklem yükü düşük, kas pompası etkili",
          "<strong>Pilates ve esneme:</strong> hareket açıklığını korur"]),
   ("h3","Dikkat edilmesi gerekenler"),
   ("ul",["Yüksek darbeli aktiviteler (koşu, zıplama) ağrıyı artırabilir",
          "Aşırı ağırlık çalışması hassasiyeti tetikleyebilir",
          "Egzersiz sırasında bası giysisi kullanmak faydalıdır",
          "Ağrı sınırında değil, ağrı öncesinde durmak esastır"]),
   ("note","Lipödemde egzersizin amacı bacakları inceltmek değildir — bu gerçekçi bir hedef değil. Amaç lenf akımını desteklemek, eklem sağlığını korumak ve hareket kabiliyetini sürdürmektir.")]},
  {"id":"beslenme","tag":"Beslenme","h2":"Beslenmenin rolü","body":[
   "Lipödemi ortadan kaldıran bir diyet yoktur. Ancak beslenme düzeninin iki gerçek katkısı vardır: <strong>kilo kontrolü lenfatik yükü azaltır</strong> ve <strong>inflamasyonu azaltan bir düzen şikâyetleri hafifletebilir</strong>.",
   ("ul",["Stabil kilo, lipödemin ilerlemesini yavaşlatan faktörlerden biridir",
          "İşlenmiş gıda ve aşırı tuz azaltıldığında ödem hissi azalabilir",
          "Yeterli protein ve su alımı doku sağlığı için önemlidir",
          "Aşırı kısıtlayıcı diyetler lipödemde hedefe ulaştırmaz ve sürdürülemez"]),
   ("note","Lipödemde katı ve kısıtlayıcı diyet döngüleri sık görülür ve çoğu zaman hayal kırıklığıyla sonuçlanır — çünkü hastalıklı yağ dokusu bu çabaya yanıt vermez. Sürdürülebilir bir beslenme düzeni, agresif diyetlerden hem daha etkili hem de daha sağlıklıdır. Ayrıntılı bilgi için <a href=\"lipodem-diyeti.html\">lipödem ve beslenme sayfamıza</a> bakabilirsiniz.")]},
  {"id":"cerrahi","tag":"Cerrahi Ne Zaman","h2":"Cerrahi ne zaman gündeme gelir?","body":[
   "Konservatif tedavi düzenli uygulanmasına rağmen şu durumlar sürüyorsa cerrahi değerlendirme zamanı gelmiştir:",
   ("ul",["Ağrı günlük yaşamı etkilemeye devam ediyorsa",
          "Uyluk sürtünmesi yürüyüşü ve duruşu bozuyorsa",
          "Hareket kısıtlılığı ilerliyorsa",
          "Diz ve kalça eklemlerine binen yük şikâyet yaratıyorsa",
          "Bası giysisine rağmen evre ilerliyorsa",
          "Yaşam kalitesi belirgin düşmüşse"]),
   ("note","Cerrahi için ileri evreyi beklemek gerekmez. Aksine, doku fibrozlaşmadan yapılan müdahale hem teknik olarak daha kolaydır hem de sonuç daha iyidir. Konservatif tedaviyi denemiş ve fayda görmemiş bir hastanın beklemesi için tıbbi bir gerekçe yoktur.")]}],
 "faqs":[
  ("Lipödem ameliyatsız geçer mi?","Hayır. Ameliyatsız yöntemler ağrıyı azaltır, ödemi kontrol eder ve ilerlemeyi yavaşlatır — ancak hastalıklı yağ dokusunu ortadan kaldırmaz. Bu dürüst çerçeveyi baştan bilmek, doğru karar vermenizi sağlar."),
  ("En etkili ameliyatsız yöntem hangisi?","Düzenli kullanılan bası giysisi ve düzenli hareket. Bu ikisi birlikte uygulandığında ağrı ve ödem üzerindeki etki en belirgindir. Manuel lenf drenajı bunlara ek olarak fayda sağlar."),
  ("Lenf drenajı lipödemi geçirir mi?","Hayır. Manuel lenf drenajı ödem bileşenini azaltır ve rahatlama sağlar, ancak yağ dokusunu azaltmaz. Tek başına bir tedavi olarak sunulması doğru değildir."),
  ("Egzersizle bacaklarım incelir mi?","Lipödemde bu gerçekçi bir hedef değildir. Hastalıklı yağ dokusu egzersize direnç gösterir. Egzersizin amacı lenf akımını desteklemek, eklemleri korumak ve hareket kabiliyetini sürdürmektir."),
  ("Bası giysisini sürekli mi kullanmalıyım?","Düzenli kullanım aralıklı kullanımdan belirgin şekilde etkilidir. Günlük kullanım önerilir; sıcak havalarda zorlayıcı olabilir ancak tedaviden fayda görmenin en önemli koşuludur."),
  ("Ne kadar süre ameliyatsız devam etmeliyim?","Belirli bir süre kuralı yoktur. Düzenli uygulanan konservatif tedaviye rağmen ağrı ve hareket kısıtlılığı sürüyorsa cerrahi değerlendirme zamanı gelmiştir. İleri evreyi beklemek gerekmez.")],
 "related":["lipodem-nedir","lipodem","lipodem-diyeti","lipodem-hangi-doktor"],
 "ctah":"Hangi yaklaşımın size uygun olduğunu konuşalım",
 "ctap":"Şu an uyguladığınız tedavileri, ne kadar süredir devam ettiğini ve ağrınızın günlük yaşamınızı nasıl etkilediğini yazın."},

{"key":"lipodem-diyeti",
 "slug":"lipodem-diyeti.html",
 "prio":0.85,
 "crumb":"Lipödem ve Beslenme",
 "title":"Lipödem Diyeti: Beslenmenin Gerçek Rolü | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lipödem ve Beslenme: Neyin Faydası Var?",
 "desc":"Lipödemde beslenmenin rolü nedir? Diyet lipödemi geçirir mi, hangi yaklaşımlar şikâyetleri hafifletir ve kısıtlayıcı diyetlerin neden işe yaramadığı.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Lipödem ve beslenme",
 "lead":"Lipödemi ortadan kaldıran bir diyet yok. Bunu baştan söylemek gerekiyor, çünkü bu hastalıkta en çok tekrarlanan deneyim şu: yıllarca süren diyetler, düşen kilolar ve hiç değişmeyen bacaklar. Ama beslenmenin gerçek ve ölçülebilir bir katkısı var — sadece beklendiği yerde değil.",
 "watopic":"lipödemde beslenme",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Lipödem ve beslenme","cardsub":"Beslenmenin gerçek katkısı ve sınırları",
 "procedure":{"name":"Lipödemde Beslenme Yaklaşımı",
   "how":"Sürdürülebilir bir beslenme düzeni ile stabil kilo sağlanır, lenfatik yük azaltılır ve inflamatuar yanıt hafifletilir.",
   "prep":"Mevcut beslenme alışkanlıklarının ve kilo geçmişinin değerlendirilmesi.",
   "follow":"Sürdürülebilirlik odaklı takip.",
   "body":"Genel"},
 "keyfacts":[("Diyet ne yapar","Lenfatik yükü azaltır, şikâyetleri hafifletir"),
             ("Ne yapmaz","Hastalıklı yağ dokusunu eritmez"),
             ("Öncelik","Sürdürülebilirlik, kısıtlama değil"),
             ("Uyarı","Katı diyet döngüleri fayda getirmez")],
 "authority":"Beslenmenin lipödemdeki rolünü abartmak da küçümsemek de hastaya zarar verir. Doç. Dr. Acartürk, yağ dokusu biyolojisi üzerine Pittsburgh Üniversitesi'nde araştırma yapmış bir cerrah olarak, bu dokunun neden diyete direnç gösterdiğini hastasına açıklayabilecek konumdadır.",
 "creds":["Pittsburgh Üniversitesi'nde yağ dokusu ve kök hücre araştırmaları",
          "Carnegie Mellon Üniversitesi'nde doku mühendisliği doktora sonrası çalışması",
          "Lipödem ve lenfödemde birleşik değerlendirme yaklaşımı"],
 "sections":[
  {"id":"neden-direnc","tag":"Neden Direnç","h2":"Lipödem yağı neden diyete direnç gösterir?","body":[
   "Bu sorunun cevabı, hastaların yıllarca duydukları suçlamayı geçersiz kılar.",
   "Vücuttaki yağ dokusu tek tip değildir. Lipödemde etkilenen dokuda hücre yapısı, damarlanma ve inflamatuar aktivite normal yağ dokusundan farklıdır. Kalori kısıtlaması vücudun genel yağ deposunu azaltır — ama bu bölgesel, hastalıklı dokuya aynı ölçüde etki etmez.",
   "Pratikte görülen tablo şudur: hasta kilo verir, <strong>yüzü, kolları ve beli incelir</strong>, bacakları büyük ölçüde aynı kalır. Hatta orantısızlık daha belirgin hale gelebilir.",
   ("note","Bu, diyetin işe yaramadığı anlamına gelmez — hedefin yanlış konduğu anlamına gelir. Bacakları inceltmek beslenmenin hedefi olamaz. Ama lenfatik yükü azaltmak ve şikâyetleri hafifletmek olabilir.")]},
  {"id":"gercek-katki","tag":"Gerçek Katkı","h2":"Beslenmenin gerçek katkısı","body":[
   ("ul",["<strong>Lenfatik yükün azalması:</strong> vücut kitle indeksinin düşmesi lenfatik sistemin taşıma yükünü doğrudan hafifletir. Bu, özellikle lipo-lenfödeme ilerlemiş hastalarda önemlidir.",
          "<strong>Ödem hissinin azalması:</strong> aşırı tuz ve işlenmiş gıda kısıtlandığında gün içi şişkinlik hissi azalabilir",
          "<strong>Eklem yükünün hafiflemesi:</strong> diz ve kalça eklemlerine binen yük azalır",
          "<strong>Ameliyat sonucunun iyileşmesi:</strong> stabil kilo, cerrahi sonrası sonucun korunmasında belirleyicidir",
          "<strong>İlerlemenin yavaşlaması:</strong> kilo artışı lipödemi ağırlaştıran faktörlerden biridir"]),
   ("note","Beslenmenin katkısı gerçektir ancak dolaylıdır. Doğrudan hastalıklı dokuyu değil, o dokunun üzerindeki yükü ve çevresel koşulları iyileştirir.")]},
  {"id":"yaklasim","tag":"Yaklaşım","h2":"Hangi beslenme yaklaşımı?","body":[
   "Lipödem için kanıtlanmış ve standartlaşmış tek bir diyet protokolü bulunmamaktadır. Literatürde inflamasyonu azaltmaya yönelik yaklaşımlar üzerinde durulmakla birlikte, kanıt düzeyi henüz kesin öneri yapmaya yeterli değildir.",
   ("h3","Makul ve sürdürülebilir ilkeler"),
   ("ul",["Yeterli protein alımı — doku sağlığı ve tokluk için",
          "İşlenmiş gıda ve rafine şekerin azaltılması",
          "Aşırı tuzun sınırlanması — ödem hissini etkiler",
          "Yeterli su tüketimi",
          "Sebze ve lif ağırlıklı bir düzen",
          "Öğün düzeninin korunması"]),
   ("h3","Kaçınılması gerekenler"),
   ("ul",["Çok düşük kalorili, uzun süreli kısıtlayıcı diyetler",
          "Tek besin grubuna dayanan diyetler",
          "\"Lipödem eritir\" iddiasıyla satılan takviyeler",
          "Hızlı sonuç vaat eden ve sürdürülemez programlar"]),
   ("note","Beslenme düzenlemesi bir diyetisyenle birlikte, kişiye özel planlanmalıdır. Bu sayfa genel bir çerçeve sunar; bireysel plan yerine geçmez.")]},
  {"id":"psikoloji","tag":"Önemli Not","h2":"Diyet döngüsü ve kendinize yaklaşımınız","body":[
   "Lipödem hastalarının çoğu yıllarca \"yeterince çabalamamakla\" suçlanmış, bu suçlamayı bir süre sonra kendileri de içselleştirmiştir. Tekrarlayan diyet başarısızlıkları — ki bunlar aslında başarısızlık değil, yanlış hedefin sonucudur — bu duyguyu derinleştirir.",
   "Şunu net söylemek gerekir: <strong>bacaklarınızın diyete yanıt vermemesi iradenizle ilgili değildir.</strong> Bu, hastalığın tanımlayıcı özelliğidir. Doğru tanı konduğunda birçok hasta için en büyük rahatlama, tedaviden önce bu bilgiyi öğrenmek olur.",
   ("note","Yeme düzeninizle ilgili zorlanıyorsanız veya vücudunuzla ilişkiniz sizi yıpratıyorsa, bunu değerlendirmenizde paylaşmaktan çekinmeyin. Lipödem tedavisi yalnızca dokuyla ilgili değildir; bu süreç uzun yıllara yayılan bir deneyimin parçasıdır ve destek almak yerinde olur.")]}],
 "faqs":[
  ("Lipödem diyetle geçer mi?","Hayır. Hastalıklı yağ dokusu kalori kısıtlamasına direnç gösterir. Kilo verdiğinizde üst bedeniniz incelir, bacaklarınız büyük ölçüde aynı kalır. Bu, iradeyle değil hastalığın doğasıyla ilgilidir."),
  ("O halde diyetin faydası var mı?","Evet, ama dolaylı. Stabil kilo lenfatik yükü azaltır, eklem yükünü hafifletir, ödem hissini düşürür ve hastalığın ilerlemesini yavaşlatır. Ayrıca ameliyat sonucunun korunmasında belirleyicidir."),
  ("Lipödem için özel bir diyet var mı?","Kanıtlanmış ve standartlaşmış tek bir protokol yoktur. İnflamasyonu azaltmaya yönelik yaklaşımlar araştırılmaktadır ancak kanıt düzeyi kesin öneri için henüz yeterli değildir. Sürdürülebilir ve dengeli bir düzen en makul yaklaşımdır."),
  ("Ketojenik diyet lipödemde işe yarar mı?","Bazı hastalar şikâyetlerinde azalma bildirmektedir ve konu araştırılmaktadır, ancak lipödem için kesin öneri yapılmasını sağlayacak kanıt düzeyi henüz oluşmamıştır. Uygulanacaksa mutlaka hekim ve diyetisyen gözetiminde olmalıdır."),
  ("Lipödemi eriten takviyeler var mı?","Hayır. Bu iddiayla satılan ürünlerin lipödem üzerinde kanıtlanmış etkisi bulunmamaktadır. Bu ürünlere harcanan zaman, doğru tanı ve tedavinin gecikmesine yol açar."),
  ("Ameliyat sonrası diyet önemli mi?","Evet, çok. Alınan yağ dokusu geri gelmez ancak kalan dokudaki hücreler kilo alımıyla büyüyebilir. Stabil kilo, cerrahi sonucun korunmasındaki en önemli faktördür.")],
 "related":["lipodem-nedir","ameliyatsiz-lipodem-tedavisi","lipodem","lipodem-belirtileri"],
 "ctah":"Beslenme ve tedavi planınızı konuşalım",
 "ctap":"Kilo geçmişinizi, denediğiniz diyetleri ve bacaklarınızda gözlemlediğiniz yanıtı yazın."},

{"key":"lipodem-evreleri",
 "slug":"lipodem-evreleri.html",
 "prio":0.85,
 "crumb":"Lipödem Evreleri",
 "title":"Lipödem Evreleri: Evre 1-4 ve Tedavi Karşılığı | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lipödem Evreleri ve Tipleri",
 "desc":"Lipödem evreleri nelerdir? Evre 1, 2, 3 ve 4 bulguları, tutulum tipleri, evrelemenin nasıl yapıldığı ve her evrede uygun tedavi.",
 "eyebrow":"Mikrocerrahi Programı",
 "h1":"Lipödem evreleri",
 "lead":"Lipödemde evre, deri yüzeyinin ve yağ dokusunun durumunu tanımlar. Ancak tedavi kararı yalnızca evreye değil, ağrının şiddetine ve hareket kısıtlılığına da bakar — Evre 1'de bile yaşam kalitesi belirgin etkilenmiş olabilir.",
 "watopic":"lipödem evrelemesi",
 "about":"Lipödem",
 "aboutType":"MedicalCondition",
 "card":"Lipödem evreleri","cardsub":"Evre ve tip sınıflaması, tedavi karşılıkları",
 "procedure":{"name":"Lipödem Evreleme",
   "how":"Deri yüzeyinin görünümü, yağ dokusunun kıvamı, nodüler yapı ve lenfatik tutulum birlikte değerlendirilerek evre belirlenir.",
   "prep":"Muayene, çevre ölçümleri ve gerektiğinde lenfatik görüntüleme.",
   "follow":"Evre ve şikâyet düzeyine uygun tedavi planı.",
   "body":"Bacaklar, kalçalar, kollar"},
 "keyfacts":[("Evre 1","Deri düz, altında ince nodüller"),
             ("Evre 2","Deri düzensiz ve dalgalı"),
             ("Evre 3","Deri kalınlaşmış, büyük yağ lobları"),
             ("Evre 4","Lipo-lenfödem — lenfatik yetmezlik eklenmiş")],
 "authority":"Lipödemde evreleme tedaviyi tek başına belirlemez; ağrı ve fonksiyon kaybı en az evre kadar önemlidir. Doç. Dr. Acartürk, hem lipödem cerrahisi hem de lenfödem mikrocerrahisi yapan bir cerrah olarak lipo-lenfödem geçişini de değerlendirebilmektedir.",
 "creds":["Avrupa Lenfatik Mikrocerrahi Grubu çalışmalarına katılım",
          "Pittsburgh Üniversitesi'nde yağ dokusu ve kök hücre araştırmaları",
          "Dünya Lenfoloji Kongresi'nde bildiri sunumu"],
 "sections":[
  {"id":"evreler","tag":"Evreler","h2":"Lipödem evreleri","body":[
   ("table",["Evre","Deri ve doku","Klinik tablo"],[
     ["Evre 1","Deri yüzeyi düz, altında ince nodüller","Ağrı ve kolay morarma başlamış; şekil değişikliği hafif"],
     ["Evre 2","Deri yüzeyi düzensiz ve dalgalı","Nodüller belirginleşir; bölgesel şişlik ve hassasiyet artar"],
     ["Evre 3","Deri kalınlaşmış, büyük yağ lobları","Hareket kısıtlanır; diz ve kalça eklemleri zorlanır"],
     ["Evre 4","Lipo-lenfödem","Lipödeme lenfatik yetmezlik eklenmiştir; ayaklar da tutulabilir"]]),
   ("note","Evre 4'te önemli bir değişiklik olur: lipödemin ayırt edici özelliği olan <strong>ayakların korunması</strong> ortadan kalkar. Lenfatik yetmezlik eklendiği için şişlik ayak sırtına da uzanabilir ve Stemmer belirtisi pozitifleşebilir. Bu, tedavi planını değiştirir.")]},
  {"id":"tipler","tag":"Tipler","h2":"Tutulum tipleri","body":[
   "Evreden ayrı olarak, lipödem <strong>hangi bölgelerin tutulduğuna</strong> göre de sınıflandırılır. Bu sınıflama cerrahi planlamada doğrudan kullanılır.",
   ("table",["Tip","Tutulan bölge"],[
     ["Tip 1","Kalça ve pelvis çevresi"],
     ["Tip 2","Kalçadan dize kadar"],
     ["Tip 3","Kalçadan ayak bileğine kadar"],
     ["Tip 4","Kollar"],
     ["Tip 5","Yalnızca baldırlar"]]),
   "Tip 3 en sık görülen tablodur. Tip 4 (kol tutulumu) vakaların yaklaşık dörtte birinde bacak tutulumuna eşlik eder ve ayrı planlama gerektirir.",
   ("note","Evre ve tip birlikte değerlendirilir. Örneğin Evre 2 – Tip 3 bir hastada tedavi, Evre 2 – Tip 1 bir hastadan farklı planlanır; işlem sayısı ve sırası buna göre belirlenir.")]},
  {"id":"tedavi","tag":"Evre–Tedavi","h2":"Hangi evrede hangi tedavi?","body":[
   ("table",["Evre","Öncelikli yaklaşım"],[
     ["Evre 1","Konservatif tedavi; ağrı belirginse cerrahi değerlendirme"],
     ["Evre 2","Konservatif tedavi + cerrahi değerlendirme (WAL/PAL)"],
     ["Evre 3","Cerrahi öne çıkar; genellikle birden fazla seans"],
     ["Evre 4","Lenfatik bileşen de ele alınmalı — lipödem cerrahisi + lenfödem yaklaşımı"]]),
   ("note","<strong>Cerrahi için ileri evreyi beklemek gerekmez.</strong> Aksine, doku fibrozlaşmadan yapılan müdahale teknik olarak daha kolaydır ve sonuç daha iyidir. Evre 1'de bile ağrı yaşam kalitesini belirgin etkiliyorsa cerrahi değerlendirme yapılabilir.")]},
  {"id":"ilerleme","tag":"İlerleme","h2":"Evreler arasında geçiş","body":[
   "Lipödem ilerleyici bir hastalıktır, ancak ilerleme hızı kişiden kişiye çok değişir. Bazı hastalar yıllarca aynı evrede kalırken, bazılarında özellikle hormonal geçiş dönemlerinde hızlı ilerleme görülür.",
   ("h3","İlerlemeyi hızlandıran faktörler"),
   ("ul",["Kilo artışı",
          "Hormonal geçiş dönemleri (gebelik, menopoz)",
          "Hareketsizlik",
          "Bası giysisinin düzensiz kullanımı",
          "Tedavisiz geçen süre"]),
   ("h3","İlerlemeyi yavaşlatan faktörler"),
   ("ul",["Düzenli bası giysisi kullanımı",
          "Düzenli hareket — özellikle su içi egzersiz",
          "Stabil kilo",
          "Erken cerrahi müdahale"]),
   ("note","Evre geriye dönmez. Cerrahi ile hastalıklı yağ dokusu azaltılabilir ve şikâyetler belirgin düzelebilir, ancak deri ve doku değişiklikleri kalıcıdır. Bu nedenle erken müdahale yalnızca konfor değil, uzun dönem sonucu da etkiler.")]}],
 "faqs":[
  ("Lipödem kaç evreye ayrılır?","Dört evre tanımlanır. Evre 1'de deri yüzeyi düzdür, Evre 2'de dalgalanır, Evre 3'te kalınlaşır ve büyük yağ lobları oluşur, Evre 4'te ise tabloya lenfatik yetmezlik eklenir (lipo-lenfödem)."),
  ("Evremi nasıl öğrenirim?","Evreleme klinik muayene ile yapılır: deri yüzeyinin görünümü, nodüler yapı, doku kıvamı ve ayak tutulumu değerlendirilir. Fotoğraftan kesin evreleme yapmak doğru değildir."),
  ("Hangi evrede ameliyat olunur?","Evre tek başına belirleyici değildir. Ağrı ve hareket kısıtlılığı yaşam kalitesini etkiliyorsa Evre 1'de bile cerrahi değerlendirme yapılabilir. İleri evreyi beklemek için tıbbi bir gerekçe yoktur."),
  ("Evre 4 ne demek?","Lipödeme lenfatik yetmezliğin eklendiği durumdur — lipo-lenfödem. Bu evrede lipödemin ayırt edici özelliği olan ayakların korunması ortadan kalkar. Tedavi planı hem yağ dokusunu hem lenfatik bileşeni ele almalıdır."),
  ("Evre geriye döner mi?","Hayır. Cerrahi ile hastalıklı yağ dokusu azaltılabilir ve şikâyetler belirgin düzelebilir, ancak deri ve doku değişiklikleri kalıcıdır. Bu nedenle erken müdahale önemlidir."),
  ("Tip ne anlama geliyor?","Tip, hangi bölgelerin tutulduğunu tanımlar — kalça, uyluk, baldır, kol. Evre dokunun durumunu, tip ise yayılımı gösterir. İkisi birlikte cerrahi planı belirler.")],
 "related":["lipodem-nedir","lipodem-belirtileri","lipodem","lenfodem-evreleri"],
 "ctah":"Evrenizi birlikte belirleyelim",
 "ctap":"Şikâyetlerinizin süresini, ağrının şiddetini, hangi bölgelerin etkilendiğini ve ayaklarınızda şişlik olup olmadığını yazın; mümkünse fotoğraf ekleyin."},

]
