# -*- coding: utf-8 -*-
"""Estetik cerrahi sayfalari."""

def std_steps(op, gun, is_donus):
    return ("steps",[
     ("1. ADIM — ÖN GÖRÜŞME","WhatsApp veya form üzerinden ilk temas. Beklentiniz, sağlık geçmişiniz ve varsa fotoğraflarınız üzerinden ilk yönlendirme."),
     ("2. ADIM — MUAYENE VE PLANLAMA","Anatominizin değerlendirilmesi, uygulanabilir tekniklerin, risklerin ve gerçekçi beklentilerin açıkça konuşulması."),
     ("3. ADIM — HAZIRLIK","Kan tetkikleri, anestezi değerlendirmesi, sigara ve kan sulandırıcı düzenlemesi."),
     ("4. ADIM — AMELİYAT",op),
     ("5. ADIM — İLK GÜNLER",gun),
     ("6. ADIM — DÖNÜŞ VE TAKİP",is_donus)])

ESTETIK = [
{
 "key":"rinoplasti", "slug":"burun-estetigi-rinoplasti.html", "prio":"0.85",
 "crumb":"Burun Estetiği (Rinoplasti)",
 "title":"Burun Estetiği (Rinoplasti) — Doğal Sonuç ve Nefes Alma | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Burun Estetiği (Rinoplasti): İşlevsel ve Estetik Cerrahi",
 "desc":"Rinoplasti nedir, açık ve kapalı teknik farkı, septum eğriliği ile birlikte tedavi, iyileşme süreci ve revizyon rinoplasti hakkında bilinmesi gerekenler.",
 "eyebrow":"Estetik Cerrahi",
 "h1":"Burun estetiği (rinoplasti)",
 "lead":"İyi bir rinoplasti, ameliyat olduğu anlaşılmayan burundur. Yüzün geri kalanıyla uyumlu, yaşla birlikte doğal biçimde yaşlanan ve en az görünüm kadar nefes almayı da düşünen bir sonuç hedeflenir.",
 "watopic":"burun estetiği (rinoplasti)",
 "about":"Rinoplasti", "aboutType":"MedicalProcedure",
 "card":"Rinoplasti", "cardsub":"İşlevsel ve estetik burun cerrahisi",
 "procedure":{"name":"Rinoplasti",
   "how":"Burun iskeletini oluşturan kemik ve kıkırdak yapılar, açık veya kapalı teknikle yeniden şekillendirilir; gerektiğinde kıkırdak greftleriyle destek eklenir ve septum düzeltilir.",
   "prep":"Muayene, nefes alma değerlendirmesi, fotoğraf analizi ve kan tetkikleri.",
   "follow":"Atel ve tampon bakımı, ödem yönetimi, ilk yıl güneşten korunma.",
   "body":"Burun"},
 "keyfacts":[("Anestezi","Genel anestezi"),("Süre","2–4 saat"),
             ("Sosyal dönüş","7–10 gün"),("Son şekil","12–18 ay")],
 "sections":[
  {"id":"kimler","tag":"Kimler İçin","h2":"Rinoplasti kimler için uygundur?","body":[
   "Rinoplasti, burnun görünümünü ve/veya nefes alma işlevini iyileştirmek için yapılır. En sık başvuru nedenleri:",
   ("ul",["Burun sırtındaki kemik veya kıkırdak çıkıntı (kemer)",
          "Burun ucunun düşük, geniş ya da belirsiz olması",
          "Burnun yüze göre büyük veya küçük görünmesi",
          "Eğrilik ve asimetri",
          "Septum eğriliği ve konka büyümesine bağlı nefes alma güçlüğü",
          "Önceki bir ameliyattan kalan şekil bozukluğu veya nefes sorunu"]),
   "Burun gelişimi kızlarda yaklaşık 16, erkeklerde 17–18 yaşta tamamlanır; ameliyat bu gelişim tamamlandıktan sonra planlanır.",
   ("note","Rinoplasti bir yüz ameliyatıdır, yalnızca burun ameliyatı değil. Çene yapısı, alın eğimi ve yüz oranları birlikte değerlendirilmeden alınan kararlar, teknik olarak başarılı ama yüze yakışmayan sonuçlar üretir.")]},
  {"id":"teknik","tag":"Teknik","h2":"Açık ve kapalı teknik","body":[
   ("h3","Açık rinoplasti"),
   "Burun deliklerini ayıran kolumella bölgesine küçük bir kesi yapılır ve burun cildi kaldırılır. Cerrah tüm iskeleti doğrudan görür; asimetriler, greft yerleşimi ve burun ucu şekillendirmesi daha kontrollü yapılır. Kolumelladaki iz birkaç ay içinde belirsizleşir.",
   ("h3","Kapalı rinoplasti"),
   "Tüm kesiler burun içinde kalır, dışarıda iz olmaz. Ödem daha az ve iyileşme daha hızlıdır. Sınırlı düzeltme gerektiren, iskeleti simetrik burunlarda tercih edilir.",
   ("h3","Koruyucu (preservation) yaklaşım"),
   "Burun sırtının doğal yapısını mümkün olduğunca bozmadan yeniden konumlandırmayı hedefleyen tekniklerdir. Uygun anatomide daha doğal bir sırt hattı ve daha az ödem sağlayabilir.",
   ("note","Teknik seçimi cerrahın alışkanlığına değil, burnunuzun anatomisine göre yapılmalıdır. Revizyon olguları, belirgin asimetriler ve kıkırdak desteği gereken burunlarda açık teknik genellikle daha güvenlidir.")]},
  {"id":"nefes","tag":"İşlev","h2":"Nefes alma ve septum","body":[
   "Burun estetiğinin ayrılmaz parçası nefes almaktır. Görünümü düzeltip nefes alma sorununu göz ardı eden bir ameliyat, hastanın yaşam kalitesini düşürür.",
   ("ul",["<strong>Septum eğriliği:</strong> Burnu ikiye ayıran duvarın eğriliği; aynı seansta düzeltilir (septorinoplasti)",
          "<strong>Konka büyümesi:</strong> Burun içi etli yapıların küçültülmesi",
          "<strong>Nazal valv darlığı:</strong> Burun kanadının içe çökmesi; kıkırdak greftleriyle desteklenir"]),
   "Septumdan alınan kıkırdak aynı zamanda burun ucunu desteklemek için greft olarak kullanılır. Bu, hem işlevi hem şekli tek seansta ele almayı mümkün kılar.",
   ("note","Sağlık sigortası kapsamı, işlemin işlevsel bileşeni olup olmadığına göre değişir. Bu konuyu planlama görüşmesinde netleştirmeniz önerilir.")]},
  {"id":"surec","tag":"Süreç","h2":"İyileşme süreci","body":[
   std_steps("Genel anestezi altında 2–4 saat. Genellikle bir gece hastanede kalınır.",
             "Burun sırtında atel, gerekirse silikon tampon. İlk 48 saat buz ve baş yüksekte yatma. Morarma ve şişlik 3–5. günde en yoğun hâlindedir.",
             "Atel 7. günde alınır; çoğu hasta 7–10 gün içinde sosyal hayata döner. Burun ucundaki ödem 12–18 ay boyunca kademeli çözülür."),
   ("ul",["İlk 6 hafta gözlük burun sırtına oturtulmamalı",
          "İlk 3 hafta ağır egzersiz ve öne eğilmekten kaçınılmalı",
          "İlk yıl güneş koruması ihmal edilmemeli"])]}],
 "faqs":[
  ("Rinoplasti sonrası nefes alma sorunum düzelir mi?","Septum eğriliği, konka büyümesi ya da valv darlığı varsa aynı seansta düzeltilebilir ve nefes almada belirgin iyileşme sağlanır. Bu değerlendirme muayenede yapılır."),
  ("Sonucu ne zaman görürüm?","Şeklin genel hatları atel alındıktan sonra belli olur, ancak burun ucundaki ödem yavaş çözülür. Nihai sonuç için 12–18 ay gerekir; kalın ciltli burunlarda bu süre uzayabilir."),
  ("Açık teknikte iz kalır mı?","Kolumelladaki kesi izi birkaç ay içinde soluklaşır ve normal mesafeden fark edilmez hâle gelir. İz bakımı bu süreçte önemlidir."),
  ("Revizyon rinoplasti ne zaman yapılabilir?","Dokuların yumuşaması ve ödemin tamamen çözülmesi gerektiğinden genellikle ilk ameliyattan en az 12 ay sonra planlanır. Revizyon, ilk ameliyattan teknik olarak daha zordur."),
  ("Ameliyat çok ağrılı mı?","Rinoplasti beklenenden daha az ağrılıdır. Asıl rahatsızlık burun tıkanıklığı hissidir; günümüzde kullanılan hava kanallı silikon tamponlar bu şikâyeti belirgin biçimde azaltır."),
  ("Yaşlandıkça burnum değişir mi?","Her burun yaşlanır. İyi planlanmış bir rinoplastide destek yapıları korunduğu için burun ucu zamanla aşırı düşmez; aşırı doku alınmış burunlarda ise yaşla birlikte çökme görülebilir.")],
 "related":["yuz-germe","goz-kapagi","lip-lift"],
 "ctah":"Rinoplasti değerlendirmesi",
 "ctap":"Beklentinizi, nefes alma ile ilgili şikâyetiniz olup olmadığını ve varsa önden–yandan fotoğraflarınızı gönderin. Planlama görüşmesi için size dönüş yapılır."},

{
 "key":"meme-estetigi", "slug":"meme-estetigi.html", "prio":"0.85",
 "crumb":"Meme Estetiği",
 "title":"Meme Estetiği: Büyütme, Küçültme ve Dikleştirme | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Meme Estetiği: Büyütme, Küçültme ve Dikleştirme",
 "desc":"Meme büyütme, meme küçültme ve meme dikleştirme (mastopeksi) ameliyatları: implant seçimi, iz yerleri, emzirme, iyileşme süreci ve sık sorulan sorular.",
 "eyebrow":"Estetik Cerrahi",
 "h1":"Meme estetiği: büyütme, küçültme, dikleştirme",
 "lead":"Meme estetiğinde tek bir doğru yoktur. Doğru olan, sizin vücut ölçülerinize, doku kalitenize ve yaşam biçiminize uyan plandır. Bazı hastalar hacim ister, bazıları yükü azaltmak; çoğu için asıl mesele ise formu ve dikliği geri kazanmaktır.",
 "watopic":"meme estetiği",
 "about":"Meme estetik cerrahisi", "aboutType":"MedicalProcedure",
 "card":"Meme estetiği", "cardsub":"Büyütme, küçültme ve dikleştirme",
 "procedure":{"name":"Meme Estetik Cerrahisi",
   "how":"Hedefe göre implant yerleştirme, meme dokusunun küçültülerek yeniden şekillendirilmesi veya meme dokusunun daha yüksek konuma taşınması uygulanır.",
   "prep":"Muayene, ölçüm, meme görüntülemesi ve implant planlaması.",
   "follow":"Sporcu sütyeni kullanımı, ağır kaldırma kısıtlaması ve planlı kontroller.",
   "body":"Meme"},
 "keyfacts":[("Anestezi","Genel anestezi"),("Süre","1,5–3 saat"),
             ("İşe dönüş","5–10 gün"),("Spor","4–6 hafta sonra")],
 "sections":[
  {"id":"buyutme","tag":"Büyütme","h2":"Meme büyütme","body":[
   "Hacim kaybı, doğuştan küçük meme yapısı veya gebelik sonrası boşalma nedeniyle uygulanır. Amaç iri bir meme yapmak değil, vücut hatlarınızla uyumlu ve doğal görünen bir hacim oluşturmaktır.",
   ("h3","İmplant seçimi"),
   ("ul",["<strong>Yerleşim:</strong> Kas altı, kas üstü ya da çift düzlem. Doku kalınlığınız belirleyicidir; ince dokuda kas altı daha doğal sonuç verir.",
          "<strong>Şekil:</strong> Yuvarlak implantlar üst kutupta dolgunluk verir; damla şeklindekiler daha doğal bir eğim oluşturur.",
          "<strong>Yüzey ve boyut:</strong> Göğüs kafesi genişliğinize göre seçilir. Anatominizin taşıyabileceğinden büyük implant, uzun vadede sarkma ve doku incelmesine yol açar."]),
   ("h3","Yağ enjeksiyonu ile büyütme"),
   "Kendi yağ dokunuzla sınırlı bir hacim artışı sağlanabilir. Yabancı madde içermez ve doğal his verir, ancak artış implanta göre daha azdır ve enjekte edilen yağın bir bölümü emilir.",
   ("note","İmplantlar ömür boyu garantili ürünler değildir. Yıllar içinde değiştirilmeleri gerekebilir; düzenli kontrol ve gerektiğinde görüntüleme planın parçasıdır.")]},
  {"id":"kucultme","tag":"Küçültme","h2":"Meme küçültme","body":[
   "Meme küçültme yalnızca estetik bir tercih değildir. İri memeler sırt, boyun ve omuz ağrısına, sütyen askısı izlerine, meme altında mantar enfeksiyonlarına ve duruş bozukluğuna yol açar. Ameliyat sonrası hastaların en sık kullandığı ifade \"keşke daha önce yaptırsaydım\" olur.",
   "Doç. Dr. Acartürk, Amerika'daki meslektaşlarından farklı olarak <strong>daha az iz bırakan ve memeyi daha çok kaldıran</strong> bir teknik kullanmakta; bu nedenle özellikle estetiğin ön planda olduğu genç hastalar kendisine yönlendirilmiştir.",
   ("h3","İz biçimleri"),
   ("ul",["<strong>Tek dikey iz (lollipop):</strong> Areola çevresi ve aşağı doğru dikey hat. Orta düzeydeki küçültmelerde tercih edilir.",
          "<strong>Ters T (anchor):</strong> Dikey ize ek olarak meme altı katlantısında yatay hat. Çok büyük hacimlerde gerekir."]),
   ("note","Küçültme ameliyatı memeyi aynı zamanda dikleştirir; ayrı bir mastopeksi gerekmez. Emzirme çoğu hastada mümkün olmaya devam eder ancak süt kanallarına müdahale edildiği için garanti edilemez.")]},
  {"id":"dikleştirme","tag":"Dikleştirme","h2":"Meme dikleştirme (mastopeksi)","body":[
   "Gebelik, emzirme, kilo değişimi ve yerçekimi zamanla meme dokusunun aşağı kaymasına yol açar. Mastopeksi, doku eklemeden ya da çıkarmadan memeyi olması gereken yüksekliğe taşır ve meme başını yeniden konumlandırır.",
   ("ul",["Yalnızca sarkma varsa: mastopeksi tek başına yeterlidir",
          "Sarkma + hacim kaybı varsa: mastopeksi + implant birlikte planlanır",
          "Sarkma + fazla hacim varsa: küçültme ameliyatı her ikisini birden çözer"]),
   "Hangi grupta olduğunuz, meme başının meme altı katlantısına göre konumuyla belirlenir. Bu ayrım, ameliyat planını doğrudan değiştirir."]},
  {"id":"surec","tag":"Süreç","h2":"İyileşme süreci","body":[
   std_steps("Genel anestezi altında 1,5–3 saat. Genellikle bir gece hastanede kalınır.",
             "Sporcu sütyeni ile destek. İlk günlerde gerginlik hissi normaldir; ağrı kontrol altına alınır.",
             "Masa başı işe 5–10 günde dönülür. Ağır kaldırma ve spor 4–6 hafta ertelenir. Son şekil 3–6 ayda oturur, izler bir yıl içinde soluklaşır.")]}],
 "faqs":[
  ("Ameliyattan sonra emzirebilir miyim?","Meme büyütmede süt kanallarına genellikle dokunulmaz ve emzirme mümkündür. Küçültme ve dikleştirmede kanalların bir bölümü etkilenebilir; çoğu hasta emzirebilir ancak garanti edilemez. Planlarınızı ameliyat öncesi paylaşın."),
  ("İzler ne kadar belirgin kalır?","İzler ilk aylarda kırmızı ve belirgindir, birinci yılın sonunda soluklaşarak ten rengine yaklaşır. Silikon bant, güneşten korunma ve sigara içmemek iz kalitesini doğrudan etkiler."),
  ("İmplantlar ömür boyu kalır mı?","Hayır. İmplantlar zamanla değiştirilmesi gerekebilen tıbbi ürünlerdir. Belirli bir süre garanti edilemez; düzenli kontrol ve gerektiğinde görüntüleme önerilir."),
  ("Meme küçültme sigortadan karşılanır mı?","İri memeye bağlı sırt–boyun ağrısı ve cilt sorunları belgelendiğinde bazı sigortalar kapsam sağlayabilir. Koşullar poliçeye göre değişir; ameliyat öncesi netleştirilmelidir."),
  ("Ameliyat mamografi çekimimi engeller mi?","Hayır. İmplantlı hastalarda özel çekim teknikleri (Eklund yöntemi) kullanılır. Meme kanseri taramanız normal takviminde sürer; radyoloji ekibini bilgilendirmeniz yeterlidir."),
  ("Meme başımda his kaybı olur mu?","Geçici his değişikliği sıktır ve aylar içinde büyük ölçüde geri döner. Kalıcı duyu azalması ihtimali küçüktür ancak vardır; küçültme ameliyatlarında bu risk büyütmeye göre biraz daha yüksektir.")],
 "related":["meme-rek","jinekomasti","yag-enjeksiyonu"],
 "ctah":"Meme estetiği değerlendirmesi",
 "ctap":"Beklentinizi, gebelik ve emzirme planınızı, varsa geçirdiğiniz meme ameliyatlarını ve boy–kilo bilginizi paylaşın."},

{
 "key":"yuz-germe", "slug":"yuz-germe.html", "prio":"0.8",
 "crumb":"Yüz Germe",
 "title":"Yüz Germe ve Boyun Gençleştirme — SMAS Teknikleri | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Yüz Germe ve Boyun Gençleştirme",
 "desc":"Yüz germe ameliyatı nedir, SMAS ve derin düzlem teknikleri, boyun germe ile birlikte planlama, iz yerleri ve iyileşme süreci.",
 "eyebrow":"Estetik Cerrahi",
 "h1":"Yüz germe ve boyun gençleştirme",
 "lead":"Yaşlanma yalnızca cildin sarkması değildir: yağ yastıkçıkları aşağı kayar, hacim kaybolur, kas tabakası gevşer. Yalnızca cildi germek gergin ama yaşlı bir yüz üretir. Doğru sonuç, dokuları eski konumlarına taşımaktan geçer.",
 "watopic":"yüz germe",
 "about":"Ritidektomi", "aboutType":"MedicalProcedure",
 "card":"Yüz germe", "cardsub":"SMAS ve derin düzlem teknikleriyle yüz–boyun gençleştirme",
 "procedure":{"name":"Yüz Germe (Ritidektomi)",
   "how":"Cilt altındaki SMAS tabakası ayrıştırılarak yukarı ve arkaya doğru yeniden konumlandırılır; ardından fazla cilt gerginlik yaratmadan alınır.",
   "prep":"Muayene, fotoğraf analizi, kan tetkikleri ve sigara bırakma.",
   "follow":"Yüz bandajı, ödem yönetimi, ilk hafta baş yüksekte dinlenme.",
   "body":"Yüz ve boyun"},
 "keyfacts":[("Anestezi","Genel anestezi"),("Süre","4–6 saat"),
             ("Sosyal dönüş","2–3 hafta"),("Kalıcılık","8–12 yıl")],
 "sections":[
  {"id":"teknik","tag":"Teknik","h2":"SMAS ve derin düzlem yaklaşımı","body":[
   "Yüzün cilt altında SMAS adı verilen kas ve bağ dokusundan oluşan bir tabaka bulunur. Yaşlanmada asıl sarkan yapı budur. Modern yüz germede cilt yalnızca örtüdür; taşıyıcı iş SMAS tabakasına yaptırılır.",
   ("ul",["<strong>SMAS plikasyonu:</strong> Tabaka katlanarak askıya alınır. Daha az invaziv, orta düzeyde sarkmada uygundur.",
          "<strong>SMAS ektomisi:</strong> Tabakadan bir şerit çıkarılıp gerginlik sağlanır.",
          "<strong>Derin düzlem (deep plane):</strong> SMAS ve cilt tek parça hâlinde kaldırılıp yeniden konumlandırılır. Orta yüzde ve nazolabial bölgede daha güçlü ve daha uzun süreli sonuç verir."]),
   ("note","\"Gergin\" görünüm, ciltten aşırı çekilmenin sonucudur. Yükü SMAS tabakasının taşıdığı bir ameliyatta cilt gerginliği düşük kalır, ifade doğal olur ve iz kalitesi belirgin biçimde artar.")]},
  {"id":"boyun","tag":"Boyun","h2":"Boyun germe ile birlikte planlama","body":[
   "Yüz ve boyun ayrı düşünülemez. Gergin bir yüzün altında gevşek bir boyun, sonucu bütünüyle bozar. Boyunda üç ayrı sorun bir arada bulunabilir:",
   ("ul",["Çene altında yağ birikimi — liposuction ile alınır",
          "Platisma kasının orta hatta ayrılması ve bant oluşturması — dikişlerle birleştirilir (platismaplasti)",
          "Fazla ve gevşemiş cilt — kulak arkasındaki kesiden askıya alınır"]),
   "Bu üç bileşenden hangilerinin sizde bulunduğu muayenede belirlenir ve plan buna göre kurulur."]},
  {"id":"tamamlayici","tag":"Tamamlayıcı","h2":"Tamamlayıcı işlemler","body":[
   "Yüz germe sarkmayı düzeltir, ancak <strong>kaybolan hacmi geri getirmez</strong>. Bu nedenle çoğu planda yağ enjeksiyonu eşlik eder: şakaklar, elmacık bölgesi ve göz altı çukurluğu kendi yağınızla doldurulur.",
   ("ul",["<a href=\"goz-kapagi-estetigi.html\">Göz kapağı estetiği</a> — bakışın yorgun ifadesini gidermek için sık birlikte yapılır",
          "<a href=\"yag-enjeksiyonu.html\">Yağ enjeksiyonu</a> — hacim kaybının giderilmesi",
          "Kaş kaldırma — alın ve kaş düşüklüğü belirginse",
          "Cilt yüzeyi tedavileri — leke ve ince çizgiler için, iyileşme sonrasında"]),
   ("note","Yüz germe cilt kalitesini değiştirmez. Leke, ince çizgi ve gözenek sorunları ameliyatla düzelmez; bunlar için ayrı yüzey tedavileri gerekir ve genellikle iyileşme tamamlandıktan sonra planlanır.")]},
  {"id":"surec","tag":"Süreç","h2":"İyileşme süreci","body":[
   std_steps("Genel anestezi altında 4–6 saat. Bir gece hastanede kalınır.",
             "Yüz bandajı ve dren. Şişlik ve morarma 4–7. günde en yoğun hâlindedir; ilk hafta baş yüksekte dinlenmek gerekir.",
             "Dikişler 7–10. günde alınır. Sosyal dönüş çoğu hastada 2–3 hafta. Ödemin tam çözülmesi ve izlerin soluklaşması 6–12 ay sürer."),
   ("ul",["Sigara, yara iyileşmesini bozarak cilt kaybı riskini ciddi biçimde artırır — en az 4 hafta önce bırakılmalıdır",
          "İlk 3 hafta ağır egzersiz ve öne eğilme kısıtlanır",
          "Saç boyası genellikle 4–6 hafta ertelenir"])]}],
 "faqs":[
  ("Yüz germe sonucu ne kadar kalıcı?","Ameliyat saati geri alır ama durdurmaz. SMAS tabakasının taşıdığı iyi planlanmış bir germede sonuç genellikle 8–12 yıl korunur; yaşlanma bu noktadan itibaren devam eder."),
  ("İzler nerede kalır?","Kesiler saç çizgisi içinde, kulak önü doğal katlantısında ve kulak arkasında gizlenir. Doğru planlandığında saç ve kulak gölgesinde kalır, normal mesafeden fark edilmez."),
  ("İpli askı yüz germenin yerini tutar mı?","Hayır. İp askıları sınırlı ve geçici bir etki sağlar, genellikle 1–2 yılda kaybolur. Belirgin sarkmada cerrahi germenin alternatifi değildir."),
  ("Kaç yaşında yüz germe yaptırılır?","Yaş değil, doku durumu belirleyicidir. Çoğu hasta 45–65 yaş aralığındadır, ancak erken yaşlanan veya belirgin kilo kaybı yaşayan kişilerde daha erken de uygun olabilir."),
  ("Yüz ifadem değişir mi?","Amaç ifadeyi korumaktır. Yük cilde değil SMAS tabakasına verildiğinde ifade doğal kalır. Sinir yaralanmasına bağlı geçici zayıflık nadirdir ve genellikle haftalar içinde düzelir."),
  ("Ameliyattan sonra ne zaman iş toplantısına girebilirim?","Morarmanın kapatılabilir hâle gelmesi genellikle 2 hafta, rahat hissetmek ise 3 haftayı bulur. Kritik bir sosyal etkinliğiniz varsa en az 4 hafta pay bırakmanız önerilir.")],
 "related":["goz-kapagi","yag-enjeksiyonu","rinoplasti"],
 "ctah":"Yüz germe değerlendirmesi",
 "ctap":"Sizi en çok rahatsız eden bölgeyi, varsa geçmiş estetik işlemlerinizi ve önden–yandan fotoğraflarınızı gönderin."},

{
 "key":"goz-kapagi", "slug":"goz-kapagi-estetigi.html", "prio":"0.8",
 "crumb":"Göz Kapağı Estetiği",
 "title":"Göz Kapağı Estetiği (Blefaroplasti) — Üst ve Alt Kapak | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Göz Kapağı Estetiği (Blefaroplasti)",
 "desc":"Üst ve alt göz kapağı estetiği: sarkan kapak, göz altı torbaları, lokal anestezi ile uygulama, iyileşme süreci ve sık sorulan sorular.",
 "eyebrow":"Estetik Cerrahi",
 "h1":"Göz kapağı estetiği (blefaroplasti)",
 "lead":"Yüzün en erken yaşlanan bölgesi göz çevresidir. Üst kapaktaki sarkma bakışı yorgun gösterir, ileri düzeyde görüş alanını daraltır; alt kapaktaki torbalanma dinlenmiş bir insanı bile bitkin gösterir. Blefaroplasti, küçük bir işlemle ifadeyi belirgin biçimde değiştirir.",
 "watopic":"göz kapağı estetiği",
 "about":"Blefaroplasti", "aboutType":"MedicalProcedure",
 "card":"Göz kapağı estetiği","cardsub":"Üst ve alt kapak, göz altı torbaları",
 "procedure":{"name":"Blefaroplasti",
   "how":"Üst kapakta doğal katlantı çizgisinden fazla deri ve gerektiğinde yağ dokusu çıkarılır; alt kapakta yağ yastıkçıkları yeniden dağıtılır veya azaltılır.",
   "prep":"Göz muayenesi, gerektiğinde görme alanı testi ve kuru göz değerlendirmesi.",
   "follow":"Soğuk uygulama, göz damlaları ve ilk hafta zorlanmadan kaçınma.",
   "body":"Göz kapakları"},
 "keyfacts":[("Anestezi","Çoğunlukla lokal + sedasyon"),("Süre","45–90 dakika"),
             ("Dikiş alma","5–7. gün"),("Sosyal dönüş","7–10 gün")],
 "sections":[
  {"id":"ust","tag":"Üst Kapak","h2":"Üst göz kapağı estetiği","body":[
   "Üst kapakta zamanla deri gevşer ve kirpik hattına doğru sarkar. Bu, bakışa yorgun ve öfkeli bir ifade verir; ileri düzeyde kirpiklerin üzerine binerek görüş alanını daraltır ve alın kaslarının sürekli kasılmasına yol açar.",
   "İşlemde fazla deri, kapağın <strong>doğal katlanma çizgisinden</strong> çıkarılır. İz bu çizginin içinde kaldığı için iyileşme sonrası büyük ölçüde gizlenir. Gerektiğinde iç köşedeki yağ yastıkçığı da azaltılır.",
   ("note","Kaş düşüklüğü ile kapak sarkması karıştırılabilir. Asıl sorun kaşın düşmesiyse yalnızca kapak ameliyatı yapmak sonucu yetersiz bırakır, hatta kaşı daha da aşağı çekebilir. Ayrım muayenede yapılır.")]},
  {"id":"alt","tag":"Alt Kapak","h2":"Alt göz kapağı ve göz altı torbaları","body":[
   "Alt kapaktaki şişkinlik genellikle deri fazlalığından değil, göz çevresindeki <strong>yağ yastıkçıklarının öne doğru itilmesinden</strong> kaynaklanır. Bu nedenle yalnızca deri almak sonucu düzeltmez, kapağın aşağı çekilmesine yol açabilir.",
   ("ul",["<strong>Transkonjonktival yaklaşım:</strong> Kesi kapağın içinden yapılır, dışarıda hiç iz kalmaz. Deri fazlası olmayan genç hastalarda tercih edilir.",
          "<strong>Yağ yeniden dağıtımı:</strong> Yağ tamamen alınmak yerine göz altı çukurluğuna yayılır. Çökük ve gölgeli görünümü önler.",
          "<strong>Cilt kesisiyle yaklaşım:</strong> Belirgin deri fazlası varsa kirpik altından ince bir kesiyle uygulanır."]),
   ("note","Göz altı morlukları her zaman torbalanmadan kaynaklanmaz. İnce ciltten yansıyan damar yapısı ya da pigmentasyon söz konusuysa cerrahi bunları düzeltmez; bu ayrımın önceden yapılması gerekir.")]},
  {"id":"surec","tag":"Süreç","h2":"İyileşme süreci","body":[
   std_steps("Çoğu hastada lokal anestezi ve sedasyon yeterlidir; 45–90 dakika sürer ve aynı gün taburcu olunur.",
             "İlk 48 saat düzenli soğuk uygulama. Şişlik ve morarma 2–3. günde en yoğun hâlindedir; baş yüksekte yatmak süreci hızlandırır.",
             "Dikişler 5–7. günde alınır. Çoğu hasta 7–10 gün içinde makyajla sosyal hayata döner; ince ödem birkaç hafta daha sürebilir."),
   ("ul",["İlk hafta ağır kaldırma ve öne eğilmekten kaçınılmalı",
          "Kontakt lens genellikle 2 hafta ertelenir",
          "Ekran karşısında kuruluk olabilir; yapay gözyaşı önerilir",
          "İlk aylarda güneş gözlüğü ve koruyucu kullanılmalı"])]}],
 "faqs":[
  ("Göz kapağı ameliyatı sigortadan karşılanır mı?","Üst kapak sarkması görüş alanını daralttığında ve bu görme alanı testiyle belgelendiğinde bazı sigortalar kapsam sağlayabilir. Koşullar poliçeye göre değişir."),
  ("Kaç yıl sonra tekrar gerekir?","Üst kapak ameliyatının sonucu genellikle 10 yıl ve üzeri korunur. Alt kapakta yağ yeniden dağıtıldığında sonuç uzun ömürlüdür; yaşlanma sürecine bağlı olarak yıllar sonra ek işlem gerekebilir."),
  ("Gözlerim çekik görünür mü?","Doğru planlanmış bir blefaroplastide göz şekli değişmez. Aşırı deri alınması ya da alt kapağın desteklenmemesi bu görünüme yol açabilir; bu nedenle ölçü, alınan dokudan daha önemlidir."),
  ("Botoks ile arasındaki fark nedir?","Botoks kas hareketine bağlı çizgileri azaltır; sarkan deriyi ya da yağ torbalarını düzeltmez. İkisi birbirinin alternatifi değil, farklı sorunların çözümüdür ve birlikte planlanabilir."),
  ("Kuru göz şikâyetim var, ameliyat olabilir miyim?","Ameliyat öncesi mutlaka belirtilmelidir. Kuru göz ameliyat sonrası geçici olarak artabilir; bu durumda planlama daha korumacı yapılır ve göz doktoruyla birlikte değerlendirilir.")],
 "related":["yuz-germe","yag-enjeksiyonu","rinoplasti"],
 "ctah":"Göz kapağı değerlendirmesi",
 "ctap":"Sizi rahatsız eden görünümü, görme ile ilgili bir şikâyetiniz olup olmadığını ve varsa yakın plan fotoğraflarınızı gönderin."},

{
 "key":"karin-germe", "slug":"karin-germe.html", "prio":"0.8",
 "crumb":"Karın Germe",
 "title":"Karın Germe (Abdominoplasti) — Kas Onarımı ve İyileşme | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Karın Germe (Abdominoplasti)",
 "desc":"Karın germe ameliyatı: kim uygun adaydır, kas ayrılması (diastazis) onarımı, mini abdominoplasti farkı, iz yeri ve iyileşme süreci.",
 "eyebrow":"Estetik Cerrahi",
 "h1":"Karın germe (abdominoplasti)",
 "lead":"Gebelik ve büyük kilo kayıpları karın bölgesinde iki kalıcı iz bırakır: gevşemiş fazla deri ve orta hatta ayrılmış karın kasları. Bunların ikisi de spor ve diyetle geri gelmez. Karın germe, deriyi ve kas duvarını birlikte onarır.",
 "watopic":"karın germe",
 "about":"Abdominoplasti", "aboutType":"MedicalProcedure",
 "card":"Karın germe", "cardsub":"Fazla deri ve ayrılmış karın kaslarının onarımı",
 "procedure":{"name":"Abdominoplasti",
   "how":"Bikini hattındaki kesiden fazla deri ve yağ dokusu çıkarılır, ayrılmış karın kasları dikişlerle orta hatta birleştirilir ve göbek yeniden şekillendirilir.",
   "prep":"Kilo hedefinin sabitlenmesi, sigara bırakma, kan tetkikleri ve gerektiğinde fıtık değerlendirmesi.",
   "follow":"Korse kullanımı, erken yürüyüş, ağır kaldırma kısıtlaması.",
   "body":"Karın"},
 "keyfacts":[("Anestezi","Genel anestezi"),("Süre","2–4 saat"),
             ("Hastane","1–2 gece"),("İşe dönüş","2–3 hafta")],
 "sections":[
  {"id":"kimler","tag":"Kimler İçin","h2":"Kimler için uygundur?","body":[
   ("ul",["Gebelik sonrası karın derisi gevşemiş ve kasları ayrılmış olanlar",
          "Belirgin kilo kaybı sonrası sarkan karın derisi bulunanlar",
          "Diyet ve egzersizle düzelmeyen alt karın sarkması olanlar",
          "Kilosunu stabil hâle getirmiş ve bu kiloyu koruyabilecek olanlar"]),
   ("h3","Kimler için uygun değildir?"),
   ("ul",["Ciddi kilo verme planı olanlar — ameliyat kilo hedefine ulaşıldıktan sonra yapılmalıdır",
          "Yakın zamanda gebelik planlayanlar — gebelik onarılan kas duvarını yeniden ayırır",
          "Sigarayı bırakamayanlar — yara iyileşmesi ve doku kaybı riski belirgin şekilde artar"]),
   ("note","Karın germe bir kilo verme yöntemi değildir. Bölgesel yağ ve fazla deriyi alır; genel kiloyu düşürmez. Beklentinin bu çerçevede kurulması, memnuniyetin en belirleyici etkenidir.")]},
  {"id":"diastazis","tag":"Kas Onarımı","h2":"Diastazis: ayrılmış karın kasları","body":[
   "Gebelikte büyüyen rahim, karın ön duvarındaki iki düz kası orta hattan yanlara doğru iter. Doğumdan sonra bu kaslar çoğu zaman eski konumlarına dönmez; aralarındaki bağ dokusu gerilmiş hâlde kalır. Buna <strong>rektus diastazisi</strong> denir.",
   "Diastazis yalnızca göbek çıkıntısına yol açmaz; bel ağrısı, karın içi basınç sorunları ve duruş bozukluğu da yaratır. Şınav veya plank gibi egzersizler açıklığı kapatmaz, bazen artırır.",
   "Karın germede bu kaslar dikişlerle orta hatta yeniden birleştirilir. Bel çevresi daralır, karın duvarı işlevsel olarak güçlenir. Bu, ameliyatın estetikten çok işlevsel yanıdır.",
   ("note","Karın germe sırasında göbek fıtığı varsa aynı seansta onarılabilir. Muayenede fıtık taraması yapılması ve gerekiyorsa görüntüleme istenmesi standart uygulamadır.")]},
  {"id":"tipler","tag":"Yöntem","h2":"Tam ve mini abdominoplasti","body":[
   ("table",["","Tam abdominoplasti","Mini abdominoplasti"],[
    ["Kapsam","Göbek üstü ve altı","Yalnızca göbek altı"],
    ["Göbek","Yeniden şekillendirilir","Yerinde kalır"],
    ["Kas onarımı","Tüm orta hat boyunca","Yalnızca alt bölge"],
    ["İz","Bikini hattı boyunca daha uzun","Daha kısa"],
    ["Uygun aday","Belirgin sarkma ve diastazis","Sınırlı alt karın gevşekliği"]]),
   "Liposuction çoğu planda karın germeye eşlik eder; bel ve yan bölgelerin şekillendirilmesi sonucun bütünlüğünü belirler. Gövdenin tümünde sarkma varsa <a href=\"kol-uyluk-germe.html\">gövde germe</a> gündeme gelebilir."]},
  {"id":"surec","tag":"Süreç","h2":"İyileşme süreci","body":[
   std_steps("Genel anestezi altında 2–4 saat. Hastanede 1–2 gece kalınır, dren yerleştirilir.",
             "İlk günlerde hafif öne eğik yürünür; bu normaldir ve birkaç gün içinde düzelir. Erken yürüyüş pıhtı riskini azalttığı için önemlidir.",
             "Korse 6 hafta kullanılır. Masa başı işe 2–3 haftada dönülür; ağır egzersiz 6–8 hafta ertelenir. Son şekil 6 ayda oturur."),
   ("ul",["Pıhtı önlemi: erken hareket, gerektiğinde varis çorabı ve kan sulandırıcı",
          "İlk 6 hafta ağır kaldırma yasak",
          "İz bakımı için silikon bant ve güneşten korunma birinci yıl boyunca sürdürülmeli"])]}],
 "faqs":[
  ("İz nerede kalır ve ne kadar uzun olur?","Kesi bikini hattına, iç çamaşırının gizleyebileceği seviyeye yerleştirilir. Uzunluğu alınan deri miktarına bağlıdır; belirgin sarkmada kalça kemikleri arasında uzanır. İz kalıcıdır ancak zamanla soluklaşır."),
  ("Ameliyattan sonra hamile kalabilir miyim?","Tıbben mümkündür ancak gebelik onarılan kas duvarını yeniden ayırır ve deriyi tekrar gevşetir. Gebelik planınız varsa ameliyatı sonraya bırakmanız önerilir."),
  ("Karın germe ile liposuction arasındaki fark nedir?","Liposuction yalnızca yağ alır; deri kalitesi iyi olan hastalarda uygundur. Deri gevşemişse veya kaslar ayrılmışsa liposuction tek başına yetersiz kalır, hatta sarkmayı artırabilir."),
  ("Göbeğim nasıl görünecek?","Tam abdominoplastide göbek yerinde bırakılır, çevresindeki deri aşağı çekilir ve göbek yeni deriden çıkarılır. Çevresinde ince bir iz oluşur, zamanla belirsizleşir."),
  ("Ne zaman spora başlayabilirim?","Yürüyüşe ilk günlerde başlanır. Hafif kardiyo 4. haftadan sonra, karın çalıştıran egzersizler ise 8. haftadan sonra hekim onayıyla kademeli olarak eklenir."),
  ("Ameliyat sonrası his kaybı olur mu?","Göbek altı bölgede geçici uyuşukluk beklenir ve aylar içinde büyük ölçüde geri döner. Küçük bir alanda kalıcı his azalması olabilir.")],
 "related":["liposuction","kol-uyluk-germe","meme-estetigi"],
 "ctah":"Karın germe değerlendirmesi",
 "ctap":"Gebelik öykünüzü, kilo değişiminizi, mevcut kilonuzun ne kadar süredir sabit olduğunu ve varsa fotoğraflarınızı paylaşın."},

{
 "key":"liposuction", "slug":"liposuction-vucut-sekillendirme.html", "prio":"0.8",
 "crumb":"Liposuction ve Vücut Şekillendirme",
 "title":"Liposuction (Yağ Aldırma) ve Vücut Şekillendirme | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Liposuction ve Vücut Şekillendirme",
 "desc":"Liposuction nedir, kimler için uygundur, VASER ve güç destekli teknikler, yağ transferiyle şekillendirme, iyileşme süreci ve gerçekçi beklentiler.",
 "eyebrow":"Estetik Cerrahi",
 "h1":"Liposuction ve vücut şekillendirme",
 "lead":"Liposuction kilo verme yöntemi değildir; diyet ve egzersize direnen bölgesel yağ birikimlerini alarak vücut oranlarını düzenler. Doğru hastada dramatik bir kontur değişimi sağlar, yanlış hastada hayal kırıklığı yaratır. Fark, doğru adaylıkta başlar.",
 "watopic":"liposuction ve vücut şekillendirme",
 "about":"Liposuction", "aboutType":"MedicalProcedure",
 "card":"Liposuction", "cardsub":"Bölgesel yağ alımı ve vücut konturu",
 "procedure":{"name":"Liposuction",
   "how":"Küçük kesilerden yerleştirilen kanüllerle, tümesan sıvı verildikten sonra cilt altı yağ dokusu kontrollü biçimde aspire edilir.",
   "prep":"Kilo hedefinin sabitlenmesi, cilt esnekliğinin değerlendirilmesi ve korse ölçüsü.",
   "follow":"Korse kullanımı, lenf drenajı masajı ve kademeli aktiviteye dönüş.",
   "body":"Karın, bel, uyluk, kol, sırt, çene altı"},
 "keyfacts":[("Anestezi","Genel veya sedasyon"),("Süre","1–3 saat"),
             ("Korse","4–6 hafta"),("Son şekil","3–6 ay")],
 "sections":[
  {"id":"kimler","tag":"Kimler İçin","h2":"Doğru aday kimdir?","body":[
   "Liposuction'da sonucu belirleyen en önemli etken alınan yağ miktarı değil, <strong>cildin toparlanma kapasitesidir</strong>. Yağ alındıktan sonra cilt yeni hacme uyum sağlamalıdır; esnekliğini yitirmiş bir ciltte yağ alımı sarkmayı görünür hâle getirir.",
   ("ul",["İdeal kilosuna yakın, ancak bölgesel yağ birikimi olanlar",
          "Cilt esnekliği korunmuş olanlar",
          "Kilosunu koruyabilecek yaşam düzenine sahip olanlar",
          "Gerçekçi beklentileri olanlar"]),
   ("note","Cilt gevşemişse liposuction tek başına yetersizdir. Bu durumda <a href=\"karin-germe.html\">karın germe</a> ya da <a href=\"kol-uyluk-germe.html\">kol ve uyluk germe</a> ile birlikte planlanması gerekir. Bu ayrımın önceden yapılması, memnuniyetsizliğin en sık nedenini ortadan kaldırır.")]},
  {"id":"teknik","tag":"Teknik","h2":"Kullanılan teknikler","body":[
   ("ul",["<strong>Tümesan liposuction:</strong> Bölgeye önce özel bir sıvı verilir; kanama ve ağrı azalır, yağ daha kolay ayrışır. Tüm yöntemlerin temelidir.",
          "<strong>VASER (ultrason destekli):</strong> Ultrason enerjisi yağ hücrelerini seçici olarak parçalar. Fibröz bölgelerde ve kas hatlarının belirginleştirilmesinde avantaj sağlar.",
          "<strong>PAL (güç destekli):</strong> Titreşimli kanül, sert dokuda daha az travmayla çalışmayı sağlar.",
          "<strong>WAL (su jeti destekli):</strong> Su jeti yağı nazikçe ayırır; lenfatik yapıları koruduğu için <a href=\"lipodem-cerrahisi.html\">lipödem cerrahisinde</a> tercih edilir."]),
   ("h3","Yağ transferi ile şekillendirme"),
   "Alınan yağ atılmak zorunda değildir. İşlenerek kalça, meme ya da yüz gibi hacim istenen bölgelere aktarılabilir. Bu, aynı seansta hem inceltme hem hacimlendirme yapılmasını sağlar. Ayrıntılar <a href=\"yag-enjeksiyonu.html\">yağ enjeksiyonu sayfamızda</a>.",
   ("note","Tek seansta güvenli biçimde alınabilecek yağ miktarının bir sınırı vardır. Bu sınırın aşılması sıvı–elektrolit dengesini bozar ve ciddi risk yaratır. Geniş alanlar gerektiğinde seanslara bölünür.")]},
  {"id":"surec","tag":"Süreç","h2":"İyileşme süreci","body":[
   std_steps("Alan sayısına göre 1–3 saat. Sınırlı bölgelerde aynı gün, geniş alanlarda bir gece hastanede kalınır.",
             "Korse ilk günden itibaren kullanılır. Morarma ve şişlik 3–5. günde en yoğun hâlindedir; ilk günlerde sızıntı olması normaldir.",
             "Masa başı işe 3–7 günde dönülür. Korse 4–6 hafta kullanılır, spor 4 hafta sonra kademeli başlar. Son şekil 3–6 ayda oturur."),
   ("ul",["Manuel lenf drenajı ödemin çözülmesini hızlandırır",
          "Erken dönemde ciltte sertlik ve düzensizlik hissedilmesi normaldir, zamanla yumuşar",
          "Sonucun korunması kilo dengesine bağlıdır"])]}],
 "faqs":[
  ("Alınan yağ geri gelir mi?","Alınan yağ hücreleri geri gelmez. Ancak kilo alınırsa kalan yağ hücreleri büyür ve vücutta yağ dağılımı değişebilir; bu da sonucun bozulmasına yol açar."),
  ("Liposuction selüliti geçirir mi?","Hayır. Selülit, cildi alta bağlayan bağ dokusu bantlarından kaynaklanır ve yağ alımıyla düzelmez. Bazı durumlarda yağ alımı sonrası daha belirgin bile görünebilir."),
  ("Kaç kilo veririm?","Liposuction kilo verme yöntemi değildir. Tartıdaki değişim genellikle birkaç kilodur; asıl fark ölçülerde ve kıyafet bedeninde görülür."),
  ("Ciltte düzensizlik olur mu?","Erken dönemde sertlik ve dalgalanma hissi normaldir ve aylar içinde yumuşar. Kalıcı düzensizlik riski, kanül kalınlığı ve tekniğe bağlıdır; gerekirse yağ enjeksiyonuyla düzeltilebilir."),
  ("Genel anestezi şart mı?","Sınırlı bölgelerde sedasyon ve lokal anestezi yeterli olabilir. Geniş alanlarda güvenlik açısından genel anestezi tercih edilir."),
  ("Korseyi ne kadar kullanmalıyım?","Genellikle 4–6 hafta; ilk 2–3 hafta gün boyu. Korse ödemin çözülmesine ve cildin yeni kontura oturmasına doğrudan katkı sağlar.")],
 "related":["karin-germe","lipodem","yag-enjeksiyonu"],
 "ctah":"Liposuction değerlendirmesi",
 "ctap":"Hangi bölgelerden rahatsız olduğunuzu, boy–kilo bilginizi ve kilonuzun ne kadar süredir sabit olduğunu paylaşın; varsa fotoğraflarınızı ekleyin."},

{
 "key":"yag-enjeksiyonu", "slug":"yag-enjeksiyonu.html", "prio":"0.75",
 "crumb":"Yağ Enjeksiyonu",
 "title":"Yağ Enjeksiyonu (Lipofilling) ve Kök Hücre Destekli Hacimlendirme | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Yağ Enjeksiyonu ve Kök Hücre Destekli Hacimlendirme",
 "desc":"Kendi yağ dokunuzla yüz ve vücut hacimlendirme: lipofilling nedir, kalıcılığı, kök hücre zenginleştirme, ışın görmüş dokularda kullanımı.",
 "eyebrow":"Estetik Cerrahi",
 "h1":"Yağ enjeksiyonu ve kök hücre destekli hacimlendirme",
 "lead":"Kendi yağ dokunuz, vücudun en uyumlu dolgu maddesidir: yabancı madde içermez, alerji yapmaz, doğal his verir ve tuttuğu ölçüde kalıcıdır. Üstelik yalnızca hacim vermez — içindeki hücreler cilt kalitesini de iyileştirir.",
 "watopic":"yağ enjeksiyonu",
 "about":"Otolog yağ transferi", "aboutType":"MedicalProcedure",
 "card":"Yağ enjeksiyonu", "cardsub":"Kendi yağınızla hacimlendirme ve doku iyileştirme",
 "procedure":{"name":"Otolog Yağ Transferi (Lipofilling)",
   "how":"Karın veya uyluktan ince kanüllerle alınan yağ dokusu işlenip saflaştırılır ve hedef bölgeye küçük hacimler hâlinde, çok katmanlı olarak enjekte edilir.",
   "prep":"Verici bölgenin belirlenmesi ve hedef hacmin planlanması.",
   "follow":"Enjeksiyon bölgesine bası uygulanmaması, ödem yönetimi.",
   "body":"Yüz, meme, kalça, skar bölgeleri"},
 "keyfacts":[("Anestezi","Sedasyon veya genel"),("Kalıcılık","Tutan yağ kalıcıdır"),
             ("Tutma oranı","Yaklaşık %50–70"),("Seans","Gerektiğinde tekrarlanır")],
 "sections":[
  {"id":"nedir","tag":"Temel Bilgi","h2":"Yağ enjeksiyonu nedir?","body":[
   "Lipofilling, vücudun bir bölgesinden alınan yağ dokusunun işlenip başka bir bölgeye aktarılmasıdır. Aktarılan yağın yaşayabilmesi için yeni bölgede damarlanması gerekir; bu nedenle büyük kütleler hâlinde değil, ince katmanlar hâlinde dağıtılarak enjekte edilir.",
   "Enjekte edilen yağın bir bölümü ilk aylarda emilir. Tutan bölüm ise kalıcıdır ve vücutla birlikte kilo alıp verir. Ortalama tutma oranı %50–70 arasında değişir; bu yüzden planlamada bir miktar fazladan hacim verilir ve gerektiğinde ikinci seans yapılır.",
   ("h3","Kullanım alanları"),
   ("ul",["<strong>Yüz:</strong> Şakak, elmacık, göz altı çukurluğu, çene hattı ve dudak hacimlendirmesi",
          "<strong>Meme:</strong> Sınırlı büyütme, implant kenarlarının yumuşatılması, rekonstrüksiyon sonrası kontur düzeltmesi",
          "<strong>Kalça ve vücut:</strong> Hacim ve kontur düzenlemesi",
          "<strong>Skar ve ışın hasarı:</strong> Sertleşmiş dokunun yumuşatılması"])]},
  {"id":"kokhucre","tag":"Kök Hücre","h2":"Kök hücre destekli yaklaşım","body":[
   "Yağ dokusu yalnızca hacim değil, aynı zamanda <strong>rejeneratif hücreler</strong> içerir. Bu hücreler yeni damar oluşumunu destekler, cilt kalitesini iyileştirir ve doku iyileşmesine katkı sağlar. Yağın hücre içeriği bakımından zenginleştirilmesi, tutma oranını ve doku üzerindeki etkiyi artırmayı hedefler.",
   "Pittsburgh Üniversitesi bu alanda uluslararası bir merkezdir. Doç. Dr. Acartürk, yağ kökenli kök hücre teknolojileriyle çalışmış ilk Türk plastik cerrahlardan biridir ve bu tekniği özellikle kanser, yanık ve <a href=\"yanik-travma-onarimi.html\">radyoterapi sonrası doku onarımlarında</a> kullanmaktadır.",
   ("note","Kök hücre kavramı estetik alanda sıkça abartılı biçimde pazarlanmaktadır. Yağ dokusundan elde edilen hücreler doku kalitesine katkı sağlar; ancak yaşlanmayı durduran ya da geri çeviren bir tedavi değildir. Beklentinin bu çerçevede kurulması önemlidir.")]},
  {"id":"surec","tag":"Süreç","h2":"İşlem ve iyileşme","body":[
   ("steps",[
    ("1. ADIM — PLANLAMA","Hedef bölge, gereken hacim ve verici bölge belirlenir."),
    ("2. ADIM — YAĞ ALIMI","Karın veya uyluktan ince kanüllerle, hücreleri zedelemeyecek düşük basınçla alınır."),
    ("3. ADIM — İŞLEME","Yağ, kan ve sıvıdan ayrıştırılarak saflaştırılır."),
    ("4. ADIM — ENJEKSİYON","Hedef bölgeye çok sayıda ince tünel hâlinde, katmanlı olarak yerleştirilir."),
    ("5. ADIM — İLK 3 AY","Ödem çözülür ve emilim tamamlanır. Kalıcı sonuç bu dönem sonunda değerlendirilir.")]),
   ("ul",["Enjeksiyon bölgesine ilk hafta bası uygulanmamalı",
          "Sigara, yağ hücrelerinin yaşama oranını belirgin biçimde düşürür",
          "Belirgin kilo değişimi sonucu etkiler",
          "Gerektiğinde 3–6 ay sonra ikinci seans planlanır"])]}],
 "faqs":[
  ("Enjekte edilen yağın ne kadarı kalıcı olur?","Ortalama %50–70'i kalıcıdır. Kalan bölüm ilk 3 ay içinde emilir. Bu nedenle planlamada fazladan hacim verilir ve gerekirse ikinci seans yapılır."),
  ("Dolgu maddelerine göre avantajı nedir?","Kendi dokunuz olduğu için yabancı madde reaksiyonu riski yoktur, doğal his verir ve tutan bölüm kalıcıdır. Ayrıca cilt kalitesine katkı sağlar. Dezavantajı, cerrahi bir işlem olması ve sonucun daha az öngörülebilir olmasıdır."),
  ("Yüzüme yağ enjeksiyonu şişkin bir görünüm yapar mı?","İlk 2–3 hafta ödem nedeniyle dolgun görünür; bu geçicidir. Aşırı hacim verilmediği ve katmanlı teknik kullanıldığı sürece sonuç doğaldır."),
  ("Meme büyütmede implant yerine yağ kullanılabilir mi?","Sınırlı bir büyütme için kullanılabilir. Ancak tek seansta sağlanabilecek hacim artışı implanta göre azdır ve birden fazla seans gerekebilir. Beklentiye göre karar verilir."),
  ("Yağ enjeksiyonu meme kanseri taramasını etkiler mi?","Enjekte edilen yağın bir bölümü kireçlenmeye yol açabilir; bu radyolojide görülebilir ancak deneyimli bir radyolog tarafından kanserden ayırt edilebilir. Radyoloji ekibini bilgilendirmeniz yeterlidir."),
  ("Zayıfım, yeterli yağım var mı?","Genellikle karın, uyluk iç yüzü veya diz iç bölgesinden yeterli miktar alınabilir. Çok zayıf hastalarda hedef hacim sınırlı kalabilir; bu muayenede değerlendirilir.")],
 "related":["yuz-germe","meme-estetigi","yanik"],
 "ctah":"Yağ enjeksiyonu değerlendirmesi",
 "ctap":"Hangi bölgede hacim istediğinizi, daha önce dolgu yaptırıp yaptırmadığınızı ve varsa fotoğraflarınızı gönderin."},

{
 "key":"kol-uyluk-germe", "slug":"kol-uyluk-germe.html", "prio":"0.7",
 "crumb":"Kol, Uyluk ve Gövde Germe",
 "title":"Kol Germe (Brakioplasti), Uyluk ve Gövde Germe | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Kol, Uyluk ve Gövde Germe",
 "desc":"Büyük kilo kaybı sonrası kol germe (brakioplasti), uyluk germe ve gövde germe ameliyatları: iz yerleri, planlama sırası ve iyileşme süreci.",
 "eyebrow":"Estetik Cerrahi",
 "h1":"Kol, uyluk ve gövde germe",
 "lead":"Büyük kilo kaybı bir başarıdır, ancak arkasında sarkan deri bırakır. Kolların iç yüzü, uyluklar ve gövde bu değişimi en çok gösteren bölgelerdir. Germe ameliyatları fazla deriyi çıkararak vücudun kaybedilen kiloyla uyumlu hâle gelmesini sağlar.",
 "watopic":"kol ve uyluk germe",
 "about":"Vücut kontur cerrahisi", "aboutType":"MedicalProcedure",
 "card":"Kol ve uyluk germe", "cardsub":"Kilo kaybı sonrası fazla derinin alınması",
 "procedure":{"name":"Brakioplasti ve Uyluk Germe",
   "how":"Fazla deri ve yağ dokusu, izin en iyi gizlenebileceği hat boyunca çıkarılır; alttaki dokular askıya alınarak kontur oluşturulur.",
   "prep":"Kilonun stabil hâle gelmesi, beslenme ve vitamin durumunun değerlendirilmesi.",
   "follow":"Kompresyon giysisi, ödem kontrolü, kademeli aktiviteye dönüş.",
   "body":"Kol, uyluk, gövde"},
 "keyfacts":[("Ön koşul","Kilonun 6 ay sabit olması"),("Anestezi","Genel anestezi"),
             ("İz","Kalıcı, gizlenebilir hatlarda"),("İşe dönüş","2–3 hafta")],
 "sections":[
  {"id":"kol","tag":"Kol Germe","h2":"Kol germe (brakioplasti)","body":[
   "Kolun iç yüzündeki sarkma, kilo kaybı sonrası en çok şikâyet edilen bölgelerden biridir. Kısa kollu giysilerden kaçınmaya, kolun sallanmasından rahatsızlık duymaya yol açar. Egzersizle kas kazanmak bu sarkmayı düzeltmez; fazla deri cerrahi olarak alınmalıdır.",
   ("ul",["<strong>Sınırlı sarkmada:</strong> Koltuk altında gizlenen kısa bir kesi yeterli olabilir",
          "<strong>Belirgin sarkmada:</strong> Koltuk altından dirseğe uzanan, kolun iç yüzünde kalan bir kesi gerekir",
          "Liposuction genellikle eşlik eder ve konturu yumuşatır"]),
   ("note","Kol germenin izi kalıcıdır ve gizlenmesi sınırlıdır. Bu ameliyatta karar, sarkmanın yarattığı rahatsızlık ile izin kabul edilebilirliği arasında verilir. Hastaların büyük bölümü izi sarkmaya tercih ettiğini belirtir; ancak bu tercihin önceden net olması gerekir.")]},
  {"id":"uyluk","tag":"Uyluk Germe","h2":"Uyluk germe","body":[
   "Uyluk iç yüzündeki sarkma yürürken sürtünmeye, tahrişe ve kıyafet seçiminde kısıtlamaya yol açar. Kesi, sarkmanın derecesine göre iki biçimde planlanır:",
   ("ul",["<strong>Kasık hattı kesisi:</strong> İz iç çamaşırı hattında gizlenir. Sınırlı sarkmada tercih edilir.",
          "<strong>Dikey kesi:</strong> Kasıktan diz iç yüzüne uzanır. Belirgin sarkmada gereklidir; iz uzun ancak sonuç daha etkilidir."]),
   "Uyluk bölgesi yara iyileşmesi açısından hassastır: hareketli, nemli ve baskıya maruz kalan bir alandır. Bu nedenle yara açılması ve iyileşme gecikmesi diğer bölgelere göre daha sık görülür."]},
  {"id":"govde","tag":"Gövde Germe","h2":"Gövde germe ve sıralama","body":[
   "Gövde germe (body lift), karın, bel, kalça ve dış uylukları çevreleyen bir kesiyle fazla derinin tümüyle çıkarılmasıdır. Bariatrik cerrahi sonrası belirgin kilo kaybı yaşayan hastalarda uygulanır.",
   ("h3","Planlama sırası"),
   ("ul",["Genellikle önce gövde ve karın bölgesi ele alınır — en büyük hacim değişimi buradadır",
          "3–6 ay sonra kol ve uyluk germe planlanır",
          "Meme ve yüz bölgesi genellikle en sona bırakılır",
          "Aşamalar arasında iyileşmenin tamamlanması beklenir"]),
   ("note","Büyük kilo kaybı sonrası vitamin ve protein eksiklikleri yara iyileşmesini doğrudan etkiler. Ameliyat öncesi beslenme durumunun değerlendirilmesi ve gerekiyorsa desteklenmesi, komplikasyon riskini belirgin biçimde azaltır.")]},
  {"id":"surec","tag":"Süreç","h2":"İyileşme süreci","body":[
   std_steps("Genel anestezi altında; bölge ve kapsama göre 2–5 saat. Genellikle 1–2 gece hastanede kalınır.",
             "Kompresyon giysisi ilk günden itibaren kullanılır. Dren yerleştirilebilir. İlk hafta hareket kısıtlı tutulur.",
             "Masa başı işe 2–3 haftada dönülür. Kompresyon 6 hafta sürer. İzler ilk yıl boyunca olgunlaşır; bakım bu süreçte kritik önemdedir.")]}],
 "faqs":[
  ("Kilo kaybımdan ne kadar sonra ameliyat olabilirim?","Kilonuzun en az 6 ay sabit kalması beklenir. Erken yapılan ameliyat, sonraki kilo değişimiyle sonucun bozulmasına yol açar."),
  ("İzler ne kadar belirgin olur?","Bu ameliyatlarda izler uzun ve kalıcıdır. Zamanla soluklaşır ancak tümüyle kaybolmaz. Silikon bakımı, güneşten korunma ve sigara içmemek iz kalitesini doğrudan etkiler."),
  ("Hepsini tek seansta yaptırabilir miyim?","Genellikle önerilmez. Uzun ameliyat süresi ve geniş yara alanı riski artırır. Aşamalı planlama hem güvenlik hem sonuç kalitesi açısından tercih edilir."),
  ("Liposuction tek başına yeterli olmaz mı?","Cilt esnekliği yitirilmişse hayır. Yağ alındığında sarkma daha da belirginleşir. Kilo kaybı sonrası olgularda deri fazlasının çıkarılması gerekir."),
  ("Ameliyat sonrası spor ne zaman?","Yürüyüş ilk günlerde başlar. Hafif egzersiz 4. haftadan, ağırlık çalışması 8. haftadan sonra hekim onayıyla kademeli olarak eklenir.")],
 "related":["karin-germe","liposuction","meme-estetigi"],
 "ctah":"Germe ameliyatları değerlendirmesi",
 "ctap":"Ne kadar kilo verdiğinizi, kilonuzun ne kadar süredir sabit olduğunu, bariatrik cerrahi geçirip geçirmediğinizi ve varsa fotoğraflarınızı paylaşın."},

{
 "key":"jinekomasti", "slug":"jinekomasti.html", "prio":"0.75",
 "crumb":"Jinekomasti",
 "title":"Jinekomasti (Erkekte Meme Büyümesi) Ameliyatı | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Jinekomasti: Erkekte Meme Büyümesi ve Cerrahi Tedavisi",
 "desc":"Jinekomasti nedir, nedenleri nelerdir, yağlanma ile farkı, cerrahi tedavi seçenekleri, iz yeri ve iyileşme süreci hakkında bilinmesi gerekenler.",
 "eyebrow":"Estetik Cerrahi",
 "h1":"Jinekomasti (erkekte meme büyümesi)",
 "lead":"Jinekomasti, erkeklerde meme dokusunun büyümesidir. Erkeklerin yaklaşık üçte birini yaşamlarının bir döneminde etkiler. Spor ve diyetle geçmez, çünkü sorun yağ değil bez dokusudur. Cerrahi, kalıcı ve tek etkili çözümdür.",
 "watopic":"jinekomasti ameliyatı",
 "about":"Jinekomasti", "aboutType":"MedicalCondition",
 "card":"Jinekomasti", "cardsub":"Erkekte meme büyümesinin cerrahi tedavisi",
 "procedure":{"name":"Jinekomasti Cerrahisi",
   "how":"Areola alt kenarındaki kesiden bez dokusu çıkarılır; çevredeki yağ dokusu liposuction ile alınarak göğüs duvarına doğal erkek konturu verilir.",
   "prep":"Hormonal değerlendirme, ilaç ve madde kullanımının sorgulanması, gerektiğinde meme ultrasonu.",
   "follow":"Kompresyon yeleği, ağır egzersiz kısıtlaması.",
   "body":"Göğüs"},
 "keyfacts":[("Sıklık","Erkeklerin ~%30'u"),("Anestezi","Genel veya sedasyon"),
             ("Süre","1–2 saat"),("İşe dönüş","3–7 gün")],
 "sections":[
  {"id":"nedir","tag":"Temel Bilgi","h2":"Jinekomasti nedir, neden olur?","body":[
   "Jinekomasti, erkeklerde meme bezi dokusunun hormonal dengesizlik nedeniyle büyümesidir. Yalnızca yağlanmadan (psödojinekomasti) ayırt edilmesi gerekir: bez dokusu areola altında sert, disk şeklinde ele gelir; yağ dokusu ise yumuşak ve yaygındır.",
   ("h3","Başlıca nedenler"),
   ("ul",["<strong>Ergenlik:</strong> En sık nedendir. Olguların büyük bölümü 1–2 yıl içinde kendiliğinden geriler.",
          "<strong>İlaçlar:</strong> Bazı tansiyon ilaçları, mide ilaçları, antidepresanlar ve prostat ilaçları",
          "<strong>Anabolik steroid ve performans artırıcılar</strong>",
          "<strong>Hormonal hastalıklar:</strong> Tiroid, karaciğer ve testis kaynaklı sorunlar",
          "<strong>Kilo alımı ve yaşlanma</strong>"]),
   ("note","Ameliyat öncesi altta yatan bir neden araştırılmalıdır. Tek taraflı, hızlı büyüyen ya da sert ve düzensiz kitle şeklindeki büyümelerde ileri tetkik gerekir. Ergenlik döneminde başlayan olgularda genellikle 1–2 yıl beklenir.")]},
  {"id":"derece","tag":"Derecelendirme","h2":"Derecelendirme ve yöntem seçimi","body":[
   ("table",["Derece","Görünüm","Yaklaşım"],[
    ["Derece 1","Areola çevresinde sınırlı büyüme, deri fazlası yok","Bez eksizyonu ± liposuction"],
    ["Derece 2","Orta düzeyde büyüme, deri fazlası sınırlı","Bez eksizyonu + liposuction"],
    ["Derece 3","Belirgin büyüme, deri fazlası mevcut","Eksizyon + liposuction + deri sıkılaştırma"],
    ["Derece 4","Kadın memesi görünümü, meme başı düşük","Eksizyon + deri çıkarımı + meme başı konumlandırma"]]),
   "Derece 1 ve 2'de kesi areolanın alt kenarında kalır ve iz renk geçişinde gizlenir. Derece 3 ve 4'te ek kesiler gerekebilir; bu, planlama görüşmesinde açıkça konuşulur.",
   ("note","Yalnızca liposuction yapılması jinekomastinin en sık tekrarlama nedenidir. Bez dokusu liposuction ile alınamaz; areola altında sert bir disk olarak kalır ve şikâyet sürer.")]},
  {"id":"surec","tag":"Süreç","h2":"İyileşme süreci","body":[
   std_steps("Genel anestezi ya da sedasyon altında 1–2 saat. Çoğu hastada aynı gün taburcu olunur.",
             "Kompresyon yeleği ilk günden itibaren kullanılır. Morarma ve şişlik 3–5. günde en yoğun hâlindedir.",
             "Masa başı işe 3–7 günde dönülür. Kompresyon 4–6 hafta kullanılır. Göğüs çalıştıran egzersizler 6 hafta ertelenir. Son şekil 3–6 ayda oturur."),
   ("ul",["Areola altında geçici sertlik hissedilmesi normaldir",
          "Meme başında geçici his değişikliği olabilir, aylar içinde geri döner",
          "Sonucun korunması kilo dengesine ve steroid kullanmamaya bağlıdır"])]}],
 "faqs":[
  ("Spor yaparak geçer mi?","Hayır. Egzersiz yağ dokusunu azaltabilir ancak bez dokusunu ortadan kaldırmaz. Areola altındaki sert doku sporla geçmez; cerrahi gerekir."),
  ("Ameliyat sonrası tekrarlar mı?","Bez dokusu tam olarak çıkarıldığında tekrarlama beklenmez. Ancak anabolik steroid kullanımı, belirgin kilo alımı veya yeni bir hormonal sorun tabloyu yeniden başlatabilir."),
  ("İz belli olur mu?","Kesi areolanın alt kenarında, koyu ve açık deri arasındaki renk geçişine yerleştirilir. Bu hatta iyileşen izler zamanla belirsizleşir. İleri derecelerde ek izler gerekebilir."),
  ("Ergenlik döneminde ameliyat olunur mu?","Genellikle 1–2 yıl beklenir; olguların çoğu kendiliğinden geriler. Ancak sosyal ve psikolojik etkisi belirginse ve tablo sabitleşmişse erken cerrahi düşünülebilir."),
  ("Sigortadan karşılanır mı?","Bazı durumlarda, özellikle ağrı ve belgelenmiş hormonal patoloji varlığında kapsam sağlanabilir. Koşullar poliçeye göre değişir."),
  ("Ameliyattan sonra ne zaman göğüs çalışabilirim?","Genellikle 6 hafta sonra hekim onayıyla kademeli olarak başlanır. Erken başlanan ağır göğüs egzersizleri ödemi artırır ve iyileşmeyi geciktirir.")],
 "related":["liposuction","meme-estetigi","karin-germe"],
 "ctah":"Jinekomasti değerlendirmesi",
 "ctap":"Ne zamandır devam ettiğini, kullandığınız ilaç veya takviyeleri ve varsa önden–yandan fotoğraflarınızı gönderin."},

{
 "key":"lip-lift", "slug":"lip-lift-bisektomi-kulak-estetigi.html", "prio":"0.7",
 "crumb":"Lip Lift, Bişektomi ve Kulak Estetiği",
 "title":"Lip Lift, Bişektomi ve Kulak Estetiği (Otoplasti) | Doç. Dr. T. Oğuz Acartürk",
 "ogtitle":"Lip Lift, Bişektomi ve Kulak Estetiği",
 "desc":"Dudak kaldırma (lip lift), yanak yağı alınması (bişektomi) ve kepçe kulak estetiği (otoplasti): kimler için uygun, teknik, iz ve iyileşme süreci.",
 "eyebrow":"Estetik Cerrahi",
 "h1":"Lip lift, bişektomi ve kulak estetiği",
 "lead":"Yüz estetiğinde küçük ölçekli ama etkisi büyük üç işlem. Hepsi lokal anestezi ile yapılabilir, iyileşme süreleri kısadır ve sonuçları kalıcıdır. Ortak noktaları: doğru hastada belirgin fark yaratır, yanlış hastada gereksizdir.",
 "watopic":"lip lift, bişektomi veya kulak estetiği",
 "about":"Yüz estetik cerrahisi", "aboutType":"MedicalProcedure",
 "card":"Lip lift · Bişektomi · Otoplasti","cardsub":"Dudak kaldırma, yanak inceltme, kepçe kulak",
 "procedure":{"name":"Lip Lift (Dudak Kaldırma)",
   "how":"Burun tabanının hemen altından ince bir deri şeridi çıkarılarak üst dudak yukarı kaldırılır; dudak kırmızısı belirginleşir ve diş görünürlüğü artar.",
   "prep":"Dudak–burun mesafesinin ölçülmesi ve diş görünürlüğünün değerlendirilmesi.",
   "follow":"Dikiş bakımı ve ilk haftalarda aşırı mimikten kaçınma.",
   "body":"Üst dudak"},
 "keyfacts":[("Anestezi","Lokal anestezi"),("Süre","30–60 dakika"),
             ("Dikiş alma","5–7. gün"),("Sosyal dönüş","1 hafta")],
 "sections":[
  {"id":"liplift","tag":"Lip Lift","h2":"Lip lift (dudak kaldırma)","body":[
   "Yaşla birlikte burun tabanı ile üst dudak arasındaki mesafe uzar, dudak kırmızısı incelir ve gülümserken görünen diş miktarı azalır. Bu, yüze yaşlı ve sert bir ifade verir. Lip lift, burun tabanının hemen altından ince bir deri şeridi çıkararak dudağı yukarı kaldırır.",
   ("ul",["Dudak kırmızısı belirginleşir — dolgu gibi hacim eklenmez, var olan doku ortaya çıkar",
          "Gülümserken diş görünürlüğü artar",
          "Sonuç kalıcıdır; dolgu gibi tekrarlanması gerekmez",
          "İz burun tabanı kıvrımında gizlenir"]),
   ("note","Lip lift dolgunun alternatifi değildir. Dolgu hacim ekler, lip lift oranı değiştirir. Uzun dudak–burun mesafesi olan hastalarda dolgu sorunu çözmez, hatta üst dudağı daha ağır gösterebilir.")]},
  {"id":"bisektomi","tag":"Bişektomi","h2":"Bişektomi (yanak yağı alınması)","body":[
   "Bişektomi, yanakların derininde yer alan Bichat yağ yastıkçığının bir bölümünün ağız içinden alınmasıdır. Yanak orta bölgesindeki dolgunluğu azaltır, elmacık kemiği ve çene hattını daha belirgin gösterir. Kesi ağız içinde kaldığı için dışarıda iz oluşmaz.",
   ("h3","Kimler için uygun değildir?"),
   ("ul",["Zayıf ve yanakları zaten çökük olanlar",
          "İleri yaşta, yüzünde hacim kaybı başlamış olanlar",
          "Yüz sarkmasının asıl sorun olduğu hastalar"]),
   ("note","Bu yastıkçık yaşla birlikte zaten küçülür. Genç yaşta aşırı alınması, ileride çökük ve yaşlı bir yüz görünümüne yol açabilir. Bu nedenle miktar tutucu belirlenmelidir; alınan doku geri konulamaz.")]},
  {"id":"otoplasti","tag":"Otoplasti","h2":"Kepçe kulak estetiği (otoplasti)","body":[
   "Kepçe kulak, kulak kepçesinin başa göre fazla açılı durması ya da kıvrımlarının yeterince gelişmemesidir. Çocukluk döneminde sosyal etkisi belirgin olabildiği için erken yaşta ele alınması sık tercih edilir.",
   ("ul",["Kulak kıkırdağı kulak arkasındaki kesiden şekillendirilir ve dikişlerle sabitlenir",
          "İz kulak arkasında kalır, önden görünmez",
          "Kulak gelişimi 5–6 yaşta büyük ölçüde tamamlandığı için okul öncesi dönemde yapılabilir",
          "Erişkinlerde lokal anestezi ile uygulanır"]),
   "Doğuştan kulak yokluğu (mikrotia) farklı bir tablodur ve çok aşamalı rekonstrüksiyon gerektirir; ayrıntılar <a href=\"mikrotia-kulak-onarimi.html\">mikrotia sayfamızda</a>."]},
  {"id":"surec","tag":"Süreç","h2":"İyileşme süreci","body":[
   ("steps",[
    ("LIP LIFT","Dikişler 5–7. günde alınır. İlk hafta ödem belirgindir; sosyal dönüş genellikle 1 haftadır. İz 3–6 ayda soluklaşır."),
    ("BİŞEKTOMİ","İlk 3–5 gün yumuşak beslenme ve ağız bakımı. Ödem 1–2 haftada çözülür. Sonuç 3–6 ayda oturur."),
    ("OTOPLASTİ","Kulak bandı ilk hafta gün boyu, sonraki 3–4 hafta gece kullanılır. Sosyal dönüş 5–7 gün. Spor 4 hafta ertelenir.")])]}],
 "faqs":[
  ("Lip lift izi belli olur mu?","Kesi burun tabanının kıvrımına yerleştirilir. İlk aylarda pembe kalır, 3–6 ay içinde soluklaşarak doğal kıvrımla bütünleşir. İz bakımı ve güneşten korunma sonucu doğrudan etkiler."),
  ("Bişektomiden sonra yanaklarım çöker mi?","Ölçülü miktar alındığında hayır. Ancak yaşla birlikte bu yastıkçık zaten küçüldüğü için, genç yaşta fazla alınması ileride çökük görünüme yol açabilir. Bu yüzden tutucu yaklaşım tercih edilir."),
  ("Kepçe kulak ameliyatı için doğru yaş nedir?","Kulak gelişimi 5–6 yaşta büyük ölçüde tamamlanır; okul öncesi dönem sık tercih edilir. Erişkinlerde de her yaşta yapılabilir."),
  ("Kepçe kulak tekrarlar mı?","Kıkırdağın hafızası nedeniyle kısmi geri açılma görülebilir. Bu riski azaltmak için kıkırdağın şekli kalıcı dikişlerle desteklenir ve ameliyat sonrası bant kullanımına uyulması önem taşır."),
  ("Bu işlemler birlikte yapılabilir mi?","Evet. Lip lift ve bişektomi sıklıkla aynı seansta uygulanır. Diğer yüz işlemleriyle de birleştirilebilir; planlama muayenede yapılır.")],
 "related":["rinoplasti","yuz-germe","mikrotia"],
 "ctah":"Değerlendirme için ilk adım",
 "ctap":"Hangi işlemle ilgilendiğinizi, beklentinizi ve varsa önden–yandan fotoğraflarınızı gönderin."},
]
